### ISSUE TITLE
Support PEP-561 type hints in Python SDK

### ISSUE THREAD

**Issue by csssuf** [pulumi/pulumi-kubernetes#1000]
### Problem description

`pulumi-kubernetes` should support PEP-561 type hints the same way the main Pulumi SDK/providers using `pulumi-terraform-bridge` do.

See also pulumi/pulumi#3704 and pulumi/pulumi-terraform-bridge#100.

### Suggestions for a fix

I'm happy to submit a PR if the Python SDK's `setup.py`, etc. are hand-maintained in this repo, but I wasn't sure if that bit of the Python SDK is autogenerated for this package.

**Comment by lukehoban** [comment]
> I'm happy to submit a PR if the Python SDK's setup.py

PR definitely welcome. It will likely require updating the code generator, but shouldn’t be too involved. Note that this is likely to be overhauled anyway soon as part of https://github.com/pulumi/pulumi/issues/3764. 

Note that especially for Kubernetes, https://github.com/pulumi/pulumi/issues/3771 will really be needed before this is particularly helpful, as without that there is very limited typing that is provided in existing api definitions.

**Comment by justinvp** [comment]
The core support for https://github.com/pulumi/pulumi/issues/3771 is landing this week, which will largely address this issue, and will roll out to the kubernetes provider soon after. I'll keep this issue open until the changes make their way here.

**Comment by justinvp** [comment]
This is now available in v2.5.1. There are a couple of follow-up items that are in-progress, but will track those as individual items (https://github.com/pulumi/pulumi/issues/5212, https://github.com/pulumi/pulumi/issues/5278).
