### ISSUE TITLE
Details of probes in a podspec are not rendered correctly

### ISSUE THREAD

**Issue by ringods** [pulumi/pulumi-kubernetes#1004]
I’m adding a `livenessProbe` to my Pod spec. Here is a snippet:

```
livenessProbe: {
    httpGet: {
        path: '/auth',
        port: 80
    },
    initialDelaySeconds: 300,
    timeoutSeconds: 5
}
```

But when looking at the details of `pulumi up`, I see this:

```
~ livenessProbe : {
    ~ httpGet: {
      }
  }
```

The details of the `httpGet` are not displayed. Similar behaviour for `readinessProbe`

Context:
* Pulumi v1.10.1
* Typescript package `@pulumi/pulumi` v1.8.1
* Typescript package `@pulumi/kubernetes` v1.4.3

**Comment by lblackstone** [comment]
This was fixed at some point
