### ISSUE TITLE
`Configure` should accept a `kubeconfig` spec as JSON

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-kubernetes#101]
e.g. I should be able to JSON-serialize a `kubeconfig` value and supply it as the value for `kubernetes:config:kubernetes`.

**Comment by pgavlin** [comment]
This depends on #100.

**Comment by hausdorff** [comment]
@pgavlin Somewhat relatedly, I think we should also consider making the literal `$KUBECONFIG` file an "input" (in some loose sense) to the Pulumi application. That is to say, if the user changes the active context to point at a new cluster (_e.g._, with something like `kubectl config use-context some-new-cluster`), then we'll want to report something different -- that none of the resources are available, and we will need to create new ones.

And related to that, I'm still not sure how to reason about multiple stacks on different clusters.

**Comment by pgavlin** [comment]
Here's a prototype approach to the original issue: https://github.com/pulumi/pulumi-kubernetes/compare/pgavlin/kubeconfig

**Comment by pgavlin** [comment]
Closed with #119.
