### ISSUE TITLE
Can't set annotations on yaml files with transformations

### ISSUE THREAD

**Issue by squarebracket** [pulumi/pulumi-kubernetes#1031]
### Problem description

Transformations on yaml files fail to set annotations on an object.

### Errors & Logs

There are none; it simply doesn't work.

### Affected product version(s)

At least 1.10.1 and 1.12.0

### Reproducing the issue

```
const albUrl = 'https://raw.githubusercontent.com/kubernetes-sigs/aws-alb-ingress-controller/v1.1.5/docs/examples/alb-ingress-controller.yaml';
const transformations = [];
transformations.push((obj: any, opts: pulumi.CustomResourceOptions) => {
  if (obj && obj.kind == 'ServiceAccount' &&
      obj.metadata.name === 'alb-ingress-controller') {
    obj.metadata.namespace = 'default';
  }
});
const alb = new k8s.yaml.ConfigFile('alb-ingress-controller-deployment', {
  file: alb2Url,
  transformations,
}, { provider });
```

You will see the annotations are not applied.

### Suggestions for a fix

I wish I had a suggestion but I do not :(

**Comment by squarebracket** [comment]
Woops, looks like this one was user error.

**Comment by shiyuhang0** [comment]
Could you please give an example on how to use correctly?
