### ISSUE TITLE
[GCP] Helm chart creation ignores the GOOGLE_CREDENTIALS service account and instead uses the default Cloud Build Service account

### ISSUE THREAD

**Issue by AgrimPrasad** [pulumi/pulumi-kubernetes#1033]
### Problem description

In our build pipeline (using Google Cloud Build), we have specified a separate service account using the `GOOGLE_CREDENTIALS` secret environment variable for use with Pulumi. This is as per the instructions from https://www.pulumi.com/docs/intro/cloud-providers/gcp/service-account/ and is required by us for proper access control.

In our entire Pulumi project, everything created by Pulumi (such as VPC, GKE k8s cluster itself etc.) uses this service account, except for the helm charts. For some reason, helm chart creation ignores this environment variable, and uses the default cloud build service account instead. Since we haven't granted any permissions to this cloud build service account (by design), our builds fail with errors mentioned in the next section. Note that this example is trying to install the [cadence helm chart](https://github.com/banzaicloud/banzai-charts/tree/master/cadence)

### Errors & Logs

```bash
Step #2:  +  kubernetes:apps:Deployment default/cadence-worker **creating failed** error: resource default/cadence-worker was not successfully created by the Kubernetes API server : deployments.apps is forbidden: User "<project-id>@cloudbuild.gserviceaccount.com" cannot create resource "deployments" in API group "apps" in the namespace "default": Required "container.deployments.create" permission.

Step #2:  +  kubernetes:core:ConfigMap default/cadence creating Retry #0; creation failed: configmaps is forbidden: User "<project-id>@cloudbuild.gserviceaccount.com" cannot create resource "configmaps" in API group "" in the namespace "default": Required "container.configMaps.create" permission.
```

### Affected product version(s)

Running the latest `pulumi/pulumi` docker image from https://hub.docker.com/r/pulumi/pulumi

`@pulumi/kubernetes` version `1.5.7`
`@pulumi/gcp` version `2.8.0`
`@pulumi/pulumi` version `1.12.0`

### Reproducing the issue

Standard helm chart installation code in typescript:

```ts
import * as helm from "@pulumi/kubernetes/helm";
.
.
.
const createChart = () => {
  const cadenceChart = new helm.v3.Chart(
    "cadence",
    {
      repo: "banzaicloud-stable",
      chart: "cadence",
      namespace: "default",
      values: {...},
	  transformations: [...]
	},
    {
      providers: { kubernetes: k8sProvider },
      dependsOn: services.get(mysqlServiceName)
    }

  return cadenceChart;
);

export let cadenceChart: helm.v3.Chart;

if (config.charts.includes("cadence")) {
  cadenceChart = createChart();
}
```

### Suggestions for a fix

`GOOGLE_CREDENTIALS` service account should always be respected.

**Comment by AgrimPrasad** [comment]
@leezen @lblackstone Any updates on this issue? 🙂

**Comment by lblackstone** [comment]
Sorry for the delay. It looks like this problem may apply to the entire k8s provider. I found this code block in the GCP provider, which indicates that the `GOOGLE_CREDENTIALS` env var isn't officially supported by the `gcloud` binary; it's specific to the GCP Terraform provider:
https://github.com/pulumi/pulumi/blob/3e7b3667eef11e88e4b8e7c544d1530b81de13f9/pkg/backend/filestate/gcpauth.go#L30-L42

@AgrimPrasad I assume that `gcloud` is responsible for authentication in your kubeconfig? If so, it looks like you might be able to use the `GOOGLE_APPLICATION_CREDENTIALS` var instead. https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable
