### ISSUE TITLE
Support Helm/YAML in Go

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#1037]
Once core Kubernetes resources are available in the Go SDK, we will need to follow up to add the Helm and YAML support to the SDK as well.

**Comment by joeduffy** [comment]
I'm going to give this a Go at our community Hackathon tomorrow (see what I did there? 😄 )

This change is a helpful comparison https://github.com/pulumi/pulumi-kubernetes/pull/980
