### ISSUE TITLE
Add apiextensions.CustomResource support to .NET SDK

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1038]
### Problem description

Support for Kubernetes `CustomResource` resources appears to be missing in the .NET SDK. This should be implemented along the lines of https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/apiextensions/CustomResource.ts

**Comment by mitchellmaler** [comment]
Not able to manage CustomResources in .NET has become a show stopper for us using Pulumi for Kubernetes. We are a .NET shop and most of our projects are written in .NET so it is not feasible to convert to a different language.

Is there an ETA on when this will be added?

**Comment by mikhailshilkov** [comment]
@mitchellmaler This will be available in the next release. Looking forward to your feedback!

**Comment by mitchellmaler** [comment]
@mikhailshilkov Perfect! Excited to give it a try.
