### ISSUE TITLE
Upcoming ambient config for namespaces could confuse engine

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#104]
In https://github.com/kubernetes/kubernetes/issues/27308 it is proposed that `KUBECTL_NAMESPACE` allow users to specify to which namespace we deploy. Because we use client-go, we get these env vars "for free". But, a lot of logic for doing things like determining delete-before-replace logic (_cf_., https://github.com/pulumi/pulumi-kubernetes/pull/103), depends on the namespaces being written statically down.

To me, this issue is not merely a matter of disabling these env vars:

- [ ] Decide whether to support these env vars, and if so, how
- [ ] If the answer is no, decide how we can make these multi-cluster/multi-namespace scenarios convenient for our users.

**Comment by hausdorff** [comment]
@lblackstone I propose to bounce this to you, if you have time, but I don't think this needs to be in M21 necessarily.

**Comment by AaronFriel** [comment]
@hausdorff @lblackstone I'm just getting started prototyping a deployment to our development cluster and the first thing I wanted to do was create a custom resource wrapping around [Stackdriver Prometheus Sidecar](https://github.com/Stackdriver/stackdriver-prometheus-sidecar/tree/master/kube) configuration, and to place that in its own namespace.

It was surprising to me that none of the k8s resources allow me to specify a namespace as an argument or input.

**Comment by lblackstone** [comment]
@AaronFriel You can specify the namespace in the `.metadata.namespace` field of any k8s resource. You're right that we don't have a namespace argument on most of the provider methods, but you could create your own classes to provide that functionality if it makes sense.

For example, something like:
```ts
function NamespacedPod(ns: string) {
    return new k8s.core.v1.Pod("example", { 
        metadata: { namespace: ns },
        // ...
    });
```

**Comment by hausdorff** [comment]
I doubt the kubernetes/kubernetes issue will actually get addressed. I think we should close this out.

**Comment by lblackstone** [comment]
Closing this out, and we can reopen if it causes problems later.
