### ISSUE TITLE
Add ability to re-create PersistentVolume with Reclaim Policy "Retain" if it has "Released" status

### ISSUE THREAD

**Issue by maxromanovsky** [pulumi/pulumi-kubernetes#1040]
### Problem description

Currently, Persistent Volumes with status `Released` are not updated/re-created, even though they cannot be re-used unless re-created manually ([Reference](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#retain)).

How about adding a logic to re-create PV if it's status  is `Released`, if `opts.delete_before_replace` is `true`?

Somewhat related to #1014 #1015

**Comment by george-ayris** [comment]
Just hit this, had to solve manually by deleting with `kubectl delete`  and `pulumi state delete`

**Comment by lukehoban** [comment]
@maxromanovsky @george-ayris If I understand the issue here, I believe https://github.com/pulumi/pulumi/issues/6753 would address this - does that sound right?  Perhaps this should also be the default for a `PersistentVolume` though?

**Comment by maxromanovsky** [comment]
@lukehoban I believe it will. PVs just look like a specific case of that wider issue you're referring to.

**Comment by lblackstone** [comment]
It looks like all of the linked issues merged and the `replaceOnChanges` option will work for this.
