### ISSUE TITLE
PriorityClassList fails to create due to: failed to determine if namespaced

### ISSUE THREAD

**Issue by CoreyLoose** [pulumi/pulumi-kubernetes#1045]
### Problem description

When creating a PriorityClassList the following error happens:
```
resource scheduler-priorities-rqaatzhi was not successfully created by the Kubernetes API server : failed to determine if the following GVK is namespaced: scheduling.k8s.io/v1, Kind=PriorityClassList
```

### Errors & Logs

This is simplest version of the code I've got that causes the error. Running just the PriorityClass piece by itself works, so the problem is definitely with the PriorityClassList
```
new k8s.scheduling.v1.PriorityClassList("scheduler-priorities", {
    items: [
        new k8s.scheduling.v1.PriorityClass("selector-spread-priority", {value: 10})
    ]
});
```

### Affected product version(s)

I'm using pulumi 1.6

**Comment by CoreyLoose** [comment]
Talked with @lblackstone a little bit in the slack

**Comment by deepio** [comment]
Same for CronJobList

**Comment by deepio** [comment]
I got something that works for me. Instead of using any *List (e.g., CronJobList, NamespaceList, PriorityClassList) try just putting them in an array.

```typescript
const cronJob = [
  new k8s.batch.v1beta1.CronJob(...),
  new k8s.batch.v1beta1.CronJob(...),
];
```
