### ISSUE TITLE
route53.get_zone doesn't work unless the zone has already been created

### ISSUE THREAD

**Issue by dieswaytoofast** [pulumi/pulumi-kubernetes#1052]
### Problem description

`route53.get_zone` doesn't work unless the zone has already been created. 
If I've already created the zone, (e.g., by commenting out the `get_zone` line in the code below), it works just fine. 
But, if the zone doesn't exist, it'll barf with the error shown below

### Errors & Logs
```
      File "/Users/mahesh/.local/share/virtualenvs/cyclope-ZNWFwu6H/lib/python3.8/site-packages/pulumi/runtime/rpc_manager.py", line 67, in rpc_wrapper
        result = await rpc
      File "/Users/mahesh/.local/share/virtualenvs/cyclope-ZNWFwu6H/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 166, in do_invoke
        resp = await asyncio.get_event_loop().run_in_executor(None, do_invoke)
      File "/Users/mahesh/.asdf/installs/python/3.8.1/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/mahesh/.local/share/virtualenvs/cyclope-ZNWFwu6H/lib/python3.8/site-packages/pulumi/runtime/invoke.py", line 164, in do_invoke
        raise Exception(details)
    Exception: invocation of aws:route53/getZone:getZone returned an error: invoking aws:route53/getZone:getZone: no matching Route53Zone found
```

### Affected product version(s)

I'm on 1.13.0

### Reproducing the issue

Here's the code
```
import pulumi
import pulumi_aws
from pulumi_aws import alb, route53

zone = route53.Zone(
        'blockfitrading-biz-record',
        name='blockfitrading.biz',
    )
print(zone.zone_id)
route53.get_zone(name='blockfitrading.biz')
```

**Comment by leezen** [comment]
Are you not able to catch this exception?

**Comment by dieswaytoofast** [comment]
Ah.
I assumed that it _wouldn't_ throw an error.
I assume that the thing to do then is to create the zones separately?

**Comment by leezen** [comment]
I think I'm missing why you create a zone and then get it in the same program? You'd typically only use a getter like `get_zone` to reference resources that aren't created in the stack. And if you've already created the zone in the stack, why aren't you able to use the `zone` object you created? Sorry if I'm not understanding your use-case.

**Comment by dieswaytoofast** [comment]
I'm creating our entire infrastructure in one stack.  e.g.
1.  create zones
2. create certificates
3. create EC2 instances, ELBs, etc.
4. profit

I'm guessing I need to do all of this in separate stacks?  Something like
- Stack "DNS"
   * Create zones
- Stack "Certificates"
   * Create certificates.
- Stack "Other Stuff"
  * Create all the dependent stuff

eh?

**Comment by leezen** [comment]
It's a matter of preference and architecture if you want to split them into separate stacks. There's nothing preventing you from doing something like:

```
  zone = route53.Zone(...)

  certificate = acm.Certificate(...)

  validation_record = route53.Record(..., certificate.domain_validation_options[0]...)
```

I see you're actually trying to do something like that in https://github.com/pulumi/pulumi-aws/issues/917 -- I'll answer your question there about doing that.

I'll close this issue as I presume you're able to create the zone and use it in the same script with other resources and it's a matter of preference for how you organize your code and stacks.
