### ISSUE TITLE
CustomResource kinds fail to update

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1061]
### Problem description

It appears that we're not handling update patches correctly for k8s `CustomResource` kinds. Notably, [this comment](https://github.com/kubernetes/kubernetes/issues/71024#issuecomment-438743207) indicates that strategic merge (our default) is not supported for `CustomResource` kinds.

I traced through our provider logic, and it looks like a valid patch is calculated (no error is returned), so it doesn't fall back to using a 3-way JSON merge patch. This patch is passed on to the Update await logic where it fails with the `UnsupportedMediaType` error.

### Errors & Logs

We've seen a few user-reported failures with messages similar to this:
```
Diagnostics:
  kubernetes:monitoring.coreos.com:Prometheus (prometheus):
    error: 1 error occurred:
    	* the Kubernetes API server reported that "monitoring/main" failed to fully initialize or become live: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json
```

### Suggestions for a fix

We should add logic to fallback to the 3-way JSON patch if an `UnsupportedMediaType` error is returned during an update. It might also be worth trying to identify `CustomResource` kinds during the initial patch calculation, and skip the strategic merge step entirely.

**Comment by fernandocarletti** [comment]
Hey guys, any news on this? It has been a quite annoying issue since it prevents a normal update from running, requiring the resource to be replaced. Thanks!

**Comment by lblackstone** [comment]
Hi @fernandocarletti -- I haven't had a chance to get back to this one yet, but it's on my TODO list. Any further information you have about reproducing the issue would be useful.

**Comment by mleclercq** [comment]
I'm having that error with the following custom resource:

```typescript

new k8s.apiextensions.CustomResource(
  'my-monitoring',
  {
    apiVersion: 'monitoring.coreos.com/v1',
    kind: 'ServiceMonitor',
    spec: {
      selector: {
        matchLabels: { app: 'my-app' },
      },
      endpoints: [
        {
          port: 'http',
          interval: '65s',
          // trying to remove the following:
          // relabelings: [
          //   {
          //     regex: '(.*)',
          //     targetLabel: 'stackdriver',
          //     replacement: 'true',
          //     action: 'replace'
          //   }
          // ],
          // trying to add the following
          metricRelabelings: [
            {
              sourceLabels: ['__name__'],
              regex: 'typhoon_(.*)',
              targetLabel: 'stackdriver',
              replacement: 'true',
              action: 'replace'
            }
          ]
        },
      ],
    },
  },
);
```

This is a service monitor CRD from prometheus-operator.
I have other CRDs for which I'm not having problems (updates of istio ones in particular works fine)

For reference, I'm using the following `ComponentResource` to deploy prometheus-operator:

```typescript

export interface PrometheusOperatorArgs {
  namespace: pulumi.Input<string>;
  version?: string;
}

export class PrometheusOperator extends pulumi.ComponentResource {
  constructor(
    name: string,
    args: PrometheusOperatorArgs,
    opts?: pulumi.ComponentResourceOptions,
  ) {
    super('automat:monitoring/v1:PrometheusOperator', name, {}, opts);

    new k8s.yaml.ConfigFile(
      name,
      {
        file: `https://github.com/coreos/prometheus-operator/raw/release-${args.version ||
          '0.38'}/bundle.yaml`,
        transformations: [
          obj => {
            if (obj.metadata.namespace) {
              obj.metadata.namespace = args.namespace;
            }
            if (obj.kind === 'ClusterRoleBinding') {
              obj.subjects[0].namespace = args.namespace;
            }
          },
        ],
      },
      { parent: this },
    );
  }
}
```

**Comment by farcaller** [comment]
Got exactly the same issue with this crd:

```
const cert = new k8s.apiextensions.CustomResource('tiddly', {
  apiVersion: 'cert-manager.io/v1alpha2',
  kind: 'Certificate',
  spec: {
    dnsNames: ['example.com'],
    secretName: 'tiddly-net-tls',
    issuerRef: {
      name: 'letsencrypt-prod',
      kind: 'ClusterIssuer',
    },
  },
}, { provider });
```

after changing `dnsNames: ['example.com']` to `dnsNames: ['example.com', '*.example.com']`.

Note that adding `deleteBeforeReplace: true` didn't help at all.

**Comment by seunggs** [comment]
Hi, still having this issue:

```
this.service = new k8s.apiextensions.CustomResource(name, {
      apiVersion: 'serving.knative.dev/v1',
      kind: 'Service',
      metadata: {
        namespace,
        name,
        labels,
      },
      spec: {
        template: {
          spec: {
            containers: [container],
          }
        },
      },
    }, { parent: this })
```

Seeing this error:
```
error: 1 error occurred:
        * the Kubernetes API server reported that "sidetrek-webapp-staging-cd3aydbs/frontend-svc" failed to fully initialize or become live: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml
```

**Comment by lblackstone** [comment]
@seunggs What version of the k8s provider are you using? Unless we've regressed somehow, this issue should be fixed in versions >= `v2.1.0`.

**Comment by seunggs** [comment]
Hi, I'm using @pulumi/pulumi ^3.10.1 and @pulumi/kubernetes: ^3.6.0.

This is definitely happening (every time I do a `pulumi up`) - maybe it is
a regression?

If you need more information for debugging I'd be happy to help.

With Knative, every deployment does a revision tracking so if I'm
not mistaken, if I have to deploy a new service every time, I can't take
advantage of this revision feature (which is a major advantage of Knative).

Thanks!

Seungchan Lee

**Comment by seunggs** [comment]
Will do thanks
Seungchan Lee

**Comment by seunggs** [comment]
Created the issue: https://github.com/pulumi/pulumi/issues/8259

Please let me know if more details are needed for this to be looked at.

Thanks!

Seungchan Lee
