### ISSUE TITLE
Helm Chart with "FetchOpts" doesn't render correctly

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1063]
### Problem description

When trying to install a helm chart using the python SDK and `fetch_opts`, the chart isn't rendered correctly. The helm template command seems to be trying to use the `.tgz` directory (which is empty)

### Errors & Logs

```
File "/Users/lbriggs/.pyenv/versions/3.8.2/lib/python3.8/subprocess.py", line 512, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['helm', 'template', '/var/folders/sl/hwz2lz290jq64tgbv102w3kc0000gn/T/tmp0ftsrjfu/cert-manager-v0.14.1.tgz', '--name-template', 'cert-manager', '--values', '/var/folders/sl/hwz2lz290jq64tgbv102w3kc0000gn/T/tmp0ftsrjfu/cert-manager-v0.14.1.tgz/values.yaml', '--values', '/var/folders/sl/hwz2lz290jq64tgbv102w3kc0000gn/T/tmpqnnz8q2t', '--namespace', 'cert-manager']' returned non-zero exit status 1.
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

### Affected product version(s)

Pulumi 1.14.0 and `pulumi-kubernetes` `1.16.0`

### Reproducing the issue

```
# Install the helm chart
helm.Chart("cert-manager", helm.ChartOpts(
    chart="cert-manager",
    namespace=ns.metadata["name"],
    values={},
    fetch_opts=helm.FetchOpts(
        repo="https://charts.jetstack.io",
    )
    ), pulumi.ResourceOptions(provider=provider) 
)
```

**Comment by lblackstone** [comment]
I believe the same bug exists in the .NET SDK as well, and the cause of the problem was that the SDK isn't handling the case where multiple files exist in the temp directory (`cert-manager` and `cert-manager.tgz`). The template command is incorrectly selecting the `.tgz` file.

This works if you don't use the `fetch_opts` setting and instead configure the local helm repo.

**Comment by jaxxstorm** [comment]
I found the issue in the python sdk, it seems here:
https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/pulumi_kubernetes/helm/v2/helm.py#L326

It seems we either:

A) assume there's only one directory in the `chart_dir` - which isn't the case:
```
ls /var/folders/sl/hwz2lz290jq64tgbv102w3kc0000gn/T/tmpxqkt9au_/
cert-manager  cert-manager-v0.14.1.tgz
```

or B) assume that the extracted chart dir is first in this array, which is [also not the case](https://docs.python.org/3/library/os.html#os.listdir)

> Return a list containing the names of the entries in the directory given by path. **The list is in arbitrary order**, and does not include the special entries '.' and '..' even if they are present in the directory.

I managed to get it working by modifying the package manually like so:

```
fetched_chart_name = os.listdir(chart_dir)[1]
```

But we might need to be more deterministic on how we get this?

**Comment by jaxxstorm** [comment]
I've looking into this some more, I found:

- This problem also exists on dotnet:

```
Diagnostics:
  kubernetes:helm.sh:Chart (cert-manager):
    error: Pulumi.ResourceException: Error: open /var/folders/sl/hwz2lz290jq64tgbv102w3kc0000gn/T/05a05ken.spa/cert-manager-v0.14.1.tgz/values.yaml: no such file or directory

       at Pulumi.Kubernetes.Helm.ChartBase.<>c__DisplayClass0_0.<.ctor>b__1(ValueTuple`2 values)
       at Pulumi.Output`1.ApplyHelperAsync[U](Task`1 dataTask, Func`2 func)
       at Pulumi.Output`1.Pulumi.IOutput.GetDataAsync()
       at Pulumi.Serialization.Serializer.SerializeAsync(String ctx, Object prop)
       at Pulumi.Deployment.SerializeFilteredPropertiesAsync(String label, IDictionary`2 args, Predicate`1 acceptKey)
       at Pulumi.Deployment.SerializeAllPropertiesAsync(String label, IDictionary`2 args)
       at Pulumi.Deployment.RegisterResourceOutputsAsync(Resource resource, Output`1 outputs)
       at Pulumi.Deployment.Runner.WhileRunningAsync()
```

It _probably_ exists on Windows with nodejs as well due to the reasons documented here:
https://github.com/nodejs/node/issues/3232
