### ISSUE TITLE
Updating StatefulSet using OnDelete UpdateStrategy results in always waiting

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-kubernetes#1066]
### Problem description

HashiCorp vault uses the `OnDelete` `UpdateStrategy` (https://github.com/hashicorp/vault-helm/issues/81). This results in having to manually delete the pods. Once the pods are deleted, and the new ones are up, Pulumi is stuck with `Waiting for StatefulSet update to roll out (2/2 Pods ready)`

### Errors & Logs

Stuck on `Waiting for StatefulSet update to roll out (2/2 Pods ready)`

**Comment by ringods** [comment]
More than a year later, we still bump into this problem:

```
15:58:30 ~ kubernetes:apps/v1:StatefulSet statefulset updating [diff: ~spec]; [1/2] Waiting for StatefulSet to create Pods (0/0 Pods ready)
15:58:30 ~ kubernetes:apps/v1:StatefulSet statefulset updating [diff: ~spec]; [1/3] Waiting for StatefulSet update to roll out (0/3 Pods ready)
15:58:40 ~ kubernetes:apps/v1:StatefulSet statefulset updating [diff: ~spec]; warning: [Pod vault-1]: containers with unready status: [vault]
15:58:40 ~ kubernetes:apps/v1:StatefulSet statefulset updating [diff: ~spec]; warning: [Pod vault-2]: containers with unready status: [vault]
15:58:40 ~ kubernetes:apps/v1:StatefulSet statefulset updating [diff: ~spec]; warning: [Pod vault-0]: containers with unready status: [vault]
15:58:55 ~ kubernetes:apps/v1:StatefulSet statefulset updating [diff: ~spec]; [1/3] Waiting for StatefulSet update to roll out (1/3 Pods ready)
15:58:58 ~ kubernetes:apps/v1:StatefulSet statefulset updating [diff: ~spec]; [1/3] Waiting for StatefulSet update to roll out (2/3 Pods ready)
15:58:58 ~ kubernetes:apps/v1:StatefulSet statefulset updating [diff: ~spec]; [1/3] Waiting for StatefulSet update to roll out (3/3 Pods ready)
16:08:30 ~ kubernetes:apps/v1:StatefulSet statefulset updating [diff: ~spec]; error: 3 errors occurred:
16:08:30 ~ kubernetes:apps/v1:StatefulSet statefulset **updating failed** [diff: ~spec]; error: 3 errors occurred:
16:08:31 pulumi:pulumi:Stack gcp-delivery running error: update failed
16:08:31 pulumi:pulumi:Stack gcp-delivery **failed** 1 error
```

@nesl247 did you find a workaround for this?
@lblackstone any news to get this fixed?

**Comment by nesl247** [comment]
No, I never found a solution for this.

**Comment by wrbbz** [comment]
There was a [similar issue](https://github.com/argoproj/argo-cd/issues/1881) in argo-cd. 
With OnDelete strategy and StatefulSets.
Maybe, there is some useful thoughts to fix this in Pulumi

**Comment by lblackstone** [comment]
Thanks for the link @wrbbz! It looks like https://github.com/argoproj/gitops-engine/pull/136/files#diff-b7f1feaa038882966a9d30e0b96e476dccccc2608dd8a660f80767dbbc635b6fR332-R337 might be what we'd need to fix this.
