### ISSUE TITLE
Failing plugin downloads for 2.1.0

### ISSUE THREAD

**Issue by jeid64** [pulumi/pulumi-kubernetes#1110]
error: [resource plugin kubernetes-2.1.0] downloading from https://api.pulumi.com/releases/plugins: 404 HTTP error fetching plugin from https://api.pulumi.com/releases/plugins/pulumi-resource-kubernetes-v2.1.0-linux-amd64.tar.gz

Did 2.1.0 get published to pypi but not added to the plugins repo?

**Comment by jeid64** [comment]
@lblackstone

**Comment by lblackstone** [comment]
Sorry about that. We had a problem with the release configuration, and are publishing v2.1.1 now. Should be available soon.

**Comment by lblackstone** [comment]
`2.1.0` kubernetes plugins are available now.
