### ISSUE TITLE
Error creating helm chart when passing provider in Go SDK

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1114]
### Problem description

When trying to create a few resource using the Go SDK, I passed a provider as a `pulumi.ResourceOption` to both a configmap and a helm chart. The code itself can be found in this gist:

https://gist.github.com/jaxxstorm/799206024d36de8ec1347d83d3f8226a

### Errors & Logs

The error thrown pulumi is 

```
error: expected '::' in provider reference ''
```

### Affected product version(s)

Affects the new pulumi-kubernetes 2.1 release

### Reproducing the issue

See the above code/snippet

**Comment by lblackstone** [comment]
I was unable to reproduce this behavior with this minimal example:

```go
package main

import (
	"io/ioutil"
	"os/user"
	"path/filepath"

	"github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/helm/v2"
	"github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/providers"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		usr, _ := user.Current()
		dir := usr.HomeDir
		kubeconfigBytes, err := ioutil.ReadFile(filepath.Join(dir, ".kube", "config"))
		if err != nil {
			return err
		}
		// provider init
		provider, err := providers.NewProvider(ctx, "k8sprovider", &providers.ProviderArgs{
			Kubeconfig: pulumi.String(kubeconfigBytes),
		})
		if err != nil {
			return err
		}
		_, err = helm.NewChart(ctx, "test", helm.ChartArgs{
			Chart:   pulumi.String("stable/nginx-ingress"),
			Version: pulumi.String("1.36.3"),
		}, pulumi.Provider(provider))
		if err != nil {
			return err
		}
		return nil
	})
}
```

**Comment by lblackstone** [comment]
@jaxxstorm Does that example work for you? I'm not sure if the error you reported requires a more complex setup, or if it's something on your end (perhaps passing the filename of the KUBECONFIG rather than the contents?)

**Comment by jaxxstorm** [comment]
@lblackstone yes, that seems to work.

I can't seem to repro it with this example, I'll try with my original stack

**Comment by lukehoban** [comment]
Sounds like we're not sure there's a repro - so closing our for now - @jaxxstorm please do reopen if you can find another repro for this.

**Comment by jaxxstorm** [comment]
I'm reopening this for now because a customer is experiencing the same issue

**Comment by jaxxstorm** [comment]
working with the customer, we figured out what this was.

the kubeconfig was being generated with a `pulumi.Sprintf` and the json being generated wasn't valid (trailing commas in the wrong place)

for anyone who finds this, it's recommended to use structs and marshal json to generate the values, example here:

https://github.com/jaxxstorm/iac-in-go/blob/master/eks/kubeConfig.go
