### ISSUE TITLE
[.NET] Fix apiextensions.CustomResource case in YAML support

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1120]
### Problem description

https://github.com/pulumi/pulumi-kubernetes/blob/cf42dd909019db18bd08aa52c31795e6bea2157d/sdk/dotnet/Yaml/Yaml.cs#L1666-L1671 is incorrect. The default case should create an `apiextensions.CustomResource` rather than a `apiextensions.v1.CustomResourceDefinition`.

It's possible that this will also require changes to the `CustomResource` implementation.

**Comment by polivbr** [comment]
I ran into this issue as well and have submitted a PR which fixes it.

**Comment by lblackstone** [comment]
Fixed by #1741
