### ISSUE TITLE
Malformed externalIPs property in Python

### ISSUE THREAD

**Issue by clstokes** [pulumi/pulumi-kubernetes#1126]
### Problem description

In Python, the `ExternalIPs` property is malformed as `external_i_ps` on https://www.pulumi.com/docs/reference/pkg/kubernetes/core/v1/service/#servicespec.

**Comment by joeduffy** [comment]
Also seems to affect `pod_i_ps`.

**Comment by lblackstone** [comment]
@praneetloke I'm guessing you would know where to look on this issue?

**Comment by praneetloke** [comment]
Hmm I suspect this is an issue with the Python name builder that the docs generator uses from the Python schema code gen.

**Comment by lblackstone** [comment]
This was fixed at some point
