### ISSUE TITLE
Helm Atomic Rollback

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi-kubernetes#1131]
Today when we deploy to Kubernetes using Helm we pass the --atomic flag so that way it rolls back after a failed release. Is this possible when using the helm integration of Pulumi?

**Comment by jaxxstorm** [comment]
@mitchellmaler this isn't possible at the moment. We don't ever interact with the Kubernetes API using the helm CLI, instead, we template the chart locally using `helm template` and apply the rendered YAML.

My understanding at the moment is that all `--atomic` does is roll back the chart release in the Secret that it stores the chart in, and the resources in the chart never actually get rolled back. Can you confirm that?

**Comment by mitchellmaler** [comment]
@jaxxstorm the --atomic will roll back all updated/new resources to the last release of it. This makes sure that a failed release does not stay running and it can always end up in a good state.

I understand that it just templates the resources so maybe this is more a bigger conversion on how can we have rollbacks on kubernetes resources that fail to deploy. Usually will be workloads that fail and need rolled back but a lot of the time the related configuration and secrets need to be rolled back to the last version as well.

**Comment by lblackstone** [comment]
Yeah, this isn't currently supported automatically, but I think the idea of atomic updates is interesting. Have you run into problems where a pulumi update left your k8s resources in a bad state?

**Comment by mitchellmaler** [comment]
Currently we use helm for all of our Kubernetes deployments. I know we want to look into moving to just native pulumi but that can't happen for all projects and wont be a quick conversion. One requirement is to have automated rollbacks on failed deployments. Many teams deployments include secrets, config maps, and networking setup. If we roll a bad deployment using pulumi it will time out on a failed deployment where new pods are crashing, not starting, etc. and usually the old ones are kept running so their configs are not reloaded but networking could have changed. We really like helms atomic flag which rolls back all changes if the deployment failed back to the last successful (usually last) release.

I know in the IaC work this rollback situation is a common issue cause do we roll everything or just some back and would require keeping track of the last successfully state compared to just the existing state. I can see it where atomic rollbacks might just not be supported in this type of process but thought to bring it up to see what is thought about it.

**Comment by patriziobrunops** [comment]
it looks like this has been implemented, or I misinterpreting the docs?
https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/#atomic_go

**Comment by mitchellmaler** [comment]
Yes this is now possible using the helm release since that just called the local helm command. I’ll close this.

**Comment by cooervo** [comment]
this is what I did to rollback with helm and pulumi

```
# get the revision number you want to go back to 
helm history example -n example 

# go back to revision 9
 helm rollback -n example example 9

# if you run pulumi update it will mark as needing change so run pulumi refresh targeted to the helm release
pulumi refresh --config-file stacks/Pulumi.example.yaml --target urn:my-urn-example

# now pulumi update should work
```
