### ISSUE TITLE
Should set recommended labels

### ISSUE THREAD

**Issue by thrixton** [pulumi/pulumi-kubernetes#1147]
### Problem description
Kubernetes has a set of [Recommended Labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/). 3 are applicable to pulumi-kubernetes. 1 is applied, 2 are not.

The `app.kubernetes.io/name` and `app.kubernetes.io/instance` labels are not applied.

### Suggestions for a fix
The 2 applicable labels should be applied based on the name of the resource and then the instance name (with suffix).

Thoughts?

**Comment by lblackstone** [comment]
@thrixton Do you have a use case for this in mind? I'm hesitant to add labels to existing resources, but it could make sense to add those labels on newly created resources.

**Comment by lblackstone** [comment]
Both of the suggested labels can be set by the user, but aren't something that the provider can infer in the same way as the `app.kubernetes.io/managed-by` label.
