### ISSUE TITLE
regression: pulumi no longer supports v1/List

### ISSUE THREAD

**Issue by Place1** [pulumi/pulumi-kubernetes#1156]
I've been using the following helm chart transformation for removing helm hooks:

```
function removeHelmTests() {
  return (obj: any) => {
    if (!obj) {
      return;
    }
    if (obj.metadata && obj.metadata.annotations && obj.metadata.annotations['helm.sh/hook']) {
      // transforms in nodejs expects you to mutate input object, not return a new one.
      // https://github.com/pulumi/pulumi-kubernetes/blob/4b01b5114df3045cecefd2ff3e2f2ed64430e3dd/sdk/nodejs/yaml/yaml.ts#L2214
      for (const key in obj) {
        delete obj[key];
      }
      Object.assign(obj, {
        kind: 'List',
        apiVersion: 'v1',
        metadata: {},
        items: [],
      });
      return null;
    }
    return;
  };
}
```

This used to work when i first wrote it because pulumi handled the v1/List type: [see the code](https://github.com/pulumi/pulumi-kubernetes/blob/4b01b5114df3045cecefd2ff3e2f2ed64430e3dd/sdk/nodejs/yaml/yaml.ts#L2237)

But now this special handling for "list" is gone: [see the code](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/yaml/yaml.ts#L2550)

I think this is a regression.

**Comment by lblackstone** [comment]
Sorry about that. I'll get that fixed shortly.
