### ISSUE TITLE
Enable using `pulumi config` to set k8s-related configuration.

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi-kubernetes#1159]
### Problem description

We currently [parse configuration values](https://github.com/pulumi/pulumi-kubernetes/blob/master/provider/pkg/provider/provider.go#L347-L441) for k8s from provided/ambient kubeconfig files.

We should enable using `pulumi config` to set these values.

Edit: To clarify, use already support using `pulumi config` for these parameters. What we don't do is expose a `config` module in our SDKs; the values are only used by the provider.

**Comment by lblackstone** [comment]
I chatted with @lukehoban about this and we agreed that this isn't something we want to do for the k8s provider at this point. Closing out for now.
