### ISSUE TITLE
Depending on Chart resources does not wait for creation to complete

### ISSUE THREAD

**Issue by jmgilman** [pulumi/pulumi-kubernetes#1164]
### Problem description

It's not clear whether this is an issue with the main Pulumi stack or just the Kubernetes API, however, the problem is that resources that depend on a Chart are still being created despite the Chart not finishing the creation process. 

### Errors & Logs

`creation failed: no matches for kind "ClusterIssuer"`

I'm deploying cert-manager via the Helm chart and then creating a `ClusterIssuer` custom resource. I have the custom resource depending on the chart, however, Pulumi still attempts to create the custom resource at the same time it makes the chart. This results in Pulumi throwing an error because the CRD gets installed with the Helm chart and it won't exist until the chart is done deploying. 

### Affected product version(s)

Pulumi: v2.4.0
Pulumi kubernetes: 2.3.0

### Reproducing the issue

[Here is an excerpt from my code](https://gist.github.com/jmgilman/ee8dc01df41fbb12d409ae1b6552a840). The chart is made on line 26 and custom resource is made on line 46. You can see the dependency of the chart being added to the custom resource on line 75. 

### Suggestions for a fix

Not clear.

**Comment by lukehoban** [comment]
I believe this is the same issue tracked in https://github.com/pulumi/pulumi-kubernetes/issues/861?

**Comment by jmgilman** [comment]
Yes, it appears to be a duplicate of that issue. Although the proposed workaround I think is not applicable in this case since child resources are not made available to pass to `depends_on`.

**Comment by jmgilman** [comment]
Closing since this is a duplicate of #861.
