### ISSUE TITLE
Problem: K8s Resources from Helm chart are prefixed with the release name

### ISSUE THREAD

**Issue by xtellurian** [pulumi/pulumi-kubernetes#1167]
### Problem description

I'm using [cert-manager by jetstack ](https://cert-manager.io/docs/installation/kubernetes/), and installing via pulumi-kubernetes. The following code (typescript) is the guts of how it works.

```ts
// cert manager crds
const certManagerVersion = "v0.15.0";
const certManagerCrds = new k8s.yaml.ConfigFile("cert-man-crds", {
    file: `https://github.com/jetstack/cert-manager/releases/download/${certManagerVersion}/cert-manager.crds.yaml`,
}, opts);

const releaseName = "cert-man";
const chartName = "cert-manager";
const certManagerChart = new k8s.helm.v3.Chart(releaseName,
    {
        chart: chartName,
        fetchOpts: {
            repo: "https://charts.jetstack.io",
        },
        namespace: certManNamespace.metadata.name,
        values: {},
        version: certManagerVersion,
    },
    {
        ...opts,
        dependsOn: certManagerCrds,
    });
```

When this chart is deployed, all the kubernetes resources are prefixed with the release name `cert-man`... For example:

```
# k get svc -n cert-manager
NAME                            TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
cert-man-cert-manager           ClusterIP   10.0.228.142   <none>        9402/TCP   162m
cert-man-cert-manager-webhook   ClusterIP   10.0.10.7      <none>        443/TCP    162m
```

The big problem is the webhook service name. Cert Manager expects the service to be called `cert-manager-webhook`. 

How can I prevent the release name being prefixed onto the Kubernetes resources?

### Affected product version(s)

pulumi 2.2.1
pulumi/kubernetes 2.2.0

**Comment by leezen** [comment]
You should be able to apply a `transformation` to modify the name. See https://www.pulumi.com/docs/guides/adopting/from_kubernetes/#configuration-transformations

**Comment by xtellurian** [comment]
Yes, that's possible.

For anyone looking what to do in this situation, I applied the following transformation to the chart

```ts
     transformations: [
          (obj: any) => {
            if (
              obj.metadata.name &&
              obj.metadata.name.startsWith(`${releaseName}-`)
            ) {
              obj.metadata.name = obj.metadata.name.slice(
                `${releaseName}-`.length
              );
            }
          },
        ],
```

**Comment by xtellurian** [comment]
I should point out that using the above transforms *does not* fix the issue.

Pulumi/Kubernetes is transforming many things in the helm chart.

@leezen  Am I supposed to figure out every change, and then reverse it with my own transform? There must be some way to prevent Pulumi manipulating the resource names, and just using vanilla Helm

**Comment by xtellurian** [comment]
Just in case anyone finds this issue, here's what I went with. 

Don't bother using the pulumi+helm combo. Just make sure you only have 1 cert-manager per Pulumi stack, and use the following:

```ts
        const certManagerVersion = "v0.15.0";
        const chartName = "cert-manager";

        const cm = new k8s.yaml.ConfigFile("cert-manager", {
            file: `https://github.com/jetstack/cert-manager/releases/download/${certManagerVersion}/cert-manager.yaml`,
        }, {
            ...opts
        })
```
