### ISSUE TITLE
Incorrect snake_case translation for certain properties.

### ISSUE THREAD

**Issue by komalali** [pulumi/pulumi-kubernetes#1179]
### Problem description

- There are a number of properties that have unexpected translations to snake_case. Examples:
  - ["non_resource_ur_ls": "nonResourceURLs"](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/pulumi_kubernetes/tables.py#L265)
  - ["pod_i_ps": "podIPs"](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/pulumi_kubernetes/tables.py#L295)
  - ["pod_cid_rs": "podCIDRs"](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/pulumi_kubernetes/tables.py#L292)

- This happens when there is an acronym e.g. "CIDR" that is pluralized with a lowercase "s" e.g. "CIDRs". The `PyName()` algorithm categorizes the "Rs" as a separate word.

- These properties are already in the SDK so merely replacing the existing values with the "correct" translation would be a breaking change.

### Suggestions for a fix

Consider the lowercase 's' a part of the acronym. https://github.com/pulumi/pulumi/pull/4918

Note: This doesn't account for backwards compatibility.

**Comment by justinvp** [comment]
I'd really like to get these "right" as part of doing https://github.com/pulumi/pulumi/issues/3771. For the generated types, we can use the "correct" naming we want and still maintain the old naming for the "old" way of doing things with untyped dicts for backwards compatibility.

**Comment by komalali** [comment]
@justinvp @lblackstone any thoughts on what we might want to do here? If we do fix the `PyName()` algorithm this will result in a breaking change for `pulumi-kubernetes`.

**Comment by justinvp** [comment]
Now's our opportunity to use the "right" names on the input/output types. I'd be in favor of fixing `PyName()` to better handle these, and then have some kind of fallback that maintains the old behavior that would only be used in the small number of places where the old names need to remain for compatibility (e.g. when generating the mapping tables).

**Comment by komalali** [comment]
> have some kind of fallback that maintains the old behavior (e.g. PyNameLegacy())

Ah interesting, yeah that sounds good to me.
