### ISSUE TITLE
: Could not create watcher for Endpoint objects associated with Service ... : unknown

### ISSUE THREAD

**Issue by z1230601** [pulumi/pulumi-kubernetes#1206]
### Problem description

I tried applying pulumi on a AWS EKS kubernetes cluster with permissions management. At first when the error occured the CI user in question had create/get/list permissions for services but not for endpoints. I then got read permissions for endpoints but I still continue to get the error:

I tried applying the annotation  "pulumi.com/timeoutSeconds": "600" which does not change behaviour at all only disabling the await leads to a successful deployment. kubectl describe services lists the endpoints correctly though. 

### Errors & Logs

    error: 1 error occurred:
    	* the Kubernetes API server reported that "..." failed to fully initialize or become live: Could not create watcher for Endpoint objects associated with Service "...": unknown

coming from service.go line 140 I assume 
pulumi logs or pulumi logs -f not working

### Affected product version(s)

pulumi version: 2.5.0
pulumi-kubernetes: 
├─┬ @pulumi/kubernetes@2.3.1
├─┬ @pulumi/kubernetesx@0.1.3
│ ├─┬ @pulumi/kubernetes@2.3.1

### Reproducing the issue

Setup k8s cluster user/role permissions on a dedicated namespace in an EKS k8s cluster so that following applies in that namespace: 
kubectl auth can-i get ep
yes
kubectl auth can-i create ep
no
kubectl auth can-i create service
yes
kubectl auth can-i get service
yes

and try to create a Service with a certificate 

```
k8sprovider as needed ... 
const appLabels = { app: "someApp" };

const cert = new aws.acm.Certificate("cert", {
    domainName: "<domainname from Zone>",
    validationMethod: "DNS",
});   
const certValidation = new aws.route53.Record("cert-validation", {
    name: cert.domainValidationOptions[0].resourceRecordName,
    records: [cert.domainValidationOptions[0].resourceRecordValue],
    ttl: 60,
    type: cert.domainValidationOptions[0].resourceRecordType,
    zoneId: selectedZone.zoneId!,
},{
    dependsOn: [cert]
});  

const service = new k8s.core.v1.Service("service", {
    kind: "Service",
    metadata: { 
        labels: appLabels, 
        name: "service", 
        annotations: {
            "service.beta.kubernetes.io/aws-load-balancer-ssl-cert": cert.arn,
            "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http",
            "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0",
            "service.beta.kubernetes.io/aws-load-balancer-type": "nlb"
        }
    },
    spec: {
        type: "LoadBalancer",
        ports: [{ port: 443, targetPort: 8080, protocol: "TCP", name: "https"}],
        selector: appLabels
    }
}, 
{
    provider: clusterProvider,
    dependsOn: [cert, deployment]
});
```

```
kubectl describe service
Name:                     service
Namespace:                service
Labels:                   app=service
                          app.kubernetes.io/managed-by=pulumi
Annotations:              pulumi.com/timeoutSeconds: 600
                          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
                          service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
                          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:<accountNr>:certificate/<certificate hash>
                          service.beta.kubernetes.io/aws-load-balancer-type: nlb
Selector:                 app=service
Type:                     LoadBalancer
IP:                       <x.x.x.x>
LoadBalancer Ingress:     <valid ingress>
Port:                     https  443/TCP
TargetPort:               8080/TCP
NodePort:                 https  30735/TCP
Endpoints:                x.x.x.x:8080,x.x.x.x:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age                From                Message
  ----    ------                ----               ----                -------
  Normal  EnsuringLoadBalancer  25m (x2 over 32m)  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   25m (x2 over 32m)  service-controller  Ensured load balancer
(I removed any sensitive information e.g. ipaddress replaced number with x)
```

### Suggestions for a fix

Endpoints are assigned to the LoadBalancer accordingly still pulumi returns an error. I do not know why I assume a permissions issue, but not quite sure. As a quick fix having the possibility to disable single watchers for (associated) resources in this case would be nice I get the service watcher for service creation I do (kind of) get the endpoint watcher although in this case its making problems i guess so I would like the possibility to disable the endpoint watcher only or document what permissions are needed for watchers generally.

**Comment by metral** [comment]
> At first when the error occurred the CI user in question had create/get/list permissions for services but not for endpoints. I then got read permissions for endpoints but I still continue to get the error

Have you tried adding `watch` to the allowed verbs for the Role in the namespace (along with `update` and `delete` to patch and delete once done)?

e.g.

```
const appsNamespace = new k8s.core.v1.Namespace("apps", undefined, {provider: cluster.provider});
const role = new k8s.rbac.v1.Role("devs",
    {
        metadata: { namespace: appsNamespace.metadata.name },
        rules: [
            {
                apiGroups: [""],
                resources: ["endpoints"],
                verbs: ["get", "list", "watch", "create", "update", "delete"],
            },
        ],
    }, { provider: cluster.provider },
);
```

If that does not help, could you please provide a more complete repro of the cluster and RBAC code so that we can try to replicate the issue?

**Comment by z1230601** [comment]
Thanks @metral . I am failry new to k8s and I never encountered kubernetes "watch" before I thought it was a polling implemented library function from pulumi-kubernetes. I added all suggested role permissions as within the namespace it should be fine I guess. Thanks works now!
