### ISSUE TITLE
Client.Timeout or context cancellation while reading body

### ISSUE THREAD

**Issue by vitobotta** [pulumi/pulumi-kubernetes#1216]
Hi!

I am using Pulumi 2.6.1 and pulumi-kubernetes 2.4.0. Almost every time I run pulumi commands to update the cluster etc it fails with this:

```
configured Kubernetes cluster is unreachable: unable to load schema information from the API server: unexpected error when reading response body. Please retry. Original error: net/http: request canceled (Client.Timeout or context cancellation while reading body)
```

However I don't have any problems at all accessing the cluster with kubectl and other tools.

What can I do?

Thanks!

**Comment by Gwojda** [comment]
Hi,
Got the same problem with `ConfigFile` from pulumi to access my cluster. dont have problem with deployment.
How did you solve this ?
