### ISSUE TITLE
Hangs at the preview stage when attempting to update cert-manager from helm chart

### ISSUE THREAD

**Issue by vitobotta** [pulumi/pulumi-kubernetes#1219]
Hi,

I am trying to update cert manager in K8s using the Helm chart, and Pulumi hangs at updating a CRD (certificates.cert-manager.io). I have also tried uninstalling it and reinstalling. It reinstalled OK, but then I tried to do update to ensure things are OK with Pulumi, and it hangs again at the preview with no errors etc. I am waiting now to see what happens but it's been a while already. Is there a default timeoyt for an update/preview action?

I've used this code so far without problems. The only difference is that I am now using the latest versions of both the pulumi binary and pulumi-kubernetes. What can I do to find out why it hangs?

Thanks

**Comment by lblackstone** [comment]
You can turn on [verbose logging](https://www.pulumi.com/docs/troubleshooting/#verbose-logging), which might shed some light on the problem. The update/preview should eventually time out.

**Comment by vitobotta** [comment]
Hi @lblackstone 

It seems to be a problem with cert manager 0.16.0 somehow - it was released today. With the previous 0.15.2 the problem doesn't happen so I have reverted for now.
