### ISSUE TITLE
feature request: support kubernetes server-side validation

### ISSUE THREAD

**Issue by zjj2wry** [pulumi/pulumi-kubernetes#1230]
### Problem description
kubectl apply --help
```
 --server-side=false: If true, apply runs in the server instead of the client.
```

i hope `pulumi preview ` can execute server-side validation, this would be help avoid some wrong PR being merged. something like `invalid name` or `xxx not allowed`. thanks you very much

- I saw an issue in the following Pulumi Program: <URL>

- I saw an issue in the following documentation: <URL>

- I had trouble finding the information that I needed: <URL>

- Other: <DETAILS>

**Comment by lukehoban** [comment]
I believe this is being tracked as part of https://github.com/pulumi/pulumi-kubernetes/issues/352.  There is also a preview feature to do server side diffing available via https://www.pulumi.com/docs/reference/pkg/kubernetes/provider/#enabledryrun_nodejs.  @lblackstone Does the existing support include doing server-side validation as well?  Or is that tracked separately anywhere?

**Comment by lblackstone** [comment]
We're already performing validation by default whenever possible:
https://github.com/pulumi/pulumi-kubernetes/blob/d7871675b54727f63f1e2254d06653daf06cc8c8/provider/pkg/provider/provider.go#L1045-L1054

This unfortunately has the limitation of not validating if the resource includes a computed value, or if the cluster is unreachable during preview.

**Comment by kwiesmueller** [comment]
Hey there,
this came up in a GitHub search for Server-Side Apply.
If you need any help implementing this, feel free to get in touch with us (wg-api-expression) on the Kubernetes slack: https://kubernetes.slack.com/archives/C0123CNN8F3

**Comment by nesl247** [comment]
Is there any update on this? We're having our developers have more and more access to submitting PRs, and we're finding that because they can't run preview themselves, more errors are being introduced for things we can't tell via code review. One thing that bit us just today was using a non-standard cron schedule. By looking at it, it looks perfectly valid, but it isn't in Kubernetes.

**Comment by lblackstone** [comment]
You can opt in to server-side apply today using the https://www.pulumi.com/docs/reference/pkg/kubernetes/provider/#enabledryrun_go flag, but it isn't well tested yet, and likely has some bugs. Finishing this is still high on the priority list, but no updates beyond that for now. If you do enable the feature flag, please file issues for any bugs you encounter.

**Comment by lblackstone** [comment]
> @lblackstone Is there any way to know if that flag has been properly picked up by pulumi (some way to verify it's working)?

The logs should include messages of the form `calculated diffs for [namespace/name] using dry-run` if it's enabled, or `calculated diffs for [namespace/name] using inputs only` if not.

**Comment by lblackstone** [comment]
Server-side apply/diff support can be enabled using the [enableServerSideApply](https://www.pulumi.com/registry/packages/kubernetes/api-docs/provider/#enableserversideapply_nodejs) Provider flag, so I'll close this as fixed.
