### ISSUE TITLE
Unable to suppress Kubernetes deprecation warnings via provider configuration.

### ISSUE THREAD

**Issue by Sodki** [pulumi/pulumi-kubernetes#1244]
### Problem description

Using Python I'm unable to suppress Kubernetes deprecation warnings via `suppress_deprecation_warnings` on the provider.

### Errors & Logs

I still have deprecation errors:

```
Diagnostics:
  kubernetes:apiregistration.k8s.io:APIService (v1beta1.metrics.k8s.io):
    warning: apiregistration.k8s.io/v1beta1/APIService is deprecated by apiregistration.k8s.io/v1/APIService.
```

The error don't show up if I use the environment variable `PULUMI_K8S_SUPPRESS_DEPRECATION_WARNINGS` instead.

### Affected product version(s)

Pulumi version: v2.8.2
Pulumi-kubernetes version: v2.4.2

### Reproducing the issue

```
provider = kubernetes.Provider(k8s-provider,
    kubeconfig=kubeconfig,
    namespace="default",
    suppress_deprecation_warnings=True)

kubernetes.yaml.ConfigFile("metrics-server",
    file_id="https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.7/components.yaml",
    opts=pulumi.ResourceOptions(provider=provider))
```

**Comment by viveklak** [comment]
@Sodki thanks for the detailed bug report. Confirmed this is an issue and will update with a fix shortly.
