### ISSUE TITLE
Auto-generate libraries for all operators/CRDs in community-managed operator-framework/community-operators

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#1261]
We recently added the `crd2pulumi` tools, which is a nice way to generate a strongly typed wrapper around a CRD.  However, users need to find the tool, download it, run it, check in the generated code and own it, re-run it on every future update to the CRD version, etc.  Moreover, while it helps provide wrappers over the CRD and the CRs, it does not help make it easier to install the Operators themselves that power these - so users still have to find bespoke instructions for that for each operator (Helm chart, etc.).

An option for addressing these remaining issues in a scalable way is to auto-generate the CRs, CRDs, and possibly even the deployments of the Operators based on the metadata that is captured in https://github.com/operator-framework/community-operators (or possibly another open registry if there are others out there that are now, or in the future become, more complete).

https://github.com/operator-framework/community-operators powers https://operatorhub.io/ today, and has 148 operators managed there, with versioning for all operators, active community contribution, and schematization of both the CRD metadata needed for `crd2pulumi` - but also the information needed to install the corresponding Operator that powers the CRD if we want to use it (e.g. https://github.com/operator-framework/community-operators/blob/master/upstream-community-operators/cockroachdb/3.0.7/cockroachdb.v3.0.7.clusterserviceversion.yaml#L225-L347).  

In theory, we could auto-generate a Pulumi library from this that provided easy access to all of these (without the need for unreliable Helm charts, etc.) including all versions and strongly typed APIs in all Pulumi languages.

**Comment by justinvp** [comment]
We've generated these at https://github.com/pulumi/pulumi-kubernetes-crds
