### ISSUE TITLE
Kubernetes resources don't take CustomResourceOptions

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#127]
The primary motivation for adding custom providers is so that you can provision a Kubernetes cluster and then deploy resources on top of it. Sadly, it appears that for this to work without compilation errors, we need to update the Kubernetes types to accept `CustomResourceOptions`, rather than just `ResourceOptions`, similar to https://github.com/pulumi/pulumi-terraform/pull/228.

```
λ tsc
index.ts:14:6 - error TS2345: Argument of type '{ provider: Provider; }' is not assignable to parameter of type 'ResourceOptions'.
  Object literal may only specify known properties, and 'provider' does not exist in type 'ResourceOptions'.

14 }, { provider: k8sProvider });
        ~~~~~~~~~~~~~~~~~~~~~
```

Please let's ensure we hit the core Kubernetes types in addition to the Helm ones.

**Comment by lukehoban** [comment]
Yes - this was a late break on Friday that was fixed for TF providers yesterday, but we must take a fix for Kubernetes as well.

**Comment by joeduffy** [comment]
I thought I'd be able to fool the compiler and simply pass the properties to my Helm Chart, but it appears to be more difficult than that:

`info: error: [runtime] Explicit providers may not be used with component resources`

I guess the `ComponentResource `is supposed to pull out the provider, pass it to all of its child resources, and make sure it doesn't include the `provider` property in its `super` call?

This is the offending code snippet, in case I'm doing something that isn't meant to work:

```typescript
import * as helm from "@pulumi/kubernetes/helm";
import { k8sProvider } from "./cluster";

const nginx = new helm.v2.Chart("nginx", {
    repo: "stable",
    chart: "nginx-lego",
    version: "0.31.",
}, <any>{ provider: k8sProvider });
```

**Comment by lukehoban** [comment]
This was fixed with https://github.com/pulumi/pulumi-kubernetes/pull/129.

With those changes - you can do the following (since `Chart` is a component):

```typescript
import * as helm from "@pulumi/kubernetes/helm";
import { k8sProvider } from "./cluster";

const nginx = new helm.v2.Chart("nginx", {
    repo: "stable",
    chart: "nginx-lego",
    version: "0.31.0",
}, { providers: { kubernetes: k8sProvider } });
```
