### ISSUE TITLE
Helm context not found

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi-kubernetes#1288]
```
error: Error: Command failed: helm fetch kured --untar --version 2.1.1 --destination C:\Users\barcl\AppData\Local\Temp\tmp-4776ZcB0780Cshns --repo https://weaveworks.github.io/kured
helm.go:71: invalid configuration: context was not found for specified context: s365-uat-ukw-cluster-admin
```

I'm trying to use Helm to deploy to multiple AKS clusters (within the same script, see issue pulumi/pulumi#2587), but running into the above error.

I may misunderstand how the Helm integration works, but from previous experience when deploying the same application to a single cluster it "just worked".

## Expected Behavior

I can use Helm to deploy charts without managing context / Helm itself.

## Current Behavior

Deployment fails with the above error.

## Steps to Reproduce

Attempt to deploy the same Helm release to multiple different clusters at the same time, using the below resource definition:

````ts
        const kuredNamespace = new k8s.core.v1.Namespace(
            r.pulumiName('kured'),
            {
                metadata: {name: 'kured'},
            },
            {
                provider,
            });

        new k8s.helm.v2.Chart(r.pulumiName('kured'),
            {
                namespace: kuredNamespace.metadata.name,
                resourcePrefix: r.shortName,
                chart: 'kured',
                fetchOpts: {
                    repo: 'https://weaveworks.github.io/kured',
                },
                version: '2.1.1', // kubernetes 1.16/1.17/1.18, Kured v1.4.5
                values: {
                    nodeSelector: {
                        'kubernetes.io/os': 'linux',
                    },
                },
            },
            {provider});
    });
````

Note that `r.pulumiName` is a function that will generate a region-specific name (i.e. `ukwest-kured`)

## Context (Environment)
OS: Windows 10
Pulumi version: v2.9.2
Packages:

```
  "devDependencies": {
    "@pulumi/azure": "^3.19.0",
    "@pulumi/azuread": "^2.5.1",
    "@pulumi/cloudflare": "^2.5.0",
    "@pulumi/docker": "^2.3.0",
    "@pulumi/kubernetes": "^2.5.1",
    "@pulumi/kubernetesx": "^0.1.3",
    "@pulumi/pulumi": "^2.9.2",
    "@pulumi/random": "^2.3.1",
    "@pulumi/tls": "^2.3.0",
  },
```

**Comment by lblackstone** [comment]
I'm not sure how you're setting that context, but the error is coming from the Helm CLI, so I don't think this problem is specific to Pulumi's Helm support.

**Comment by barclayadam** [comment]
I have not manually touched the Helm CLI all the time I have been using Pulumi, I've wanted to treat it as a black-box and allow Pulumi to completely manage it.

I would have expected by providing the `provider` (a `k8s.Provider`), configured with `kubeconfig` to a specific cluster, that it would direct Helm to use that and only that, and therefore the ambient configuration of helm / kubectl would not matter. Is that not the case?

I believe that context it complains about is an old cluster that has since been deleted (also managed by Pulumi).

**Comment by barclayadam** [comment]
The reason for the error was because I had removed a context from kubectl that helm had reference to. Just running `helm` at the command line resulted in the same error.

To isolate the use of `helm` within `pulumi` would it make sense to, if a provider is given for a specific `kubeconfig,` to specify to helm through CLI arguments to use kubeconfig and/or context. As even calling the `fetch` command, as seen here, fails.

I understand it's not really pulumi's job to ensure helm is in a good state, but if it can isolate itself from the ambient environment would make for a more reliable experience

**Comment by lblackstone** [comment]
Glad to hear you solved the problem, and also to report that we're in the process of cutting the Helm CLI out of the loop entirely! https://github.com/pulumi/pulumi-kubernetes/issues/920

For the v3 SDK, the CLI will no longer be involved.
