### ISSUE TITLE
crd2pulumi does not work with ECK CRDs

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi-kubernetes#1299]
Download this yaml which contains all the CRD definitions for Elastic Cloud on Kubernetes: 
https://github.com/elastic/cloud-on-k8s/blob/15a5fd79d4b96dadfa45bbc6cf1d116b7da97e03/hack/manifest-gen/assets/charts/eck/crds/all-crds.yaml

Try to generate static crds for nodejs:  `crd2pulumi nodejs all-crds.yaml`.
It fails with this error: 
`error: could not generate files for all-crds.yaml: could not generate files for nodejs: could not create package: could not import spec: binding types: type kubernetes:apm.k8s.elastic.co/v1beta1:ApmServer must be an object, not a`

crd2pulumi version: v1.1.0
OS: Debian Bullseye under WSL2
Binary: linux-amd64

**Comment by albert-zhong** [comment]
@ncsibra Thanks for catching this! 

I just fixed this in the latest commit to `crd2pulumi`, which has moved to a stand-alone repo at [pulumi/crd2pulumi](https://github.com/pulumi/crd2pulumi). To build the latest version, you can clone the repo and run `make rel-linux` to compile the executable.

The command has changed slightly, so now you can run:
```bash
$ crd2pulumi -n all-crds.yaml
``` 
Or, if you want them to get generated in an `eck` folder:
```bash
$ crd2pulumi --nodejsPath ./eck all-crds.yaml
```
