### ISSUE TITLE
question: health checking

### ISSUE THREAD

**Issue by ghostsquad** [pulumi/pulumi-kubernetes#1319]
What part of the code is responsible for health checking? I browsed around, but I couldn't find the logic for example of when a Pod or Deployment becomes healthy

**Comment by leezen** [comment]
The documentation on https://www.pulumi.com/docs/reference/pkg/kubernetes/apps/v1/deployment/ provides some details on when deployment resources are considered created.

**Comment by ghostsquad** [comment]
@leezen I'm looking for the actual _code_ that does the health checking.
