### ISSUE TITLE
Kubernetes secrets created by helm are saved as plaintext in the state

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi-kubernetes#1353]
It seems that pulumi doesn't encrypt the data property of Kubernetes secrets when it is saved to the state. 
I'm doing the following to deploy charts:

```
helmv3.NewChart(ctx, deploymentName, chartArgs, pulumi.Provider(p))
```

I tried using local file backend and s3 backend and had the same result.
My encryption provider is `passphrase`

**Comment by lblackstone** [comment]
I tested this out, and it seems to be working as expected for me:

1. The Secret outputs (`data` and `stringData`) were properly masked/encrypted in the state
1. Exporting the `.Data` field did not reveal the secret in the terminal (`secret: "[secret]"`)

 I did notice that the input field in the statefile will contain the secret string in plaintext if you don't have it marked as secret, so perhaps that was the issue you were seeing?

Here's the program I tested:
```go
package main

import (
	"fmt"

	corev1 "github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/core/v1"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {

		val, ok := ctx.GetConfig("go-passphrase:test")
		if !ok {
			return fmt.Errorf("missing expected config: test")
		}

		secret, err := corev1.NewSecret(ctx, "test", &corev1.SecretArgs{
			StringData: pulumi.StringMap{
				"test": pulumi.ToSecret(val).(pulumi.StringOutput),
			},
		})
		if err != nil {
			return err
		}
		ctx.Export("secret", secret.Data)

		return nil
	})
}
```

I created the config value with the following:

```sh
pulumi config set test foobar --secret
```

Here's the resulting state:
```json
{
    "version": 3,
    "deployment": {
        "manifest": {
            "time": "2020-10-12T14:55:48.163619-06:00",
            "magic": "98f78d57683dc19b6e286aab23b466609878e712bd0deda86789fe3abe0f8146",
            "version": "v2.11.2"
        },
        "secrets_providers": {
            "type": "passphrase",
            "state": {
                "salt": "v1:EQVleCdv9FM=:v1:Qr9ZMlSy0AdlsPdp:rERnXfkwdwT9GOmLLSg9guvzxLxK5A=="
            }
        },
        "resources": [
            {
                "urn": "urn:pulumi:dev::go-passphrase::pulumi:pulumi:Stack::go-passphrase-dev",
                "custom": false,
                "type": "pulumi:pulumi:Stack",
                "outputs": {
                    "secret": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "v1:sbDgE3TUzr0hKSwe:lnMYmYe8MUCLD6I4IBM7K/NCITNI4e9ERfhyBkjZQSlvY0U="
                    }
                }
            },
            {
                "urn": "urn:pulumi:dev::go-passphrase::pulumi:providers:kubernetes::default",
                "custom": true,
                "id": "cd63e3f2-fd08-4061-b84a-791f60e03363",
                "type": "pulumi:providers:kubernetes",
                "inputs": {
                    "version": "2.5.1"
                },
                "outputs": {
                    "version": "2.5.1"
                }
            },
            {
                "urn": "urn:pulumi:dev::go-passphrase::kubernetes:core/v1:Secret::test",
                "custom": true,
                "id": "default/test-fj5j6gc1",
                "type": "kubernetes:core/v1:Secret",
                "inputs": {
                    "apiVersion": "v1",
                    "kind": "Secret",
                    "metadata": {
                        "annotations": {
                            "pulumi.com/autonamed": "true"
                        },
                        "labels": {
                            "app.kubernetes.io/managed-by": "pulumi"
                        },
                        "name": "test-fj5j6gc1"
                    },
                    "stringData": {
                        "test": {
                            "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                            "ciphertext": "v1:xK9KiHyPzoxDYApK:RWEiaa+0Ky4u/4yzSdRxeJKa2CGdxOu5"
                        }
                    }
                },
                "outputs": {
                    "__initialApiVersion": "v1",
                    "__inputs": {
                        "apiVersion": "v1",
                        "kind": "Secret",
                        "metadata": {
                            "annotations": {
                                "pulumi.com/autonamed": "true"
                            },
                            "labels": {
                                "app.kubernetes.io/managed-by": "pulumi"
                            },
                            "name": "test-fj5j6gc1"
                        },
                        "stringData": {
                            "test": {
                                "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                                "ciphertext": "v1:kqoXS1p/1WuzX4JX:gL0ixYEYdv5O0KFcsmaDOp51DII4PNSl"
                            }
                        }
                    },
                    "apiVersion": "v1",
                    "data": {
                        "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                        "ciphertext": "v1:7TE4cX2ur2Zk6yOX:tlxkAKp73ClEmIsXqIJSH8GXRn0QI2fx2VmzOJjT3G/bFEyqDEFaiuLgJJgetFM1Dwt2KFnUIPelo7a9KgvcThuPRTOcDbNJ34P+kCjg7ufd+bmpYt5cS45TNkCtJT535w+R4Z9GJ0HWQWKAmOdWlhZsPPMl16YFQEf8GA=="
                    },
                    "kind": "Secret",
                    "metadata": {
                        "annotations": {
                            "kubectl.kubernetes.io/last-applied-configuration": {
                                "4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
                                "ciphertext": "v1:WtECzeJ12SUkRtC4:bJz00nGT3G4xBhIKcxt+9l92DbD7qo3DbCMIk0UWusX4ydQKO28nCaBXHI4Yv5EIERZUlm/q16al9/NMIMiXmpJGr4buFnpJDuyvViwP5ZF6Jjr99nhmfOuvNZHbtnxq8fa0dJYNszUMXtAiB3WZ8pIlmNNeOubMFw6o7moMxyUvx80I1yQ9gwcXel9XaOwO6OhKwHg+bW+FN7xA491MZR1nysh0EbVSt5OPpO+N3PMELdyCs4Ox+o816s95zRVskMNyQowZu9yvYkg3CtwSpLOVqfQqpwZ6oRRV2qFzgXoKGzKM4F+P1g8rxwxBG7fi8tfhfbYV2NnZxZA="
                            },
                            "pulumi.com/autonamed": "true"
                        },
                        "creationTimestamp": "2020-10-12T20:55:48Z",
                        "labels": {
                            "app.kubernetes.io/managed-by": "pulumi"
                        },
                        "managedFields": [
                            {
                                "apiVersion": "v1",
                                "fieldsType": "FieldsV1",
                                "fieldsV1": {
                                    "f:data": {
                                        ".": {},
                                        "f:test": {}
                                    },
                                    "f:metadata": {
                                        "f:annotations": {
                                            ".": {},
                                            "f:kubectl.kubernetes.io/last-applied-configuration": {},
                                            "f:pulumi.com/autonamed": {}
                                        },
                                        "f:labels": {
                                            ".": {},
                                            "f:app.kubernetes.io/managed-by": {}
                                        }
                                    },
                                    "f:type": {}
                                },
                                "manager": "pulumi-resource-kubernetes",
                                "operation": "Update",
                                "time": "2020-10-12T20:55:48Z"
                            }
                        ],
                        "name": "test-fj5j6gc1",
                        "namespace": "default",
                        "resourceVersion": "721442",
                        "selfLink": "/api/v1/namespaces/default/secrets/test-fj5j6gc1",
                        "uid": "4f29a4ef-469d-4b67-9fc6-60a808af1c5b"
                    },
                    "type": "Opaque"
                },
                "parent": "urn:pulumi:dev::go-passphrase::pulumi:pulumi:Stack::go-passphrase-dev",
                "provider": "urn:pulumi:dev::go-passphrase::pulumi:providers:kubernetes::default::cd63e3f2-fd08-4061-b84a-791f60e03363",
                "propertyDependencies": {
                    "apiVersion": [],
                    "kind": [],
                    "stringData": []
                },
                "additionalSecretOutputs": [
                    "data",
                    "stringData"
                ]
            }
        ]
    }
}
```

**Comment by yarinm** [comment]
This is an example of part of my state:

```
{
  "urn": "urn:pulumi:test::test::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Secret::default/datadog-agent-key",
  "custom": true,
  "id": "default/datadog-agent-key",
  "type": "kubernetes:core/v1:Secret",
  "inputs": {
    "apiVersion": "v1",
    "data": {
      "api-key": "THIS IS PLAIN VALUE"
    },
    "kind": "Secret",
    "metadata": {
      "name": "datadog-agent-key",
      "namespace": "default"
    },
    "type": "Opaque"
  },
  "outputs": {
    "__initialApiVersion": "v1",
    "__inputs": {
      "apiVersion": "v1",
      "__inputs": {
        "apiVersion": "v1",
        "data": {
          "api-key": "THIS IS PLAIN VALUE"
        },
        "kind": "Secret",
        "metadata": {
          "labels": {
            "name": "datadog-agent-key",
            "namespace": "default"
          },
          "type": "Opaque"
        },
        "apiVersion": "v1",
        "data": {
          "api-key": "THIS IS PLAIN VALUE"
        },
        "kind": "Secret",
        "metadata": {
          "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"data\":{\"api-key\":\"THIS IS PLAIN VALUE\"},\"kind\":\"Secret\",\"metadata\":{\"labels\":{\"app.kubernetes.io/instance\":\"test-secrets\",\"app.kubernetes.io/managed-by\":\"pulumi\",\"app.kubernetes.io/name\":\"test-secrets\",\"app.kubernetes.io/version\":\"1.16.0\",\"helm.sh/chart\":\"test-secrets-0.1.0\"},\"name\":\"datadog-agent-key\",\"namespace\":\"default\"},\"type\":\"Opaque\"}\n"
          },
          "creationTimestamp": "2020-10-11T13:15:09Z",
          "name": "datadog-agent-key",
          "namespace": "default",
          "resourceVersion": "1296443",
          "selfLink": "/api/v1/namespaces/default/secrets/datadog-agent-key",
          "uid": "a8e3ca8a-e0bf-4ba8-8430-1a96e2319504"
        },
        "type": "Opaque"
      },
      "parent": "urn:pulumi:test::test::kubernetes:helm.sh/v3:Chart::test-secrets",
      "provider": "urn:pulumi:test::test::pulumi:providers:kubernetes::eks::9c913767-6a0e-47ac-88e5-526e8392cf95",
      "propertyDependencies": {
        "apiVersion": [],
        "data": [],
        "kind": [],
        "metadata": [],
        "type": []
      },
      "aliases": [
        "urn:pulumi:test::test::kubernetes:helm.sh/v2:Chart$kubernetes:core/v1:Secret::default/datadog-agent-key"
      ]
    },
```
I replaced the secret value with `THIS IS PLAIN VALUE`

As you can see it misses in several spots.

Also notice that I talked about **helm** deployment and not creating secrets directly (that worked)

**Comment by mcBIG** [comment]
I have encountered same issue. I even tried to add additinalSecretOutputs but apparantly it doesn't apply to that.

`{
				"urn": "urn:pulumi:[stackname]::kubernetes:core/v1:Namespace$pulumi:providers:kubernetes$core-core:k8s:namespace$kubernetes:core/v1:Secret::bob-core-kv-secret",
				"custom": true,
				"id": "icbob5-bob/bob-core-kv-secret-gmskmg48",
				"type": "kubernetes:core/v1:Secret",
				"inputs": {
					"apiVersion": "v1",
					"kind": "Secret",
					"metadata": {
						"annotations": {
							"pulumi.com/autonamed": "true"
						},
						"labels": {
							"app": "bob-core",
							"app.kubernetes.io/managed-by": "pulumi"
						},
						"name": "bob-core-kv-secret-gmskmg48",
						"namespace": "icbob5-bob"
					},
					"stringData": {
						"clientid": "cc706a65-24b6-4f0e-b2d9-1ba4f08b05c5",
						"clientsecret": {
							"4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
							"ciphertext": "[encrypted value]"
						}
					},
					"type": "azure/kv"
				},
				"outputs": {
					"__initialApiVersion": "v1",
					"__inputs": {
						"apiVersion": "v1",
						"kind": "Secret",
						"metadata": {
							"annotations": {
								"pulumi.com/autonamed": "true"
							},
							"labels": {
								"app": "bob-core",
								"app.kubernetes.io/managed-by": "pulumi"
							},
							"name": "bob-core-kv-secret-gmskmg48",
							"namespace": "icbob5-bob"
						},
						"stringData": {
							"clientid": "cc706a65-24b6-4f0e-b2d9-1ba4f08b05c5",
							"clientsecret": "[plain text value]"
						},
						"type": "azure/kv"
					},
					"apiVersion": "v1",
					"data": {
						"4dabf18193072939515e22adb298388d": "1b47061264138c4ac30d75fd1eb44270",
						"ciphertext": "[encrypted value]"
					},
					"kind": "Secret",
					"metadata": {
						"annotations": {
							"kubectl.kubernetes.io/last-applied-configuration": [ configuration with values in plain text ],
							"pulumi.com/autonamed": "true"
						},
						"creationTimestamp": "2020-09-10T10:51:17Z",
						"labels": {
							"app": "bob-core",
							"app.kubernetes.io/managed-by": "pulumi"
						},
						"name": "bob-core-kv-secret-gmskmg48",
						"namespace": "icbob5-bob",
						"resourceVersion": "2604632",
						"selfLink": "/api/v1/namespaces/icbob5-bob/secrets/bob-core-kv-secret-gmskmg48",
						"uid": "6ad641bc-8759-4555-9bdb-e4394f828db9"
					},
					"type": "azure/kv"
				},
				"parent": "urn:pulumi:[stackname]::kubernetes:core/v1:Namespace$pulumi:providers:kubernetes$core-core:k8s:namespace::icbob5-bob-resource",
				"dependencies": [
					"urn:pulumi:[stackname]::kubernetes:core/v1:Namespace$pulumi:providers:kubernetes$core-core:k8s:namespace$infra-cxm:bob:bob$azuread:index/application:Application$azuread:index/servicePrincipal:ServicePrincipal::icbob5-bob-sp",
					"urn:pulumi:[stackname]::kubernetes:core/v1:Namespace$pulumi:providers:kubernetes$core-core:k8s:namespace$infra-cxm:bob:bob$azuread:index/application:Application$random:index/randomPassword:RandomPassword::icbob5-bob-pass",
					"urn:pulumi:[stackname]::kubernetes:core/v1:Namespace::icbob5-bob"
				],
				"provider": "urn:pulumi:[stackname]::kubernetes:core/v1:Namespace$pulumi:providers:kubernetes::icbob5-bob-provider::b5a6fda9-f673-41fa-bdf3-e8aed7b6b549",
				"propertyDependencies": {
					"apiVersion": null,
					"kind": null,
					"metadata": [
						"urn:pulumi:[stackname]::kubernetes:core/v1:Namespace::icbob5-bob"
					],
					"stringData": [
						"urn:pulumi:[stackname]::kubernetes:core/v1:Namespace$pulumi:providers:kubernetes$core-core:k8s:namespace$infra-cxm:bob:bob$azuread:index/application:Application$azuread:index/servicePrincipal:ServicePrincipal::icbob5-bob-sp",
						"urn:pulumi:[stackname]::kubernetes:core/v1:Namespace$pulumi:providers:kubernetes$core-core:k8s:namespace$infra-cxm:bob:bob$azuread:index/application:Application$random:index/randomPassword:RandomPassword::icbob5-bob-pass"
					],
					"type": null
				},
				"additionalSecretOutputs": [
					"metadata.annotations",
					"__inputs.stringData",
					"data",
					"stringData"
				]
			},`

**Comment by yarinm** [comment]
@mcBIG it makes sense that `additionalSecretOutputs` won't work here because it's a direct output field of the helm chart module

**Comment by lblackstone** [comment]
> Also notice that I talked about helm deployment and not creating secrets directly (that worked)

Oh, I bet I know what the problem is. I think the values are being expanded into YAML by Helm, which loses context about the "secretness" of any values.

Two possible workarounds:

1. You might be able to use a transformation to set the secret value on the Secret resource. I haven't tested this, but the transformation happens in the context of the Pulumi SDK rather than in Helm, so it seems plausible.
1. You could use a transformation to [omit the Secret resource](https://www.pulumi.com/docs/reference/pkg/kubernetes/helm/v3/chart/#chart-with-transformations), and create it directly with Pulumi instead. 

I'll have to think some more to see if there's a way to preserve secretness of values passed to Helm without requiring user intervention.

**Comment by lblackstone** [comment]
Related: https://github.com/pulumi/pulumi-kubernetes/issues/999

**Comment by yarinm** [comment]
@lblackstone I think the default approach should be that any kubernetes secret generated by helm is considered as secret value that needs to be encrypted.

**Comment by nesl247** [comment]
Is there any update to this, or a plan? The security around pulumi has been a struggle for a long time (though it's slowly getting better). I would hope these types of issues were made higher priority.

**Comment by lblackstone** [comment]
> Is there any update to this, or a plan?

Nothing new to report, but we are planning to increase focus on known quality issues this quarter. This is on the k8s TODO list.
