### ISSUE TITLE
Enhancement Request: Be able to control the app.kubernetes.io/managed-by label

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-kubernetes#1357]
### Problem description

As a provider, I sometimes need to deploy infrastructure into a customer's environment.
In those cases, I would like to control the `app.kuberenetes.io.managed-by:pulumi`  label that is applied by the Pulumi K8s provider to use my company or project name.

![image](https://user-images.githubusercontent.com/2699172/96587818-7021c880-12a8-11eb-867d-e8475106aad3.png)

### Errors & Logs

N/A

### Affected product version(s)
2.6.3

### Reproducing the issue
- Deploy a namespace via Pulumi K8s provider
- See labels in K8s dashboard.

### Suggestions for a fix

At a minimum provide a mechanism to overwrite the label after the initial deployment.
But, optimally, provide a mechanism to inject the preferred label value as part of the deployment.

**Comment by hausdorff** [comment]
This is a good idea. Kubernetes generally [recommends](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) a `managed-by` label, a lot of tools have standardized on it, and it would be cheap to add in implementation cost.

**Comment by infin8x** [comment]
@stack72 confirming: this seems to have been done and merged, right? Please reopen if not.

@clstokes Snapblocs was interested in this.

**Comment by stack72** [comment]
@infin8x yes we delivered something in this area - any further work here can be scheduled as appropriatly

**Comment by MitchellGerdisch** [comment]
Issues are being seen when using PULUMI_KUBERNETES_MANAGED_BY_LABEL env variable. 
Here's the scenario:
1. Run `PULUMI_KUBERNETES_MANAGED_BY_LABEL=mycompany pulumi up` and deploy the stack. 
As expected, pulumi has changed the app.kubernetes.io/managed-by: "mycompany".
2. If some iterative deployments using the same command `PULUMI_KUBERNETES_MANAGED_BY_LABEL=mycompany pulumi up` are run, we see state diff showing app.kubernetes.io/managed-by: company as deleted.
It doesn't matter how many times we try the same command above, pulumi is not able to recognize the env variable and hence it's not updating the managed by label.
