### ISSUE TITLE
Support "List" resources?

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi-kubernetes#1382]
I've been trying to install the helm chart [aad-pod-identity](https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity)

One of the features of the chart is to deploy multi CRs using the override `azureIdentities`, the chart translate that list to a list of resources using `List` kubernetes resource type - You can see it [here](https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/templates/identities.yaml)

Currently pulumi-kubernetes fails because `List` doesn't have a `.metadata.name` but in fact it doesn't need to.

This assertion could be easily fixed but what concerns me is that kubernetes translates this single resource to multiple ones, and I think pulumi wouldn't handle the state properly (it will only save the "List" resource) while it doesn't exist in kubernetes.

Currently my workaround to solve this is to not use the chart's ability to generate azure identities and I'm creating them myself using pulumi with `NewCustomResource()`

**Comment by lblackstone** [comment]
This was fixed by #1457
