### ISSUE TITLE
Resource failed to initialize warning is not actionable

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#141]
I had a stack that failed to provision, due to two issues: (1) a timeout and (2) a ReplicaSet not being created (but which was actually created -- possibly also a timeout?) This left my stack in a state where no matter what I did, running `up` led to the following output

```
$ pulumi up
Previewing update of stack 'k8s-guestbook-dev'
Previewing changes:

     Type                           Name                             Plan          Info
 *   pulumi:pulumi:Stack            k8s-guestbook-k8s-guestbook-dev  no change
 *   └─ kubernetes:apps:Deployment  frontend                         no change     1 warning

Diagnostics:
  kubernetes:apps:Deployment: frontend
    warning: This resource failed to initialize in a previous deployment. It is recommended
             to update it to fix these issues:
               - Problem #1 Timeout occurred for 'frontend'
               - Problem #2 Updated ReplicaSet was never created

info: no changes required:
      7 resources unchanged
```

It was not clear to me how to proceed. The message says "It is recommended to update it to fix these issues:", and then proceeded to give me two issues that aren't immediately obviously fixable.

@hausdorff instructed me to run `refresh`, which I did, and that failed for a different reason, however if this is the suggested course of action to take, we should explicitly say that.

I found the whole experience here very bizarre, especially after growing accustomed to working with AWS resources where we "never" timeout waiting for a resource, except for bugs.

**Comment by hausdorff** [comment]
This should be resolved with #174.
