### ISSUE TITLE
Failed to generate YAML for specified Helm chart

### ISSUE THREAD

**Issue by aaronhayes** [pulumi/pulumi-kubernetes#1411]
Getting this error when trying to update my stack - occurs on `pulumi up` and `pulumi preview` . I'm not sure if it's a pulumi related issue - I posted in the Slack channel asking for help - but thought having it here helps others. Any advice is much appreciated as I can no longer update my stack! 

Things to note:
1. This was working yesterday. 
2. I haven't changed any of the stack code.
3. The only things that have changed are pulumi versions and packages. See my issue from [yesterday](https://github.com/pulumi/pulumi/issues/5955) 

```
error: Running program '/Users/…/myproject' failed with an unhandled exception: 
Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to load chart from temp directory: stat /var/folders/pm/ftb5j1d51_gbr3cdxfpl1v4r0000gn/T/helm179799543/nginx-ingress: no such file or directory
unhandled rejection: CONTEXT(516): Invoking function: tok=kubernetes:helm:template asynchronously
```

This is the code for my helm chart which i think is the culprit.

```
const certManager = new k8s.helm.v3.Chart(
  `cert-manager`,
  {
    chart: `cert-manager`,
    version: `v0.15.1`,
    fetchOpts: {
      repo: 'https://charts.jetstack.io'
    },
    namespace: `cert-manager`,
    values: {
      ingressShim: {
        defaultIssuerName: certClusterIssuerName,
        defaultIssuerKind: 'ClusterIssuer'
      }
    }
  },
  {
    dependsOn: [certNamespace, crds],
    provider: cluster.provider
  }
);
```
## Expected Behavior

Preview Succesful

## Current Behavior

Preview Errors

## Steps to Reproduce

1.
2.
3.
4.

**Comment by aaronhayes** [comment]
I don't think so have ~170GB free on the disk partition.

**Comment by aaronhayes** [comment]
The repo `https://charts.jetstack.io` redirects to a 404 page now, I'm not sure if that's the cause. See https://github.com/jetstack/cert-manager/issues/3513

**Comment by aaronhayes** [comment]
Getting a different error now ... so progress. Looks like it's related to https://helm.sh/blog/charts-repo-deprecation/

```
Error: invocation of kubernetes:helm:template returned an error: failed to generate YAML for specified Helm chart: failed to pull chart: looks like "https://kubernetes-charts.storage.googleapis.com/" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
```

**Comment by aaronhayes** [comment]
And it's working again! :D thanks for the help @leezen

**Comment by buric** [comment]
For me running `helm repo update`worked.
