### ISSUE TITLE
Helm chart stopped deploying - The system cannot find the file specified

### ISSUE THREAD

**Issue by barclayadam** [pulumi/pulumi-kubernetes#1412]
One of my stacks has recently stopped working without any changes to the code, due to an error during the execution of a helm chart (which has not changed in terms of values specified, nor the version).

## Expected Behavior
The helm chart is detected as not changed, no errors occur.

## Current Behavior
Pulumi outputs the following:

````
    error: Error: Command failed: helm template C:\Users\barcl\AppData\Local\Temp\tmp-40228M92B2AG7CIlI\deprecation --name-template kube-state-metrics --values C:\Users\barcl\AppData\Local\Temp\tmp-40228M92B2AG7CIlI\deprecation\values.yaml --values C:\Users\barcl\AppData\Local\Temp\tmp-40228eL5MEkDuu74E.yaml  --namespace apm --include-crds
    Error: open C:\Users\barcl\AppData\Local\Temp\tmp-40228M92B2AG7CIlI\deprecation\values.yaml: The system cannot find the file specified.
    error: an unhandled error occurred: One or more errors occurred
````

from the chart defined as:

````typescript
new k8s.helm.v2.Chart('kube-state-metrics',
    {
        namespace: 'apm',
        chart: 'kube-state-metrics',
        version: '2.4.1',
        fetchOpts: {
            repo: 'https://kubernetes-charts.storage.googleapis.com',
        },
        values: {
            'nodeSelector': {
                'kubernetes.io/os': 'linux',
            },

            'prometheusScrape': false,

            'collectors': {
                'cronjobs': false,
            },
        },
    },
    {
        // Root has kubernetes provider defined
        parent: root,
    });
````

## Context (Environment)
Pulumi version 2.15.4 + 2.15.6 on Windows and Ubuntu respectively
Using Automation API, with "workspace" defined as the current working directory (i.e. overrides the use of the temporary folder)
Pulumi dependencies:
````json
  "devDependencies": {
    "@pulumi/azure": "^3.33.2",
    "@pulumi/azure-nextgen": "^0.2.8",
    "@pulumi/azuread": "^3.0.1",
    "@pulumi/cloudflare": "^2.9.0",
    "@pulumi/docker": "^2.5.0",
    "@pulumi/kubernetes": "^2.7.4",
    "@pulumi/kubernetesx": "^0.1.3",
    "@pulumi/pulumi": "^2.15.4",
    "@pulumi/random": "^2.4.4",
    "@pulumi/tls": "^2.4.2",
  },
````

**Comment by leezen** [comment]
This looks quite similar (if not the same) as https://github.com/pulumi/pulumi-kubernetes/issues/1411

**Comment by leezen** [comment]
Okay, this is not the same as #1411. Still not sure what's happening in that other issue. In this case, we can throw a better warning. The chart referenced above is deprecated. When you pull the chart manually (`helm pull stable/kube-state-metrics`) you end up pulling a tgz that doesn't actually have a real chart. Instead it has a `README.md` with a deprecation notice pointing at https://helm.sh/blog/charts-repo-deprecation/

If you update your program above to point at `https://charts.helm.sh/stable` as the repo, I believe this should work.

**Comment by barclayadam** [comment]
@leezen Thank you for the pointer, you are indeed correct. That has resolved this issue. Not sure if you want this issue open as a ticket to improve the handling of this situation? I'm happy for it to be closed for my individual case though

**Comment by leezen** [comment]
Great to hear @barclayadam. Yes, let's keep this open to track improving the UX here.

**Comment by leezen** [comment]
It looks like the repo just 403s correctly now, so I think the erroring is pretty clear on this. It's not clear how often the case we ran into above (chart fetches, but untars into something semi-valid) occurs, so I'm going to close this.
