### ISSUE TITLE
Using helm.v3.Chart via "@pulumi/kubernetes/helm/v3" throws TypeError

### ISSUE THREAD

**Issue by shousper** [pulumi/pulumi-kubernetes#1422]
### Problem description

A simple TypeScript Pulumi program like so:

```
import {Chart} from '@pulumi/kubernetes/helm/v3';

new Chart(..);
```

Doesn't matter how the `Chart` is configured, it will throw this error:

```
TypeError: Class extends value undefined is not a constructor or null
        at Object.<anonymous> (/Users/shousper/Source/test/node_modules/@pulumi/helm/v2/helm.ts:134:33)
```

However if you change the program like this:

```
import "@pulumi/kubernetes";
import {Chart} from '@pulumi/kubernetes/helm/v3';

new Chart(..);
```

or like this:

```
import * as k8s from "@pulumi/kubernetes";

new k8s.helm.v3.Chart(..);
```

It'll work fine.

### Affected product version(s)

- pulumi@2.17.0
- pulumi/pulumi@2.17.0
- pulumi/kubernetes@2.7.5

### Suggestions for a fix

This seems like some global namespace modifications are happening in the root, but the sub-module depends upon these. I'm not sure this is a typical TypeScript library behaviour?

While not critical, this cost me a bit of time to identify and could be a trap for others.

**Comment by bob-bins** [comment]
I'm hitting a similar issue with `k8s.yaml.ConfigFile`
