### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by adir-intsights** [pulumi/pulumi-kubernetes#1425]
When executing `pulumi up` the process takes more than 100% CPU usage on my machine.

**Comment by coreprocess** [comment]
Me too. On macOS and Linux too.

**Comment by lukehoban** [comment]
I suspect this is the issue that is being fixed with https://github.com/pulumi/pulumi/pull/7175.

**Comment by nesl247** [comment]
In my case we use typescript not python, so are you saying this issue should be fixed there too?

**Comment by lblackstone** [comment]
@nesl247 I'd guess yours is a different issue with similar symptoms. We're working on some other performance improvements that would apply to all SDKs, but this particular issue only applies to Python.

**Comment by nesl247** [comment]
@lblackstone Are you wanting me to open another issue then? I ask as the the original issue description did not mention python, and as @clstokes mentioned here https://github.com/pulumi/pulumi-kubernetes/issues/1425#issuecomment-690005773, it's definitely got an issue with typescript.

**Comment by lblackstone** [comment]
@nesl247 I'll open an issue specific to the Jobs repro, and it would be helpful if you could add any additional context I miss.
