### ISSUE TITLE
Inconsistent environment variables on deployment

### ISSUE THREAD

**Issue by mastoj** [pulumi/pulumi-kubernetes#1442]
### Problem description

We have a very obscure issue in our deployment of a kubernetes deployment where some time the some of the environments variables that we have defined isn't included in the manifest that is deployed.

We are using .NET (F#) and have created some helper functions for a more functional API experience.

First we have the create default args function:

```
    let createDefaultArgs appName imageName =
        let appLabels = inputMap [ "app", input appName ]

        DeploymentArgs(
            Metadata = input (ObjectMeta.createDefaultArgs appName),
            Spec = input (
                DeploymentSpecArgs(
                    Replicas = input 2,
                    RevisionHistoryLimit = input 3,
                    Selector = input (
                        LabelSelectorArgs(
                            MatchLabels = appLabels
                        )
                    ),
                    Template = input (
                        PodTemplateSpecArgs(
                            Metadata = input (
                                ObjectMetaArgs(
                                    Labels = appLabels
                                )
                            ),
                            Spec = input (
                                PodSpecArgs(
                                    PriorityClassName = input "itds-moderate",
                                    ImagePullSecrets = 
                                        inputList [
                                            input (
                                                LocalObjectReferenceArgs(
                                                    Name = input "acr-auth"
                                                )
                                            )
                                        ],
                                    SecurityContext = input (
                                        PodSecurityContextArgs(
                                            RunAsUser = input 2000
                                        )
                                    ),
                                    Containers = inputList [
                                        input (Container.createDefaultContainerArgs appName imageName)
                                    ]
                                )
                            )
                        )
                    )
                )
            )
        )
```

Then we have the function where we add secrets to the args

```
    let withEnvVarFromSecret (name, (secretName, key)) (depArgs: DeploymentArgs) =
        let updateContainers (containers: InputList<ContainerArgs>) : InputList<ContainerArgs> =
            containers.Apply(fun cList ->
                for c in cList do
                    c.Env.Add(
                        input(
                            EnvVarArgs(
                                Name = input name,
                                ValueFrom = input (
                                    EnvVarSourceArgs(
                                        SecretKeyRef = input (
                                            SecretKeySelectorArgs(
                                                Key = key,
                                                Name = input secretName
                                            )
                                        )
                                    )
                                )
                            
                        )
                    )
                )
            ) |> ignore
            containers

        depArgs.Spec.Apply(fun s ->
            s.Template.Apply(fun t -> 
                t.Spec.Apply(fun ts ->
                    ts.Containers <- updateContainers(ts.Containers)
                    ts) |> ignore
                t) |> ignore
            s) |> ignore
        depArgs
```

and lastly the create deployment helper

```
    let createDeployment appName options deploymentArgs =
        Deployment(appName, deploymentArgs, options = options)
```

We also have some other helpers, but those aren't that relevant as I see it. With these in place we can now create our deployment:

```
                let deployment =
                    Deployment.createDefaultArgs
                        appName
                        imageName
                    |> Deployment.withEnvVarsFromSecrets
                        [
                            ("SPLUNK_TOKEN", ("splunk-secrets", input "TOKEN"))
                            ("SPLUNK_INDEX", ("splunk-secrets", input "INDEX"))
                            ("KAFKA_KEY", ("kafka-secrets", input "KEY"))
                            ("KAFKA_SECRET", ("kafka-secrets", input "SECRET"))
                            ("KAFKA_BROKERS", ("kafka-secrets", input "BROKERS"))
                            ....
                            ("DBUP_SERVER", ("api-db-user-secrets", input "SERVER"))
                            ("DBUP_DATABASE", ("api-db-user-secrets", input "DATABASE"))
                            ("DBUP_APIUSER", ("api-db-user-secrets", input "USER"))
                            ("DBUP_APIUSERPASSWORD", ("api-db-user-secrets", input "PASSWORD"))
                        ]
                    |> Deployment.createDeployment appName deployOptions
```

Removed some of the environment variables to make it more concise. 

When we deploy this we some times don't get all the environment variables in the manifest, which is really strange. The behavior doesn't seem deterministic for some reason. The only thing we though of is if there is some kind of race condition somewhere, but I have a hard time seeing that a race condition is possible in the code above... 

I have added very verbose logging to our pipeline now so maybe we can get some more information when we see it again.

**Comment by mastoj** [comment]
@mikhailshilkov I saw that you labelled it a bug, have you seen anything like this before? Also, I'll try to find some time next week to go through the logs which have set to extremely verbose at the moment. Anything in particular that you think might be worth looking for in the logs when it comes to this?

**Comment by mikhailshilkov** [comment]
@mastoj  Nothing from my own experience - I was just triaging issues and this sounded like a bug. Any details are welcome!

**Comment by mastoj** [comment]
@mikhailshilkov, what should I look in the log for when trying to see what the new manifest looks like for a kubernetes deployment?

I've a pretty verbose log, so it is about 30000 lines of logs... The manifest I find is only "last-applied-manifest", which I think is a property from the deployed kubernetes resource. What I'm after is what is it that the kubernetes provider tries to send.

The log contains secrets, so I can't upload the complete log, it is also hard to locate all the secrets.

**Comment by mastoj** [comment]
I think I found it, and from my point of view it looks like environment variables are there in the log... so not sure why the aren't in the manifest when I do 

> kubectl get pod <name> -o yaml

**Comment by mastoj** [comment]
we hit this fairly regularly at the moment. What log level should be used to not expose secrets but still information on exactly what has been sent to kubernetes?

We could of course try to update pulumi, I think we are using a month old version or so in azure.... but that feels like cheating and not really fixing the problem.

**Comment by EvanBoyle** [comment]
Hi @mastoj, sorry you're running into trouble here. I'm not an F# expert, so bear with me as I ask a few questions. 

First off, `.apply` is not supposed to produce side-effects. It produces a new output value:

```ts
const newContainers = containers.apply(.../*any changes here will not be saved on the original 'containers' variable*/)
```

This is where my lack of F# expertise comes in. It looks like this code expects that `.apply` will have a side effect on containers and then return an updated containers value:

```f#
            containers.Apply(fun cList ->
                for c in cList do
                    c.Env.Add(
                        input(
                            EnvVarArgs(
                                Name = input name,
                                ValueFrom = input (
                                    EnvVarSourceArgs(
                                        SecretKeyRef = input (
                                            SecretKeySelectorArgs(
                                                Key = key,
                                                Name = input secretName
                                            )
                                        )
                                    )
                                )
                            
                        )
                    )
                )
            ) |> ignore
            containers
```

If that is the case, you probably want something closer to:

```f#
            updatedContainers = containers.Apply(fun cList ->
                for c in cList do
                    c.Env.Add(
                        input(
                            EnvVarArgs(
                                Name = input name,
                                ValueFrom = input (
                                    EnvVarSourceArgs(
                                        SecretKeyRef = input (
                                            SecretKeySelectorArgs(
                                                Key = key,
                                                Name = input secretName
                                            )
                                        )
                                    )
                                )
                            
                        )
                    )
                )
            ) |> ignore
            updatedContainers
```

Similarly, I see the same pattern elsewhere in the code provided:

```f#
        depArgs.Spec.Apply(fun s ->
            s.Template.Apply(fun t -> 
                t.Spec.Apply(fun ts ->
                    ts.Containers <- updateContainers(ts.Containers)
                    ts) |> ignore
                t) |> ignore
            s) |> ignore
        depArgs
```

Forgive me if I'm not interpreting the code correctly 😄

**Comment by mastoj** [comment]
Thanks for input @EvanBoyle 

Got it... so if I understand you correctly that is what might cause a potential race condition? Sometimes it manage to run through the apply and update, and sometime it doesn't and will just use what is defined the first time or somewhere in the middle of the loop. I think I see how that could potentially happen even though I have a clean separation between the creation of the arguments and the resource in the code.

**Comment by mikhailshilkov** [comment]
This is basically https://github.com/pulumi/pulumi/issues/3991 (we should extend it to .NET too).

P.S. side effects and mutations strike again ;)

**Comment by mastoj** [comment]
To clarify @EvanBoyle, everytime I do a reply I should use what is returned from the apply and not "trust" that the values have been updated accordingly. Correct? I gake for granted that goes for the nested `Apply` as well.

**Comment by EvanBoyle** [comment]
@mastoj yes, the guidance is to always explicitly return a value from the apply function and to always capture the newly returned output in a variable. 

Don't do this:
```ts
a.apply(/*side effect*/)
a.apply(/*side effect*/)
a.apply(/*side effect*/)
```
Instead do:

```ts
a1 = a.apply(...)
a2 = a1.apply(...)
a3 = a3.apply(...)
```

**Comment by mastoj** [comment]
@mikhailshilkov definitely agree... it definitely was the path of least resistance for me, and as long as it is that for someone it will happen again and again. Even though I'm using F# here, due to the base programming model the SDK is based on I went for mutation.... I would love to see a true immutable SDK :).

**Comment by mastoj** [comment]
@mikhailshilkov do you have a suggestion on how I go from `Output<ImmutableArray<Something>>` to `InputList<Something>`.

Using `io` will create `Input<ImmutableArray<Something>>`, not sure how I convert between them... I guess there is some simple trick to do.

**Comment by mastoj** [comment]
I think i figured it out, need to take it for a test run. But does this look ok?

```
    let withEnvVarFromSecret (name, (secretName, key)) (depArgs: DeploymentArgs) =
        let updateContainers (containers: InputList<ContainerArgs>) =
            let updatedContainers = containers.Apply(fun cList ->
                for c in cList do
                    c.Env.Add(
                        input(
                            EnvVarArgs(
                                Name = input name,
                                ValueFrom = input (
                                    EnvVarSourceArgs(
                                        SecretKeyRef = input (
                                            SecretKeySelectorArgs(
                                                Key = key,
                                                Name = input secretName
                                            )
                                        )
                                    )
                                )
                            
                        )
                    )
                )
                cList
            )
            InputList<ContainerArgs>.op_Implicit(updatedContainers)

        let spec =
            depArgs.Spec.Apply(fun s ->
                let template =
                    s.Template.Apply(fun t ->
                        let templateSpec =
                            t.Spec.Apply(fun ts ->
                                ts.Containers <- updateContainers(ts.Containers)
                                ts)
                        t.Spec <- io templateSpec
                        t)
                s.Template <- io template
                s)
        depArgs.Spec <- io spec
        depArgs
```

But is their an easier and more elegant way of doing this kind of updates?

**Comment by mastoj** [comment]
I sort of have to do mutation in the nested `Apply` since creating complete new values and copying everything is way to tedious. But I guess it is ok as long as I do use the values from the `Apply` and not just rely on the mutation.

**Comment by lblackstone** [comment]
It looks like the linked issues were fixed, and there has been no update on this issue for a long time, so I'll close it out.
