### ISSUE TITLE
Go SDK is bloated

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi-kubernetes#1445]
I'm trying to upgrade from 2.6.1 to 2.7.7 and I noticed two things:
1. My final binary size was increased by 250mb
2. Circle CI builds started to fail consistently due to OOM when building the package (I'm using a 16gb machine and it's not enough)

From some testing it seems that each version gradually increases the pulumi-kubernetes in size and build times.

I know that @EvanBoyle is doing some work with reducing pulumi go modules size so that might help here as well.

Edit:
The major increase happens from 2.7.6 to 2.7.7 from 2.6.1 to 2.7.X increased in about 50mb

Builds usually fail at this point:
```
go: downloading github.com/pulumi/pulumi/sdk/v2 v2.18.2
go: downloading github.com/pulumi/pulumi-kubernetes/sdk/v2 v2.7.6
go: downloading github.com/pulumi/pulumi-random/sdk/v3 v3.0.1
go: downloading github.com/gofrs/uuid v3.3.0+incompatible
go build github.com/pulumi/pulumi-kubernetes/sdk/v2/go/kubernetes/extensions/v1beta1: /usr/local/go/pkg/tool/linux_amd64/compile: signal: killed
```

**Comment by lblackstone** [comment]
I just tested the linked PR locally, and it cut ~170 MB off the binary size. Still testing the change, but we should make some progress on this in the near future.

**Comment by yarinm** [comment]
@lblackstone  Any idea why the binary size increased in about 200mb between 2.7.6 to 2.7.7?

**Comment by lblackstone** [comment]
> @lblackstone Any idea why the binary size increased in about 200mb between 2.7.6 to 2.7.7?

Yes, we added a bunch of types to support the upcoming multi-language component work. That change scales with the number of resources in the SDK, so providers like k8s with a lot of resources were most impacted by the change. We're evaluating ways to optimize the memory requirements as it's a known issue with our Go SDKs in general.

**Comment by lblackstone** [comment]
This should be improved in https://github.com/pulumi/pulumi-kubernetes/releases/tag/v2.7.8

I'm going to close this out since we don't have further concrete improvements in mind at this time.
