### ISSUE TITLE
Plugin isn't backwards compatible

### ISSUE THREAD

**Issue by yarinm** [pulumi/pulumi-kubernetes#1451]
I'm usually running pulumi on a fresh docker and using the automation API I'm installing kubernetes plugin + running the stack.

When I tried to upgrade from 2.6.1 to some other version if the 2.6.1 plugin isn't installed I get this error when trying to update the stack:

```
Diagnostics:
  pulumi:providers:kubernetes (default_2_6_1):
    error: no resource plugin 'kubernetes-v2.6.1' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource kubernetes v2.6.1`
```

So far this is the only plugin that behaves this way, other plugins I've used are compatible with stacks created with older versions.

**Comment by lukehoban** [comment]
I believe this is due to the issue tracked in https://github.com/pulumi/pulumi/issues/5619.

**Comment by lblackstone** [comment]
Assuming this is for the Go SDK, I'd guess this is caused by invoke parameters for Helm/YAML/Kustomize support. Related: https://github.com/pulumi/pulumi-kubernetes/issues/1324

**Comment by yarinm** [comment]
Yes, this is in the go SDK
