### ISSUE TITLE
Change existing CRD instance

### ISSUE THREAD

**Issue by ppawiggers** [pulumi/pulumi-kubernetes#1453]
### Problem description

I create a GKE cluster with Pulumi, with the config connector addon enabled. This creates the CRD `configconnectors.core.cnrm.cloud.google.com`. It also creates an instance of this CRD with the name `configconnector.core.cnrm.cloud.google.com`.

I want to make a change to this instance. I've created the Python CRD schema and defined the CRD instance in Pulumi:

```
ConfigConnector(
    "config-connector",
    metadata=ObjectMetaArgs(
        name="configconnector.core.cnrm.cloud.google.com",
    ),
    spec=ConfigConnectorSpecArgs(
        mode="cluster",
        google_service_account="my-sa@google.com",
    ),
    opts=ResourceOptions(
        provider=k8s_provider,
    ),
)
```

However, when I run `pulumi up` it says that the resource already exists - which is correct because GKE created it automatically.

### Errors & Logs

```
Diagnostics:
  kubernetes:core.cnrm.cloud.google.com/v1beta1:ConfigConnector (config-connector):
    error: resource configconnector.core.cnrm.cloud.google.com was not successfully created by the Kubernetes API server : configconnectors.core.cnrm.cloud.google.com "configconnector.core.cnrm.cloud.google.com" already exists
```

### Affected product version(s)

```
pulumi            2.18.2
pulumi-gcp        4.8.0
pulumi-kubernetes 2.7.7
```

### Suggestions for a fix

Pulumi should maybe `kubectl apply` the manifest instead of forcing a `kubectl create`.

**Comment by lblackstone** [comment]
This is related to the feature being tracked in https://github.com/pulumi/pulumi-kubernetes/issues/264

In the meantime, you can accomplish this using [import](https://www.pulumi.com/docs/guides/adopting/import/). The problem currently is that you are telling Pulumi to overwrite an existing resource that not under its management. Import indicates that Pulumi will assume management of the resource. Note that this could potentially conflict with changes made by controllers (e.g., operators) running in the cluster.

I'm going to close this issue in favor of #264 

> Pulumi should maybe `kubectl apply` the manifest instead of forcing a `kubectl create`.

FYI, the provider is communicating with the k8s API directly using client-go, so `kubectl` isn't involved here.
