### ISSUE TITLE
Can't get Kubernetes object not managed by Pulumi

### ISSUE THREAD

**Issue by maxromanovsky** [pulumi/pulumi-kubernetes#1479]
Previously it was possible to fetch the resource not managed by Pulumi, but as of `pulumi-kubernetes==2.8.2` in Python it doesn't work and returns `None`.

Example below shows Namespace, but I have experienced that issue with Secret as well.

It works after importing it via `pulumi import kubernetes:core/v1:Namespace kube-system kube-system`, but the whole reason is to get state of the object that is not managed by pulumi.
I haven't found that change in changelog.

## Expected behavior
Namespace is returned.

## Current behavior
`None` is returned.

## Steps to reproduce

Tested on `pulumi-kubernetes==2.1.1`:
```python
namespace_system = Namespace.get('kube-system', 'kube-system')
```

**Comment by leezen** [comment]
Playing with different versions, it appears the behavior difference takes place b/t 2.3.1 and 2.6.0

**Comment by leezen** [comment]
It appears `2.3.1` is the last version that has the correct behavior.
