### ISSUE TITLE
Support CRD creation with `.status` field

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1481]
Some CRDs contain an erroneous `.status` field that cause an error when they are deployed by Pulumi. Although `.status` is not a valid input field, it would be better for us to ignore this input and allow the resource creation rather than simply returning an error. (`kubectl` deploys these CRDs, and ignores the status field)

The current error message looks something like this:
```
TypeError: __init__() got an unexpected keyword argument 'status'
```

Here's an example CRD with this issue: https://github.com/nginxinc/kubernetes-ingress/blob/f69bdc80b7269fe24c137ac82ff35a5b28377ec5/deployments/helm-chart/crds/k8s.nginx.org_globalconfigurations.yaml#L51-L56

**Comment by georgyo** [comment]
While investigating #1541, it seems that this only affects python. Neither the go or typescript interfaces care about the `.status` field.

**Comment by logileifs** [comment]
I'm running into this same issue when trying to install https://projectcontour.io/quickstart/contour.yaml with Pulumi.  
It would be great if the status would be ignored to avoid a rather messy workaround 🙃

**Comment by logileifs** [comment]
This is also preventing me from installing Traefik helm chart.
Example code:
```
ingress = helm.Chart(
		"traefik",
		helm.ChartOpts(
			chart="traefik",
			values={"service": {"type": "NodePort"}},
			fetch_opts=helm.FetchOpts(
				repo="https://helm.traefik.io/traefik"
			)
		),
		pulumi.ResourceOptions(provider=k8s_provider)
	)
```
Produces error:
```
File "/Users/logi/.pyenv/versions/localenv/lib/python3.9/site-packages/pulumi_kubernetes/apiextensions/v1/CustomResourceDefinition.py", line 121, in __init__
        __self__._internal_init(resource_name, *args, **kwargs)
    TypeError: _internal_init() got an unexpected keyword argument 'status'
    error: an unhandled error occurred: Program exited with non-zero exit code: 1
```

**Comment by jancespivo** [comment]
Same for `kubevela` chart
```
kubevela = kubernetes.helm.v3.Chart(
    "kubevela",
    kubernetes.helm.v3.ChartOpts(
        chart="vela-core",
        fetch_opts=kubernetes.helm.v3.FetchOpts(
            repo="https://charts.kubevela.net/core",
        ),
    ),
    opts=pulumi.ResourceOptions(provider=gke_provider)
)
```
