### ISSUE TITLE
Document limitations of Helm Chart component resource

### ISSUE THREAD

**Issue by hugbubby** [pulumi/pulumi-kubernetes#1484]
So far I've installed only four helm charts with pulumi (cert-manager, nginx-ingress, [loft](https://github.com/loft-sh/loft), and gitlab). Two out of four don't work out of the box, gitlab and loft. It took me a very long time to find the issue that gives the transformation to fix the Gitlab chart, and the loft chart seems to break all subsequent updates in a way I have yet to workaround. I'd really like a reference of the limitations that pulumi has installing, modifying, and upgrading helm charts so that I know what to look out for in these scenarios.

**Comment by viveklak** [comment]
We announced a new Helm Release resource (public preview) as part of v3.7.0 of the Kubernetes provider. The blog [here](https://www.pulumi.com/blog/full-access-to-helm-features-through-new-helm-release-resource-for-kubernetes/) describes a bit of the limitations. Keeping this open for updating the docs to reflect some of the limitations.

**Comment by lblackstone** [comment]
[This guide](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/choosing-the-right-helm-resource-for-your-use-case/) explains the differences between the two resource types.
