### ISSUE TITLE
Pulumi refresh marks resources provisioned with render_yaml_to_directory as deleted

### ISSUE THREAD

**Issue by maxromanovsky** [pulumi/pulumi-kubernetes#1488]
`pulumi refresh` marks resources provisioned with render_yaml_to_directory as deleted.
Possibly related to #992

## Expected behavior

No changes detected

## Current behavior

Resources provisioned with `provider_yaml` are marked as deleted

## Steps to reproduce

1. `provider_yaml = Provider('yaml', render_yaml_to_directory='resources/yaml')`
2. `# some resources with opts=ResourceOptions(provider=provider_yaml)`
2. `pulumi up`
3. `pulumi refresh -y --skip-preview`

## Context (Environment)
```
macOS Big Sur 11.3 Beta (20E5196f)
Python 3.9.2
pulumi v2.22.0
pulumi-kubernetes 2.8.2
```

## Affected feature

Pulumi Kubernetes provider with `render_yaml_to_directory`

**Comment by lblackstone** [comment]
I found the problem and have a WIP fix up in #1523. I need to do some more testing, but should have this fixed soon.
