### ISSUE TITLE
Helm Chart doesn't honor Templates folder

### ISSUE THREAD

**Issue by NArnott** [pulumi/pulumi-kubernetes#1489]
When installing the following helm chart using Pulumi, it installs more than it is supposed to: https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller

The chart has both a **templates** folder, and a **crds** folder. The Helm CLI only installs yaml files defined in the templates folder. Pulumi, for some reason, is also including yaml files defined in the crds folder, which is incorrect.

You'll notice in the git repo that if you scroll down, the instructions ask you to apply the crds yaml files manually before using the helm chart, which I do using a ConfigGroup. However, as part of the helm chart, Pulumi then tries to run the crds/*.yaml files again, causing a conflict and failure.  

I confirmed that the Helm CLI does not include the **crds** folder, as expected, by running the Helm Template command (which doesn't include that folder's yaml files.

I've been waiting a long time to be able to apply this using helm inside Pulumi (now that https://github.com/pulumi/pulumi/issues/4224 as been resolved), but now hit this roadblock.

**Comment by viveklak** [comment]
This is because of the behavior described in #1195 and the fix for that in https://github.com/pulumi/pulumi-kubernetes/pull/1572 should fix this as well. Closing as duplicate.
