### ISSUE TITLE
Changing namespace of secret causes error

### ISSUE THREAD

**Issue by awoimbee** [pulumi/pulumi-kubernetes#1493]
Changing the namespace of a secret fail (EKS: 1.19, pulumi: 2.22.0, `@pulumi/kubernetes`: 2.8.2)

## Expected behavior
Delete then recreate the secret.

## Current behavior
```
kubernetes:core/v1:Secret (my-secret):
  error: resource new-namespace/my-secret-k71i45u5 was not successfully created by the Kubernetes API server : namespaces "new-namepace" not found
```

## Steps to reproduce
Create a secret in a namespace, then edit metadata.namespace.

```typescript
  import * as k8s from "@pulumi/kubernetes";
  
  const n1 = new k8s.core.v1.Namespace("base", {metadata: { name: "namespace1" }});
  const n2 = new k8s.core.v1.Namespace("base", {metadata: { name: "namespace2" }});
  const n1Name = n1.metadata.apply(m => m.name);
  const n2Name = n2.metadata.apply(m => m.name);

  const secretAuthCreds = new k8s.core.v1.Secret("basic-auth", {
    metadata: {namespace: n1Name}, // create, then replace n1Name by n2Name
    stringData: {"auth": "toto"}
  });
```

## Affected feature
core.v1.Secret

**Comment by lblackstone** [comment]
I wasn't able to reproduce this behavior locally, so I suspect you may have changed something else about your cluster unrelated to Pulumi. The error message indicates that the Namespace doesn't exist, so perhaps it was deleted out of band.

Closing this out, but feel free to reopen if you are still having problems.
