### ISSUE TITLE
Helm resource integer values cannot be set as string

### ISSUE THREAD

**Issue by eljoth** [pulumi/pulumi-kubernetes#1497]
Setting resource limits as string which are defined in the values as int, cannot be set.

## Expected behavior

Resource limits can be set as string as well to allow less than 1 CPU to be set as limit e.g.

## Current behavior

Placing a string in a value for a resource which defaults to an int in the values.yaml, leads to an error:

<img width="580" alt="grafik" src="https://user-images.githubusercontent.com/21229601/111426377-dfcf9e80-86f4-11eb-8814-d0ada7a2b1cf.png">

Values.yaml section:
https://github.com/scylladb/scylla-operator/blob/6ff5d1a5530d657512d8f70daa425cf0025cb77d/helm/scylla/values.yaml#L48-L66

**Comment by eljoth** [comment]
Although I believe this not really a bug, I think, this should be fixed because (many?) helm charts exist, that are not using units for their resource quotas.

Just for reference:
https://github.com/scylladb/scylla-operator/issues/505

**Comment by EronWright** [comment]
The issue was due to an upstream bug in the scylla chart's schema; `cpu` was modeled as an `integer`.
https://github.com/scylladb/scylla-operator/blob/42a0f1e3df9843066296a14a83c9add6cb48434b/helm/scylla/values.schema.json#L128-L130
