### ISSUE TITLE
Accept actual Namespace resources wherever a namespace name is accepted

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-kubernetes#152]
Right now ObjectMetadata.namespace is typed as Input<string>.  It would be nice if it could actually take a core.Namespace instance.

**Comment by CyrusNajmabadi** [comment]
This is especially obnoxious since you effectively have to both create a Namespace object and then later do: `namespace: namespace.metadata.apply(m => m.name)`

Not discoverable or easy.

**Comment by casey-robertson** [comment]
Sorry to be dense - how does one specify a namespace(s) to be created using Pulumi?

**Comment by hausdorff** [comment]
@casey-robertson Something like this should work: https://github.com/pulumi/examples/blob/master/kubernetes-ts-sock-shop/index.ts#L13

**Comment by hausdorff** [comment]
This is easy to do, but I also don't think it's _necessary_ for the Q3 march. Up to you all if we slot it in.

**Comment by lblackstone** [comment]
@hausdorff This change was backed out, right?
