### ISSUE TITLE
Pod image is marked as optional. Should be required value

### ISSUE THREAD

**Issue by shinebayar-g** [pulumi/pulumi-kubernetes#1527]
## Expected behavior

All kubernetes required values are marked as required in typescript package.

## Current behavior

Pod spec's container image is marked as optional. But it's required value in kubernetes.

![image](https://user-images.githubusercontent.com/3091558/114743063-52df2b80-9d1a-11eb-9eab-ff1261ec8f67.png)

## Steps to reproduce

Try to run following code snippet

```ts
import * as k8s from '@pulumi/kubernetes';

new k8s.apps.v1.Deployment('test-deployment', {
    metadata: {
      name: 'testing',
      namespace: 'default',
      labels: {
        app: 'test'
      }
    },
    spec: {
      selector: {
        matchLabels: {
          app: 'test'
        }
      },
      replicas: 1,
      template: {
        metadata: {
          labels: {
            app: 'test'
          },
        },
        spec: {
          terminationGracePeriodSeconds: 3,
          containers: [
            {
              name: 'nginx',
              ports: [
                {
                  containerPort: 80
                }
              ],
              env: [
                {
                  name: "EKS",
                  value: "1"
                }
              ]
            }
          ]
        }
      }
    }
  })
```

## Context (Environment)

```
"@pulumi/kubernetes": "^2.8.3",
```

**Comment by lblackstone** [comment]
I double-checked the upstream spec, and `image` is explicitly optional. We want to avoid diverging from upstream, so marking this as wont-fix.

> This field is optional to allow higher level config management to default or override container images in workload controllers like Deployments and StatefulSets.

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#container-v1-core
