### ISSUE TITLE
ingress.status.loadBalancer.ingress[0].hostname is undefined

### ISSUE THREAD

**Issue by zkkxu** [pulumi/pulumi-kubernetes#1537]
when using pulumi 3.0.0 create ingress, after the ingress is created, can't fetch `ingress.status.loadBalancer.ingress[0].hostname`.  
I also notice the output json of pulumi, the ingress status is empty
## Steps to reproduce

1. use pulumi 3.0.0
2. create ingress via typescipt 
3. in the ts, trying to fetch the `ingress.status.loadBalancer.ingress[0].hostname`
4. the ts will failed with `TypeError: Cannot read property '0' of undefined`

**Comment by lblackstone** [comment]
@zkkxu Thanks for the report. What Kubernetes provider are you using (EKS, GKE, etc.)? Can you provide the code snippet you're using to create the Ingress resource?

**Comment by lblackstone** [comment]
I wasn't able to reproduce, and haven't heard back from the user with the requested info, so I'm closing this out.

@zkkxu Feel free to reopen if you're still hitting this issue.

**Comment by stelescuraul** [comment]
I am having this issue as well. 
I am creating an ingress using `k8s.networking.v1.Ingress` and it seems like pulumi does not wait for the underlying load balancer to spawn and have the host name available. 
Exporting it like this does not work (returns undefined as the op).
```ts 
export const ingressUrl = ingressgame.status.apply(
  (status) => status.loadBalancer.ingress[0].hostname
);
```
could be related to: https://github.com/pulumi/pulumi-kubernetes/issues/1649 
and this: https://github.com/pulumi/pulumi-kubernetes/issues/1498
@lblackstone Can we reopen this ?

**Comment by lblackstone** [comment]
Thanks for the information. It looks like the underlying issue is likely the one tracked in #1649, so let's track it there rather than reopening this one.
