### ISSUE TITLE
Warning also emitted as error.  I was very confused.

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-kubernetes#154]
My kuberenetes update failed with teh following:

```
    warning: Service 'frontend' does not target any Pods
 
    info: ✅ Service has been allocated an IP
 
    error: Plan apply failed: 2 errors occurred:
    
    * Timeout occurred for 'frontend'
    * Service does not target any Pods
```

Note that i was first told about the warning that a service was not targeting any pods.  That didn't seem so bad.  However, right below that i then got an error, and it says the error was due to the service not targeting any pods.

This is definitely confusing and strange to me.  I honestly don't know why it's an warning one time, and an error another time.

**Comment by hausdorff** [comment]
Fixed with #174.
