### ISSUE TITLE
Same Chart Multiple Release

### ISSUE THREAD

**Issue by reidlai** [pulumi/pulumi-kubernetes#1542]
I am trying to use kubernetes helm v3 api to create ingress controller.  Based on my design, I like to create two controllers using Contour or Nginx, one for public and one for intranet with different NodePort or LoadBalancer configuration.

I did successfully create one controller...but Pulumi exit without error when I try to create two release with same chart configuration.  After running verbose level 9 and spool error to text file, I found the following error.  Is there any Typescript example to show how to do it?

I0425 12:33:05.767648   54357 ignore.go:44] Explicitly ignoring and discarding error: rpc error: code = Canceled desc = grpc: the client connection is closing
I0425 12:33:05.803658   54357 ignore.go:44] Explicitly ignoring and discarding error: 1 error occurred:
        * operation not permitted

**Comment by lblackstone** [comment]
It looks like we missed this issue originally, and I don't have enough info to reproduce now. I suspect that the solution would have been using the [resourcePrefix](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/#resourceprefix_nodejs) option.
