### ISSUE TITLE
`GetNamespace` in the Go SDK throws a type assertion error

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1545]
It seems the Go SDK's implementation of `GetNamespace` doesn't work:

```
ns, err := corev1.GetNamespace(ctx, "test", pulumi.ID("foo"), nil)
		if err != nil {
			return err
		}
		ctx.Export("ns", ns)
```

This code throws a type assertion error.

## Expected behavior
It returns the namespace

**Comment by lblackstone** [comment]
https://github.com/pulumi/pulumi/blob/eb2dcf24884bab173af175cd41d8279e07797a75/pkg/engine/diff.go#L511 is the assertion failure. I did a little digging and the ID is actually a `ResourceReference` here.
![Screen Shot 2021-04-27 at 11 28 32 AM](https://user-images.githubusercontent.com/9253463/116285782-b4a48a00-a74b-11eb-9a37-c4dd3f89883f.png)

@pgavlin Any idea what's going on here?

**Comment by lblackstone** [comment]
This was fixed at some point
