### ISSUE TITLE
Link to appropriate docs when an update fails

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-kubernetes#155]
Update of my app failed with:

```
info: 7 changes performed:
    + 7 resources created
Update duration: 10m4.425182837s

Permalink: https://app.pulumi.com/CyrusNajmabadi/cy-guestbook-dev/updates/1
error: update failed
```

I'm not sure what to do at this point.  Going to the link in the message shows my app status, with an appropriate alert icon and "Initialization Errors" message that shows a problem with my "Frontend" resource.  However, i have no information at all given on what steps i might take next to try to address this.

**Comment by CyrusNajmabadi** [comment]
Note: running `pulumi up` again gave me this *really good* message:

```
Diagnostics:
  kubernetes:core:Service: frontend
    warning: This resource failed to initialize in a previous deployment. It is recommended
             to update it to fix these issues:
               - Problem #1 Timeout occurred for 'frontend'
               - Problem #2 Service does not target any Pods
```

It would have been great to have heard that when the failure happened, not on a later step that i had to guess at.

**Comment by blampe** [comment]
Lost to the sands of time.
