### ISSUE TITLE
Updating a configmap's data with enableDryRun fails with "configsmap already exists"

### ISSUE THREAD

**Issue by pierlucg-xs** [pulumi/pulumi-kubernetes#1560]
Changing the data on a ConfigMap with `enableDryRun: true` on EKS 1.19/ K3S v1.20.4 causes the following error:
```
kubernetes:core/v1:ConfigMap (test2):
    error: resource default/pierlucg-test was not successfully created by the Kubernetes API server : configmaps "pierlucg-test" already exists
```

## Steps to reproduce

Run `pulumi up` **twice** with the following code:
```ts
const eksProviderDry = new k8s.Provider('eksdry', {
  enableDryRun: true,
  kubeconfig: 'mykubeconfig'
});

const configMapTest = new k8s.core.v1.ConfigMap(
  'this-will-fail',
  {
    data: {foo: `${Date.now()}`},
    metadata: {
      name: `failing-configMap`,
    },
  },
  {provider: eksProviderDry},
);

const eksProvider = new k8s.Provider('eks', {
  kubeconfig: 'mykubeconfig'
});

const configMapWorking = new k8s.core.v1.ConfigMap(
  'this-will-succeed',
  {
    data: {foo: `${Date.now()}`},
    metadata: {
      name: `fonctioning-configMap`,
    },
  },
  {provider: eksProvider},
);

```

This will be the result the second time:

```
Previewing update (mystack.dev):
     Type                             Name                                       Plan        Info
     pulumi:pulumi:Stack              myproject-mystack.dev              1 error
 +-  ├─ kubernetes:core/v1:ConfigMap  this-will-succeed                          replace     [diff: ~data]
 +-  └─ kubernetes:core/v1:ConfigMap  this-will-fail                             replace     [diff: ~data]; 1 error
 
Diagnostics:
  pulumi:pulumi:Stack (myproject-mystack.dev):
    error: preview failed
 
  kubernetes:core/v1:ConfigMap (this-will-fail):
    error: Preview failed: resource default/failing was not successfully created by the Kubernetes API server : configmaps "failing" already exists
```

## Context (Environment)

Using Typescript
EKS Server Version: v1.19.8-eks-96780e
Pulumi Version: v3.1.0
"@pulumi/kubernetes" Version: "^3.1.0"

I also tested with a local K3S cluster and the issue still occurs.

-----

Might affect https://github.com/pulumi/pulumi-kubernetes/issues/1556

**Comment by lukehoban** [comment]
> Changing the data on a ConfigMap with `enableDryRun: true`

I assume this does not repro with `enableDryRun: false`?  In which case it sounds like an issue with the server-side diff support.  cc https://github.com/pulumi/pulumi-kubernetes/issues/1556 which is tracking making that the default.

**Comment by pierlucg-xs** [comment]
I tried with `enableDryRun: false` and the configmap updated just fine.

**Comment by pierlucg-xs** [comment]
@lblackstone could not using auto-naming be the cause of this issue as well?

**Comment by lblackstone** [comment]
> @lblackstone could not using auto-naming be the cause of this issue as well?

Yes, quite possibly. Sorry for the troubles here. We may need to rethink the provider's behavior in the case where the resources are not auto-named.

**Comment by pierlucg-xs** [comment]
I'll leave the decision whether to close this issue up to you. With my newly found understanding (thank you), I now know how to avoid this problem. That being said, I agree that there might be a better way to at least provide a more meaningful error.

Thanks again!

**Comment by nesl247** [comment]
Just ran into this myself. It really needs to support updating (instead of replacing) `ConfigMap`s if the name is not autonamed.
