### ISSUE TITLE
Validation error during 'apply' but not during 'preview'

### ISSUE THREAD

**Issue by CyrusNajmabadi** [pulumi/pulumi-kubernetes#157]
I got this error during apply:

```
Diagnostics:
  kubernetes:core:Service: frontendService
    error: Plan apply failed: Service "frontendService" is invalid: metadata.name: Invalid value: "frontendService": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
```

I would have expected to get such an error during preview.  It's definitely somthing that would scare me as a user as i could have done some amount of updates and then be left in a bad state.

**Comment by hausdorff** [comment]
I agree, but I'm not sure how to implement this in general. The API server only really allows us to check that some object is adherent to a schema.

**Comment by hausdorff** [comment]
Talking to @lukehoban I think we should close this as `wontfix`, because it is pretty hard to implement, and probably not worth the effort. Stakeholders, (@joeduffy, @lukehoban) feel free to re-open the issue and discuss if you don't agree.
