### ISSUE TITLE
Checkmarks during Updates don't render on Windows

### ISSUE THREAD

**Issue by ellismg** [pulumi/pulumi-kubernetes#159]
When you run `pulumi up` on Windows, the emjois displayed in the console as part of the status rich updates don't render correctly on a default windows install (you end up with question-mark boxes)

We should just not print emjoi's on windows.  We already do this elsewhere in the CLI, but I assume these messages are coming from the kubernetes provider and we'll need a change here as well.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/9602953/44552903-a7a08480-a6e0-11e8-83d4-1489e4f973e6.png)

**Comment by hausdorff** [comment]
Is this issue still relevant now that Windows terminal supports emoji?
