### ISSUE TITLE
Restructure await logic to use shared informers instead of relying on fine-grained watches

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes#1598]
Currently our await logic relies on setting up independent watches on each resource (and in some cases for higher order resources like deployments/stateful sets etc., on their respective components like pods, replicasets, PVCs etc.). This can cause a lot of redundant information to be spewed to the watches. We should restructure the awaits to use a [shared informer](https://pkg.go.dev/k8s.io/client-go/informers#SharedInformerFactory) on the namespace witch filter options.

This will also necessitate less reliance on strong consistency/ordering of events which should make the await logic less brittle (e.g. see https://github.com/pulumi/pulumi-kubernetes/issues/1502)

**Comment by lblackstone** [comment]
Here's an example I found that specifically uses the dynamic client + shared informers: https://hackernoon.com/platforms-on-k8s-with-golang-watch-any-crd-0v2o3z1q

**Comment by lblackstone** [comment]
I've got a simple demo project set up that shows how to use the dynamic informers: https://github.com/lblackstone/k8s-dynamic-informer
