### ISSUE TITLE
k8s.networking.v1.Ingress creates extensions/v1beta1 Ingress resource

### ISSUE THREAD

**Issue by shinebayar-g** [pulumi/pulumi-kubernetes#1606]
## Steps to reproduce

1. Apply:
```ts
new k8s.networking.v1.Ingress(
  `test`,
  {
    metadata: {
      name: 'test',
      annotations: 'test',
    },
    spec: {
      rules: [
        {
          host: 'example.com',
          http: {
            paths: [
              {
                path: '/',
                pathType: 'Prefix',
                backend: {
                  service: {
                    name: 'test-svc',
                    port: {
                      number: 80
                    },
                  },
                },
              },
            ],
          },
        },
      ],
    },
  },
);
```
2. Check Ingress resource that is just created.

```
kubectl get ing test -o yaml
```

Expected: pulumi-kubernetes package creates `Ingress` resource with `apiVersion: networking.k8s.io/v1`
Actual: `Ingress` resource was created with `apiVersion: extensions/v1beta1` which is deprecated.

This also affects helm chart's Ingress resource. Example: https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml

**Comment by lblackstone** [comment]
@shinebayar-g FYI, `kubectl` will return the apiVersion of the resource that you request, regardless of which version was used to create the resource. (It automatically converts between versions on the server). If you look at the resource in the Pulumi state, you can see which version it was created with in the `__initialApiVersion` field of the resource outputs.

**Comment by shinebayar-g** [comment]
Mhm, thanks for the explanation. I took the hint from Ingress resource's last-applied-configuration annotation. It was indeed networking.k8s.io/v1
