### ISSUE TITLE
`@pulumi/pulumi` should be a peer dependency

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/pulumi-kubernetes#1608]
Not doing so can cause multiple copies of `@pulumi/pulumi` in `node_modules` which can cause all sorts interesting problems. See the PR in KX that made this change for reference:

https://github.com/pulumi/pulumi-kubernetesx/pull/66/files

**Comment by lblackstone** [comment]
Closing as [no longer needed](https://github.com/pulumi/pulumi/issues/7271#issuecomment-885980228)
