### ISSUE TITLE
Make `transforms` more `bind`-like

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#161]
In `k8s.helm.Chart` and `k8s.yaml.Config*`, we allow people to transform the arguments to Kubernetes resources before the constructor is called. This is useful when, _e.g._, a Helm chart is broken, and we need to change it before the `CustomResource` is created.

Currently, a transform relies on the user mutating the actual arguments object. This is convenient, but it doesn't help when we need to add resources to the Chart.

To express this, we might change the signature to look like: `(o: any) => any[]`, _i.e._, we might allow people return an arbitrary number of results, as is true of Scala's `flatMap`, Haskell's `bind`, and so on. This would allow people to change objects in place, delete objects, or add objects to the Chart.

**Comment by hausdorff** [comment]
We're booting this out to M22 because I think it is worth waiting until we're done with the AWS-infra work. I am hoping once that lands, it will be clear how to move forward and we can finally close the issue instead of booting out again.

**Comment by lukehoban** [comment]
Great explicit use case and scenario for this in https://github.com/pulumi/pulumi-kubernetes/issues/556#issue-440347474.

**Comment by lukehoban** [comment]
Going to close this out and let https://github.com/pulumi/pulumi-kubernetes/issues/486 track the one issue that motivate additions to the API design - though even that has a workaround.
