### ISSUE TITLE
Require explicit declaration of Kubernetes Provider

### ISSUE THREAD

**Issue by empperi** [pulumi/pulumi-kubernetes#1643]
## Affected feature
As of now Kubernetes Provider in `k8s.Provider` is an optional argument to all of Kubernetes resources under `opts` object. If this provider is not given then Pulumi will revert to default provider which will use kubeconfig found in `~/.kube/config`. This is error-prone, confusing and depending on language used **can cause remote state corruption**. Let me explain.

First of all, not requiring provider in K8s resources and defaulting to default provider is confusing. If one uses an explicit provider it is **very** easy to forget to set that provider to resources. This gets even more confusing since most likely your `~/.kube/config` is pointing to that exact cluster you are working with and everything might seem to work just fine. In truth however you are using two providers: the explicit one and the default one. This is stored to state and now if someone else tries to use this state and doesn't have their `~/.kube/config` pointing to that same cluster it won't work.

Secondly one can screw up remote state even if one has set the provider correctly. This can lead to large portion of Kubernetes resources getting destroyed and recreated and corrupt the remote state with the default provider as described above. This can happen at least with TypeScript when the following criteria is met:

1. Namespace A is referring namespace B. Namespace B defines the provider
2. Namespace B refers to namespace A either directly or via transitive imports

Now depending on execution order that is not controllable by Pulumi it might be that namespace A is executed first. This creates kubernetes resources defined there and those are referring to the provider defined in namespace B. However, that namespace has not executed yet and as such the provider is still `null`. This leads to before mentioned functionality where Pulumi defaults to the default provider.

Basically this means that if one adds an `import` to the namespace defining the provider and that import refers to a namespace which declares Kubernetes resources itself then one silently manages to corrupt all those resources in state.

## Suggested improvement
I suggest Pulumi Kubernetes changes the functionality in the following way:

1. Provide a way to register a default provider that is used by *all* resources if no explicit provider is provided as an argument
2. Make it an error to **not** provide an provider if the default provider has not been registered
3. Make it easy to define the default provider that is currently used under the hood

This is a breaking change but one that is easily fixed even in large codebases relying on default provider functionality. It fixes all of the above problems: accidental mistake of forgetting to give the provider to a resource decalaration, cross-referring namespaces with imports and in general it makes it easier to handle the most common use case: configuring a single kubernetes cluster per stack.

I guess this should start as a deprecation warning and later become an error to not provide the provider explicitly or not register the default provider.

**Comment by headconnect** [comment]
I'll second this - it's far too easy to make mistakes where you end up trying to debug why on earth a new resource hasn't been deployed to the cluster, only to find that you forgot the provider.. and then you look at the current kubeconfig context pointing at the staging cluster.. 

As an aside - considering that for a lot of resources, the safest way to ensure namespacing is to declare the k8s provider again with the namespace scope - there might be a thought to ensuring that providers are always declared so as to avoid that particular hurdle early on before it becomes frustrating/dangerous.

**Comment by lukehoban** [comment]
This is the issue being tracked in https://github.com/pulumi/pulumi/issues/3383 (and the description above also touches on the issue being tracked in https://github.com/pulumi/pulumi/issues/2059), and both are very commonly requested feature, so something I expect we will add support for in the near future.  Would love to consolidate additional scenarios and upvotes on that issue so that we can track it there.
