### ISSUE TITLE
Using server side apply requires namespace to exist before previewing resources that use it

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-kubernetes#1646]
When using server side apply, if you have a resource that depends upon a namespace existing, kubernetes tells pulumi that the namespace is not found, and thus cannot complete the preview.

**Comment by mikhailshilkov** [comment]
I believe this is fixed by https://github.com/pulumi/pulumi-kubernetes/pull/1633 @lblackstone ?

**Comment by nesl247** [comment]
I'll try upgrading. I haven't setup a dependency updater yet as I'm used to and didn't realize we were behind.
