### ISSUE TITLE
How to ask for Job status from automation API?

### ISSUE THREAD

**Issue by adammrozik** [pulumi/pulumi-kubernetes#1653]
Hey,

I am launching k8s job via Pulumi and want to verify its status (not the deployment status).

minimal code is:

```
import os

from pulumi import automation as auto
from pulumi_kubernetes.yaml import ConfigGroup

os.environ['PULUMI_CONFIG_PASSPHRASE'] = 'abc'
os.environ['KUBECONFIG'] = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                        'sa.kubeconfig')
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'job.yaml')

os.environ['AZURE_STORAGE_ACCOUNT'] = 'test'
os.environ[
    'AZURE_STORAGE_KEY'] = 'test'


def pulumi_program():
    a = ConfigGroup(f'test_program', files=[path], skip_await=True)
    print(a.resources.resources())


project_name = f"project_test"
stack_name = f"test"

backend = auto.ProjectBackend(url='azblob://pulumi')
settings = auto.ProjectSettings(name='projects', runtime='python', backend=backend)
opts = auto.LocalWorkspaceOptions(project_settings=settings)


stack = auto.create_or_select_stack(stack_name=stack_name,
                                    project_name=project_name,
                                    program=pulumi_program,
                                    opts=opts)
stack.up()
```

How can I then programatically access the status of the job via pulumi?

**Comment by leezen** [comment]
@adammrozik One approach would be to export the value of the job from your program, along the lines of the example in https://www.pulumi.com/docs/guides/adopting/from_kubernetes/#deploying-multiple-kubernetes-yaml-files

```python
frontend = guestbook.get_resource("v1/Service", "frontend")
export(
  name="privateIp",
  value=frontend.spec.cluster_ip)
```

Then, from Automation API, you can access this value via

```
up_res = stack.up()
up_res.outputs['privateIp'].value
```

(replacing in the above with whatever values and properties you're actually trying to access) and you could even export the identifier to then poll via the API if it's something you wanted to continue to examine outside of Pulumi program execution.

**Comment by adammrozik** [comment]
Hey, thanks for the answer!

This is not solving the issue, as inside Kuberenetes Job Config I do not see things like status of the job, or that POD has failed, only the status of the deployment. Also, this will give me only the value after creation, meanwhile status of the job may keep changing (it may fail, still be running or finish).

What I need is some code that will help me reliably return this status

**Comment by leezen** [comment]
@adammrozik My suggestion is that after you get the value back, since Automation API allows you to mix execution of Pulumi with anything else, you could at that point rely on the k8s client API to query for the status.
