### ISSUE TITLE
Remove last-applied-configuration annotation for resources managed with server-side diff

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1659]
Related to https://github.com/pulumi/pulumi-kubernetes/issues/1556#issuecomment-831526609

It should be possible to remove the `last-applied-configuration` annotation for resources that are created using server-side apply (currently enabled with the [enableDryRun](https://www.pulumi.com/docs/reference/pkg/kubernetes/provider/#enabledryrun_nodejs) Provider flag. This would fix the following issues:

https://github.com/pulumi/pulumi-kubernetes/issues/1464
https://github.com/pulumi/pulumi-kubernetes/issues/1118
https://github.com/pulumi/pulumi-kubernetes/issues/1048

**Comment by viveklak** [comment]
Fixed in https://github.com/pulumi/pulumi-kubernetes/pull/1863
