### ISSUE TITLE
Schema verification in `Check` should be bypassed for resources with any unknown inputs

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-kubernetes#166]
As per discussion with @hausdorff, we cannot reasonably generate valid stand-ins for these values, so verification is very likely to fail. Instead we should bypass verification in `Check`. We'll find any errors when we actually attempt to create/update the relevant resource.

**Comment by lukehoban** [comment]
Is this the same as (the fix we plan to take for) https://github.com/pulumi/pulumi-kubernetes/issues/124?

**Comment by pgavlin** [comment]
Yes, I think so. Closing.
