### ISSUE TITLE
Tooling for generating strongly-typed `values` for Helm charts

### ISSUE THREAD

**Issue by pgavlin** [pulumi/pulumi-kubernetes#167]
Today `values` is simply typed as `any` s.t. it may accommodate the varying shapes of each particular Helm chart's configuration parameters. It would be nice if we had some simple tooling for generating a strongly-typed projection for a particular chart.

**Comment by pavankumarkatakam** [comment]
Actually, i wasted 1 days why my values in chart options not applied. and realized there is some spelling mistake in the python dict keys. Its better if there is typings for the values too.

**Comment by EronWright** [comment]
Pulumi provides some tooling for generating a strongly-typed component wrapper for a given Helm chart, based on the chart's built-in schema:
https://github.com/pulumi/pulumi-go-helmbase
