### ISSUE TITLE
Golang github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/providers package missing in 3.6.0+

### ISSUE THREAD

**Issue by athensofamerica** [pulumi/pulumi-kubernetes#1686]
Upgraded to pulumi-kubernetes v3.6.2. I got this error:

```
go: finding module for package github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/providers
imports
    github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/providers: module github.com/pulumi/pulumi-kubernetes/sdk/v3@latest found (v3.6.2), but does not contain package github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/providers
```
    
Looks like the providers package is removed. instead, we should import: `github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes`
   
Downgrade to 3.5.2 solved the problem. However, according to Alexander Trelore on slack channel, looks like the providers package is removed. instead, we should import: `github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes`
  
Change providers.NewProvider  to kubernetes.NewProvider to create a new provider worked with v3.6.2
In this case, we will need a documentation change, include examples.

## Steps to reproduce

1. change "github.com/pulumi/pulumi-kubernetes/sdk/v3 v3.5.1" to "github.com/pulumi/pulumi-kubernetes/sdk/v3 v3.6.2" in go.mod. Follow by "go mod tidy"

Expected: expect go download the new github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/providers ? 
Actual: The error complain about not able to find github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/providers?

**Comment by lblackstone** [comment]
Sorry for the confusion here. It looks like we were mistakenly including an old version of the Provider at `github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes/providers` that was incidentally removed in https://github.com/pulumi/pulumi-kubernetes/pull/1551.

I am going to add an updated copy back to this path with deprecation notices that you should instead use the version at `github.com/pulumi/pulumi-kubernetes/sdk/v3/go/kubernetes`.
