### ISSUE TITLE
[Helm/Release] Import support

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes#1698]
Helm doesn't store repository information for charts used to create releases. Currently import of existing resources is failing due to failure in resolving charts. We may have to assume the repository is configured on the host system already and search for the helm chart. We may also consider dropping the repository information as a required field.

**Comment by mikhailshilkov** [comment]
Can we close this issue yet?

**Comment by viveklak** [comment]
Fixed in #1818
