### ISSUE TITLE
ConfigGroup and renderYamlToDirectory provider

### ISSUE THREAD

**Issue by thrixton** [pulumi/pulumi-kubernetes#1707]
Might be more of a question, is an explicit provider with `renderYamlToDirectory` supported?

If so, it's not working and this is a bug :)

Pulumi: v3.10.1
kubernetes: 3.7.0

This is in the context of a ConfigGroup with transformations if it matters.

**Comment by mikhailshilkov** [comment]
Hi @thrixton Could you elaborate on what "not working" looks like? A repro code snippet would be helpful. Thank you!

**Comment by thrixton** [comment]
Hi @mikhailshilkov,  
Given the below:
``` typescript

        const yamlProvider = new k8s.Provider("yaml-provider", {
            renderYamlToDirectory: "debug-yaml",
        });

//....//

        const group = new k8s.yaml.ConfigGroup("group", {
//...//
        },
            { provider: yamlProvider }
        );
```  
I get the error
> pulumi:providers:kubernetes yaml-provider  error: pulumi:providers:kubernetes resource 'yaml-provider's property 'kubeconfig' value {...{PATH}...\.kube\config-merged} has a problem: "kubeconfig" arg is not compatible with "renderYamlToDirectory" arg

This looks the same / similar to #992

I do have a heap of transformations applied in the ConfigGroup if it matters.

Apologies, this was an atrocious issue.

**Comment by mikhailshilkov** [comment]
> "kubeconfig" arg is not compatible with "renderYamlToDirectory" arg

This is [saying](https://github.com/pulumi/pulumi-kubernetes/blob/9e7903ccdcdcb28b8f6faec8e5ab79cd37dbae30/provider/pkg/provider/provider.go#L246-L266) that you also have the `kubeconfig` option set to a non-empty string. Do your transformations set kubeconfig?

**Comment by thrixton** [comment]
@mikhailshilkov , thanks for replying.
Just instantiating the yamlProvider (and not using it in any way), causes the same error.
```
        const yamlProvider = new k8s.Provider("yaml-provider", {
            renderYamlToDirectory: "debug-yaml",
        });

//....//

        const group = new k8s.yaml.ConfigGroup("group", {
//...//
        },
            { provider: myOtherProvider }
        );

```
Is there any barrier to instantiating multiple providers side-by-side?

**Comment by mikhailshilkov** [comment]
I ran this:

```ts
import * as k8s from "@pulumi/kubernetes";

const yamlProvider = new k8s.Provider("yaml-provider", {
    renderYamlToDirectory: "debug-yaml",
});

const group = new k8s.yaml.ConfigGroup("group", {
    files: "yaml/*.yaml"
}, { provider: yamlProvider });
```

and it works just fine for me. Could you try this little repro?

You haven't responded to

> Do your transformations set kubeconfig?

I still believe this may be the case?

**Comment by thrixton** [comment]
Sorry @mikhailshilkov , I had to do some other work then forgot about this issue.
I'm definitely not setting kubeconfig anywhere in the transformations.

Question: Is there an issue instantiating two providers at the same time?

I have a conf object which uses stackRefs to tie stacks together and one thing it does is instantiate a provider.

e.g. `provider: new k8s.Provider("admin-provider", { kubeconfig: stackRef.requireOutput("kubeConfigAdmin"), }),`

My conf object is created at the start of each stack run and the provider is not lazy loaded or anything.

Then, I also instantiate the `yamlProvider` as per the original issue.

Could this cause problems?

**Comment by mikhailshilkov** [comment]
Any chance you can extend my short program above to get it to fail the same way you see on your end?

**Comment by thrixton** [comment]
@lamson , thanks for that, that was the exact problem.  
Much appreciated.
