### ISSUE TITLE
Explore better `kubectl` integration

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#171]
It would be nifty if we could hook into `kubectl` somehow, a la

```
$ kubectl pup
```

to do a Pulumi update. I'm not sure if some combination of [plugin magic](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) can achieve this, but @hausdorff thought so.

**Comment by lukehoban** [comment]
Going to close this out - fairly old and I don't think we've seen this come up anywhere else.
