### ISSUE TITLE
[Helm/Release] Resources without explicit namespace are created in default namespace

### ISSUE THREAD

**Issue by michael-barker** [pulumi/pulumi-kubernetes#1710]
When installing a chart that has resources without an explicit namespace set to the release namespace, the resources are created in the default namespace. This can be reproduced by creating a basic chart with `helm create`.

```
helm create /tmp/test
```

```
new k8s.helm.v3.Release('test', {
      name: 'test',
      chart: 'test',
      version: '0.1.0',
      namespace: 'test',
      repositoryOpts: {
        repo: '/tmp/test',
      },
      values: {
      },
    },
  )
```

If the following is added to a manifest in the chart then the resource is created in the `test` namespace as configured in the `Release` resource above.

```
metadata:
  namespace: "{{ $.Release.Namespace }}"
```

**Comment by ruckc** [comment]
From a helm cli equivalent, the `-n {namespace}` isn't being provided.  This is important for helm cli compatibility, as most charts don't specify the namespace as that should be specified at install time.
