### ISSUE TITLE
Can't deploy kube-prometheus-stack with helm.v3.Release

### ISSUE THREAD

**Issue by ruckc** [pulumi/pulumi-kubernetes#1712]
Can't deploy kube-prometheus-stack with helm.v3.Release.  It appears that pulumi is trying to build kubernetes objects for the CRDs that are not yet installed.

## Steps to reproduce

```ts
const prometheusNamespace = new k8s.core.v1.Namespace("prometheus", {
    metadata: {
        name: "prometheus",
    },
});
const prometheusRelease = new k8s.helm.v3.Release("prometheus", {
    name: "kube-prometheus-stack",
    chart: "kube-prometheus-stack",
    repositoryOpts: {
        repo: "https://prometheus-community.github.io/helm-charts",
    },
    version: "18.0.8",
    namespace: prometheusNamespace.metadata.name,
    values: {},
}, { dependsOn: [prometheusNamespace], provider: cluster.provider });
```

Expected: Deployment of kube-prometheus-stack with CRDs
Actual: Fails with error as the CRDs the chart installs are not already installed.

```
Diagnostics:
  kubernetes:helm.sh/v3:Release (prometheus):
    error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
```

**Comment by mikhailshilkov** [comment]
@viveklak could you please take a look?

**Comment by viveklak** [comment]
@ruckc Thanks for raising the issue. This happens to be a limitation with Helm v3's integration with CRDs. We currently attempt the equivalent of a `helm install --dry-run` but this has known issues with CRDs. You can replicate this by running the following on helm directly:
```
 helm install --disable-openapi-validation --dry-run prom prometheus-community/kube-prometheus-stack
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Alertmanager" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "Prometheus" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "PrometheusRule" in version "monitoring.coreos.com/v1", unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"]
```
See https://github.com/helm/helm/issues/7449#issuecomment-591498826 for a detailed description but essentially this has to do with the attempt to dry-run install CRs when the CRDs installation is skipped due to dry-run.

The reason why we do the dry-run is to do some pre-rendering of the manifests (coming soon) and to provide a summary of items installed by the chart at preview time. We might have to treat chart CRDs as a special case and leave these computed. Thoughts @lblackstone?

For now a workaround is to manually install the CRDs first as in https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#from-17x-to-18x

**Comment by ruckc** [comment]
I'm trying to orchestrate a full end to end kubernetes setup, including CRDs and their operators in one project.  I can preinstall them with k8s.file.ConfigGroup, but I'll have to figure out how to detect if they have already been installed before turning on the helm install.

**Comment by viveklak** [comment]
> I'm trying to orchestrate a full end to end kubernetes setup, including CRDs and their operators in one project. I can preinstall them with k8s.file.ConfigGroup, but I'll have to figure out how to detect if they have already been installed before turning on the helm install.

Agreed this is not ideal. We will prioritize this issue.

**Comment by viveklak** [comment]
> but I'll have to figure out how to detect if they have already been installed before turning on the helm install.

You could install the helm chart with `skipCrds: true` to make sure the CRDs are installed through the configFile option instead (and not competed with by the chart).

**Comment by ruckc** [comment]
I have tried the `skipCrds: true` with them installed via configFile, but it still fails since helm is trying to resolve them during preview (and during an up).  i am trying to figure out how to wrap the helm.v3.Release in a conditional so it just will take two ups

**Comment by ruckc** [comment]
Oh also, @viveklak, pulumi is the closest I've come to be able to have one project, that can declaratively describe our infrastructure that we need to spin up and tear down.  terraform's DSL has too many limitations (lack of conditional and clear dependency support).

**Comment by viveklak** [comment]
> I have tried the `skipCrds: true` with them installed via configFile, but it still fails since helm is trying to resolve them during preview (and during an up). i am trying to figure out how to wrap the helm.v3.Release in a conditional so it just will take two ups

Ah yes. You might have to move the chart creation inside an apply block depending on the configFile resource which should avoid the preview issue. If you ping me on [community slack](https://slack.pulumi.com/), happy to help you navigate this.

**Comment by viveklak** [comment]
> We currently attempt the equivalent of a `helm install --dry-run` but this has known issues with CRDs.

Overall it seems doing a dry-run might be the wrong call on preview. Instead we should do what the Helm chart resource currently does and just use the output of the equivalent of `helm template` for the manifests and resource summary instead.

**Comment by viveklak** [comment]
This is now rolled out in v3.7.2

**Comment by ruckc** [comment]
I saw, and appreciate it.  My next stumbling block is the namespace issue in #1710.
