### ISSUE TITLE
[Helm/Release] Ambassador Traffic Manager charts fails to install with Release but succeeds with Helm

### ISSUE THREAD

**Issue by michael-barker** [pulumi/pulumi-kubernetes#1715]
Installing the [Ambassador Traffic Manager](https://www.getambassador.io/docs/telepresence/latest/install/helm/) chart as a `Release` resource fails with the following error.

```
  kubernetes:helm.sh/v3:Release (telepresence):
    error: Object 'Kind' is missing in 'null'
```

Below is the `Release` definition.

```
new k8s.helm.v3.Release('telepresence', {
    name: 'traffic-manager',
    chart: 'telepresence',
    version: '2.4.0',
    namespace: 'ambassador',
    repositoryOpts: {
      repo: 'https://app.getambassador.io',
    },
    values: {},
  }
)
```

Installing the chart directly with Helm succeeds.

```
helm install traffic-manager --namespace ambassador datawire/telepresence
```

Not sure if this is helpful but I found a [similar issue in Flux Helm Operator](https://github.com/fluxcd/flux/issues/2137) for the same error. It looks like the issue was resolved by filtering out nil resources.

**Comment by viveklak** [comment]
Thanks for opening the issue! This has been fixed in v3.7.2.
