### ISSUE TITLE
[Helm/Release] Should helm.v3.Release perform a `helm upgrade -i`

### ISSUE THREAD

**Issue by ruckc** [pulumi/pulumi-kubernetes#1727]
I've run into a few occurances where helm.v3.Release fails to create the initial release (for many reasons), the Release doesn't get recorded in state, but it still exists in the kubernetes cluster.  Upon fixing the mistake and attempting to re-up, it fails because the release already exists.  I think that helm.v3.Release should perform the equivalent of `helm upgrade -i` where it installs if not already present, or upgrades if it is already present.  

## Steps to reproduce
1.  
```ts
const release = new k8s.helm.v3.Release("kibana", {
            name: "kibana",
            chart: "kibana",
            repositoryOpts: {
                repo: "https://helm.elastic.co",
            },
            version: "7.14.0",
            values: {
                elasticsearchHosts: "http://nowhere",
            },
            timeout: 30,
}
```
2. Wait for it to timeout and fail
3. Try to pulumi up again
4. Fails with 
```
kibana (kubernetes:helm.sh:Release)
error: cannot re-use a name that is still in use
```

Expected: I expected it to perform the equivalent of a `helm upgrade -i`
Actual: It fails causing a human to manually reconcile the state.

**Comment by viveklak** [comment]
This is an instance of https://github.com/pulumi/pulumi-kubernetes/issues/1697. I have added your recommendation to that ticket.

**Comment by viveklak** [comment]
Tracked in https://github.com/pulumi/pulumi-kubernetes/issues/1697
