### ISSUE TITLE
[Python] MyPy Error on Output.all(ConfigFile().resources)

### ISSUE THREAD

**Issue by SharpEdgeMarshall** [pulumi/pulumi-kubernetes#1729]
MyPy throw an error when you pass a `Chart` or `ConfigFile` `resources` property to `Output.all`

## Steps to reproduce

```
foo = ConfigFile("foo")

ConfigFile(
    "bar",
    opts=pulumi.ResourceOptions(
        depends_on=Output.all(
            foo.resources
        ).apply(lambda res: list(res.values())),
    ),
)
```

Expected: No Error on MyPy
Actual: `Argument 1 to "all" of "Output" has incompatible type "Output[Dict[Any, Any]]"; expected "Union[<nothing>, Awaitable[<nothing>], Output[<nothing>]]"`

**Comment by mikhailshilkov** [comment]
`resources` is an `pulumi.Output[dict]` ([link](https://github.com/pulumi/pulumi-kubernetes/blob/36a5fb34240a38a60b52a5f4e55e66e248d9305f/sdk/python/pulumi_kubernetes/helm/v3/helm.py#L14)) - why are you trying to pass it to `Output.all`. I think you should be able to run `foo.resources.apply(...)` directly.

**Comment by SharpEdgeMarshall** [comment]
@mikhailshilkov because i need to wait for resources from multiple ConfigFiles/Charts/Kustomize like this:

```
foo = ConfigFile("foo")
baz = ConfigFile("baz")

ConfigFile(
    "bar",
    opts=pulumi.ResourceOptions(
        depends_on=Output.all(
            foo.resources, baz.resources
        ).apply(lambda res: [*(res[0].values()), *(res[1].values())]),
    ),
)
```

**Comment by mikhailshilkov** [comment]
Maybe unrelated - but I don't think you can pass outputs to `depends_on`, since it's defined as 

```py
depends_on: Optional[List['Resource']]
```

**Comment by mikhailshilkov** [comment]
cc @lblackstone who is more savvy with Python and awaiting for resources

**Comment by SharpEdgeMarshall** [comment]
That's what I see on depends_on: `(parameter) depends_on: Sequence[Input[Resource]] | Resource | Awaitable[Sequence[Input[Resource]] | Resource] | Output[Sequence[Input[Resource]] | Resource] | None`

**Comment by lblackstone** [comment]
I'd guess you need to pass just the values to `Output.all`. Something along these lines (untested):

```py3
foo = ConfigFile("foo")

ConfigFile(
    "bar",
    opts=pulumi.ResourceOptions(
        depends_on=Output.all(
            foo.resources.values()
        ),
    ),
)
```

**Comment by EronWright** [comment]
This problem is now solved with  `v2.ConfigFile`.
- One may now depend on a `ConfigFile` resource in the ordinary way, to wait for the objects to be installed.  Try: `depends_on=foo`.
- The `resources` output property is now an array of resources, not a dictionary.

See blog post for more information:
https://www.pulumi.com/blog/kubernetes-yaml-v2/
