### ISSUE TITLE
[Helm/Release] Support local path

### ISSUE THREAD

**Issue by cynial** [pulumi/pulumi-kubernetes#1732]
Currently Helm/Chart support path：
```
		_, err := helmv3.NewChart(ctx, "wpdev", helmv3.ChartArgs{
			Path: pulumi.String("./hello"),
		})
```
But Helm/Release doesn't support：
```
		rel, err := helmv3.NewRelease(ctx, "test", &helmv3.ReleaseArgs{
                         // No Path args for Release
			RepositoryOpts: helmv3.RepositoryOptsArgs{
				Repo: pulumi.String("./hello"),
			},
		})
---
throw error:
          failed to pull chart: could not find protocol handler for:
```
Is it possible to support path for Helm/Release? Thanks.

**Comment by mikhailshilkov** [comment]
@viveklak Is there a way forward here?

**Comment by lblackstone** [comment]
There's no technical reason we can't support this. The current implementation appears to be making some bad assumptions, but it's fixable. I'll go ahead and pull this into the current milestone since I'm working on related code.
