### ISSUE TITLE
CustomResource's `.spec.node_selector` gets overwritten to `.spec.nodeSelector`

### ISSUE THREAD

**Issue by stanislav-zaprudskiy** [pulumi/pulumi-kubernetes#1740]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have a CustomResource with `node_selector` in its `.spec`. When deploying such a resources, Pulumi seem to be sending a request with `nodeSelector` instead, however - which is not picked up, thus the resource doesn't get its proper configuration applied.

### Steps to reproduce

Here is the Pulumi program:

```python
awx_operator = ConfigGroup(
    "awx-operator",
    files=[
        "https://raw.githubusercontent.com/ansible/awx-operator/0.13.0/deploy/awx-operator.yaml",
    ],
)

awx = CustomResource(
    "awx",
    api_version="awx.ansible.com/v1beta1",
    kind="AWX",
    metadata={
        "name": "awx",
    },
    spec={
        "node_selector": 'kubernetes.io/hostname: "docker-desktop"\n',
        "replicas": 1,
        "service_type": "ClusterIP",
    },
    opts=pulumi.ResourceOptions(
        depends_on=awx_operator.resources
        .apply(lambda resources: list(resources.values()))
    ),
)
```

After doing `pulumi update` I get the following resource created:

```yaml
$ kubectl get awx/awx -o yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"awx.ansible.com/v1beta1","kind":"AWX","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"awx"},"spec":{"nodeSelector":"kubernetes.io/hostname: \"docker-desktop\"\n","replicas":1,"service_type":"ClusterIP"}}
  creationTimestamp: "2021-09-30T11:18:02Z"
  generation: 1
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx
    app.kubernetes.io/operator-version: 0.13.0
    app.kubernetes.io/part-of: awx
  name: awx
  namespace: default
  resourceVersion: "605"
  uid: 58c57e37-c345-45d2-a42e-b165bce35aa0
spec:
  admin_user: admin
  create_preload_data: true
  garbage_collect_secrets: false
  image_pull_policy: IfNotPresent
  loadbalancer_port: 80
  loadbalancer_protocol: http
  projects_persistence: false
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  replicas: 1
  route_tls_termination_mechanism: Edge
  service_type: ClusterIP
  task_privileged: false
status:
  conditions:
  - lastTransitionTime: "2021-09-30T11:18:05Z"
    reason: Running
    status: "True"
    type: Running
```

Expected: the resource must have `node_selector` key set in its specification.

Actual: no `node_selector` spec is set; also notice `kubectl.kubernetes.io/last-applied-configuration` annotation, containing the following json:

```json
{
  "apiVersion": "awx.ansible.com/v1beta1",
  "kind": "AWX",
  "metadata": {
    "labels": {
      "app.kubernetes.io/managed-by": "pulumi"
    },
    "name": "awx"
  },
  "spec": {
    "nodeSelector": "kubernetes.io/hostname: \"docker-desktop\"\n",
    "replicas": 1,
    "service_type": "ClusterIP"
  }
}
```

which indicates that `node_selector` has been overwritten with `nodeSelector`.

Additional notes: the same is experienced also when deploying the similar resource via local Helm chart or `ConfigFile`.

**Comment by leezen** [comment]
Interesting -- this is a use case that is an edge-case of something we thought we had closed out via https://github.com/pulumi/pulumi/issues/3151. That issue has the workaround you need https://github.com/pulumi/pulumi/issues/3151#issuecomment-704509706 where you can patch the resource to use a different `translate` on the input/output side to avoid having the key rewritten.

I think `CustomResource` didn't pick up the new codegen changes that came in https://github.com/pulumi/pulumi/pull/6696/files as it uses a different codegen path. We should do an audit of those paths to ensure we don't have other cases like this.

**Comment by stanislav-zaprudskiy** [comment]
The workaround helped, thank you
