### ISSUE TITLE
[Helm Release] Not working with private helm repos

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes#1757]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

Copied from https://github.com/pulumi/pulumi-kubernetes/issues/1735#issuecomment-933611354
## Issue details
I tried using the new helm.Release but that does not seem to work with a private helm repo.
```
argo_args = helm.ReleaseArgs(
    chart="argocd",
    skip_await=False,
    namespace='argocd',
    values=values['argocd'],
    repository_opts=helm.RepositoryOptsArgs(
        repo=config.require('helm_repo'),
        username=config.require('helm_user'),
        password=config.require('helm_password')
    )
)
argo_release = helm.Release("argocd", args=argo_args)
```
This gives me the following error:

```
error: failed to pull chart: looks like "https://genuitysci.jfrog.io/artifactory/gorkubbe" is not a valid chart repository or cannot be reached: failed to fetch https://genuitysci.jfrog.io/artifactory/gorkubbe/index.yaml : 401 Unauthorized
This is using the same credentials that work with helm.Chart so they are not the problem
```

**Comment by viveklak** [comment]
Updated to include local helm charts in scope as well since I expect the fix to cover both.

**Comment by lblackstone** [comment]
I don't think the local chart not working is actually the same underlying problem. It appears that the current implementation doesn't consider local charts at all, but I'd guess that the private repo issue is related to credentials not being plumbed through correctly. It looks like https://github.com/pulumi/pulumi-kubernetes/issues/1732 is the local path issue, so I'll track progress there separately.
