### ISSUE TITLE
Please provide working examples

### ISSUE THREAD

**Issue by VikramVasudevan** [pulumi/pulumi-kubernetes#1765]
File: [themes/default/content/docs/reference/pkg/kubernetes/networking/v1/ingress/_index.md](https://www.pulumi.com/docs/reference/pkg/kubernetes/networking/v1/ingress/)

Like in the other pulumi documentation, please provide working examples. It would be very helpful for people who are trying to learn.

**Comment by lblackstone** [comment]
> Are there external sample sets that we may consider converting?

I don't know of a single canonical source, but we should be able to find good examples for the common types in the upstream reference docs.

**Comment by lblackstone** [comment]
Here's the first wave of examples:

[Deployment](https://www.pulumi.com/registry/packages/kubernetes/api-docs/apps/v1/deployment/#example-usage)
[StatefulSet](https://www.pulumi.com/registry/packages/kubernetes/api-docs/apps/v1/statefulset/#example-usage)
[Job](https://www.pulumi.com/registry/packages/kubernetes/api-docs/batch/v1/job/#example-usage)
[Pod](https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/pod/#example-usage)
[Service](https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/service/#example-usage)
[Ingress](https://www.pulumi.com/registry/packages/kubernetes/api-docs/networking/v1/ingress/#example-usage)

We'll continue to add more in the future once https://github.com/pulumi/pulumi-kubernetes/issues/1800 is done.
