### ISSUE TITLE
CustomResource update fails with "the body of the request was in an unknown format" error

### ISSUE THREAD

**Issue by seunggs** [pulumi/pulumi-kubernetes#1774]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When running `pulumi up` for the second time, CustomResource fails to update with the error:

```
error: 1 error occurred:
        * the Kubernetes API server reported that "sidetrek-webapp-staging-cd3aydbs/frontend-svc" failed to fully initialize or become live: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml
```

Currently using @pulumi/pulumi ^3.10.1 and @pulumi/kubernetes ^3.6.0

### Steps to reproduce
Run `pulumi up` with a CustomResource for Knative service (runs fine the first time the resource is created but fails for every subsequent `pulumi up`):

```
const KService = new k8s.apiextensions.CustomResource('api-svc', {
  apiVersion: 'serving.knative.dev/v1',
  kind: 'Service',
  metadata: {
    namespace,
    name,
  },
  spec: {
    template: {
      spec: {
        containers: [
          {
            image
          }
        ],
      }
    },
  },
}, { provider: k8sProvider })
```

**Expected**: Expected the CustomResource to be updated without error
**Actual**: Works fine on first `pulumi up` but fails on update (i.e. every subsequent `pulumi up`)

**Comment by lblackstone** [comment]
It's out now! https://github.com/pulumi/pulumi-kubernetes/releases/tag/v3.8.3

**Comment by seunggs** [comment]
Awesome! 🎉

I can confirm that Knative revisions are now getting created properly on code update:

```
NAME            CONFIG NAME   K8S SERVICE NAME   GENERATION   READY   REASON   ACTUAL REPLICAS   DESIRED REPLICAS
app-svc-00001   app-svc                          1            True             1                 1
app-svc-00002   app-svc                          2            True             1                 1
```

Thanks for the quick turnaround on this!
