### ISSUE TITLE
Schematize and use codegen'ed versions of custom resources where possible

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes#1778]
Follow up from #1740 and other similar issues. We are supporting hand-crafted resource types for things like custom resources, custom resource definitions etc. loosely based on point-in-time codegen status. We miss codegen fixes in this process. We should use the next major release to deprecate older implementations and replace these resources with schematized versions.

**Comment by lblackstone** [comment]
Closing this issue in favor of https://github.com/pulumi/pulumi-kubernetes/issues/1971, which includes more details about the problem.
