### ISSUE TITLE
Python docs for helm.Chart are not working?

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#1799]
At https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/.

Python:
![Screen Shot 2021-11-15 at 11 56 25 AM](https://user-images.githubusercontent.com/223467/141845662-5914c279-68b1-4c79-bd62-0b6e19d89ba5.png)

TypeScript and all other languages work correctly:
![Screen Shot 2021-11-15 at 11 56 32 AM](https://user-images.githubusercontent.com/223467/141845657-c58397d2-d4ea-4f14-a9eb-d43d506fc13a.png)

**Comment by mikhailshilkov** [comment]
Hmm, the same problem exists for `Release` but not e.g. for `ConfigGroup`. @lblackstone any ideas?

**Comment by lblackstone** [comment]
I took a look and don't know for sure. `Chart` is still based on older codegen, and hasn't been updated to include input types or constructor overloads. Perhaps it's a bug triggered by having `Chart` in the same module as `Release`, since the latter is using the latest codegen.

**Comment by mikhailshilkov** [comment]
But docs are based purely on the Pulumi schema - why would codegen matter?

**Comment by lblackstone** [comment]
Oh, good point. I'm not sure what the problem is, so we'll need to investigate further.
