### ISSUE TITLE
Port the Heptio AWS QuickStart to Pulumi

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#18]
It would be interesting to port the Heptio AWS QuickStart to Pulumi.  Taking a glance, it looks pretty straightforward, and much like most of our other CloudFormation porting exercises:

* QuickStart: https://aws.amazon.com/quickstart/architecture/heptio-kubernetes/
* Deploying Into a New VPC Template: https://s3.amazonaws.com/quickstart-reference/heptio/latest/templates/kubernetes-cluster-with-new-vpc.template
* Deploying Into an Existing VPC Template: https://console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/new?stackName=Heptio-Kubernetes&templateURL=https://s3.amazonaws.com/quickstart-reference/heptio/latest/templates/kubernetes-cluster.template

This has certainly gotten less interesting thanks to EKS, however it still could be useful, especially if there's any hope of sharing some of the configuration across cloud providers.

Note, subtly, that this is all about managing AWS resources, not Kubernetes one.  This is a "base layer" stack that defines a Kubernetes cluster.  We would expect application-level ones to layer atop.

**Comment by hausdorff** [comment]
@joeduffy do you still think this is worth doing?
