### ISSUE TITLE
[Helm/Release] Examples are missing in docs

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-kubernetes#1803]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
[Release](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/) needs examples similar to the ones that are in [Chart](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/#example-usage).  The examples need to be above the [create](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/#create) section

**Comment by mikhailshilkov** [comment]
Is this the same as https://github.com/pulumi/pulumi-kubernetes/issues/1695?

**Comment by tusharshahrs** [comment]
Yes, closing as duplicate
