### ISSUE TITLE
Upgrade CI, use recent API versions

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#181]
_e.g._, prefer `apps.v1.Deployment` to `apps.v1beta1.Deployment`. This is prevented by our lagging minikube version.

**Comment by lblackstone** [comment]
@hausdorff Is this still relevant? If so, can you add some more details?

**Comment by hausdorff** [comment]
@lblackstone we're just using old versions of API objects in tests. We can close this because we moved all the examples to the tests directory.
