### ISSUE TITLE
Helm Release vs. Chart guide

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-kubernetes#1811]
When we get the `Release` resource to GA, we should publish a doc or a blog to highlight our guidance on when `Release` should be used instead of `Chart` and vice versa and what our longer term plans are in this regards. Are we going to deprecate `Chart`? Are we going to ship new features to it?

**Comment by viveklak** [comment]
https://github.com/pulumi/pulumi-hugo/pull/1023 includes a guide on using chart vs. release. We are not deprecating Chart as yet though we do intend to deprecate Helm v2 Chart support when Helm OCI support is merged (https://github.com/pulumi/pulumi-kubernetes/pull/1892)
