### ISSUE TITLE
kubeconfig rotation `x509: certificate signed by unknown authority`

### ISSUE THREAD

**Issue by MichaelSp** [pulumi/pulumi-kubernetes#1814]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I have rotated the `certificate-authority-data` and the `token` of a **target** cluster. That results in a new `kubeconfig`, which is stored in a dedicated cluster as secret.
Subsequent requests to the **target** cluster fail because the `x509: certificate signed by unknown authority`

### Steps to reproduce

Provider definition
```ts
// get the cluster config from another k8s cluster that stores kubeconfigs in secrets using default provider
const kubeconfig = await k8s.core.v1.Secret.get(name, `my-namespace/${clusterName}.kubeconfig`, {
    additionalSecretOutputs: ['data']
}).data.apply(data => Buffer.from(data["kubeconfig"], "base64").toString("utf-8"));

// build a new provider for destination cluster
k8sProviders[clusterName] = new k8s.Provider(clusterName, {
    kubeconfig,
    kubeClientSettings: { burst: 130, qps: 100 }
});
```

refresh resources to fetch the new `kubeconfig`
```shell 
$ pulumi refresh`
[...]

  kubernetes:rbac.authorization.k8s.io/v1:Role (namespace-admin):
    warning: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://<my-target-cluster-api>/openapi/v2?timeout=32s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
    error: Preview failed: failed to read resource state due to unreachable cluster. If the cluster has been deleted, you can edit the pulumi state to remove this resource

[...]
```

Expected: 
New `kubeconfig` is fetched and applied.

Actual: 
Unable to connect to the target cluster

**Comment by MichaelSp** [comment]
I have tried to delete the `pulumi:providers:kubernetes` from the state but that results in an inconsistent state because it is still used in dependent resources. 
I don't know what else to try to update the providers `kubeconfig`.

**Comment by lblackstone** [comment]
Since the credentials have changed, you'll need to run an `update` rather than `replace` to propagate that change to the Provider resource. I'm not sure if the dependent resources are in the same stack, but if so, you should be able to use the [`--target` option](https://www.pulumi.com/docs/reference/cli/pulumi_up/#options) to selectively update the Provider and Secret resources before running the `refresh` operation as normal once those updates complete.

**Comment by MichaelSp** [comment]
They are in the same stack.

```shell
$ pulumi up --target  urn:pulumi:<kubeconfig-secret> --target urn:pulumi:infra.dev::infra::pulumi:providers:kubernetes::<my-provider>

Previewing update (infra.dev):
     Type                            Name             Plan
     pulumi:pulumi:Stack             infra-infra.dev
 +-  └─ pulumi:providers:kubernetes  <my-provider>      replace

Resources:
    +-1 to replace
    116 unchanged
```

and then  `pulumi refresh && pulumi up` worked quite nicely. Thanks for your help @lblackstone
