### ISSUE TITLE
Importing a helm Release resource stores local path to gpg pubring in state

### ISSUE THREAD

**Issue by silphid** [pulumi/pulumi-kubernetes#1825]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When importing a helm Release using the new version of `helm.v3.Release` (that @viveklak worked on, thanks!!), the provider stores the local path `/Users/mathieu/.gnupg/pubring.gpg` in the `keyring` input field in the state, which obviously is valid only on current machine. Afterwards, doing a `pulumi up` from another machine will require an update of that field.

### Steps to reproduce

Here's an example:
https://app.pulumi.com/nesto/host/dev/resources/latest/urn:pulumi:dev::host::nesto:ingress-nginx$kubernetes:helm.sh/v3:Release::ingress-nginx-controller

Take a look at the `keyring` field there, which is set to `/Users/mathieu/.gnupg/pubring.gpg`.

The code used to perform the import was:
```
    new k8s.helm.v3.Release(
      model.name,
      {
        chart: 'ingress-nginx',
        values: values,
        version: model.repoVersion,
        namespace: 'nginx-ingress-controller',
      },
      {
        parent: this,
        import: 'nginx-ingress-controller/release-kl2buwnx',
        provider: cluster.provider,
      }
    );
```

Expected: That the `keyring` field would not be stored in state at all, or that it would at least have some more generic value with better chances of working on other machines (ie: `~/.gnupg/pubring.gpg`).

Actual: It is stored in state and has a value specific to the machine that did the import.

**Comment by gitfool** [comment]
@viveklak the [fix for this issue](https://github.com/pulumi/pulumi-kubernetes/commit/a04dd69fd0d41af2d6cbac0e206e8e2f1ce81041#diff-5617494009217af4c00b644fdb55b2aaaedce6497f9ae5d6620963f87e25cfc3R365-R367) seems to have been regressed by the [fix for 1953](https://github.com/pulumi/pulumi-kubernetes/commit/337146ebdc9e8c1eddd2c377cb12a1ca304d1c9f#diff-5617494009217af4c00b644fdb55b2aaaedce6497f9ae5d6620963f87e25cfc3L388) released in [v3.18.1](https://github.com/pulumi/pulumi-kubernetes/releases/tag/v3.18.1).

I'm not importing helm releases but pulumi update now has the following diffs when I switch between windows and linux:
```
 ~  kubernetes:helm.sh/v3:Release ack-iam-controller update [diff: ~keyring]
 ~  kubernetes:helm.sh/v3:Release ack-s3-controller update [diff: ~keyring]
 ~  kubernetes:helm.sh/v3:Release appmesh-controller update [diff: ~keyring]
 ~  kubernetes:helm.sh/v3:Release aws-ebs-csi-driver update [diff: ~keyring]
 ~  kubernetes:helm.sh/v3:Release aws-efs-csi-driver update [diff: ~keyring]
 ~  kubernetes:helm.sh/v3:Release aws-load-balancer-controller update [diff: ~keyring]
 ~  kubernetes:helm.sh/v3:Release cert-manager update [diff: ~keyring]
 ~  kubernetes:helm.sh/v3:Release cluster-autoscaler update [diff: ~keyring]
 ~  kubernetes:helm.sh/v3:Release external-dns update [diff: ~keyring]
 ~  kubernetes:helm.sh/v3:Release fluent-bit update [diff: ~keyring]
```
