### ISSUE TITLE
kustomize.Directory doesn't work with github repository

### ISSUE THREAD

**Issue by jancespivo** [pulumi/pulumi-kubernetes#1829]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

`kustomize.Directory` resource doesn't install anything when directory is https://github.com/kubernetes-sigs/gateway-api/tree/v0.4.0/config/crd/

### Steps to reproduce

```python
import pulumi_kubernetes as kubernetes
kubernetes.kustomize.Directory(
    "gateway-api",
    directory="https://github.com/kubernetes-sigs/gateway-api/tree/v0.4.0/config/crd/",
)
```

Expected: 
It should install files from a directory `v1alpha2` as it is declared in a file `kustomization.yaml`

Actual:
no files are installed

**Comment by mikhailshilkov** [comment]
@lblackstone Could you please respond to this issue?

**Comment by lblackstone** [comment]
I wasn't able to reproduce the problem, and the CRDs installed as expected when I tested locally. 

![Screen Shot 2021-12-10 at 1 53 00 PM](https://user-images.githubusercontent.com/9253463/145639947-25842244-e9d0-46cb-ac28-187b10429f7c.png)

I'm going to close this issue for now, but feel free to reopen with info on particular errors if you're still having troubles.

**Comment by jancespivo** [comment]
@lblackstone Thx!
I'm sorry. I hit a combination of two errors (https://github.com/pulumi/pulumi-kubernetes/issues/1755 and probably this one https://github.com/pulumi/pulumi-kubernetes/issues/1773). Actually I wonder you don't hit the first one :thinking: Never mind, this issue is solved.
