### ISSUE TITLE
Too frequent Client.Timeout

### ISSUE THREAD

**Issue by liubog2008** [pulumi/pulumi-kubernetes#1839]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Too many Client.Timeout when I run `pulumi up`. A global CLI timeout option is needed.

I don't know whether the problem is because of uncached(only memory cached) openapi schema. Some error outputs:

```
configured Kubernetes cluster is unreachable: unable to load schema information from the API server: unexpected error when reading response body. Please retry. Original error: net/http: request canceled (Client.Timeout or context cancellation while reading body)
```

Maybe disk cached openapi schema is needed (use same cache of kubectl？)

By the way, if I add `--refresh` it will always timeout.

### Steps to reproduce

Expected: 

1. Global CLI timeout flag.
2. Disk cached openapi schema discovery.

Actual:

**Comment by mikhailshilkov** [comment]
@liubog2008 Do you have a code snippet that I could try to reproduce this error?

**Comment by liubog2008** [comment]
Maybe you should have a bad network and install many CRDs in kubernetes.

**Comment by liubog2008** [comment]
It's worked fine if network is quick.

**Comment by liubog2008** [comment]
@mikhailshilkov Any progress?

**Comment by PRIHLOP** [comment]
I agree with @tusharshahrs , he described the requirements well. But, only the first point is implemented and not solve all issues about k8s cluster connection.
I think, the second point of @tusharshahrs  suggestion also requires implementation.

> If automatic retry logic does not exist for query/idempotent requests, retry logic should be added. If retry logic does exist, perhaps its behavior could be exposed as parameters on the provider (i.e. # of retry attempts, backoff base, backoff duration)
