### ISSUE TITLE
PenableReplaceCRD not working

### ISSUE THREAD

**Issue by ncsibra** [pulumi/pulumi-kubernetes#1840]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

**Comment by mikhailshilkov** [comment]
@ncsibra Could you please provide some details to the issue?

**Comment by ncsibra** [comment]
@mikhailshilkov Sorry, it was a misclick, the correct issue is here: https://github.com/pulumi/pulumi-kubernetes/issues/1841
