### ISSUE TITLE
Silent lack of progress when a deployment's pods can't be scheduled

### ISSUE THREAD

**Issue by antifuchs** [pulumi/pulumi-kubernetes#1843]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

We just ran into an issue on our EKS k8s cluster while running `pulumi up` that exposed a slightly confusing behavior in pulumi for us. The "background radiation problem" was the following:

* A system node had run out of IPs that it could attach to an ENI
* That caused new pods to be created, but be stuck in "ContainerCreating" states.

While this was going on, I ran `pulumi up` and saw the following in both the CLI and the "Diagnostic" view for the update:

* None of the actions pulumi was attempting to take had been logged: It had created a "Job", but didn't display that it had done so, and didn't say it was waiting.
* There was a spinner at the bottom of the page.

It took opening up `k9s` and investigating the various `ContainerCreating` pods to realize what was happening.

### Steps to reproduce

This is probably hard to reproduce, but:

1. Run out of a resource (in our case, IP addresses attached to a child ENI) such that new pods get stuck in ContainerCreating
2. Run `pulumi up` such that it tries to create new containers

Expected: progress output indicating what it had attempted (created a Job, Deployment, StatefulSet)
Actual: a silent spinner, waiting until the pods move forward a state.

**Comment by EronWright** [comment]
Fixed: https://github.com/pulumi/pulumi-kubernetes/pull/3135
