### ISSUE TITLE
NewConfigFile with remote Url

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-kubernetes#1851]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
When I try to use ConfigFile with a remote file (here tekton) nothing happens.

```
tekton, err := yaml.NewConfigFile(ctx, "tekton",
		&yaml.ConfigFileArgs{
			File: "https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml",
			
		}, pulumi.Provider(args.Provider),
	) 
```

Very strange, no error message to work with. 

I checked to URL, and there is no redirect going on. At least what `curl -v -L` tells me

**Comment by matdehaast** [comment]
I'm having the exact same issue, it creates the resource. But nothing happens on the cluster

**Comment by dirien** [comment]
Works!
