### ISSUE TITLE
Chart.yml not found using k8s.helm.v3.Release

### ISSUE THREAD

**Issue by KostyaZgara** [pulumi/pulumi-kubernetes#1852]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Can't create chart release using resource `k8s.helm.v3.Release`. Failed with error `error: Preview failed: release not found: "vault": failed to load chart from temp directory: Chart.yaml file is missing`.

Before this, I used `k8s.helm.v3.Chart` and everything was fine.

I tried to disable `lint`, `verify` and other things.

After several unsuccessful tries and had a look is working the release with helm cli, and it worked, so I think the reason in not in broken helm chart.

### Steps to reproduce

```typescript
export const vaultChart = new k8s.helm.v3.Release(
  'vault',
  {
    chart: 'vault',
    name: 'vault',
    repositoryOpts: {
      repo: 'https://helm.releases.hashicorp.com',
    },
    namespace: 'vault',
    values: {
       global: {
        enabled: true,
      },
      server: {
        extraEnvironmentVars: {
          GOOGLE_REGION: 'global',
          GOOGLE_PROJECT: projectName,
          GOOGLE_APPLICATION_CREDENTIALS:
            '/vault/userconfig/kms-creds/credentials.json',
        },
        extraVolumes: [
          {
            type: 'secret',
            name: kmsAdminCredentialsSecret.metadata.name,
          },
        ],
        ha: {
          enabled: true,
          replicas: 3,
        },
        auditStorage: {
          enabled: true,
          storageClass: 'standard',
          accessMode: 'ReadWriteOnce',
        },
      },
    },
  },
);
```

Expected: 

Release successfully deployed

Actual: 

![image](https://user-images.githubusercontent.com/18326076/147679212-a498b6ca-dab9-4d76-8c7c-7f929e489715.png)

Versions:

- pulumi cli: v3.20.0
- @pulumi/pulumi: 3.20.0
- @pulumi/kubernetes: 3.12.1

**Comment by KostyaZgara** [comment]
Resolved. Seems the bug comes from `helm` due to this issue https://github.com/hashicorp/terraform-provider-helm/issues/735. So, a solution is resolving folder `vault` in my stack folder

**Comment by seunggs** [comment]
I'm running into the same issue but not sure how you resolved it? 

Do you mind elaborating a little? Not sure what you mean by "resolving folder vault in my stack folder"?

**Comment by KostyaZgara** [comment]
Sorry for the mistake instead `resolving` I mean `renaming` (I will fix my initial comment to avoid confusing). I had following structure

```
stacks/
  production/
    vault/
      vault.release.ts // Here was defined my chart class 
      index.ts // Here I made import chart to popup to the top index.ts
    index.ts // And here I imported all my resources in one place and run pulumi up from folder `production`
```

I don't exactly why, but somehow when you specify name of release `vault`, helm tries to get chart from your local folder `vault`. For me, solution was just to rename folder `vault` to `vault-system` or any other name. Resultantly, I had the next structure

```
stacks/
  production/
    vault-system/
      vault.release.ts
      index.ts
    index.ts
```

Try it yourself and share any information if it works for you as well

**Comment by seunggs** [comment]
Ah got it - yes it looks like a helm bug as you mentioned. I had the `/kratos` folder in my project which has the same name as the release name and when I renamed it, this error went away. Thanks!
