### ISSUE TITLE
Force pulumi to wait for connection to be enstablished

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-kubernetes#1857]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
Hi,
I would like to start an ssh tunnel to the kubernetes master before pulumi starts to deploy the kubernetes resources.

Consider the following snippet:

```python
from datetime import datetime

cmd = f"""
# {datetime.now()}
ssh .... -f ....
"""

k8s_ssh = local.Command(
    "k8s_ssh",
    create=cmd,
    delete=cmd,
    triggers=[cmd],
    opts=ResourceOptions(
        delete_before_replace=True,
    ),
)

k8s_provider = kubernetes.Provider(
    "k8s_provider",
    opts=ResourceOptions(
        depends_on=[k8s_ssh],
    ),
)

nginx_ns = kubernetes.core.v1.Namespace(
    "nginx-ns",
    metadata=kubernetes.meta.v1.ObjectMetaArgs(
        name="nginx",
        labels={
            "name": "nginx",
        },
    ),
    opts=ResourceOptions(
        provider=k8s_provider,
        depends_on=[k8s_ssh],
    ),
)
```

Using the `depends_on` flag I am able to let pulumi understand that `k8s_provider` and `nginx_ns` must wait for `k8s_ssh` (ssh tunnel to be established).
The `{datetime.now()}` forces pulumi to replace `k8s_ssh` on every `pulumi up`.

A `pulumi up` from scratch works as expected: pulumi waits for `k8s_ssh` and the `nginx_ns` namespace is created.

Instead if I comment the `nginx_ns` (delete the namespace) or add a new kubernetes resource, pulumi starts to communicate immediately with the kubernetes master (does not wait for `k8s_ssh` to be replaced) and I get:
```console
    error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://kubernetes.default:8443/openapi/v2?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
```
Exactly 32 seconds after `pulumi up` starts.

Same behaviour if I try to `pulumi destroy`, it will timeout as it is not able to connect with the kubernetes master.

If I manually start he ssh tunnel before `pulumi up`, every works as expected.

Any suggestions?

Thanks

**Comment by leezen** [comment]
Since the Python program is executed serially, can you shell out from within the program to establish the ssh tunnel prior to any of the resource constructors? I think that accomplishes what you want without using `local.Command` as a resource, but still ensures that you have the tunnel setup prior to anything taking place?

**Comment by yellowhat** [comment]
Are you suggesting to use the **Previewing update** stage of the `pulumi up` command to create the tunnel?

Consider the following example:

```
#!/usr/bin/env python

from datetime import datetime
from subprocess import run
from pulumi import Output, ResourceOptions
from pulumi_command import local
from vm import vm

def start_ssh_tunnel(args):
    """Create an ssh tunnel"""
    vm_name, vm_zone = args
    script = f"""
        sleep 30
        gcloud compute ssh user@{vm_name} \\
            --zone {vm_zone} \\
            --tunnel-through-iap \\
            -- -v -f -N -D 8443 \\
            &>/tmp/out
        sleep 5
    """
    _ = run(script, shell=True, check=True, capture_output=True)


ssh_tunnel = Output.all(vm.name, vm.zone).apply(start_ssh_tunnel)

cmd_ssh_test = f"""
    # Start {datetime.now()}
    ss -tulpn | grep ssh
"""

_ = local.Command(
    "ssh_tunnel_test",
    create=cmd_ssh_test,
    triggers=[cmd_ssh_test],
    opts=ResourceOptions(
        depends_on=[vm, ssh_tunnel],
    ),
)
```

On the first run of `pulumi up` the ssh tunnel is created as expected after the `vm`.
On the second run of `pulumi up` during the **Previewing update** stage the ssh tunnel is alive for 5 seconds (due to `sleep 5`, checked using `watch ss -tulpn`), but as soon as the **Updating** stage start, the processes spawned during the "Previewing update" stage are killed.
Not sure how to completely detach the "ssh tunnel" process from the pulumi ones.

**Comment by leezen** [comment]
Ah, I think I had missed that the tunnel relies on outputs from the program. Sorry -- for some reason I was initially under the impression that the tunnel parameters were all completely known.

In terms of preview vs. update on the second run, we should be spawning a new process for the update (and re-running the program), so I'd expect the tunnel to be re-established? Does that not occur for you?

**Comment by yellowhat** [comment]
I managed to solve the problem by using `subprocess.Popen` as it has an option to detach the process from `python`/`pulumi`:

```python
import subprocess

def start_ssh_tunnel(args):
    """Create an ssh tunnel"""
    vm_name, vm_zone = args
    script = f"""
        sleep 30
        gcloud compute ssh user@{vm_name} \\
            --zone {vm_zone} \\
            --tunnel-through-iap \\
            -- -v -N -D 8443 \\
            &>/tmp/out
    """
    with open("/bin/tunnel.sh", "w", encoding="utf8") as obj:
        obj.write(script)
    _ = Popen(
        ["bash", "/bin/tunnel.sh"],
        stdin=PIPE,
        stdout=PIPE,
        stderr=PIPE,
        start_new_session=True,
    )
```

The tunnel is still open after `pulumi up`, and it will start a new one during the **Previewing update** stage.

Thanks for the suggestions.
