### ISSUE TITLE
Support helm.values.schema for strong typing of values field

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#1866]
Some helm charts publish schema options for values files:

https://artifacthub.io/packages/helm/artifact-hub/artifact-hub?modal=values-schema

It would be nice to be able to strongly type those, similar to crd2pulumi

**Comment by jaxxstorm** [comment]
Duplicate of #167

**Comment by lblackstone** [comment]
Closing as dupe of #167
