### ISSUE TITLE
Pulumi silently fail to update Custom ES Resource 

### ISSUE THREAD

**Issue by eliskovets** [pulumi/pulumi-kubernetes#1871]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Pulumi reports that update for CR has been successful, but it failed (resource in K8S still has the old configuration)
The weird thing is that it has been able to update some resources with similar configuration, but not the other made in the same `pulumi up`.

### Steps to reproduce

1. Install eck operator in k8s
2. Create Elasticsearch resource
3. Try to update node_groups in ES resource via pulumi

Expected: ES resource in K8S be updated
Actual: Pulumi reports success, but resource in K8S is not updated.

**Comment by lblackstone** [comment]
I think this should be fixed by https://github.com/pulumi/pulumi-kubernetes/pull/1868

I suspect that the update failed silently due to a very long `last-applied-configuration` annotation. This fix will be included in the next release, which should be out today or tomorrow.

**Comment by eliskovets** [comment]
Thank you for getting back to me @lblackstone and thank you for providing the fix.
If you don't mind, I would like to keep this issue open and close it when the next release is released.

**Comment by lblackstone** [comment]
https://github.com/pulumi/pulumi-kubernetes/releases/tag/v3.14.1 is out now with this fix.
