### ISSUE TITLE
Support server-side apply for resource updates

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1879]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Server-side apply (SSA) was first introduced in Kubernetes 1.14 (March 2019), so most clusters support it now. Now that SSA support is widely available, we should migrate our current client-side apply usage to SSA. This will require investigation to see if we can support this migration without a breaking change.

SSA support will be especially relevant for #264

**Comment by HagaiBarel** [comment]
This might not be relevant, but I've noticed that when using SSA, setting `pulumi.IgnoreChanges` on a resource has no affect. I'm trying to come up with a simple reproduce steps to illustrate this issue. 

@lblackstone would you like me to open a separate issue for that?

**Comment by lblackstone** [comment]
> @lblackstone would you like me to open a separate issue for that?

Yes, please open a new issue for that. Thanks!

**Comment by lblackstone** [comment]
This feature is available now using the opt-in [enableServerSideApply](https://www.pulumi.com/registry/packages/kubernetes/api-docs/provider/#enableserversideapply_nodejs) flag, so I'll close this as fixed.
