### ISSUE TITLE
CRD update fails if last-applied-configuration annotation too long 

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1883]
During testing, I noticed another strange behavior, if I should put it another issue, let me know.
Looks like pulumi falsely states, that the `prometheuses.monitoring.coreos.com` CRD was updated when `enableReplaceCRD` is false, but actually, it wasn't.
I tested this on minikube with kubernetes version `v1.21.2`.

Steps to reproduce:
1. Make sure you're using an older pulumi-kubernetes version than `3.12.1`, I used `3.7.2`.
2. Use the code from my first comment with `enableReplaceCRD: false` and deploy the chart version `18.0.7`. 
    It should be deployed fine and the `prometheuses.monitoring.coreos.com` CRD should have a long `kubectl.kubernetes.io/last-applied-configuration` annotation.
3. Save the CRD definition with `kubectl get crd/prometheuses.monitoring.coreos.com -o yaml`.
4. Update the chart to `23.3.2` and try to deploy, it should fail on `prometheuses.monitoring.coreos.com` with the message `the Kubernetes API server reported that "prometheuses.monitoring.coreos.com" failed to fully initialize or become live: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`.
5. Update pulumi-kubernetes to `3.12.1`.
6. Try to deploy again, it will show, that all CRDs were updated.
7. Save the CRD definition again and compare it with the previous version, it will be the same.
8. Optionally check pulumi state with `pulumi stack export`, it will show that `prometheuses.monitoring.coreos.com` CRD resource has the newest version, both in the `inputs` and `outputs` section.
   The easiest way to do this, just to check the `controller-gen.kubebuilder.io/version` annotation, for the `18.0.7` chart it will be `v0.4.1`, for `23.3.2` will show `v0.6.2`.
9. Set `enableReplaceCRD: true` then run `pulumi up`.
10. Run `pulumi refresh`, it will show, that `~__inputs` changed on `prometheuses.monitoring.coreos.com`.
11. Optionally check pulumi state again, now both `inputs` and `outputs` will show the older CRD definition from the `18.0.7` chart.
12. Run `pulumi up`, `prometheuses.monitoring.coreos.com` will show an update, but will fail with the error: `the Kubernetes API server reported that "prometheuses.monitoring.coreos.com" failed to fully initialize or become live: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`.

So with the latest pulumi-kubernetes version without `enableReplaceCRD`, it says that every CRD updated, even `prometheuses.monitoring.coreos.com`, but on the environment, it actually stays the same.

_Originally posted by @ncsibra in https://github.com/pulumi/pulumi-kubernetes/issues/1841#issuecomment-996760823_

**Comment by gitfool** [comment]
I just hit this while trying to update kube prometheus stack crds:
```
Diagnostics:
  pulumi:pulumi:Stack (k8s-alpha):
    error: update failed

  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (prometheuses.monitoring.coreos.com):
    error: 1 error occurred:
        * the Kubernetes API server reported that "prometheuses.monitoring.coreos.com" failed to fully initialize or become live: CustomResourceDefinition.apiextensions.k8s.io "prometheuses.monitoring.coreos.com" is invalid:
metadata.annotations: Too long: must have at most 262144 bytes
```
* `Pulumi` v3.27.0
* `Pulumi.Kubernetes` v3.17.0

Should #1882 be promoted from draft? Are there any workarounds?

**Comment by gitfool** [comment]
I managed to workaround this issue by configuring the k8s provider in dotnet/c# as follows:
```c#
protected K8sProvider CreateK8sProvider(Output<string> kubeConfig) =>
    new($"{EnvName}-k8s",
        new K8sProviderArgs
        {
            EnableReplaceCRD = true, // workaround https://github.com/pulumi/pulumi-kubernetes/issues/1883
            KubeConfig = kubeConfig,
            KubeClientSettings = new KubeClientSettingsArgs { Qps = 50, Burst = 100 }
        });
```
However, now some of the crds, and not just ksp crds, are _always_ wanting to update with metadata differences:
```
~  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition prometheuses.monitoring.coreos.com update [diff: ~metadata]
```
😕

**Comment by gitfool** [comment]
This is what I see for the update diff of a couple of the crds in the pulumi web ui:

First update:
```
prometheuses.monitoring.coreos.com (kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition)
~  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (update)
    [id=prometheuses.monitoring.coreos.com]
    [urn=urn:pulumi:alpha::k8s::kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::prometheuses.monitoring.coreos.com]
 
issuers.cert-manager.io (kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition)
~  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (update)
    [id=issuers.cert-manager.io]
    [urn=urn:pulumi:alpha::k8s::kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::issuers.cert-manager.io]
    __inputs           : {
        metadata  : {
            resourceVersion: "50967243" => "50969209"
        }
    }
    metadata           : {
        generation       : 18 => 20
        resourceVersion  : "50969203" => "50975918"
    }
```
Next update:
```
prometheuses.monitoring.coreos.com (kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition)
~  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (update)
    [id=prometheuses.monitoring.coreos.com]
    [urn=urn:pulumi:alpha::k8s::kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::prometheuses.monitoring.coreos.com]
 
issuers.cert-manager.io (kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition)
~  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (update)
    [id=issuers.cert-manager.io]
    [urn=urn:pulumi:alpha::k8s::kubernetes:yaml:ConfigGroup$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::issuers.cert-manager.io]
    __inputs           : {
        metadata  : {
            resourceVersion: "50969209" => "50975925"
        }
    }
    metadata           : {
        generation       : 20 => 22
        resourceVersion  : "50975918" => "50979920"
    }
```

I'm not sure what's going on with the `metadata` and why is `prometheuses.monitoring.coreos.com` showing no diff at all? 🙄

**Comment by pyoio** [comment]
This can also be worked around by enabling: https://www.pulumi.com/registry/packages/kubernetes/api-docs/provider/#enabledryrun_nodejs on the k8s provider (for your language equivalent) which lets k8s do server-side diffing

**Comment by gitfool** [comment]
I haven't tried enabling "dry run" (server-side diff) yet, as @viveklak mentioned there were a few outstanding issues with it. Meanwhile, enabling replacing crds still has its own issues; updating the metadata every run is proving to be more than just annoying. I recently had an actual failure because of it, so it's not exactly harmless:
```
Diagnostics:
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (prometheusrules.monitoring.coreos.com):
    error: post-step event returned an error: failed to save snapshot: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (probes.monitoring.coreos.com):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (alertmanagers.monitoring.coreos.com):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (buckets.s3.services.k8s.aws):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (certificates.cert-manager.io):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (podmonitors.monitoring.coreos.com):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (servicemonitors.monitoring.coreos.com):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (gatewayroutes.appmesh.k8s.aws):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (virtualnodes.appmesh.k8s.aws):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (thanosrulers.monitoring.coreos.com):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (prometheuses.monitoring.coreos.com):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  pulumi:pulumi:Stack (k8s-opsdev):
    error: update failed
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (alertmanagerconfigs.monitoring.coreos.com):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (virtualrouters.appmesh.k8s.aws):
    error: post-step event returned an error: failed to save snapshot: renewing lease: [403] The provided update token has expired.
 
Resources:
    ~ 21 updated
    56 unchanged
```
It would be nice to fix these noisy diffs...

**Comment by lblackstone** [comment]
Appreciate your patience on this fix! I got pulled off onto another project for the last several months and am just getting back to it. I've updated the PR, and should have a release out in the next day or two.

**Comment by gitfool** [comment]
@lblackstone no unexpected changes now; thank you! 🎉 
```
Resources:
    130 unchanged
```
