### ISSUE TITLE
helm.Release ClientOnly Option for Previews

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi-kubernetes#1908]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently, when running a `pulumi up` or `pulumi preview`, the `helm.Release` resource uses `ClientOnly` mode to template out the Helm Chart.

Helm provides a [capability checker ](https://helm.sh/docs/chart_template_guide/builtin_objects/#capabilities) that allows for Helm charts to check for the existence of a API namespace and resource, which can fail without reaching out to the server.

I'm proposing that we allow `clientOnly` to be an option to `helm.Release` that allows the user to change this behaviour, though we'll default to existing behaviour of `true`.

Related #1904 

### Affected area/feature

- Helm Release

**Comment by EronWright** [comment]
I believe this issue has been made obsolete by https://github.com/pulumi/pulumi-kubernetes/pull/2672, because we no longer use templating during `Check`.
