### ISSUE TITLE
-get-provider-info failed

### ISSUE THREAD

**Issue by liavyona** [pulumi/pulumi-kubernetes#1910]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm trying to get the provider info of the kubernetes provider and the command failed (unlike the aws and gcp providers)
### Steps to reproduce

1. `pulumi plugin install resource kubernetes 3.15.2`
2. `~/.pulumi/plugins/resource-kubernetes-v3.15.2/pulumi-resource-kubernetes --get-provider-info`

Expected: 
The provider info
Actual: 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/31516429/154363792-4dcb3bb4-4ac4-4598-bbec-632b8364fc5f.png">

**Comment by liavyona** [comment]
@danielrbradley thanks for the reply.

I'm trying to convert my Kubernetes resources managed by Terraform to Pulumi. While running `tf2pulumi` it failed so I tried to get  ResoucesMap from the provider info

**Comment by danielrbradley** [comment]
Ah ok interesting. If you've got the kube YAML definitions for the resources being created by terraform then you try using [kube2pulumi](https://www.pulumi.com/kube2pulumi/) to generate the code then using [pulumi import](https://www.pulumi.com/docs/guides/adopting/import/) to adopt existing infrastructure.
