### ISSUE TITLE
Allow `k8s.core.v1.Namespace` accepts kubeconfig from code source

### ISSUE THREAD

**Issue by thepabloaguilar** [pulumi/pulumi-kubernetes#1921]
## Issue details

Hello, I'm using `Pulumi` to create a `EKS` cluster and after that I'd like to create the namespaces too. Now I'm unable to do that since the K8S operator expects the Kube Config on `$KUBECONFIG`, `~/.kube/config`, and `kubernetes:kubeconfig`.
It'll be great if I can pass through the code!

### Affected area/feature

Pulumi Kubernetes package!

**Comment by guineveresaenger** [comment]
Hi @thepabloaguilar - thank you for the suggestion! As always, feel free to try your hand at implementation.

I've transferred this issue to our kubernetes provider repo in the meantime. 😃

**Comment by lblackstone** [comment]
https://github.com/pulumi/pulumi-kubernetes/issues/1921#issuecomment-1062700277 is correct. You can set the kubeconfig for any resource using the Provider.
