### ISSUE TITLE
Helm V3 Release assertion fail on update

### ISSUE THREAD

**Issue by mfzl** [pulumi/pulumi-kubernetes#1925]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

I'm using the `Release` resource to deploy https://k8s.ory.sh/helm/kratos.html chart. It deploys fine and everything runs normally. But if I do a `pulumi up` after, it fails with an assertion error, which doesn't have a lot of details except for the stack trace.

```
  pulumi:pulumi:Stack (idp-app-k8s-dev):
    panic: fatal: An assertion has failed
    goroutine 522 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assert(...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/go/common/util/contract/assert.go:26
    github.com/pulumi/pulumi-kubernetes/provider/v3/pkg/provider.(*kubeProvider).Check(0xc0001ee180, {0x253b408, 0xc002d21620}, 0xc0022ddef0)
    	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:1239 +0x1579
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler.func1({0x253b408, 0xc002d21620}, {0x2080a00, 0xc0022ddef0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/proto/go/provider.pb.go:2593 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x253b408, 0xc002d0b440}, {0x2080a00, 0xc0022ddef0}, 0xc002835e40, 0xc0023f77b8)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x425
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Check_Handler({0x2124c60, 0xc0001ee180}, {0x253b408, 0xc002d0b440}, 0xc002b5b800, 0xc0004c4000)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.24.1/proto/go/provider.pb.go:2595 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000150540, {0x257b9a8, 0xc000103040}, 0xc002d15320, 0xc0004ba150, 0x39528b0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
    google.golang.org/grpc.(*Server).handleStream(0xc000150540, {0x257b9a8, 0xc000103040}, 0xc002d15320, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:1616 +0xa2a
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:921 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.43.0/server.go:919 +0x294
 
  kubernetes:helm.sh/v3:Release (kratos):
    error: transport is closing
   ```
### Steps to reproduce

1. `pulumi up` to deploy https://k8s.ory.sh/helm/kratos.html with `Release` resource
2. Run `pulumi up` again

Expected: To run and present a full preview and then prompt to continue
Actual: Crashes with the above stack trace without preview.

I'm using `3.16.0`

**Comment by mfzl** [comment]
Seems it's failing on this assertion https://github.com/pulumi/pulumi-kubernetes/blob/45b94216d6ae09633ac2e2e00266c57ce0844065/provider/pkg/provider/provider.go#L1239

But it's checking for `.metadata.name` on the `Release` inputs which doesn't have a metadata object.

**Comment by mfzl** [comment]
So I went ahead and edited the stack and added a `metadata.name` to inputs and it works as expected. 

Makes me think that it's not being set after Release is created?

**Comment by mfzl** [comment]
Does this line https://github.com/pulumi/pulumi-kubernetes/blob/45b94216d6ae09633ac2e2e00266c57ce0844065/provider/pkg/provider/provider.go#L1236
need to be 
```go
	if len(oldInputs.Object) > 0 && !isHelmRelease(urn) 
```

instead

**Comment by viveklak** [comment]
Could you share your code? You might have input types in the args to the release.

**Comment by mfzl** [comment]
It indeed does. I'm passing bunch of `Input` values to chart values. I'm assuming they all need to be resolved. I missed the type on `.values`. 

The error could be better though.

**Comment by mfzl** [comment]
I'm closing it since this is the expected behavior.

**Comment by RazcoDev** [comment]
@mfzl can you please elaborate on this ?
I'm encountering the same issue and couldn't figure out your resolution from this thread.
My Release's values arg also have Outputs in it.

**Comment by viveklak** [comment]
@RazcoDev can you post a repro in https://github.com/pulumi/pulumi-kubernetes/issues/1933 please?

**Comment by mfzl** [comment]
> @mfzl can you please elaborate on this ? I'm encountering the same issue and couldn't figure out your resolution from this thread. My Release's values arg also have Outputs in it.

Basically all values needed to be resolved. So inside an `apply` of all values that needed to be resolved was what we went with as a workaround.

**Comment by viveklak** [comment]
A fix is upcoming in https://github.com/pulumi/pulumi-kubernetes/pull/1953. Thanks for your patience. In the meantime using prompt (i.e. things you have already awaited) values is a good workaround.
