### ISSUE TITLE
Support wait_for_load_balancer for kubernetes_ingress

### ISSUE THREAD

**Issue by hcharley** [pulumi/pulumi-kubernetes#1934]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Build support for a `waitForLoadBalancer` option that will perform identically to this Terraform Kubernetes Ingress option:

[wait_for_load_balancer](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/ingress#wait_for_load_balancer) - (Optional) Terraform will wait for the load balancer to have at least 1 endpoint before considering the resource created. Defaults to false.

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/ingress#wait_for_load_balancer

Additional details on this feature, along with other `wait_for_*` options have been marketed on Hashicorp's blog:

https://www.hashicorp.com/blog/wait-conditions-in-the-kubernetes-provider-for-hashicorp-terraform

**Comment by viveklak** [comment]
@hcharley could you elaborate where the existing await support in the Pulumi Kubernetes provider falls short here? FWIW our ingress check has always performed endpoint and load balancer checks. Pulumi defaults to awaiting the readiness of the resources in contrast to the above support in Kubernetes. We do provide a `skipAwait` annotation for users to disable the readiness checks.

**Comment by hcharley** [comment]
@viveklak  Oh, great! I wasn't aware of the `skipAwait` annotation feature of Pulumi. 

I didn't know that Pulumi used annotations to change its behavior. Cool!

I just read this blog post, which was helpful on this subject: https://www.pulumi.com/blog/improving-kubernetes-management-with-pulumis-await-logic/
