### ISSUE TITLE
Support wait_for_rollout for kubernetes_deployment

### ISSUE THREAD

**Issue by hcharley** [pulumi/pulumi-kubernetes#1935]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Build support for a `waitForRollout` option that will perform identically to this Terraform Kubernetes Deployment option:

[wait_for_rollout](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#wait_for_rollout) - (Optional) Wait for the deployment to successfully roll out. Defaults to true.

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/deployment#wait_for_rollout

Additional details on this feature, along with other `wait_for_*` options have been marketed on Hashicorp's blog:

https://www.hashicorp.com/blog/wait-conditions-in-the-kubernetes-provider-for-hashicorp-terraform

**Comment by viveklak** [comment]
Similar to my question in #1934 - could you elaborate where the existing await support in the Pulumi Kubernetes provider is proving to be insufficient? The current await logic (turned on by default) for deployments will wait for the replicaset at the desired generation is marked available as well as the deployment. We do support a `pulumi.com/skipAwait` annotation if await logic needs to be skipped.

**Comment by hcharley** [comment]
If it works, it works! I wasn't aware this feature already exists. Closing out! Thank you @viveklak!
