### ISSUE TITLE
config.Yaml invokes decode but doesn't propagate provider

### ISSUE THREAD

**Issue by rawkode** [pulumi/pulumi-kubernetes#1938]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When the default Kubernetes provider is disabled, we cannot use `yaml.ConfigFile`. It seems that an invoke to `yaml::decode` is made without propagation of the provider.

`Error: Invoke: Default provider for 'kubernetes' disabled. 'kubernetes:yaml:decode' must use an explicit provider`

### Steps to reproduce

```typescript
    args.provider.urn.apply((u) => console.log(`Provider URN: ${u}`));

    const crds = new kubernetes.yaml.ConfigFile(
      `${this.name}-crds`,
      { file: this.crdsUrl.replace("${VERSION}", this.version) },
      {
        parent: this,
        provider: args.provider,
        dependsOn: args.dependsOn,
      }
    );
```

This code fails, even though the URN for my provider is correct.

**Comment by protometa** [comment]
Having same issue with `helm.v3.Chart` with error

```
Error: Invoke: Default provider for 'kubernetes' disabled. 'kubernetes:helm:template' must use an explicit provider.
```

**Comment by protometa** [comment]
Looks like fix is #1919?

**Comment by KaoruDev** [comment]
hey @lblackstone I just pulled down version `3.19.4` and still am observing the same behavior ☹️

**Comment by viveklak** [comment]
@KaoruDev are you able to `pulumi stack export` and make sure the provider for the resource is actually set to v3.19.4 and not using an older version?

**Comment by rosskevin** [comment]
...and is there a workaround to pass the providers explicitly inside my `ComponentResource`?

**Comment by viveklak** [comment]
@rosskevin you would need to pass the opts to `ConfigFile`. However, I believe you might run into https://github.com/pulumi/pulumi/issues/9996. Instead you might want to pass the `kubernetes` provider directly as ConfigFile's `provider` resource option.

**Comment by robertvanhoesel** [comment]
I'm getting this exact runtime error while using  https://github.com/pulumi/pulumi-kubernetes-cert-manager . Is that package updated correctly?

**Comment by EronWright** [comment]
Reopening this to cover the remaining cases in NodeJS SDK, e.g. when using `providers` as opposed to `provider`.
