### ISSUE TITLE
Pass provider options to all invokes in component resources

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes#1945]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details
This is a continuation of #1912. Specifically need to:
1. Extend https://github.com/pulumi/pulumi-kubernetes/pull/1919 to dotnet
2. Audit and fix usage in other component resources (ConfigFile, ConfigGroup, Kustomize, etc.) across the various languages.

**Comment by jasminen** [comment]
Hey @viveklak, did we release a fix for ConfigFile/ConfigGroup invokes?
