### ISSUE TITLE
Automatically fill in `.Capabilities` in Helm Charts

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#196]
These are typically filled in on the server (_e.g._, whether the API server supports RBAC or not). Helm Charts tend to use these values for doing things like determining the `apiVersion` to use for certain resources. If this is not filled in, it can fail in extremely confusing ways.

**Comment by hausdorff** [comment]
I recommend closing this issue out:

1. We probably don't want to differ from the `helm template` semantics in any major ways.
1. Tiller is going away, so this kind of feels like putting new carpet into a house we're going to tear down anyway.
1. This would be very hard to do in general.

**Comment by RichardWLaub** [comment]
I'm running into an issue trying to enable a ServiceMonitor in the [prometheus-cloudwatch-exporter chart](https://github.com/helm/charts/blob/master/stable/prometheus-cloudwatch-exporter/templates/servicemonitor.yaml).

Helm added a `--api-versions` flag to `helm template` that would allow me to enable it via `helm template` but I can't with pulumi. https://github.com/helm/helm/pull/5392

Would it make sense to be able to pass in arguments to that `--api-versions` flag via pulumi so we can fill in `.Capabilities`?

**Comment by yann-soubeyrand** [comment]
Hello, couldn’t we use https://pkg.go.dev/helm.sh/helm/v3/pkg/action#GetVersionSet using the provider Kubernetes config?

**Comment by yann-soubeyrand** [comment]
I may be wrong, but couldn’t we do it around [here](https://github.com/pulumi/pulumi-kubernetes/blob/94c160dd1a240bc4258003b50c31dcd847e6807f/provider/pkg/provider/provider.go#L713) and then somehow pass the information to helmTemplate [here](https://github.com/pulumi/pulumi-kubernetes/blob/94c160dd1a240bc4258003b50c31dcd847e6807f/provider/pkg/provider/provider.go#L791) (maybe along with the Kubernetes server version to address https://github.com/pulumi/pulumi-kubernetes/issues/753)?

**Comment by yann-soubeyrand** [comment]
I finally did it a little bit differently than what I thought, but I think I came up with a satisfactory implementation.
