### ISSUE TITLE
Attempting to deploy large CRDs hangs indefinitely with yaml.ConfigFile and kustomize.Directory

### ISSUE THREAD

**Issue by Insomniak47** [pulumi/pulumi-kubernetes#1960]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Hardware: 2021 M1 Pro Macbook Pro
Pulumi cli version: 3.28.0 (ARM64)
SDK: python

When attempting preview using a kustomize file to deploy argo CRDs (individually 1 eventually succeeds, the full deployment does not) pulumi preview hangs indefinitely.

When attempting to preview individual (large) crds via a kustomize file pulumi preview hangs indefinitely

When attempting to use the results of kustomize build (the sum of all resources from the argo deployment) from a local file to deploy yaml.ConfigFile pulumi preview hangs indefinitely.

### Steps to reproduce

Minimal kubernetes and python files:

Targeting the kustomize directory:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - "https://github.com/argoproj/argo-cd//manifests/ha/cluster-install
```

```py
kustomize.Directory(
    "argo-bootstrap",
    directory="./",
)
```

Each of the individual (large crds targeted directly with kustomize.Directory will also have the same effect. 

As a single file:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - "https://github.com/argoproj/argo-cd//manifests/ha/cluster-install
```

```sh
kustomize build > test/resources.yaml
```

```py

pulumi_kubernetes.yaml.ConfigFile("my-resource", file="./test/resources.yaml")
```

Expected: 
pulumi completes a preview in a reasonably short amount of time. 

Actual:
pulumi hangs indefinitely

## To note:

If I apply the CRDs individually as opposed to together the smallest of the CRDs succeeds the others hang forever (or at least >30m)

## Related:

#1130

**Comment by viveklak** [comment]
This is likely a dupe of https://github.com/pulumi/pulumi/issues/8717

**Comment by cbcmg** [comment]
This could be helpful: https://github.com/pulumi/pulumi-kubernetes/issues/1867#issuecomment-1107353905

**Comment by EronWright** [comment]
Closing as a duplicate of https://github.com/pulumi/pulumi/issues/8717.  The problem was resolved by https://github.com/pulumi/pulumi/pull/10063.
