### ISSUE TITLE
Deployment awaiter is wrong for the case previous state had init errors

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#197]
We want to check if the rollout succeeded only if this is not the first time we've succeeded. If there were previously initialization errors, we currently expect that any generation > 1 will imply a rollout.

**Comment by hausdorff** [comment]
Looking closer, it looks like the `extensions/v1beta1` version of the API doesn't seem to have a condition indicating that the rollout was complete. _sigh_

**Comment by hausdorff** [comment]
We've punted this out because, looking at it now, I'm not actually sure this is a bug. We filed it before #199, which seems likely to be the real problem.

**Comment by lukehoban** [comment]
@hausdorff What's the current plan for this and #199?  Are they the same issue?  Is there a fix we know we'll take in M19?

**Comment by hausdorff** [comment]
I don't think this is a bug. Let's close.
