### ISSUE TITLE
can't evaluate field create in type interface

### ISSUE THREAD

**Issue by NArnott** [pulumi/pulumi-kubernetes#1975]
### What happened?

I'm trying to deploy ExternalDNS as a Helm Release, and keep getting the following error when I provide any value for "serviceAccount":

`error: failed to create chart from template: template: external-dns/templates/serviceaccount.yaml:1:14: executing "external-dns/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: can't evaluate field create in type interface {}`

Helm Chart is defined here: https://github.com/kubernetes-sigs/external-dns/tree/master/charts/external-dns

### Steps to reproduce

Here is my resource definition.

```
    class MyExternalDNS : ComponentResource
    {
        private const string NAME = "external-dns";
        private const string NAMESPACE = "kube-system";

        public MyExternalDNS(string name, OpenIdConnectProvider oidcProvider, Resource? parent = null)
            : base(nameof(MyExternalDNS), name, new ComponentResourceOptions() { Parent = parent })
        {

            var values = new Dictionary<string, object>()
            {
                ["fullnameOverride"] = NAME,
                ["serviceAccount"] = new Dictionary<string, object>()  //if I comment this block out, it works fine, but I need to set this
                {
                    ["create"] = false,
                    ["name"] = "someName"
                }
                ["sources"] = new List<string>()
                {
                    "service",
                    "ingress"
                },
                ["registry"] = "txt",
                ["provider"] = "aws",
                ["extraArgs"] = new List<string>()
                {
                    "--aws-zone-type=public",
                    "--txt-owner-id=pfss-eks-cluster"
                },
            };

            var chart = new Release(NAME, new ReleaseArgs()
            {
                Name = NAME,
                Namespace = NAMESPACE,
                Chart = NAME,
                RepositoryOpts = new RepositoryOptsArgs()
                {
                    Repo = "https://kubernetes-sigs.github.io/external-dns/"
                },
                Values = values
            }, new CustomResourceOptions() { Parent = this });
        }
    }
```

### Expected Behavior

I expect the helm chart to be deployed without errors. Without the serviceAccount block defined, it deploys alright (though without the service account set correctly, it can't access the AWS resources needed).

### Actual Behavior

Pulumi up/preview fails with the following error:

```
Diagnostics:
  kubernetes:helm.sh/v3:Release (external-dns):
    error: failed to create chart from template: template: external-dns/templates/serviceaccount.yaml:1:14: executing "external-dns/templates/serviceaccount.yaml" at <.Values.serviceAccount.create>: can't evaluate field create in type interface {}
```

### Versions used

CLI
Version      3.29.1
Go Version   go1.17.8
Go Compiler  gc

Plugins
NAME        VERSION
aws         4.37.2
dotnet      unknown
kubernetes  3.15.2

Host
OS       Microsoft Windows 10 Enterprise
Version  10.0.19044 Build 19044
Arch     x86_64

NAME               VERSION
Pulumi.Aws         4.37.2
Pulumi.Kubernetes  3.15.2
YamlDotNet         11.2.1

### Additional context

I did this exact same thing with the cluster autoscaler helm chart (https://github.com/kubernetes/autoscaler/tree/master/charts/cluster-autoscaler), including specifing the rbac.serviceAccount values, and it works just fine. I don't get why the external-dns chart is having issues.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EronWright** [comment]
Sorry for the delay, the problem is due to a syntax error in the dictionary initialization block. Specifically there should be a comma after the value of `serviceAccount`, e.g.
```cs
["serviceAccount"] = new Dictionary<string, object>() 
{
    ["create"] = false,
    ["name"] = "someName"
},   // <--- comma needed here.
["sources"] = new List<string>()
{
    "service",
    "ingress"
},
```
