### ISSUE TITLE
Handle changes that will destroy and recreate the resource, rather than updating it in-place.

### ISSUE THREAD

**Issue by mingfang** [pulumi/pulumi-kubernetes#198]
Some Kubernetes resource changes can not be updated in-place.

One example is when changing a service's type from type: ClusterIP to type: ExternalName.  Currently this change will result an error 
```
**replacing failed**     changes: ~ spec, 1 err
```
The service must first be destroyed and then recreated.

**Comment by joeduffy** [comment]
Ah, good find! The engine supports the notion of replacements, so we will need to enlighten the diff logic to mark this as needing a replacement (see https://github.com/pulumi/pulumi/blob/679f55c355eb1563d9f4ac5d34e6ddd2cc8de24e/sdk/proto/provider.proto#L103).

Is there any definitive source of which properties cannot be changed in place, across all resources? Even if it's just in the Kubernetes source code itself? It would be good to do a full sweep of these cases rather than finding and fixing them one at a time in the months ahead.

**Comment by hausdorff** [comment]
@mingfang This should actually work, can I see the code for your service definition?

**Comment by mingfang** [comment]
This is the test script
```typescript
this.service = new k8s.core.v1.Service("test", {
  metadata: {
    name: "test"
  },
  spec: {
    ports: [{port: 80}],
    // type: "ClusterIP"
    type: "ExternalName",
    externalName: "example.com"
  },
}, {});
```

First I created it using type: "ClusterIP" and then I tried changing it to "ExternalName".
Here is the output with the error
```
pulumi up --non-interactive
Previewing update of stack 'minimal'
Previewing changes:

 *  pulumi:pulumi:Stack minimal-minimal running 
 -- kubernetes:core:Service test delete original 
 +- kubernetes:core:Service test replace changes: ~ spec
 ++ kubernetes:core:Service test create replacement changes: ~ spec
 
    ---outputs:---
  ~ service: "default/test" => computed<string>

info: 1 change previewed:
    +-1 resource to replace
      1 resource unchanged

Updating stack 'minimal'
Performing changes:

 *  pulumi:pulumi:Stack minimal-minimal running 
 -- kubernetes:core:Service test deleting original 
 -- kubernetes:core:Service test deleted original 
 +- kubernetes:core:Service test replacing changes: ~ spec
 +- kubernetes:core:Service test replaced changes: ~ spec
 ++ kubernetes:core:Service test creating replacement changes: ~ spec
 ++ kubernetes:core:Service test creating replacement changes: ~ spec, 1 error. error: Plan apply failed: object is being deleted: services "test" already exists
 ++ kubernetes:core:Service test **creating failed** changes: ~ spec, 1 error. error: Plan apply failed: object is being deleted: services "test" already exists
 *  pulumi:pulumi:Stack minimal-minimal done 
 
Diagnostics:
  kubernetes:core:Service: test
    error: Plan apply failed: object is being deleted: services "test" already exists
 
    ---outputs:---
  - service: "default/test"

info: 1 change performed:
    +-1 resource replaced
      1 resource unchanged
Update duration: 791.162785ms

error: update failed
```
The original resource was deleted but the replacement failed.
Note, this example only works with the awaiters disabled.

**Comment by joeduffy** [comment]
Ahh, I wonder if services with explicit metadata names need to be marked deleteBeforeCreate. Cc @pgavlin @swgillespie

**Comment by lukehoban** [comment]
> I wonder if services with explicit metadata names need to be marked deleteBeforeCreate

Indeed, that was the proposal as part of the initial autoname implementation for kubernetes. I thought we had implemented that already.  @hausdorff.

**Comment by hausdorff** [comment]
This should be implemented. It's definitely a bug. I'll look soon.

**Comment by hausdorff** [comment]
@mingfang I can't reproduce this. I have transformed the first of the following API objects to the second, and the operation was successfully delete-then-replace'd. Three things:

1. Have I missed something in this change?
1. Can you post the result of `pulumi preview --diff`?
1. In the meantime, as a workaround, if you remove `.metadata.name`, we should autoname it. I'd be curious to see if this issue persists here.

## Version 1

```
const service = new k8s.core.v1.Service(
    "test",
    {
        metadata: {
            name: "test"
        },
        spec: {
            selector: {
                app: "node",
                chart: "node-4.0.1",
                heritage: "Tiller",
                release: "node"
            },
            ports: [{ port: 80 }],
            type: "ClusterIP"
            // type: "ExternalName",
            // externalName: "example.com"
        }
    },
    { provider: k8sProvider }
);
```

## Version 2

```
const service = new k8s.core.v1.Service(
    "test",
    {
        metadata: {
            name: "test"
        },
        spec: {
            // selector: {
            //     app: "node",
            //     chart: "node-4.0.1",
            //     heritage: "Tiller",
            //     release: "node"
            // },
            ports: [{ port: 80 }],
            // type: "ClusterIP"
            type: "ExternalName",
            externalName: "example.com"
        }
    },
    { provider: k8sProvider }
);
```

**Comment by hausdorff** [comment]
Oh interesting, as I was copying the log from @mingfang's output to demonstrate to @joeduffy that we are definitely deleting before replacement, I discovered that there is output hidden, cut off to the right. Scroll over to the right and you'll see the text:

```
Plan apply failed: object is being deleted: services "test" already exists
```

Copied for posterity:

```
 -- kubernetes:core:Service test deleting original 
 -- kubernetes:core:Service test deleted original 
 +- kubernetes:core:Service test replacing changes: ~ spec
 +- kubernetes:core:Service test replaced changes: ~ spec
 ++ kubernetes:core:Service test creating replacement changes: ~ spec
 ++ kubernetes:core:Service test creating replacement changes: ~ spec, 1 error. error: Plan apply failed: object is being deleted: services "test" already exists
 ++ kubernetes:core:Service test **creating failed** changes: ~ spec, 1 error. error: Plan apply failed: object is being deleted: services "test" already exists
 *  pulumi:pulumi:Stack minimal-minimal done 
```

So what is happening is that we are claiming that the service was deleted, but it's not actually deleted yet.

We're basically waiting until the API server reports a 404 in response to the request, but it seems like that is not good enough. We should be catching and ignoring this specific error too, I think, and retrying that for some period of time.

cc @lukehoban. Thoughts, anyone?

**Comment by mingfang** [comment]
It looks like there is no awaitDeletion for services, https://github.com/pulumi/pulumi-kubernetes/blob/88b4b4e81a611f145bcd4b07aa7c79542f5014d9/pkg/await/awaiters.go#L183

**Comment by mingfang** [comment]
Just for testing, I used the pod's awaitDeletion, like this and sure enough that worked.
```typescript
	coreV1Service: {
		awaitCreation: awaitServiceInit,
		awaitUpdate:   awaitServiceUpdate,
		awaitDeletion: untilCoreV1PodDeleted,
	},
```
I think the 404 check is a common check for all resource deletions that can be refactored to use the same function

**Comment by hausdorff** [comment]
@mingfang when you have a minute, if you can still reproduce the issue, I'd like to have you try out this PR: https://github.com/pulumi/pulumi-kubernetes/pull/203

**Comment by mingfang** [comment]
I tested PR #203 and no longer see the issue.

**Comment by hausdorff** [comment]
@mingfang Great! We'll merge that PR tomorrow sometime and cut the new release. Thanks!
