### ISSUE TITLE
Add API docs examples in Java and YAML

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-kubernetes#1981]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Pulumi has launched new languages: YAML and Java. As API docs examples are hard-coded, I haven't found a simple way to extend them to new languages. We should generate them as a follow-up.

Note that overlay resources aren't supported in new languages.

### Affected area/feature

API docs

**Comment by lblackstone** [comment]
Fixed in #2476
