### ISSUE TITLE
Helm Chart docs missing everything from Inputs section on down

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-kubernetes#1982]
### What happened?

Docs page for Helm Chart is missing everything from inputs on down:
https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/

### Steps to reproduce

Go to 
https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/

### Expected Behavior

See full docs.

### Actual Behavior

Don't see inputs, etc.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by viveklak** [comment]
The addition of java language docs introduced a bug. Fix is tracked in https://github.com/pulumi/pulumi/pull/9691
