### ISSUE TITLE
Deleting the same resource with different API versions can fail

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#199]
When a resource (_e.g._, a `Deployment`) is given a hard-coded `.metadata.name` and the `.apiVersion` is changed (_e.g._, from `apps/v1beta2` to `apps/v1`), and but the new `Deployment` has an init error, and the user tries to just delete the resource altogether, we'll generate delete operations for both resources. But, it looks like Kubernetes considers them the same resource, so the same thing gets deleted twice.

**Comment by lblackstone** [comment]
I won't get to this in M20. Punting to M21.

**Comment by lukehoban** [comment]
I believe the current planned path for this and https://github.com/pulumi/pulumi-kubernetes/issues/546 is:
1. Land https://github.com/pulumi/pulumi/pull/2404 to support `aliases` in Pulumi, which provides a tool for users to manually work around this
2. For Helm Chart users, ensure that `transforms` can add `aliases` (they cannot currently modify `ResourceOptions`)
3. At some point - once we have confidence in (1) and (2) - have the Kubernetes SDKs automatically inject `aliases` that do the require URN renaming to remove the API Version from the `type` field - without requiring users to use the manual workaround in (1) and (2).

@lblackstone If this plan makes sense to you - I suggest we tackle (1) and (2) in M23 and hold (3) for M24.

**Comment by lukehoban** [comment]
Fixes for pulumi/pulumi#2404 and #574 are now available, and enable users to workaround this manually.  There is no concrete repro shown here to validate against - but @hausdorff if you provide one I can show how pulumi/pulumi#2404 can be used to solve this.

We're tracking automating this to further simplify these migrations in #573.
