### ISSUE TITLE
k8s StatefulSet needs service name override

### ISSUE THREAD

**Issue by bmharper** [pulumi/pulumi-kubernetes#1995]
### What happened?

When creating a `StatefulSet`, `pulumi up` hangs with "Finding Pods to direct traffic to".

If I override the pulumi-generated name of the Headless Service, then everything works. But this was surprising and took a while to discover, so I'm asking if there is a "right" way to do this.

### Steps to reproduce

```ts
import * as k8s from "@pulumi/kubernetes";

const appName = "myredis";
const appLabels = { app: appName };

const headlessService = new k8s.core.v1.Service("redis-hl", {
  //metadata: { name: "redis-hl" }, // Uncomment me to succeed
  spec: {
    ports: [{ port: 6379 }],
    selector: appLabels,
  },
});

const stateful = new k8s.apps.v1.StatefulSet("redis-ss", {
  spec: {
    //serviceName: "redis-hl", // Uncomment me to succeed
    serviceName: headlessService.metadata.name, // This seems like the right thing to do, but it doesn't work
    selector: { matchLabels: appLabels },
    replicas: 1,
    template: {
      metadata: { labels: appLabels },
      spec: {
        containers: [
          {
            name: appName,
            image: "redis:6.2.7",
            ports: [{ containerPort: 6379 }],
          },
        ],
      },
    },
  },
});
```

### Expected Behavior

I thought that referencing `headlessService.metadata.name` is the correct thing to do, so that Pulumi can use the generated name.

### Actual Behavior

`pulumi up` hangs when creating the headless service, with the message "Finding Pods to direct traffic to".

As mentioned in the code comments, if I override the service name with `metadata: NAME`, then deployment succeeds, but this was not obvious.

### Versions used

```
@types/node          14.18.18
@pulumi/kubernetes   3.19.0
@pulumi/kubernetesx  0.1.6
@pulumi/pulumi       3.33.1
```

### Additional context

I'm deploying to Minikube, in case that makes any difference.

**Comment by lblackstone** [comment]
@bmharper Can you try adding `clusterIP: "None"` to your Service spec, and see if that resolves it for you? I think the provider is detecting your current Service as a normal Service rather than a headless one, so it's waiting on readiness and causing a "chicken and egg" problem with the StatefulSet.

You can see a [full example here](https://www.pulumi.com/registry/packages/kubernetes/api-docs/apps/v1/statefulset/#create-a-statefulset-with-auto-naming) that should work.

**Comment by bmharper** [comment]
Hi @lblackstone, thanks for the reply.
I've tried adding `clusterIP: "None"`, and it doesn't make a difference.
Also, your example gives me the same behaviour.

I am running this on minikube on Ubuntu 22.04. Perhaps that's part of the problem?
One other thing - the example code has invalid resource names (upper case letters not allowed).

**Comment by lblackstone** [comment]
I looked into this again, and realized that the example I linked is broken. I opened #2001 to track the fix to the example.

Additionally, it looks like there is [a bug in the readiness logic for StatefulSet](https://github.com/pulumi/pulumi-kubernetes/issues/1974). Until that gets fixed, you'll need to either use the `pulumi.com/skipAwait` annotation on your Service as shown in that issue, or you can manually specify the name of the Service as you indicated.

Sorry for the confusion here!
