### ISSUE TITLE
CRs rendered using renderYamlToDirectory are not unique

### ISSUE THREAD

**Issue by CitadelCore** [pulumi/pulumi-kubernetes#2006]
### What happened?

When two CustomResources with the same Kind but a different APIVersion exist, one will overwrite one another.

### Steps to reproduce

Define two CustomResources with the same Kind and a different APIVersion and run `pulumi up` with `renderYamlToDirectory` set to `true`.

### Expected Behavior

Generated manifest files include the APIVersion.
For example, `monitoring.coreos.com_v1.servicemonitor.infra-system.promtail.yaml`.

### Actual Behavior

Generated manifest files are named the same and overwrite each other.
For example, `servicemonitor-infra-system-promtail.yaml`.

This line is responsible for generating the name: https://github.com/pulumi/pulumi-kubernetes/blob/308be3d4fa6a2dee78954ec743c69b58043a239c/provider/pkg/provider/provider.go#L3121

### Versions used

```
CLI          
Version      3.33.2
Go Version   go1.17.10
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.19.0
kubernetes  3.19.0
nodejs      unknown

Host     
OS       nixos
Version  21.11 (Porcupine)
Arch     x86_64

This project is written in nodejs (/etc/profiles/per-user/alex/bin/node v14.19.3)

Backend        
Name           kuiser
URL            file://~
User           alex
Organizations  

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
Thank you for submitting this issue and contributing a PR!
