### ISSUE TITLE
ignoreChanges has no effect when SSA is enabled

### ISSUE THREAD

**Issue by CitadelCore** [pulumi/pulumi-kubernetes#2012]
### What happened?

When server-side apply is enabled, `ignoreChanges` has no effect. This is a blocker to using SSA for me as I need to be able to ignore fields that are modified by operators.

### Steps to reproduce

Create a resource, enable SSA and set `ignoreChanges` on a field

### Expected Behavior

`ignoreChanges` ignores the changes

### Actual Behavior

`ignoreChanges` does not ignore the changes

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
You might be interested in: https://github.com/pulumi/pulumi-kubernetes/issues/2011, community thoughts welcome, this work will be starting soon.

**Comment by lblackstone** [comment]
Just to make sure I understand what you mean by "enable SSA", are you setting the [enableDryRun Provider option](https://www.pulumi.com/registry/packages/kubernetes/api-docs/provider/#enabledryrun_nodejs)?

**Comment by CitadelCore** [comment]
> Just to make sure I understand what you mean by "enable SSA", are you setting the [enableDryRun Provider option](https://www.pulumi.com/registry/packages/kubernetes/api-docs/provider/#enabledryrun_nodejs)?

That's correct.
