### ISSUE TITLE
Requesting: on error in refresh for unreachable cluster, allow marking as deleted

### ISSUE THREAD

**Issue by pnathan** [pulumi/pulumi-kubernetes#2033]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Hi,

I'd like to propose a flag in `refresh` to allow the pre #1522 behavior; unreachable cluster, pods, Helm releases, etc, should be marked in the Pulumi state as deleted. As it stands now, Pulumi returns an error, and I have to work through a manual delete process.

Scenario:

I have gotten a Kubernetes cluster into a bad state.  Pulumi had the state marked as "pods exist", "charts exist", "cluster exists", etc, but now is unable to access any information due to the bad state. The solution I want to effect is to remove and regenerate the cluster to, nominally, bring the system state into a known-good one. The current Pulumi process is to manually edit the state to remove the relevant resources, something regrettably error prone.  

To be precise, the "loss of state data" behavior specifified here  https://github.com/pulumi/pulumi-kubernetes/issues/1485#issuecomment-816970573  is precisely what I want to effect here. 

However, as per #1485 , this is not appropriate always; hence the request for a flag. I would suggest perhaps something as `--assume-errors-are-removals`.

**Comment by stack72** [comment]
so I can add a set of behaviour that checks for a config specific flag or an Env Var (what name?) and then restore the original behaviour

**Comment by lblackstone** [comment]
> what name?

How about `PULUMI_K8S_DELETE_UNREACHABLE`?

**Comment by lblackstone** [comment]
I think it would be easier to document if we include a config parameter. Assuming the provider can pick that up on a destroy operation, let's do both.
