### ISSUE TITLE
Helm Chart - Cannot create Service Account (docker desktop)

### ISSUE THREAD

**Issue by Jaskerv** [pulumi/pulumi-kubernetes#2062]
### What happened?

I'm attempting to provision helm charts on docker desktop (kubernetes enabled).

When running `pulumi up`, it gets stuck on creating the Service Account.

When aborting, it throws this error:
```
Diagnostics:
  kubernetes:core/v1:ServiceAccount (kubernetes-dashboard-292228bf/kubernetes-dashboard):
    error: error reading from server: read tcp 127.0.0.1:57288->127.0.0.1:45099: use of closed network connection
```

I've tried with both kuberentes-dashboard and traefik with the same result.

### Steps to reproduce

1. Create a Chart resource.
```
export default function() {
  const namespace = new core.v1.Namespace('kubernetes-dashboard');

  new helm.v3.Chart('kubernetes-dashboard', {
    chart: 'kubernetes-dashboard',
    namespace: namespace.metadata.name,
    version: '5.4.1',
    fetchOpts: {
      repo: 'https://kubernetes.github.io/dashboard/',
    },
  });
}
```
2. `pulumi up` on local kubernetes
3. See that create Service Account hangs.

### Expected Behavior

That it provisions without hanging or errors.

### Actual Behavior

Hangs with this error:

```
Diagnostics:
  kubernetes:core/v1:ServiceAccount (kubernetes-dashboard-292228bf/kubernetes-dashboard):
    error: error reading from server: read tcp 127.0.0.1:57288->127.0.0.1:45099: use of closed network connection
```

### Versions used

```
CLI          
Version      3.35.3
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  v18.5.0

Host     
OS       ubuntu
Version  20.04
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already). 

### Edit
It might not be a helm issue, rather a docker-desktop kubernetes issue. I am experiencing `pulumi up` hangs on other resources with this similar error:
`error: error reading from server: read tcp 127.0.0.1:57288->127.0.0.1:45099: use of closed network connection`

**Comment by lblackstone** [comment]
@Jaskerv Thanks for bringing this to our attention! It looks like our readiness/await logic needs to be updated to support a [change in k8s 1.24](https://itnext.io/big-change-in-k8s-1-24-about-serviceaccounts-and-their-secrets-4b909a4af4e0). Our provider currently waits for the SA secret to be available before marking the resource ready, but these secrets are no longer provisioned by default in k8s 1.24 and beyond.

Until this is fixed, you can work around the problem by skipping the readiness check for the ServiceAccount like this:

```ts
new k8s.helm.v3.Chart('kubernetes-dashboard', {
    chart: 'kubernetes-dashboard',
    version: '5.4.1',
    fetchOpts: {
        repo: 'https://kubernetes.github.io/dashboard/',
    },
    transformations: [
        // Skip readiness check for the ServiceAccount.
        (obj: any, opts: pulumi.CustomResourceOptions) => {
            if (obj.kind === "ServiceAccount" && obj.apiVersion === "v1") {
                if (!obj.metadata.annotations) {
                    obj.metadata.annotations = {};
                }
                obj.metadata.annotations["pulumi.com/skipAwait"] = "true";
            }
        },
    ],
});
```

**Comment by lblackstone** [comment]
I opened #2063 to track the underlying issue, and the workaround should get you unblocked, so I'm going to close out this issue.
