### ISSUE TITLE
Support ConfigFile in Java

### ISSUE THREAD

**Issue by hnicke** [pulumi/pulumi-kubernetes#2071]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be handy to improve the kubernetes provider support by implementing [`ConfigFile`](https://www.pulumi.com/registry/packages/kubernetes/api-docs/yaml/configfile/) in the java SDK.

Use Case: I'm currently bootstrapping a new k8s cluster and installed cert-manager using the pulumi java sdk.
I realized that there is no way to install a `ClusterIssuer`.
Preferably I'd like to use a `CustomResource` in this case. The more generic `ConfigFile` would suit me as well.

**Comment by EronWright** [comment]
This feature is available now with the new "v2" implementations, enjoy!
https://www.pulumi.com/blog/kubernetes-yaml-v2/
