### ISSUE TITLE
Problem parsing kubeconfig when passed via "kubernetes:kubeconfig"

### ISSUE THREAD

**Issue by captncraig** [pulumi/pulumi-kubernetes#209]
If I set `$KUBECONFIG` in my environment, then pulumi can find my cluster and things work fine.

But if I set `kubernetes:kubeconfig` in my stack's yaml, I get an error:

```
Diagnostics:
  global: global
    error: failed to parse kubeconfig: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

The first issue is certainly that it is [trying to parse the filename as a kubeconfig](https://github.com/pulumi/pulumi-kubernetes/blob/master/pkg/provider/provider.go#L131). That is almost certainly a bug. After that, I'm not clear if the underlying codec will accept yaml/json interchangably, but I will try to find out and make a pr.

**Comment by captncraig** [comment]
As an aside, I really like that I can set the kubeconfig in the stack's yaml because it lets us target different stacks to different clusters using only the files in the repo, so that's kinda nice.

**Comment by hausdorff** [comment]
@captncraig ah, this is actually supposed to be the _contents_ of kubeconfig. So you'd do something like `pulumi config set kubernetes:kubeconfig < cat $KUBECONFIG`. I can see now how this would be confusing, though. Perhaps we should report this with a better error and expose a second variable, `kubernetes:kubeconfigFilename`?

**Comment by hausdorff** [comment]
For more context: the reason this exists at all is so that we can, in a single Pulumi program, boot up EKS/AKS/GKE and then pass the YAML of the kubeconfig to the Kubernetes provider, so that it gets auto-configured. For example in the [AKS/helm example](https://github.com/pulumi/examples/blob/master/azure-ts-aks-helm/index.ts), we have something like this:

```typescript
import * as helm from "@pulumi/kubernetes/helm";
import * as k8s from "@pulumi/kubernetes";
import { k8sCluster, k8sProvider } from "./cluster";

const apache = new helm.v2.Chart("apache", {
    repo: "bitnami",
    chart: "apache",
    version: "1.0.0",
}, { providers: { kubernetes: k8sProvider } });
```

Basically what's happening here is `import { k8sCluster, k8sProvider } from "./cluster";` declares the AKS cluster, and then `k8sProvider` exports the YAML for the kubeconfig, providing it as `kubernetes:kubeconfig`, which allows the Helm chart to deploy _to that cluster_.

**Comment by captncraig** [comment]
Yeah, [the docs](https://pulumi.io/quickstart/kubernetes/setup.html) on that parameter definitely made me thing it was asking for a filename. But reading again I could see it either way. Yeah, a separate parameter for a file might be ok.

My use case was having a single project with multiple stacks for different tiers and clusters. Stacks like `guestbook-dev-ny`, and `guestbook-prod-co`. We also have a directory with kubeconfigs, one for each cluster. So the easy thing to do is reference the specific kubeconfig in the stack that uses it.

**Comment by hausdorff** [comment]
This can/should be just a call to `errors.Wrapf`, we should absolutely do this for Q3.
