### ISSUE TITLE
Pulumi stack fails to destroy when using SSA Patches on image field

### ISSUE THREAD

**Issue by roothorp** [pulumi/pulumi-kubernetes#2104]
### What happened?

When trying to destroy a cluster (created using pulumi-eks) which has been modified with SSA Patches the patches fail to delete, therefore failing the entire destroy. In this case, I have used a DeploymentPatch to change the CoreDNS image in use, and a DaemonsetPatch to change the kube-proxy image in use. Trying to destroy the entire stack immediately errors:

```
  kubernetes:apps/v1:DeploymentPatch (example):
    error: Deployment.apps "coredns" is invalid: spec.template.spec.containers[0].image: Required value

  kubernetes:apps/v1:DaemonSetPatch (example2):
    error: DaemonSet.apps "kube-proxy" is invalid: spec.template.spec.containers[0].image: Required value
```

### Steps to reproduce

Create a cluster, and modify an image field with a Patch (in this case in a Deployment, also happens in a Daemonset):

```ts
const cluster = new Cluster('cluster', {
  version: "1.21"
});

const example = new kubernetes.apps.v1.DeploymentPatch("example", {
  metadata: {
    name: "coredns",
    namespace: "kube-system",
    annotations: {
      "pulumi.com/patchForce": "true",
    }
  },
  spec: {
    template: {
      spec: {
        containers: [{
          name: "coredns",
          image : "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.8.7-eksbuild.1",
        }]
      }
    }
  }
}, {
  provider: cluster.provider
});
```

`pulumi up` will then create the cluster and apply the patch, changing the Deployment to use coredns 1.8.7 (by default, k8s 1.21 will use 1.8.4).

Once `pulumi up` completes, attempting to `pulumi destroy` will fail, reporting that image is a required value:
```
  kubernetes:apps/v1:DeploymentPatch (example):
    error: Deployment.apps "coredns" is invalid: spec.template.spec.containers[0].image: Required value
```

### Expected Behavior

The patches to be deleted, the values to be returned to their original/default state, and the destroy to continue.

### Actual Behavior

The destroy fails:
```
Resources:
    - 29 to delete

Do you want to perform this destroy? yes
Destroying (dev)

View Live: [...]

     Type                                   Name         Status                  Info
     pulumi:pulumi:Stack                    scratch-dev  **failed**              1 error
 -   ├─ kubernetes:apps/v1:DaemonSetPatch   example2     **deleting failed**     1 error
 -   └─ kubernetes:apps/v1:DeploymentPatch  example      **deleting failed**     1 error

Diagnostics:
  kubernetes:apps/v1:DaemonSetPatch (example2):
    error: DaemonSet.apps "kube-proxy" is invalid: spec.template.spec.containers[0].image: Required value

  pulumi:pulumi:Stack (scratch-dev):
    error: update failed

  kubernetes:apps/v1:DeploymentPatch (example):
    error: Deployment.apps "coredns" is invalid: spec.template.spec.containers[0].image: Required value

Resources:

Duration: 4s
```

### Versions used

```
CLI
Version      3.36.0
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.10.0
eks         0.41.2
kubernetes  3.20.0
nodejs      unknown

Host
OS       darwin
Version  12.4
Arch     arm64

This project is written in nodejs: executable='/opt/homebrew/bin/node' version='v18.6.0'

Current Stack: dev

[...]

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/rthorp
User           rthorp
Organizations  rthorp, pulumi

Dependencies:
NAME            VERSION
@pulumi/eks     0.41.2
@pulumi/pulumi  3.36.0
@types/node     14.18.22
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
Ok, I figured out what is happening here. The patch you specified is force-overriding the image value, which changes the FieldManager for that field. When the DeploymentPatch is deleted, the field becomes unmanaged. This normally causes the field to revert to the default value, but in this case, an empty string is not a valid value, so you get the error.

In this case, we can work around this by setting the `retainOnDelete` resource option for the DeploymentPatch. Here's a complete working example that patches the resource on create, and then destroys cleanly.

```typescript
import * as eks from "@pulumi/eks";
import * as k8s from "@pulumi/kubernetes";

const cluster = new eks.Cluster('cluster', {
    version: "1.21"
});

// Create a Provider with SSA enabled.
const provider = new k8s.Provider("k8s", {
    kubeconfig: cluster.kubeconfig,
    enableServerSideApply: true,
});

export const kubeconfig = cluster.kubeconfig;

const example = new k8s.apps.v1.DeploymentPatch("example", {
    metadata: {
        name: "coredns",
        namespace: "kube-system",
        annotations: {
            "pulumi.com/patchForce": "true",
        }
    },
    spec: {
        template: {
            spec: {
                containers: [{
                    name: "coredns",
                    image : "602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/coredns:v1.8.7-eksbuild.1",
                }]
            }
        }
    }
}, {provider, retainOnDelete: true});
```

I don't think this counts as a provider bug, since this delete behavior is expected for SSA resources. That said, we may need to add a more descriptive error message to make it clearer how to resolve the issue you encountered.
