### ISSUE TITLE
Document await conditions

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#211]
When a resource is created, Pulumi will wait until it's fully initialized. These conditions are not documented anywhere, but people in the community have indicated this would be helpful.

**Comment by lblackstone** [comment]
I'll incrementally document this as part of #450 #451 #452 #453 #454 and then create a top-level doc with a summary once that's complete.

**Comment by lukehoban** [comment]
I suggest we do this in the API doc comments for the resources themselves (`Service`, etc.).
