### ISSUE TITLE
DeploymentPatch should not require `.spec.template.metadata.name`

### ISSUE THREAD

**Issue by Iced-Sun** [pulumi/pulumi-kubernetes#2115]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

As stated in the title, `.spec.template.metadata.name` is **required** if  `.spec.template.metadata` is presented in `DeploymentPatch` (as wel as `StatefullSetPatch`, etc.), but it shouldn't.

**Comment by lblackstone** [comment]
Thanks for reporting this. I overlooked the fact that the `ObjectMetaPatch` type is reused in the nested template types, so that's why it is currently marked as required. I'm investigating options for fixing this now.
