### ISSUE TITLE
Helm Release does not pickup changes in locally stored templates

### ISSUE THREAD

**Issue by benbust** [pulumi/pulumi-kubernetes#2118]
### What happened?

When referencing a Chart with a local path, if I apply changes to the templates and run `pulumi up`,  the release is not updated. 

As a workaround, I've set `forceUpdate: true`.

### Steps to reproduce

Using `kind`: 

`kind create cluster --name pulumi`

```typescript
const kind = new k8s.Provider("kind", {context: "kind-pulumi"});
const release = new Release("pulumi-release",{
    name: "pulumi-test",
    createNamespace: true,
    namespace: "pulumi-test",
    chart: "./pulumi-chart-test/",
    forceUpdate: true,
    values: {
        pulumi: "world",
    }
    },{
        provider: kind
    }
);
```

The pulumi-chart-test/templates folder contains a simple manifest and if I add the below:

```patch
apiVersion: v1
kind: ConfigMap
metadata:
  name: pulumi
  annotations:
+    test: "update"
data: 
    hello: {{ .Values.pulumi }}
```

And run `pulumi up` nothing happens.

### Expected Behavior

The Helm release should be updated with any addition to its manifests.

### Actual Behavior

Nothing happened, the release is not updated according to the changes in the underlying manifest.

### Versions used

```
CLI          
Version      3.37.2
Go Version   go1.18.4
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.20.2
nodejs      unknown

Host     
OS       darwin
Version  11.6
Arch     x86_64

This project is written in nodejs: executable='/Users/benjamin/.nvm/versions/node/v16.15.1/bin/node' version='v16.15.1'

Current Stack: helmRelease

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:helmRelease::helm::pulumi:pulumi:Stack::helm-helmRelease
pulumi:providers:kubernetes    urn:pulumi:helmRelease::helm::pulumi:providers:kubernetes::kind
kubernetes:helm.sh/v3:Release  urn:pulumi:helmRelease::helm::kubernetes:helm.sh/v3:Release::pulumi-release


Found no pending operations associated with helmRelease

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/btuffreau
User           btuffreau
Organizations  btuffreau, starburstdata

Dependencies:
NAME                VERSION
@pulumi/kubernetes  3.20.2
@pulumi/pulumi      3.37.2
@types/node         14.18.23
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Hi @benbust - thank you for filing this bug!

Also, many thanks for the workaround; it's always helpful for others who may be running into a similar issue.

We will need to add a check to detect source file changes here and will be taking a look soon.

**Comment by lukehoban** [comment]
I believe to address this we'd need to either:
1. Support passing an Asset/Archive here (which takes care of tracking checksums and diffs)
2. Add an (optional) checksum input which the user can compute themselves and which will trigger updates

**Comment by jdmaguire** [comment]
I tried the above workaround and it wasn't working for me. An alternative workaround was this code:

```
const myChart = new k8s.helm.v3.Release("argo-configuration", {
  chart: "../charts/my-chart",
  name: "my-chart",
  namespace: deployNamespace,
  values: {
    random: Math.random()
  }
}, { parent: this });
```

**Comment by lblackstone** [comment]
Possibly related to #748

**Comment by amkartashov** [comment]
w/a I use:

* change version in Chart.yaml
* pass version in helm.v3.Release args

This is kinda logical - chart version should be bumped on chart change.

**Comment by EronWright** [comment]
Similar to: https://github.com/hashicorp/terraform-provider-helm/issues/515

Upon some investigation, the ideal seems to be to use the checksum of the rendered template, as opposed to that of the raw files. This would allow Pulumi to take into account the computed output. I observe that the template is rendered eagerly by the provider (during Check) to re-compute the resource names. I'll investigate further.
