### ISSUE TITLE
can i embed  this lib into other nodeJS/Express app ?

### ISSUE THREAD

**Issue by xmlking** [pulumi/pulumi-kubernetes#213]
I want to build my one provisioning API using NodeJS/Express framework.
can I use this package in embedded mode with in other express App  without CLI ?

**Comment by ellismg** [comment]
> can I use this package in embedded mode with in other express App without CLI ?

This is not something that is supported. The Pulumi Engine (which is part of the Pulumi CLI) is deeply involved in figuring out the operations to preform during a deployment and so it's not possible to use the JavaScript library without it present.

**Comment by ellismg** [comment]
@joeduffy gives an overview of how the entire system works in this video: https://www.youtube.com/watch?v=YMAe59BYzm4.

**Comment by hausdorff** [comment]
I think this is a reasonable scenario to support, and others have asked for similar things (_e.g._, allowing the CLI to emit JSON so other tools can consume it). I'd personally love to see something like this exist, but I'm not sure where in the roadmap it would fit just yet. @lukehoban @joeduffy , thoughts?

**Comment by xmlking** [comment]
Usecase  , someone went to build an App Store like kubeapps , and let users deploy predefined or custom  `Infrastructure as Code` snippets to a k8s cluster  via web UI and forms

**Comment by hausdorff** [comment]
Another use case we've heard from someone on the Istio team: exposing as an API allows us to wrap this up as an operator, which would allow them to manage dependencies between CRDs.

**Comment by lukehoban** [comment]
I think this is largely going to be enabled as part of https://github.com/pulumi/pulumi/issues/496.  By allowing the CLI to be invoked and used with `--json`.  

We may at some point offer SDKs that wrap this (or statically link in the engine) - but I suspect that will be longer term once we better understand the desired API for those SDKs.  In the nearer term scripting the CLI should be sufficient to flexibly enable these scenarios.

I'll close this for now as a "dupe" of the issue above - but feel free to reopen if there is a scenario not covered by that that we should track.
