### ISSUE TITLE
Custom resource creation: failed to determine if the following GVK is namespaced

### ISSUE THREAD

**Issue by mlkiefer** [pulumi/pulumi-kubernetes#2143]
### What happened?

I have the AWX operator (https://github.com/ansible/awx-operator) running on my k8s cluster. When I try to create a custom resource of kind awx, Pulumi fails complaining `resource awx/my-awx-3a77c8ca was not successfully created by the Kubernetes API server : failed to determine if the following GVK is namespaced: awx.ansible.com/v1beta1, Kind=awx`. 

### Steps to reproduce

Install the AWX operator, create an awx resource like this:

```python
awx_deployment = k8s.apiextensions.CustomResource(
    "my-awx",
    kind="awx",
    api_version="awx.ansible.com/v1beta1",
    metadata=k8s.meta.v1.ObjectMetaArgs(
        namespace="awx"
    )
)
```

### Expected Behavior

An AWX resource should be created in the cluster

### Actual Behavior

resource awx/my-awx-3a77c8ca was not successfully created by the Kubernetes API server : failed to determine if the following GVK is namespaced: awx.ansible.com/v1beta1, Kind=awx

### Output of `pulumi about`

I am using the github runner of Pulumi

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
Hi @mlkiefer, could you provide more information about the versions you're running here?

**Comment by mlkiefer** [comment]
Hi @lblackstone , this was with 
arpeggio-1.10.2 attrs-22.1.0 certifi-2022.6.15 charset-normalizer-2.1.0 dill-0.3.5.1 grpcio-1.47.0 idna-3.3 parver-0.3.1 protobuf-4.21.5 pulumi-3.38.0 pulumi-aws-5.10.0 pulumi-kubernetes-3.20.5 pyyaml-5.4.1 requests-2.28.1 semver-2.13.0 six-1.16.0 urllib3-1.26.11
and the awx-operator in version 0.25
In the meantime, I switched to using crd2pulumi, which works but means I have to manually generate pulumi code before using the custom resources

**Comment by EronWright** [comment]
The root cause of this issue is that `kind` is case-sensitive, and that the provider produces the above (misleading) error message when a kind is missing. Observe that the kind in this case should be `AWX` ([reference](https://github.com/ansible/awx-operator/blob/d5a3cb751992698e3f36ab407eee684fef3192fc/config/crd/bases/awx.ansible.com_awxs.yaml#L9)).

I'll retitle this issue accordingly.
