### ISSUE TITLE
Ingress extra spec fields

### ISSUE THREAD

**Issue by k1ng440** [pulumi/pulumi-kubernetes#2150]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
It seems `k8s.networking.v1.Ingress` does not allow extra parameters in ingress `spec`. I am are using AWS loadblancer controller and I can't provide the required fields to the `spec`. Please see examples in this link:
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/ingress_class/

### Affected area/feature
Ingress

**Comment by stack72** [comment]
@lblackstone would love your thoughts on this one?

**Comment by lblackstone** [comment]
@k1ng440 The example you linked is for `IngressClass` rather than `Ingress`. It looks like the [parameters](https://www.pulumi.com/registry/packages/kubernetes/api-docs/networking/v1/ingressclass/#parameters_nodejs) field is supported as I'd expect on `IngressClass`.

**Comment by k1ng440** [comment]
Oh yes, you are right. thank you for pointing it out.

**Comment by lblackstone** [comment]
Great, I'll go ahead and close this issue as resolved. :)
