### ISSUE TITLE
ComponentResourceOptions missing from Pulumi.Kubernetes.Helm.V3

### ISSUE THREAD

**Issue by dankitson** [pulumi/pulumi-kubernetes#2154]
### What happened?

Attempting to use V3.Release but unable to utilise ComponentResourceOptions to configure a Provider. Only CustomResourceOptions listed?

Documentation stores that ComponentResourceOptions should be available on this class?

![image](https://user-images.githubusercontent.com/56910879/186880914-9e432c04-33a2-404a-abc8-2c9b9ed9049b.png)
![image](https://user-images.githubusercontent.com/56910879/186880932-d67b118c-c87a-4850-a4e0-2cf0f0035b64.png)

### Steps to reproduce

Produce a C# dotnet pulumi package, use the following package:

Pulumi.Kubernetes 3.21.0

Attempt to declare a V3 release and pass Component Options through.

### Expected Behavior

ComponentResourceOptions available like it is for V3.Chart and as per V3.Release documentation:

![image](https://user-images.githubusercontent.com/56910879/186881376-bdc5f48c-468c-413d-ba18-ec2ee592f68f.png)

### Actual Behavior

ComponentResourceOptions not available. CustomResourceOptions instead.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @dankitson 

ComponentResourceOptions are only available when building a ComponentResource - you need to use `CustomResourceOptions` for your usecase above like the first image shows

Paul
