### ISSUE TITLE
Automerge going through despite test failures

### ISSUE THREAD

**Issue by viveklak** [pulumi/pulumi-kubernetes#2169]
### What happened?

See https://github.com/pulumi/pulumi-kubernetes/pull/2168/ which has test failures but was merged regardless by GHA automation. 

### Steps to reproduce

Re create the above PR

### Expected Behavior

Block on merging on test failures.

### Actual Behavior

Merge succeeds.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jkisk** [comment]
@stack72 have you had time to look into this at all?  I'd like to gain context on what we are doing for native branch protections.

**Comment by jkisk** [comment]
I think adding "destroy test cluster" to the `needs` requirements for the sentinel check for this repo could be helpful.

**Comment by viveklak** [comment]
FWIW I just saw the same behavior in https://github.com/pulumi/pulumi-gcp/pull/900

**Comment by stack72** [comment]
I am not sure how this happened - I've tried a few things and not been able to come up with an answer similar to it's a bug in GHA at specific points. I also took @danielrbradley through this on a call... I think we may need to schedule a little more work here and think about the automerge

FWIW, the automerge is working perfectly on azure-native and aws-native so this is behaving strangely

**Comment by lblackstone** [comment]
I think this is fixed now.
