### ISSUE TITLE
helm.v3.Release doesn't apply values from yaml file

### ISSUE THREAD

**Issue by skibadmitriy** [pulumi/pulumi-kubernetes#2178]
### What happened?

I'd created Release for ingress-nginx with vaules.yaml file, but it didn't apply my custom values from yaml file

```
    ingress_nginx = Release(
        "ingress-nginx",
        ReleaseArgs(
            name = "ingress-nginx",
            chart = "ingress-nginx",
            version = "4.2.0",
            namespace = "ingress-nginx",
            create_namespace = True,
            repository_opts = RepositoryOptsArgs(
                repo = "https://kubernetes.github.io/ingress-nginx",
            ),
            value_yaml_files = pulumi.FileAsset("./app/test/values/ingress-inginx.yaml")
        ),
        skip_await = False,
        opts = ResourceOptions(parent = parent,
                            provider = provider,
                            depends_on = depends_on,
                            protect = False
        )
    )
```
```
$ helm list -A
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-nginx   ingress-nginx   1               2022-09-20 12:17:56.112216944 +0300 MSK deployed        ingress-nginx-4.2.0     1.3.0      

$ helm -n ingress-nginx get values ingress-nginx 
USER-SUPPLIED VALUES:
null
```

### Steps to reproduce

Create helm.v3.Release with value_yaml_files option 

### Expected Behavior

User-supplied values applied to helm release

### Actual Behavior

User-supplied values didn't apply to helm release

### Output of `pulumi about`

CLI          
Version      3.40.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME          VERSION
digitalocean  4.14.0
kubernetes    3.20.2
postgresql    3.5.0
python        unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.10.4

Dependencies:
NAME                 VERSION
pip                  22.0.2
pulumi-digitalocean  4.14.0
pulumi-kubernetes    3.20.2
pulumi-postgresql    3.5.0
setuptools           59.6.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
I'm not too familiar with this area, but from a quick look at the docs, it looks like the `value_yaml_files` property is expected to be a list of assets. Let me know if that fixes your issue.

**Comment by rshade** [comment]
related to https://github.com/pulumi/pulumi-kubernetes/issues/1922
