### ISSUE TITLE
Helm Chart missing from the JAVA sdk

### ISSUE THREAD

**Issue by nicu-da** [pulumi/pulumi-kubernetes#2179]
### What happened?

The documentation for [helm charts ](https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/chart/) shows the JAVA api classes that expose the Helm Chart API. 
Going through the helm API available in the java sdk we find no classes required to create  chart.

### Steps to reproduce

Try to create a helm chart in Java.

### Expected Behavior

Classes required to create a helm chart are found in the java sdk.

### Actual Behavior

Documented classes are not present in the sdk.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
Related to https://github.com/pulumi/pulumi-kubernetes/issues/2071

The helm Chart, yaml ConfigFile and ConfigGroup, and kustomize Directory resources are currently implemented with custom logic for each SDK, but have not yet been implemented for Java. Sorry for the confusing registry docs! I opened #2181 to track that bug.

**Comment by EronWright** [comment]
This is fixed in the upcoming Chart v4 resource - full Java and YAML SDK support. Enjoy!
