### ISSUE TITLE
Provider API docs show resources that aren't present in the SDK

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#2181]
- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

### Problem description

Some resources (helm.Chart, yaml.ConfigFile, yaml.ConfigGroup, kustomize.Directory) are currently implemented as overlays rather than using the typical code generation process. These resources are not yet available in Java, but the resource documentation in the registry includes Java. These resources should include an unimplemented note to avoid confusion.

Related: https://github.com/pulumi/pulumi-kubernetes/issues/2179
Related: https://github.com/pulumi/pulumi-kubernetes/issues/2071

**Comment by nstires-ctgx** [comment]
Would be super cool if they were in though! (specifically helm.Chart, yaml.ConfigFile, yaml.ConfigGroup)

**Comment by EronWright** [comment]
A note about the ability (or lack thereof) to customize which languages are shown in an chooser block. Thanks to https://github.com/pulumi/pulumi/pull/4426 there's some support in the templates within the docs repository, but any actual usage was removed in https://github.com/pulumi/pulumi/pull/4646.
