### ISSUE TITLE
Allow users to generate types from CRD schemas

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#219]

**Comment by marcus-sa** [comment]
What's the progress on this?
I've currently made a generator which generated All the required custom Pulumi resources for Istio.

https://github.com/marcus-sa/pulumi-k8s-istio

So far I've realized that the only way these ressources will work, is if I generate YAML from the args and then parse it using the Kubernetes YAML class.

**Comment by lblackstone** [comment]
Now that CRDs have hit GA and require an OpenAPI spec as part of the definition, this should be possible to do more robustly.

**Comment by EronWright** [comment]
Just want to mention that it would be great to support any extension API server, not just CRD.  I believe the common basis is the OpenAPI v3 schema which one would obtain via the API, but am not 100% sure.

**Comment by omerlh** [comment]
Any update about that? This will be a really interesting feature :)

**Comment by lblackstone** [comment]
We’re working on some related issues now (schema-based code generation), but don’t have a firm timeline on this issue yet. Definitely still interested in getting this done.

**Comment by ringods** [comment]
@lblackstone in all openness of an OpenSource project (*grin*), feel free to pass some ideas to us for validation. I'm also wildly interested in this. CRDs are becoming more and more important in the Kubernetes ecosystem.

**Comment by lblackstone** [comment]
So my initial thought is that this would would be done as a standalone binary that could produce the CRD type snippets in the target language of your choice. 

Given the vast number of CRDs in the wild, I suspect it wouldn't make sense to bake them into the provider. It might make sense to create type libraries for particularly common CRDs like Istio.

Definitely interested in hearing any thoughts on this approach, as well as alternate suggestions!

**Comment by lblackstone** [comment]
This tool exists now, so I'm going to close out this tracking issue, and we can track additional bugs/features in new issues.

https://github.com/pulumi/pulumi-kubernetes/tree/master/provider/cmd/crd2pulumi
https://www.pulumi.com/blog/introducing-crd2pulumi/
