### ISSUE TITLE
Mount EBS Volume to K8s Pods 

### ISSUE THREAD

**Issue by sarocu** [pulumi/pulumi-kubernetes#2197]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I am trying to mount an EBS volume to multiple pods in a deployment and the attachment is timing out. When I `describe` a pod, I see the event from kubelet:
```bash
Unable to attach or mount volumes: unmounted volumes=[file-uploads], unattached volumes=[kube-api-access-fv6xd file-uploads]: timed out waiting for the condition
```

I feel like I am missing an IAM permission here and I tried to set an RBAC role allowing persistent volume claims but that was unsuccessful. Is there IAM magic happening with the EKS cluster creation that I need to consider?

Volume: 

```typescript
const uploadVolume = new aws.ebs.Volume('file-uploads', {
  availabilityZone: 'us-west-2a',
  size: 100,
  encrypted: true,
  type: 'io2',
  iops: 5000,
  multiAttachEnabled: true,
  tags: {
    Name: 'flatfile-x-file-uploads',
  },
})

const volumeAttachment = new k8s.core.v1.PersistentVolume('file-uploads', {
  spec: {
    awsElasticBlockStore: {
      volumeID: uploadVolume.id
    },
    accessModes: ['ReadWriteMany'],
    capacity: {
      storage: '1000Gi'
    }
  }
}, {provider: cluster.provider})
```

Deployments:
```typescript
const appDeployment = new k8s.apps.v1.Deployment(
  'app',
  {
    spec: {
      selector: { matchLabels: app },
      replicas: 3,
      template: {
        metadata: { labels: app },
        spec: {
          containers: [
            {
              name: 'app',
              image: '...',
              imagePullPolicy: 'Always',
              volumeMounts: [
                {
                  name: 'file-uploads',
                  mountPath: '/uploads',
                },
              ],
              ports: [{ name: 'worker', containerPort: 3001 }],
              resources: { requests: { cpu: '2', memory: '2Gi' } },
            },
          ],
          volumes: [
            {
              name: 'file-uploads',
              awsElasticBlockStore: {
                volumeID: volumeAttachment.id,
              },
            },
          ],
        },
      },
    },
  },
  {
    provider: cluster.provider,
  }
)
```

### Affected area/feature

* @pulumi/kubernetes
* @pulumi/aws

**Comment by lblackstone** [comment]
I found https://github.com/kubernetes/kubernetes/issues/110158 with a similar error message, so this message is coming from the Kubernetes API server, and seems like it may be related to a timeout condition. 

> Is there IAM magic happening with the EKS cluster creation that I need to consider?
Not that I'm aware of, but you could check what is provisioned on your AWS account.

This looks like problem with either the Kubernetes cluster, or with your configuration rather than a bug in Pulumi, so I'm going to close this issue out.
