### ISSUE TITLE
Add error when `kubernetes:yaml:ConfigGroup` provided non-existent files

### ISSUE THREAD

**Issue by errordeveloper** [pulumi/pulumi-kubernetes#2212]
When a list of file paths is passed to `kubernetes:yaml:ConfigGroup` it doesn't produce any warnings or errors about missing files, at least when some paths do exist.

I'm using TypeScript @pulumi/pulumi  3.42.0 & @pulumi/kubernetes 3.21.4.

**Comment by errordeveloper** [comment]
It's just this kind of thing:

```
kube.yaml.ConfigGroup("foo", { files: "exists.yaml", "missing.yaml")
```

The result of this was that `eixst.yaml` gets picked up as expected, but `missing.yaml` is silently ignored. I think it would be not such a big deal if there was warning, as I guess introducing an error would result in a breakage...

**Comment by lblackstone** [comment]
Dupe of #938
