### ISSUE TITLE
Retire the `watcher` package in favor of the client-go `watch` API

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#222]
The `watcher` package was originally modeled loosely so that we could contribute await logic to Terraform, if they wanted it, with a minimum of translational difficulties.

At this point the core tenants of our complex awaiters are so different that this goal now seems mostly hopeless. We should transition to simply using client-go's `watch` API, which is far more convenient to use.

Tasks:
- [x] Replace watcher usage in await.go
- [ ] Replace watcher usage in awaiters.go

**Comment by lblackstone** [comment]
Working on cleaning up the awaiters, so this won't be done before M21
