### ISSUE TITLE
Helm reads wrong Kubeversion: >=1.22.0-0 for v1.23.0 as v1.20.0

### ISSUE THREAD

**Issue by WP-LKL** [pulumi/pulumi-kubernetes#2224]
### What happened?

Tried adding ArgoCD to Kubernetes cluster on AWS (EKS) using Pulumi Python. But the wrong KubeVersion is read from the requirement.

THE CLUSTER VERSION IS: v1.23.0 verified on AWS. And NOT 1.20.0

ArgoCD install yaml used with CRD2Pulumi: https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/core-install.yaml

Any ideas as to fixing this oddity between the version error and the actual cluster version?

### Steps to reproduce

Try something like the following code (reproducibility verified):

```
cluster = eks.Cluster("argo-example") # version="1.23"

# Cluster provider
provider = k8s.Provider(
    "eks",
    kubeconfig=cluster.kubeconfig.apply(lambda k: json.dumps(k))
    #kubeconfig=cluster.kubeconfig
)

ns = k8s.core.v1.Namespace(
    'argocd',
    metadata={
        "name": "argocd", 
    },

    opts=pulumi.ResourceOptions( 
        provider=provider
    )
)

argo = k8s.helm.v3.Release(
    "argocd",  
    args=k8s.helm.v3.ReleaseArgs(
        chart="argo-cd",
        namespace=ns.metadata.name,
        repository_opts=k8s.helm.v3.RepositoryOptsArgs(
            repo="https://argoproj.github.io/argo-helm"
        ),
        values={
            "server": {
                "service": {
                    "type": "LoadBalancer",
                }
            }
        },
    ),
    opts=pulumi.ResourceOptions(provider=provider, parent=ns),
)

```

### Expected Behavior

Successfully deploys ArgoCD on the cluster.

### Actual Behavior

![image](https://user-images.githubusercontent.com/15800648/200303714-a379caae-4d9b-4699-8460-e137b803e4d8.png)

```
  kubernetes:helm.sh/v3:Release (argocd):
    error: failed to create chart from template: chart requires kubeVersion: >=1.22.0-0 which is incompatible with Kubernetes v1.20.0
```

### Additional context

I've tried:

    Deleting everything and starting over.
    Updating to the latest ArgoCD install yaml.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
This seems to be an issue with the chart and/or Helm. https://github.com/argoproj/argo-helm/pull/1579 added a [kubeVersion requirement](https://github.com/argoproj/argo-helm/blame/c82b03eac1cbe1dc28e14e3152199c52c82128cb/charts/argo-cd/Chart.yaml#L3), which is failing validation.

Can you try installing that Chart using the `helm` client directly and see if you get the same error?

**Comment by WP-LKL** [comment]
> This seems to be an issue with the chart and/or Helm. [argoproj/argo-helm#1579](https://github.com/argoproj/argo-helm/pull/1579) added a [kubeVersion requirement](https://github.com/argoproj/argo-helm/blame/c82b03eac1cbe1dc28e14e3152199c52c82128cb/charts/argo-cd/Chart.yaml#L3), which is failing validation.
> 
> Can you try installing that Chart using the `helm` client directly and see if you get the same error?

You are correct, indeed a new addition to the Argo helm chart.

However, it appears to be working fine using the helm client directly:
![image](https://user-images.githubusercontent.com/15800648/200840309-888b28ac-292b-4fdb-a1a4-6656ba447138.png)

**Comment by d-maki** [comment]
I too am experiencing this same issue with ECK on EKS and AKS.

**Comment by lblackstone** [comment]
Hmm, that's odd. I was not able to reproduce the problem locally using the TypeScript SDK. It worked both on a local cluster, and with an EKS cluster.

Can you update the issue with information about your plugin versions from `pulumi about`, and let me know if you have any more information about a consistent way to reproduce the problem?

![Screen Shot 2022-11-11 at 3 47 23 PM](https://user-images.githubusercontent.com/9253463/201441020-8f5d88ac-5143-425b-9b9e-9dbb2a399b45.png)

**Comment by d-maki** [comment]
Hey @lblackstone, apologies on the delay and appreciate you getting back to me.

The issue turned out to be an out of date eks-pulumi package. It appears that rather than checking against the local kubectl version, it's checking against the version listed in pulumi-eks or one of its dependencies:
  • Updating setuptools (65.5.0 -> 65.5.1)
  • Updating pulumi-kubernetes (3.16.0 -> 3.22.1)
  • Updating pulumi-eks (0.41.0 -> 0.42.7)

Updating to 0.42.7 resolved the issue for me.

This could be due to the code in there or it could come down to the specifics of our environment. The pulumi project is run through a local wrapper program that stores the project folder within an AWS S3 file (for stack consistency across different users running it), rather than within a local pulumi project folder.

As a final aside, the issue was not with the version running in EKS as noted above. So it's definitely related to the version check not referencing the cluster rather than an issue with what's actually deployed.

**Comment by WP-LKL** [comment]
Thanks @d-maki I will see if updating ``pulumi-eks`` and related packages solves this for us. 

And as you note, we should investigate and possibly create a new issue referencing this one for how the Kubeversion is checked.

**Comment by WP-LKL** [comment]
Great stuff -- indeed updating the package requirements solved it!

**Comment by re-thc** [comment]
@WP-LKL make a new issue? This is closed. Getting a similar error myself.

**Comment by WP-LKL** [comment]
@re-thc Yes please do, I will specify this one to relate for python and AWS.EKS.

**Comment by re-thc** [comment]
@WP-LKL created. Not much to add as the error / info is about the same.
