### ISSUE TITLE
[sdk/dotnet] Resource API group in v1.26 causes naming conflicts 

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#2233]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I attempted to generate updated SDKs using `v1.26.0-rc.0`, but am getting the following errors during code generation:
```
/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/sdk/dotnet/Helm/ChartBase.cs(263,98): error CS0118: 'Resource' is a namespace but is used like a type
/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/sdk/dotnet/Helm/V3/Chart.cs(292,175): error CS0118: 'Resource' is a namespace but is used like a type
/Users/levi/go/src/github.com/pulumi/pulumi-kubernetes/sdk/dotnet/Yaml/Yaml.cs(794,38): error CS0118: 'Resource' is a namespace but is used like a type
```

We need to figure out how to resolve these conflicts so that we can generate the updated SDKs.

**Comment by squaremo** [comment]
I can reproduce this by making these changes:

```
$ git diff -- Makefile provider/pkg/gen/
diff --git a/Makefile b/Makefile
index e7a461a04..e276be081 100644
--- a/Makefile
+++ b/Makefile
@@ -12,7 +12,7 @@ VERSION         ?= $(shell pulumictl get version)
 PROVIDER_PATH   := provider/v3
 VERSION_PATH     := ${PROVIDER_PATH}/pkg/version.Version
 
-KUBE_VERSION    ?= v1.25.0
+KUBE_VERSION    ?= v1.26.0-rc.0
 SWAGGER_URL     ?= https://github.com/kubernetes/kubernetes/raw/${KUBE_VERSION}/api/openapi-spec/swagger.json
 OPENAPI_DIR     := provider/pkg/gen/openapi-specs
 OPENAPI_FILE    := ${OPENAPI_DIR}/swagger-${KUBE_VERSION}.json
diff --git a/provider/pkg/gen/dotnet.go b/provider/pkg/gen/dotnet.go
index 473229abc..bb1f15804 100644
--- a/provider/pkg/gen/dotnet.go
+++ b/provider/pkg/gen/dotnet.go
@@ -41,6 +41,7 @@ var pascalCaseMapping = map[string]string{
        "node":                  "Node",
        "policy":                "Policy",
        "rbac":                  "Rbac",
+       "resource":              "Resource",
        "scheduling":            "Scheduling",
        "settings":              "Settings",
        "storage":               "Storage",
@@ -48,6 +49,7 @@ var pascalCaseMapping = map[string]string{
        "v1alpha1":              "V1Alpha1",
        "v1beta1":               "V1Beta1",
        "v1beta2":               "V1Beta2",
+       "v1beta3":               "V1Beta3",
        "v2":                    "V2",
        "v2alpha1":              "V2Alpha1",
        "v2beta1":               "V2Beta1",
```

then running `make build`.

The symptom seems obvious -- there's a new Kubernetes API named `resource`, for which the obvious translation into a dotnet namespace is `Resource`; but, there's also a type in the namespace `Pulumi` called `Resource` (in pulumi/pulumi, it's in sdk/dotnet/Pulumi/Resources/Resource.cs). The shape of the fix is to be explicit about where that type comes from. The Pulumi types should really be in a namespace that's not implicitly in scope in providers, to avoid exactly this situation; but, here we can alias the `Pulumi` namespace and qualify the types with it.

**Comment by lblackstone** [comment]
Fixed is included in https://github.com/pulumi/pulumi-kubernetes/pull/2234

@squaremo Let's split out the .NET naming changes and merge that separately so we can close out this issue, and then we can merge the updated SDKs later.
