### ISSUE TITLE
It's expensive to re-run integration tests

### ISSUE THREAD

**Issue by squaremo** [pulumi/pulumi-kubernetes#2243]
The way the integration tests (run by workflow `build` among others) are run, if the set of tests for a language fails, it cannot be rerun by itself. This means wasted resources, but perhaps more importantly, a longer turnaround time and (in the presence of flaky tests) a much larger chance of repeated failures.

**Comment by EronWright** [comment]
Possible improvements may include:
- use a local cluster rather than a cloud cluster (tough some tests may require the latter)
- CI refactoring, e.g. finer-grained workflow steps and/or be able to re-run a specific suite

**Comment by EronWright** [comment]
Addressed by switching to KinD: https://github.com/pulumi/pulumi-kubernetes/pull/2831
