### ISSUE TITLE
Multiple deployments of Helm Chart on different Cluster fails with " Duplicate resource URN"

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-kubernetes#2247]
### What happened?

Hi,

we got an issue reported from our customer with following situation leading to an error:

1. We use a custom component. This componenent contains a K8s cluster and a deployment of a Pulumi `Chart` resource
2. We initiate the Component twice in your main Pulumi program for one stack. The Component deploys the k8s cluster in different regions.
3. During the deployment of the Helm Chart, we can see that the deployments fails on cluster-wide resources (CRDS, ClusterRole, Clusterbinding, etc) for **one of the two clusters**

```bash
Diagnostics:
  kubernetes:core/v1:ServiceAccount (silly-helm):
    error: Duplicate resource URN 'urn:pulumi:dev::helm-issue::k8s:dirien:eks-k8s$kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::silly-helm'; try giving it a unique name
```

The customer, found a way to workaround this.

Instead having a fixed name for the ComponentResource:

```bash
err := ctx.RegisterComponentResource("k8s:dirien:eks-k8s", name, k8s, opts...)
```

The customer is adding a custom part to it, for example the region.

```bash
err := ctx.RegisterComponentResource(fmt.Sprintf("k8s:dirien:eks-k8s-%s", region), name, k8s, opts...)
```

This will make the `urn` unique and deployment works.

### Steps to reproduce

Run a `pulumi up` on this repository https://github.com/dirien/helm-issue.git

### Expected Behavior

The `Chart` is able to be deployed

### Actual Behavior

```bash
Diagnostics:
  kubernetes:core/v1:ServiceAccount (silly-helm):
    error: Duplicate resource URN 'urn:pulumi:dev::helm-issue::k8s:dirien:eks-k8s$kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:ServiceAccount::silly-helm'; try giving it a unique name
```

### Output of `pulumi about`

```bash
➜ pulumi about
CLI          
Version      3.47.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.21.1
go          unknown
kubernetes  3.22.1

Host     
OS       darwin
Version  12.5
Arch     arm64

This project is written in go: executable='/opt/homebrew/Cellar/go/1.19.3/libexec/bin/go' version='go version go1.19.3 darwin/arm64'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dirien
User           dirien
Organizations  dirien

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-aws/sdk/v5         5.21.1
github.com/pulumi/pulumi-kubernetes/sdk/v3  3.22.1
github.com/pulumi/pulumi/sdk/v3             3.47.1
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
hi @dirien - [here's an explanation for a similar question](https://github.com/pulumi/pulumi-kubernetes/issues/1470#issuecomment-778331500) - this is in fact the default behavior, and this is true across other providers as well.
A solution is, like you suggested, to concatenate the region name to the cluster as a variable. 🎉 
There's been [a bit of exploration here on usability improvement](https://github.com/pulumi/pulumi-kubernetes/issues/1472) for issues like this, but in the meantime I'm going to close this issue.
