### ISSUE TITLE
Delete a newly created ConfigMap in the code

### ISSUE THREAD

**Issue by LucasBrazi06** [pulumi/pulumi-kubernetes#2252]
I created a ConfigMap with Pulumi:
```
    // Create setup script
    const argoCDInitialSetupScript = new k8s.core.v1.ConfigMap('argo-cd-setup', {
      metadata: {
        name: 'argo-cd-setup',
        namespace: 'argo',
      },
      data: {
        'init-argo.sh': fs.readFileSync("src/assets/yaml/argo-cd/argo-cd-setup.sh").toString()
      },
    });
```
Next, I run a Job that will use this ConfigMap and when the Job completes, I want to delete this ConfigMap but I cannot find how to do so in Pulumi!

I would have expected something like this:
```
    // Delete Config Map
    argoCDInitialSetupScript.delete();
```

**Comment by lblackstone** [comment]
Hi @LucasBrazi06, to delete a resource created by Pulumi, you would need to remove it from the program, and then run an update. The normal Pulumi model doesn't support imperative ordering of operations like you expect. Our [how-pulumi-works guide](https://www.pulumi.com/docs/intro/concepts/how-pulumi-works/) has more information.

You can use the [Automation API](https://www.pulumi.com/docs/guides/automation-api/) if you need more fine-grained control over operation ordering.

**Comment by LucasBrazi06** [comment]
@lblackstone Thanks a lot for the clarification!
