### ISSUE TITLE
`yaml.ConfigFile` doesn't respect `providers` in opts

### ISSUE THREAD

**Issue by antdking** [pulumi/pulumi-kubernetes#2254]
### What happened?

Attempted to migrate to using `providers=[...]` for our resource options, however this isn't propagated to the invoke for `yaml.ConfigFile`.
This results in a failure, as we have default providers disabled.

### Steps to reproduce

with config: `pulumi:disable-default-providers: [kubernetes]`

```py
import pulumi as p
import pulumi_kubernetes as k8s

k8s_provider = k8s.Provider("gke")
default_opts = p.ResourceOptions(
  providers=[
    k8s_provider,
    # ... other providers
  ],
)

# use cert-manager as an example
k8s.yaml.ConfigFile(
  "cert-manager",
  file="https://github.com/cert-manager/cert-manager/releases/download/v1.9.1/cert-manager.yaml",
  opts=default_opts,
)
```

### Expected Behavior

For `yaml.ConfigFile` to be invoked with the `"kubernetes"` provider defined in the `providers` list

### Actual Behavior

Attempts to invoke with the default `"kubernetes"` provider

### Output of `pulumi about`

```
$ pulumi about
CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME           VERSION
command        0.6.0
gcp            6.44.0
google-native  0.27.0
kubernetes     3.22.1
python         unknown

Host     
OS       arch
Version  22.0.0
Arch     x86_64

This project is written in python: executable='/home/anthony/.pyenv/shims/python3' version='3.10.6
'

Current Stack: datapane/test

TYPE                                                                       URN
<redacted>
pulumi:providers:kubernetes                                                urn:pulumi:test::dp-infra::gcp:container/cluster:Cluster$pulumi:providers:kubernetes::gke
kubernetes:yaml:ConfigFile                                                 urn:pulumi:test::dp-infra::kubernetes:yaml:ConfigFile::cert-manager

Found no pending operations associated with datapane/test

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/antdking
User           antdking
Organizations  antdking, datapane, antdking-testing

Dependencies:
NAME                     VERSION
bump2version             1.0.1
cloudflare               2.10.1
datapane                 0.15.5
docker                   6.0.1
environs                 9.5.0
google-cloud-monitoring  2.11.1
grpcio-status            1.47.0
invoke                   1.7.1
joblib                   1.1.0
kubernetes               24.2.0
mypy                     0.971.0
pip                      22.3.0
pre-commit               2.20.0
pulumi-command           0.6.0
pulumi-gcp               6.44.0
pulumi-google-native     0.27.0
pulumi-kubernetes        3.22.1
semgrep                  0.122.0
sh                       1.14.3
wheel                    0.37.1

Pulumi locates its logs in /tmp by default
```

not sure why the python sdk version didn't show:

```
$ pip show
Name: pulumi
Version: 3.48.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by roothorp** [comment]
Hi @antdking, thanks for the issue! I've raised this with the team to be prioritized and added to our work stack.

**Comment by antdking** [comment]
Thanks, @roothorp 

I did a little digging earlier, and tested a fix locally.
It looks as if `provider` is passed explicitly to the InvokeOptions [here](https://github.com/pulumi/pulumi-kubernetes/blob/8a8d523508cc1b6279dafda05d7e106ac65eaf08/sdk/python/pulumi_kubernetes/yaml/yaml.py#L346)

The fixed I used was to pass `parent=self` in instead, which will rely on the `Resource.get_provider` functionality.

ie:
```py
invoke_opts = pulumi.InvokeOptions(version=_utilities.get_version(), parent=self)
```

In the nodejs + python sdks, this looks to give the intended behaviour.


I was going to provide a PR to patch all languages; however I'm unable to get tests running locally, so won't be contributing more today

**Comment by roothorp** [comment]
That's brilliant, thank you! I'll pass that along to the team.

**Comment by EronWright** [comment]
To recap, the problem is with using `providers` versus `provider`; the provider in `providers` is ignored and falls back to using the default provider (which may be disabled and would be incorrect to use).

Relevant background:
- https://github.com/pulumi/pulumi/issues/8796
- https://github.com/pulumi/pulumi-kubernetes/pull/2005

**Comment by EronWright** [comment]
Bugfix PRs:
- https://github.com/pulumi/pulumi-kubernetes/pull/2709

**Comment by EronWright** [comment]
Posted an announcement to the community slack:
https://pulumi-community.slack.com/archives/CB36DSVSA/p1704325722193319
