### ISSUE TITLE
pulumi-kubernetes-3.21.0 + SSA role issue

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-kubernetes#2257]
### What happened?

We are running pulumi-kubernetes 3.21.0 with ssa enabled. We are getting the following errors when we try and preview the cluster: 

```
* the Kubernetes API server reported that "namespace/devs-role3" failed to fully initialize or become live: use `pulumi.com/patchForce` to override the conflict: Apply failed with 1 conflict: conflict with "pulumi-resource-kubernetes" using rbac.authorization.k8s.io/v1: .rules
```

### Steps to reproduce

Working on getting this all together, most of it in slack. 

### Expected Behavior

The role to be patched. 

### Actual Behavior

Throws an error. 

### Output of `pulumi about`

> $ pulumi about
CLI
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         4.38.1
kubernetes  3.21.0
python      unknown
random      4.8.2
tls         4.6.1

Host
OS       ubuntu
Version  20.04
Arch     x86_64

Backend
Name           pulumi.com

Dependencies:
NAME               VERSION
Jinja2             3.1.2
pip                22.3.1
pulumi-aws         4.38.1
pulumi-kubernetes  3.21.0
pulumi-random      4.8.2
pulumi-tls         4.6.1
setuptools         65.6.3
wheel              0.38.4

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
`conflict with "pulumi-resource-kubernetes" using rbac.authorization.k8s.io/v1: .rules` probably indicates that this resource was created using Client-side Apply, and now the auto-named field manager is conflicting on the `.rules` field. There are a couple possibilities for resolving:

1. Use the `pulumi.com/patchForce` annotation as suggested, which will transfer management of that field to the auto-named field manager and override the value of the `.rules` field.
2. Use the `pulumi.com/patchFieldManager` annotation to set the name of the manager to `pulumi-resource-kubernetes`. This will update the value of the resource using the existing manager name.

**Comment by lblackstone** [comment]
I think this was likely specific to the resources in that stack, and the [workarounds](https://github.com/pulumi/pulumi-kubernetes/issues/2257#issuecomment-1344510865) should resolve the problem, so I'm closing this issue.
