### ISSUE TITLE
Ability to skip resource creation if they already exist

### ISSUE THREAD

**Issue by hahasheminejad** [pulumi/pulumi-kubernetes#2275]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
We are looking for an ability to ignore the creation of k8s resources if they already exist in the Kubernetes cluster. 

The use case is installing a helm chart like Karpenter (with `k8s.helm.v3.Chart`) only on the first run. Once Karpenter is up and running, it creates worker nodes and Argocd becomes ready and it takes over the life-cycle management of all charts, Karpenter included.

The problem is we are unable to add a condition to prevent the Karpenter chart deployment if the Karpenter deployment has already at least one container running. 

We have looked into achieving such with `@pulumi/command` but that doesn't seem working pre-deployment. Alternative solution would be a flag in `k8s.helm.v3.Chart` which we can skip the step if resources already exist or at worst ignore errors.

**Comment by danielrbradley** [comment]
Hi @hahasheminejad thanks for explaining your use-case. I think this might also be captured by https://github.com/pulumi/pulumi/issues/4834 which details a similar use-case in the core way that Pulumi works, rather than specific to the k8s provider.

I'll leave this open for now though and let @lblackstone take a look as perhaps there's some more k8s specific details here that I'm not familiar with.

**Comment by lblackstone** [comment]
I think that you might be able to achieve this behavior with the [ignoreChanges](https://www.pulumi.com/docs/intro/concepts/resources/options/ignorechanges/) resource option. Here's an example of setting the resource option using a transformation for a helm chart: https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#helm-charts

I haven't tested this myself, but I think setting a wildcard `*` to ignore would prevent updates after the initial creation.

**Comment by lblackstone** [comment]
No further activity since posting the workaround, so closing this out. We can re-open if further information is available.
