### ISSUE TITLE
Helm release unable to find aws region

### ISSUE THREAD

**Issue by badaljain** [pulumi/pulumi-kubernetes#2279]
### What happened?

I am using helm release to deploy AWS rds chart and have provided aws region in the values but my pod fails to start with error as region not defined

### Steps to reproduce

```
    new k8s.helm.v3.Release("rds-chart", {
      version: "v0.1.2",
      namespace: rdsServicesNamespace.metadata["name"],
      chart: "oci://public.ecr.aws/aws-controllers-k8s/rds-chart",      
      values: {
        region: "us-east-1", // use region from config
        serviceAccount: {
          name: serviceAccountName,
          create: false,
        },
        vpcId: vpcId,
        clusterName: clusterName,
        podLabels: {
          stack: stackName,
          app: "ack-rds-controller",
        },
      },
    },
    {
      provider,
      parent: provider,
    })
```

### Expected Behavior

Chart should be deployed and pod should be started

### Actual Behavior

2022-12-31T10:53:12.610Z	ERROR	setup	Unable to create controller manager	{"aws.service": "rds", "error": "unable to start service controller as AWS region is missing. Please pass --aws-region flag or set AWS_REGION environment variable"}
main.main
	/github.com/aws-controllers-k8s/rds-controller/cmd/controller/main.go:74
runtime.main

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @badaljain, thanks for your report. This looks like a service-side issue rather than a Pulumi problem. Can you try installing the chart directly via the Helm client to see if the problem persists? Perusing [these docs](https://aws-controllers-k8s.github.io/community/docs/user-docs/install/) it looks like an environment variable might be expected.
