### ISSUE TITLE
Allow for "adopting" existing resources

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#228]
Quoting from a user [on Slack](https://pulumi-community.slack.com/archives/C84L4E3N1/p1538029820000100):

> geekflyer [11:30 PM]
> @hausdorff I’m trying to add an internal upstream dns server in kube-dns via pulumi after a gke cluster has been setup using pulumi. In order to apply the configuration I have to edit the kube-system/kube-dns configmap. Unfortunately this configmap already exists by default in every gke cluster although it’s empty (and maybe all k8s clusters?) so pulumi complains that it already exists. Is there no way I can configure this configmap using pulumi? (edited)

The answer is no, but we probably should allow this, but I'm not yet sure what that should look like. @lukehoban @joeduffy, thoughts? I can put together a proposal, but it seems like if we're doing this elsewhere, we would probably benefit by making them similar.

**Comment by hausdorff** [comment]
It seems like the basic semantics we want (in whatever the API ends up being) are:

* Keep track or the original, existing API object.
* Expose a `transforms` argument as we do in `helm.v2.Chart`.
* Every time we do `pulumi up`, `transforms` gets applied to the original API object -- the usual update/diff semantics apply, in that changing the `transforms` could trigger an `Update` if it results in an object being different.
* Critically, if we're doing a `Delete`, this does not actually remove the resource from the API server, but instead changes it back to what it was.

This approach is not without subtlety:

* Not clear if this is compatible with the idea of a replacement -- it seems like it should be, but we'll have to re-replace "back" to the original version of the resource if we ever delete the resource.
* Typically we will not control the name of the resource. That means we could potentially be doing quite a bit of delete-before-replace ... which is not amazing.
* Probably some other stuff, too.

**Comment by lukehoban** [comment]
See https://github.com/pulumi/pulumi/issues/1662.

**Comment by joeduffy** [comment]
I think this can probably be closed as a dupe. Before doing that, however, I noticed Kubernetes resources don't seem to have static `get` functions on them. Why is that? This is an essential ingredient to even being able to do manual adoption. (I vaguely recall this being an issue in the past, but thought we resolved it ...)

**Comment by hausdorff** [comment]
It wasn't implemented because I didn't know we needed to implement it.
