### ISSUE TITLE
Kubernetes secret shown in plaintext

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-kubernetes#2283]
### What happened?

if you have a Kubernetes Secret resource that already exists in a kubernetes cluster and try and use it with .get(). Any change to the secret's values will cause the diff view in the web console to show the original values in plaintext.

### Steps to reproduce

the steps to reproduce are:
1. unzip project
2. init stack with kubernetes cluster of your choice
3. kubectl apply -f ./secret.yaml
4. pulumi up
5. change stringData.secretKey in secret.yaml to have a different value
6. kubectl apply -f ./secret.yaml
7. pulumi refresh
8. pulumi preview
9. navigate to link in preview
10. click on diff view for preview run

### Expected Behavior

no show secrets in the web console in plaintext

### Actual Behavior

Show secrets in plaintext

### Output of `pulumi about`

Software Versions:
pulumi: 3.51.0
kubernetes: 3.23.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
This should be resolved by #2301. Just tried this, and I can't reproduce anymore.
