### ISSUE TITLE
Problem with URL as a Helm chart repository

### ISSUE THREAD

**Issue by hazsetata** [pulumi/pulumi-kubernetes#229]
### Problem

When trying to install a helm chart that is not in the "stable" Helm repository like this:
```
    const fluxChart = new k8s.helm.v2.Chart("flux",
            {
                repo: "https://weaveworks.github.io/flux",
                chart: "flux",
                version: "0.3.3",
                namespace: "flux"
            }
        );
```

I got an error like this:

```
    Error: Command failed: helm fetch https\://weaveworks.github.io/flux/flux --untar --version 0.3.3 -- destination /var/folders/_6/...
    Error: Failed to fetch https://weaveworks.github.io/flux/flux : 404 Not Found
```

Looking into the code of "helm.js", the "fetch" method could handle the "opts.repo" option, but the constructor merges the repo + chart name like this: `${config.repo}/${config.chart}` and doesn't use that option.

### Workaround
Add the repository to the local Helm installation. E.g. for the above case:

```
helm repo add weaveworks https://weaveworks.github.io/flux
```  

and modify the Pulumi resource definition like this:

```  
const fluxChart = new k8s.helm.v2.Chart("flux",
            {
                repo: "weaveworks",
                chart: "flux",
                version: "0.3.3",
                namespace: "flux"
            }
        );
```

**Comment by hazsetata** [comment]
Using "@pulumi/pulumi": 0.15.3, "@pulumi/kubernetes": 0.17.0

**Comment by hausdorff** [comment]
To recap the accompanying Slack conversation: this was not the intended semantics of the API, but I actually like this idea a lot, and we should consider implementing it for M18.
