### ISSUE TITLE
k8s.core.v1.Service of kind LoadBalancer `status.loadBalancer.ingress` is undefined

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-kubernetes#2315]
### What happened?

I enabled the SSA feature on my K8S provider and started getting errors on my Typescript stat:

```typescript
service.status.loadBalancer.ingress.apply(
  (ingresses) => ingresses.map((ingress) => ingress.ip)
)
```

`ingresses` in the above is `undefined`.

### Expected Behavior

`ingresses` is set to `outputs.core.v1.LoadBalancerIngress[]` representing a list of IP addresses.

### Steps to reproduce

1. Create a service with a K8S provider `enableServerSideApply: false`.
2. Attempt to extract the IP address of the LB.
3. Switch `enableServerSideApply: true`, see references to `ingress` throw an error.

### Output of `pulumi about`

```
CLI
Version      3.46.1
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  12.6.3
Arch     x86_64
```

### Additional context

Kubernetes lib `3.22.1`
Pulumi version `3.46.1`
Node version: `16.14.2`

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
I tried to reproduce this with the following program (adapted from `pulumi new kubernetes-typescript`):

```
import * as k8s from "@pulumi/kubernetes";
import * as kx from "@pulumi/kubernetesx";

const provider = new k8s.Provider("local", { enableServerSideApply: false });

const appLabels = { app: "nginx" };
const deployment = new k8s.apps.v1.Deployment("nginx", {
    spec: {
        selector: { matchLabels: appLabels },
        replicas: 1,
        template: {
            metadata: { labels: appLabels },
            spec: { containers: [{ name: "nginx", image: "nginx" }] }
        }
    }
}, { provider });

const service = new k8s.core.v1.Service("nginx", {
    spec: {
        selector: appLabels,
        'type': "LoadBalancer",
        ports: [{name: 'http", port: 80}, {name: 'https', port: 443}],
    },
}, { dependsOn: [deployment], provider });

export const ips = service.status.loadBalancer.ingress.apply(
  (ingresses) => ingresses.map((ingress) => ingress.ip)
);

export const name = deployment.metadata.name;
```

In fact, I get an output

```
ips : [                                                                                                                                                                                                           
        [0]: <null>                                                                                                                                                                                                   
    ]                                                                                                                                                                                                                 
    name: "nginx-cf14b235"
```

because it turns out my Docker Desktop cluster gives the ingresses with hostnames:

```
$ kubectl get service nginx-b1c41cc5 -oyaml
# ...
status:
  loadBalancer:
    ingress:
    - hostname: localhost
```

Changing `enableServerSideApply: false` to `enableServerSideApply: true` didn't make a difference to the output.

Are you able to provide the program that shows the problem?

**Comment by KaoruDev** [comment]
yep:

```typescript
const service = new k8s.core.v1.Service(
  "test-service",
  {
    metadata: {
      annotations: {
        "networking.gke.io/load-balancer-type": "Internal",
      },
    },
    spec: {
      type: "LoadBalancer",
      selector: {
        app: "nginx"
      },
      ports: [
        {
          port: 6543,
          targetPort: 6543,
          protocol: "TCP",
        },
      ],
    },
  }
);

const ipAddresses = service.status.loadBalancer.ingress.apply(
  (ingresses) => ingresses.map((ingress) => ingress.ip)
)
 ```
 
 Something I forgot to mention is that my K8S cluster a GKE Autopilot cluster.

**Comment by squaremo** [comment]
Looks pretty similar! I wonder if it's something particular to the load balancer service in GKE ..
Are you putting `kubernetes:enableServerSideApply` in your config?

**Comment by KaoruDev** [comment]
> I wonder if it's something particular to the load balancer service in GKE

Yah, sounds suspect

> Are you putting kubernetes:enableServerSideApply in your config?

Here's the provider I'm using:

```typescript
export class SSAProvider extends k8s.Provider {
  public readonly namespace: string;

  constructor(
    {
      clusterName,
      endpoint,
      clusterCaCert,
      namespace = "default",
    }: ProviderArgs,
    opts: ResourceOptions = {}
  ) {
    const kubeconfig = kubeConfigTemplate(clusterName, endpoint, clusterCaCert);
    super(
      `${namespace}-k8s-ssa-provider`,
      { kubeconfig, namespace, enableServerSideApply: true },
      opts
    );
    this.namespace = namespace;
  }
}
```

Then setting `{ providers: { kubernetes: ssaProvider }}` as the Service's parent Component Resources Option

**Comment by squaremo** [comment]
What do you see in the service's .status if you look with `kubectl get service -oyaml`? Has it just removed that field entirely..

**Comment by KaoruDev** [comment]
The existing `services` has:

```yaml
status:
  loadBalancer:
    ingress:
    - ip: 1.1.1.1
```

However, the issue is when I swap it out for the SSAProvider and the service is planned to be replaced, the code block:

```typescript
const ipAddresses = service.status.loadBalancer.ingress.apply(
  (ingresses) => ingresses.map((ingress) => ingress.ip)
)
```

fails, because the `ingresses` is `undefined`. I suspect it's because the GKE controller hasn't provisioned the LB yet and therefore there are no IP addresses to publish but not sure how that works with a new service and the client-side apply provider? Idk if is making any sense so please ignore if it doesn't.

**Comment by jkodroff** [comment]
I'm also hitting this issue with a GKE cluster. The following will only pass with `enable_server_side_apply: False` on k8s Provider v4 as server-side apply is now the default:

```python
import pulumi_kubernetes as k8s

k8s_provider = k8s.Provider(
    "k8s-provider",
    k8s.ProviderArgs(
        kubeconfig=cluster_kubeconfig,
        enable_server_side_apply=False,
    )
)

deployment = k8s.apps.v1.Deployment(
    "nginx-deployment",
    metadata={
        "name": "nginx-deployment",
        "labels": {
            "app": "nginx"
        },
    },
    spec={
        "replicas": 1,
        "selector": {"matchLabels": {"app": "nginx"}},
        "template": {
            "metadata": {"labels": {"app": "nginx"}},
            "spec": {
                "containers": [{
                    "name": "nginx",
                    "image": "nginx:1.25.2",
                    "ports": [{"containerPort": 80}],
                }]
            },
        },
    },
    opts=pulumi.ResourceOptions(
        provider=k8s_provider
    )
)

service = k8s.core.v1.Service(
    "nginx-service",
    metadata=k8s.meta.v1.ObjectMetaArgs(
        name="nginx-service"
    ),
    spec=k8s.core.v1.ServiceSpecArgs(
        ports=[k8s.core.v1.ServicePortArgs(
            port=80,
            target_port=80
        )],
        selector={
            "app": "nginx"
        },
        type="LoadBalancer"
    ),
    opts=pulumi.ResourceOptions(
        provider=k8s_provider
    )
)

pulumi.export("ingress_up", service.status.load_balancer.ingress[0].ip)
```

I'm not sure whether this can be fixed per se since this seems to be particular to GKE, but it would be good to document it in a prominent place since if I'm hitting this working on a K8s intro workshop, it's probably a common issue.

It looks like GKE is returning before the LB has actually been provisioned.

**Comment by rquitales** [comment]
Looks like this is due to handling of unknown fields in SSA dry run when we do preview. A workaround for now would be to just run `pulumi up --skip-preview`, ie. skip preview.

Related: https://github.com/pulumi/pulumi-kubernetes/issues/2577

**Comment by jkodroff** [comment]
@rquitales Per Slack request, the error I get is basically that `loadBalancer` (or status? - I forget) is NoneType. It's pretty obvious from running the stack that GKE is returning before the IP address is actually provisioned. IIRC, if you don't attempt to export the IP, wait a bit, and then export it, the code will work fine (again, with SSA turned on - works fine with it turned off).

**Comment by jkodroff** [comment]
@rquitales Per Slack request, the error I get is basically that `loadBalancer` (or status? - I forget) is NoneType. It's pretty obvious from running the stack that GKE is returning before the IP address is actually provisioned. IIRC, if you don't attempt to export the IP, wait a bit, and then export it, the code will work fine (again, with SSA turned on - works fine with it turned off).
