### ISSUE TITLE
aws-load-balancer-controller Helm error: Chart.yaml file is missing for ingress-nginx

### ISSUE THREAD

**Issue by gencube** [pulumi/pulumi-kubernetes#2328]
### What happened?

// https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller
Helm CLI installation is working with simple command:
$ helm repo add eks https://aws.github.io/eks-charts
$ helm install aws-load-balancer-controller eks/aws-load-balancer-controller --version 1.4.6 --set clusterName=eksCluster-xxxyyyzzz -n kube-system 
NAME: aws-load-balancer-controller
LAST DEPLOYED: Fri Feb 24 12:19:51 2023
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
AWS Load Balancer controller installed!
$  helm history aws-load-balancer-controller -n kube-system
REVISION        UPDATED                         STATUS          CHART                                   APP VERSION     DESCRIPTION
1               Fri Feb 24 12:19:51 2023        deployed        aws-load-balancer-controller-1.4.6      v2.4.5          Install complete

---

```
// https://github.com/aws/eks-charts/tree/master/stable/aws-load-balancer-controller
	const release = new k8s.helm.v3.Release('aws-load-balancer-controller', {
		// name: name,
		chart: "aws-load-balancer-controller",
		version: "1.4.6",
		namespace: "kube-system",
		repositoryOpts: {
			repo: "https://aws.github.io/eks-charts",
		},
		// https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml
		values: {
			clusterName: 'eksCluster-xxxyyyzzz',			
			podAnnotations: {
				"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
			}
		},
	});

```
----
Pulumi up shows:
```bash
Updating (myorg/mystack-paws)

View Live: https://app.pulumi.com/myorg/myapp/mystack-paws/updates/15

     Type                              Name                          Status                  Info
     pulumi:pulumi:Stack               myapp-mystack-paws           **failed**              1 error; 1 message
 +   └─ kubernetes:helm.sh/v3:Release  aws-load-balancer-controller  **creating failed**     1 error


Diagnostics:
  pulumi:pulumi:Stack (myapp-mystack-paws):
    error: update failed

    aws-load-balancer-controller/index>config.eks.clusterName: eksCluster-xxxyyyzzz

  kubernetes:helm.sh/v3:Release (aws-load-balancer-controller):
    **error: Chart.yaml file is missing**

Resources:
    3 unchanged

Duration: 7s
```

### Expected Behavior

Able to install just like in Helm CLI.

### Steps to reproduce

pulumi up --yes -s myorg/mystack-paws

### Output of `pulumi about`

CLI
Version      3.55.0
Go Version   go1.20
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/ubuntu/.nvm/versions/node/v18.13.0/bin/node' version='v18.13.0'

### Additional context
```json
package.json
{
    "name": "myapp-infra",
    "devDependencies": {
        "@types/js-yaml": "^4.0.5",
        "@types/node": "^18"
    },
    "dependencies": {
        "@pulumi/aws": "^5.25.0",
        "@pulumi/awsx": "^1.0.1",
        "@pulumi/eks": "^1.0.1",
        "@pulumi/kubernetes": "^3.23.1",
        "@pulumi/kubernetesx": "^0.1.6",
        "@pulumi/pulumi": "^3.51.1",
        "@pulumi/random": "^4.8.2",
        "js-yaml": "^4.1.0"
    }
}
```
----

pulumi version
v3.55.0
----
```bash
npm list:
├── @pulumi/aws@5.27.0
├── @pulumi/awsx@1.0.1
├── @pulumi/eks@1.0.1
├── @pulumi/kubernetes@3.24.1
├── @pulumi/kubernetesx@0.1.6
├── @pulumi/pulumi@3.51.1
├── @pulumi/random@4.8.2
├── @types/js-yaml@4.0.5
├── @types/node@18.11.15
└── js-yaml@4.1.0
```
### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @gencube, sorry for the trouble. What kind of K8s cluster are you running this against, i.e., what's in your kubeconfig (that you can share)?

I just tried to repro locally and it failed with a timeout after five minutes, but that was against Minikube so it might be expected.

**Comment by thomas11** [comment]
Hi @gencube, I got your email and can confirm I'm getting this error when I run your steps.
```
kubernetes:helm.sh/v3:Release (zookeeper):
    error: chart "zookeeper" matching 11.1.3 not found in bitnami index.
```

I don't see the `Chart.yaml file is missing`, though.

**Comment by thomas11** [comment]
Ah, that was just because I needed to `helm repo update`. I get the Chart.yaml error now.

**Comment by thomas11** [comment]
Argh, so I tried to debug this, only for it to work fine when running in the debugger. This needs a fresh look next week.

**Comment by rquitales** [comment]
Hey @gencube 

So I've noticed 2 issues:
For the bitnami Zookeeper unable to find chart issue, the following code snippet should work:
```
const release = new k8s.helm.v3.Release("zookeeper", {
		name: "zookeeper",
		chart: "zookeeper",
		version: "11.1.4",
		namespace: namespace,
		repositoryOpts: {
			repo: "https://charts.bitnami.com/bitnami",
		},
		values: {
			controller: {
				replicaCount: 2,
				service: {
					type: "ClusterIP",
					enableHttps: false,
				},
			},
		},
	});
```
Note that chart is `chart: "zookeeper"` not `chart: "bitnami/zookeeper"`. Here, we're specifying Pulumi to use the `zookeeper` chart from the remote `https://charts.bitnami.com/bitnami` repo, so we need to omit the `bitnami/` prefix.

`chart: "bitnami/zookeeper"` works when `repositoryOpts` is commented out because Pulumi/Helm will search the local helm repository list to find the specified chart since a remote repository isn't specified.

For example, running these will also work:
```
helm repo add foobar https://charts.bitnami.com/bitnami
```
```
# Pulumi code
const release = new k8s.helm.v3.Release("zookeeper", {
		name: "zookeeper",
		chart: "foobar/zookeeper",
		version: "11.1.4",
		namespace: namespace,
		values: {
			controller: {
				replicaCount: 2,
				service: {
					type: "ClusterIP",
					enableHttps: false,
				},
			},
		},
	});
```
In this case, Pulumi will attempt to find the `zookeeper` chart in the `foobar` repo we added manually using Helm CLI.

---

For the `Chart.yaml file is missing` error, can you ensure that you do not have a folder created called `aws-load-balancer-controller` in your working directory? A current limitation is that we cannot have a folder existing with the same name as a chart since the upstream Helm code does a file path check:
https://github.com/helm/helm/blob/e007c900ce5f2233c8583565d5ba1b0433b1a213/pkg/action/install.go#L688

This function will then attempt to load the local folder as a Helm chart, rather than attempting to fetch the chart from remote, thus reporting that a `Chart.yaml` isn't found.

Here's a minimal example to reproduce using the zookeeper example:

```
mkdir zookeeper
```
```
# Pulumi code
const release = new k8s.helm.v3.Release("zookeeper", {
		name: "zookeeper",
		chart: "zookeeper",
		version: "11.1.4",
		namespace: namespace,
		repositoryOpts: {
			repo: "https://charts.bitnami.com/bitnami",
		},
                 values: {
			controller: {
				replicaCount: 2,
				service: {
					type: "ClusterIP",
					enableHttps: false,
				},
			},
		},
	});

# This is expected to fail since ./zookeeper/ folder is empty.
```

**Comment by rquitales** [comment]
@gencube Glad to hear that this solved your issues. Yes, I am currently in the process of drafting an update to our docs to make this clearer for users. Thanks for your feedback!

**Comment by mnlumi** [comment]
@rquitales Is there a PR or different issue for the docs update?
