### ISSUE TITLE
Support OCI helm chart repositories

### ISSUE THREAD

**Issue by kovaxur** [pulumi/pulumi-kubernetes#2334]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like to install a helm chart, which is in an OCI registry, but it's not supported:
```
failed to pull chart: looks like "oci://public.ecr.aws/karpenter/karpenter" is not a valid chart repository or cannot be reached: object required
```

As I saw, there were some initial steps to support OCI, but I can't find any information about this in the documentation.

### Affected area/feature

kubernetes.helm.v3.Chart

**Comment by squaremo** [comment]
Hey, thank you for logging this. I know OCI charts are supported for `helm.v3.Release`, and that's superior to `helm.v3.Chart` in some ways ([this blog post explains some of them](https://www.pulumi.com/blog/full-access-to-helm-features-through-new-helm-release-resource-for-kubernetes/), since it does what Helm does. If you can use `helm.v3.Release` that might work better anyway.

It's not clear to me whether helm.v3.Chart should support OCI charts (but I suspect it doesn't). Could you post the code you're trying?

**Comment by kovaxur** [comment]
Hi,
The code is pretty basic:
```
import * as k8s from "@pulumi/kubernetes";

new k8s.helm.v3.Chart("karpenter", {
    chart: "karpenter",
    version: "0.26.x",
    fetchOpts:{
        repo: "oci://public.ecr.aws/karpenter/karpenter",
    },
});
```

I tried with helm.v3.Release but got the same result, maybe I missed something, but I haven't seen much documentation on this, just some old issues.

Thanks

**Comment by lblackstone** [comment]
https://github.com/pulumi/pulumi-kubernetes/issues/1914#issuecomment-1293607790

> It's not clear to me whether helm.v3.Chart should support OCI charts (but I suspect it doesn't).

Yeah, OCI is only supported for `helm.v3.Release` at this time.

**Comment by kovaxur** [comment]
Hi @amkartashov 
Thanks, it's working. For me the documentation was not that clear, maybe it would worth to add an example with OCI to the pulumi registry manual.

**Comment by ecerulm** [comment]
Just to clarify, if using OCI helm chart, **do not use repoOpts / repository_opts** instead use the full  OCI url in the `chart` field like. `chart="oci://public.ecr.aws/karpenter/karpenter"`

**Comment by amkartashov** [comment]
> Is there a way to provide credentials to access OCI repositories?

Try to run `helm registry login` before running pulumi.
