### ISSUE TITLE
How to install EXACTLY ONCE for some selected resources for example: aws alb, ingress controller, EFS driver and Storage class

### ISSUE THREAD

**Issue by gencube** [pulumi/pulumi-kubernetes#2338]
### What happened?

![image](https://user-images.githubusercontent.com/663792/225889236-1f321332-df85-4440-bd76-88315d97267b.png)
![image](https://user-images.githubusercontent.com/663792/225889287-56336d87-0041-40ff-8fbc-92787ce0cef5.png)

### Expected Behavior

Since aws alb, ingress controller, EFS driver and Storage class are suppose to be created exactly once,
there should be away to properly check their existance in the k8s/EKS environments without causing any error.

Run pulumi up --yes multiple times without causing any error.

Should be able to run multiple time without any error.

### Steps to reproduce

 just run pulumi up --yes multiple times.

![image](https://user-images.githubusercontent.com/663792/225890124-b846419b-1bf3-446c-b25e-2eb64f6f16a0.png)
![image](https://user-images.githubusercontent.com/663792/225890164-b12c4d9e-4f5a-45d1-baa1-0cac8b6358e7.png)
![image](https://user-images.githubusercontent.com/663792/225890225-854de77c-9bbf-4346-8051-05a4c449073f.png)
![image](https://user-images.githubusercontent.com/663792/225890084-5ce82216-94c2-4ec3-afb8-f9f127cf128c.png)
![image](https://user-images.githubusercontent.com/663792/225890292-0dd03cc8-3512-4b20-bd9b-5f4ba33663f0.png)

### Output of `pulumi about`

![image](https://user-images.githubusercontent.com/663792/225888289-1a8ae8c3-fcef-4f07-82a0-b9ddbdccdec0.png)
![image](https://user-images.githubusercontent.com/663792/225888366-22bd9051-2116-4f09-a7c7-a1d7a5f33989.png)
![image](https://user-images.githubusercontent.com/663792/225888437-1a03f6e3-6f20-4b28-bcda-ea8527e82aff.png)

### Additional context

Please send give an email for me to disclose the full source code to reproduce the error.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
The model for Pulumi programs is that you declare the resources you want to exist, and pulumi makes sure they exist and match your specifications. You don't usually need to have code in your program for figuring out whether a resource already exists, and doing something different, because pulumi figures that out for you. (For a more precise explanation, see https://www.pulumi.com/docs/intro/concepts/).

Have I misunderstood what you're trying to do?

**Comment by danielrbradley** [comment]
Hi @gencube you might have more success asking these kinds questions in the community slack. It's not clear from an an intial read of the issue if something's misbehaving in the provider of within your program. Please can you provide a minimal program that reproduces the issue you're experiencing?
