### ISSUE TITLE
adding namespace to ChartOpts throws Preview Error

### ISSUE THREAD

**Issue by rshade** [pulumi/pulumi-kubernetes#2348]
### What happened?

When I add namespace to ChartOpts in python I get the following error:
```
venv/lib/python3.8/site-packages/pulumi_kubernetes/helm/v3/helm.py", line 457, in <lambda>
        lambda x: json.dumps(x, default=lambda o: {k: v for (k, v) in o.__dict__.items() if v is not None}))
    AttributeError: 'set' object has no attribute '__dict__'
```

### Expected Behavior

It should not throw a preview error. 

### Steps to reproduce

Create a chart resource with ChartOps and set the namespace

### Output of `pulumi about`

```
Plugins
NAME          VERSION
aws           5.33.0
cloudinit     1.3.0
datadog       4.12.0
gcp           6.51.0
kubernetes    3.24.2
python        unknown
random        4.12.0
tls           4.10.0
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by danielrbradley** [comment]
Thanks for reporting @rshade, if you have a code snippet that reproduces this issues reliably that'd be great for helping us sove this quicker.

**Comment by rshade** [comment]
```
"""An AWS Python Pulumi program"""

import pulumi
import pulumi_aws as aws
import pulumi_awsx as awsx
import pulumi_eks as eks
import pulumi_kubernetes as kube
from pulumi_kubernetes.helm.v3 import Chart, ChartOpts, FetchOpts
from cluster.cluster import Cluster
from traefik.traefik import Traefik

vpc = awsx.ec2.Vpc(
    "my-vpc",
    number_of_availability_zones=3,
    nat_gateways=1
)

# Create an EKS cluster with the default configuration.
cluster = eks.Cluster(
    "test-cluster",
    private_subnet_ids=vpc.private_subnet_ids,
    public_subnet_ids=vpc.public_subnet_ids
)

k8s_provider = kube.Provider("k8s_provider",
    kubeconfig = cluster.kubeconfig
)

dd_namespace = kube.core.v1.Namespace(
    resource_name="datadog-namespace",
    metadata=kube.meta.v1.ObjectMetaArgs(
        name="datadog"
    ),
    opts=pulumi.ResourceOptions(
        provider=k8s_provider,
    )
)

chart_opts = ChartOpts(
            fetch_opts=FetchOpts(repo="https://helm.datadoghq.com"),
            repo="datadog",
            chart="datadog",
            version="3.25.1",
            namespace=dd_namespace,
    )

chart = Chart(
    release_name="datadog",
    config=chart_opts,
    opts=pulumi.ResourceOptions(
        provider=k8s_provider,
    )
)
# Export the cluster's kubeconfig.
pulumi.export("kubeconfig", cluster.kubeconfig)
```

**Comment by rquitales** [comment]
Looking into this, it appears that there is an error with how the namespace is being used in ChartOpts. To use the computed name of a namespace object, you'd need to reference either it's ID (`dd_namespace.id`), or name (`dd_namespace.metadata.name`). This is also similar in our language SDKs.

eg:
```
chart_opts = ChartOpts(
            fetch_opts=FetchOpts(repo="https://helm.datadoghq.com"),
            repo="datadog",
            chart="datadog",
            version="3.25.1",
            namespace=dd_namespace.id,
    )
```

Example reference:
https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/aks/#access-the-kubernetes-cluster-using-pulumi-providers

Since this is a runtime/compilation error in processing application code, I'm not sure if we could improve the error messaging here. Ideally, this issue should have been picked up by the IDE/type checking.
