### ISSUE TITLE
it's not possible to alias a pulumi_kubernetes.yaml.ConfigFile resource

### ISSUE THREAD

**Issue by doy-materialize** [pulumi/pulumi-kubernetes#2356]
### What happened?

i tried to add an aliases option to an existing ConfigFile resource, but i get errors like `error: Duplicate resource alias 'urn:pulumi:doy::mzcloud::mzcloud:regions:Region/us-east-1$mzcloud:eks2/mzcloud-doy-us-east-1-0:Cluster2$mzcloud:mzcloud-doy-us-east-1-0:CertManager$kubernetes:yaml:ConfigFile::cert-manager-crds' applied to resource with URN 'urn:pulumi:doy::mzcloud::mzcloud:tls:CertManager/mzcloud-doy-us-east-1-0-cert-manager$kubernetes:yaml:ConfigFile$kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition::certificaterequests.cert-manager.io' conflicting with resource with URN 'urn:pulumi:doy::mzcloud::mzcloud:tls:CertManager/mzcloud-doy-us-east-1-0-cert-manager$kubernetes:yaml:ConfigFile::mzcloud-doy-us-east-1-0-cert-manager-crds'`. this seems to be because the ConfigFile component resource passes in the given `opts` value to all of its children literally, which means that the alias given applies to each of the subresources as well, causing conflicts.

### Expected Behavior

i should be able to alias a ConfigFile resource the same way as any other resource

### Steps to reproduce

i have a resource that looks like this
```
        k8s.yaml.ConfigFile(
            "cert-manager-crds",
            file=f"https://github.com/jetstack/cert-manager/releases/download/{cert_manager_version}/cert-manager.crds.yaml",
            opts=pulumi.ResourceOptions(
                parent=self,
                provider=cluster.provider,
            ),
        )
```

and i tried to add an `aliases=[f"urn:pulumi:<...>"]` option to the ResourceOptions

### Output of `pulumi about`

```
CLI
Version      3.58.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME             VERSION
aws              5.30.0
cloudinit        1.3.0
command          0.7.1
crds             0.0.0
docker-buildkit  0.1.21
fivetran         0.1.6
frontegg         0.2.24
honeycomb        0.0.15
kubernetes       3.24.2
python           unknown
random           4.8.2
tls              4.10.0

Host
OS       arch
Version
Arch     x86_64

This project is written in python: executable='/home/doy/materialize/cloud/venv/bin/python3' version='3.10.10
'

Current Stack: materialize/mzcloud/doy

[...]

Found no pending operations associated with materialize/doy

Backend
Name           pulumi.com
URL            https://app.pulumi.com/doy-materialize-com
User           doy-materialize-com
Organizations  doy-materialize-com, materialize

Pulumi locates its logs in /tmp by default
warning: Failed to get information about the Pulumi program's dependencies: illegal semver returned by language host: mypy-boto3-ec2@1.26.97.post1: Invalid character(s) found in patch number "97.post1"
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hi @doy-materialize - thank you for reporting this issue, and providing a reproduction!  I agree that this seems like a bug, and looking at the implementation of `ConfigFile`, it appears we're passing `opts` directly to children, which would include aliases, hence the conflicts here. My initial best-guess at a solution is for us to not pass opts down to children resources at all here: https://github.com/pulumi/pulumi-kubernetes/blob/9b7eeaeffdc6ea178eba5e8a00954d0042a0333c/sdk/python/pulumi_kubernetes/yaml/yaml.py#L492-L1924, which would cause the engine to re-compute child aliases appropriately. We'll get this lined up for a fix as soon as we can. Thanks again!
