### ISSUE TITLE
configured Kubernetes cluster is unreachable: unable to load schema information from the API server Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by tusharshahrs** [pulumi/pulumi-kubernetes#2365]
### What happened?

Question about pulumi-kubernetes. We occasionally receive this error when interacting with GKE clusters:
```
Diagnostics:
  kubernetes:networking.gke.io/v1alpha1:NetworkLoggingPatch (my-network-logging):
    error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://35.203.171.106/openapi/v2?timeout=32s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

Default timeout of 32s comes from here: https://github.com/kubernetes/client-go/blob/8005e0d28ba2db8a60bb8dbe8a5a01fed4872f67/discovery/discovery_client.go#L55
`defaultTimeout = 32 * time.Second`

Looks like this would be the place to expose a custom timeout for the entirety of the [k8s.io/client-go](http://k8s.io/client-go) package: https://github.com/pulumi/pulumi-kubernetes/blob/5f9eaba96f8749d328e56cb63073cc9e3c3bcd2e/provider/pkg/provider/provider.go#L405-L411. Not sure what the negative implications of this would be, if any. There also seem to be two environment variables we could leverage deep in the [k8s.io/client-go](http://k8s.io/client-go) package: `KUBE_CLIENT_BACKOFF_BASE` and `KUBE_CLIENT_BACKOFF_DURATION`.

Got this again:
```
Diagnostics:
  kubernetes:apps/v1:DaemonSet (my-certs):
    error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://34.168.76.74/openapi/v2?timeout=32s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

  kubernetes:networking.k8s.io/v1:NetworkPolicy (my-gke-all-metrics-from-all):
    error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://34.168.76.74/openapi/v2?timeout=32s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

  kubernetes:networking.gke.io/v1alpha1:NetworkLoggingPatch (my-network-logging):
    error: configured Kubernetes cluster is unreachable: unable to load schema information from the API server: Get "https://34.168.76.74/openapi/v2?timeout=32s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)

  pulumi:pulumi:Stack (gcp-gke-node-pool-test-8cabcdef):
    error: update failed
```

### Expected Behavior

I just noticed that it is possible to set timeouts per resource via resource option. I’ll see if this is the only resource that times out like this. If so, then this is fine — but if I must decorate every resource, I’ll be looking for a better way to set this at the provider level.

### Steps to reproduce

pending

### Output of `pulumi about`

pending

### Additional context

- Where does this timeout value come from? 
- Is there a way to increase it via environment variables? There don’t appear to be any provider-specific toggles.
- From what I did gather while scanning the [k8s.io/client-go](http://k8s.io/client-go) source, it has a fairly constrained approach to automatically retrying requests. I’m not sure that it automatically retries timeouts, so the backoff base and duration that I mentioned above may not apply. I think the solution to this issue involves two changes:
1.  The pulumi-kubernetes provider should expose an optional parameter on the provider enabling it to override the default timeout value set by [k8s.io/client-go](http://k8s.io/client-go).
1. If automatic retry logic does not exist for query/idempotent requests, retry logic should be added. If retry logic does exist, perhaps its behavior could be exposed as parameters on the provider (i.e. # of retry attempts, backoff base, backoff duration)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @tusharshahrs Thank you for the detailed issue. Do you think it's the same question as in https://github.com/pulumi/pulumi-kubernetes/issues/1839?

**Comment by tusharshahrs** [comment]
Hi @mikhailshilkov,
  Looking at the error, it seems the same.
