### ISSUE TITLE
kubectl 'exec' and 'cp' equivalent

### ISSUE THREAD

**Issue by saada** [pulumi/pulumi-kubernetes#237]
I would like to be able to exec some code on-demand. This is especially relevant for use-cases where I want to use pulumi to build kubernetes operators.

# Proposed APIs

## `exec`

```ts
// concat stream buffers into entire output strings
const pods = await deployment.getPods()
const {stdout, stderr} = await pods[0].exec("echo", ["hello", "world"])
console.log(stdout, stderr)
```

## `execStream`

```ts
const pods = await deployment.getPods()
const {stdout, stderr} = pods[0].execStream("echo", ["hello", "world"])
stdout.pipe(process.stdout)
stderr.pipe(process.stderr)
```

## `cp`

```ts
import fs from 'fs'
const pods = await deployment.getPods()
const readStream = fs.createReadStream('myfile.txt')
await pods[0].cp(readStream, "/tmp/myfile.txt")

// or from an inline string
import { Readable } from 'stream'
const inlineStream = new Readable()
const inlineFile = `
#!/bin/bash
echo hello world
`
inlineFile.split('\n').forEach(line => inlineStream.push(line))
inlineStream.push(null)
await pods[0].cp(inlineStream, "/tmp/myfile.txt")
```

**Comment by hausdorff** [comment]
I've been thinking a lot about this sort of thing too. I think it's super useful, but a key question for me is how this fits into the rest of Pulumi -- the rest of the SDK is highly declarative, and opening the door to imperative APIs that let you mutate existing resources is a huge leap, and one we should  consider carefully before committing to. I'll be playing with it more over the next couple months, after which I expect to have stronger opinions.

In the meantime, [the official Kubernetes JavaScript client](https://github.com/kubernetes-client/javascript) offers these things out of the box. It should be feasible to use this stuff with Pulumi, which should bridge the gap in the short term.

**Comment by saada** [comment]
Thanks @hausdorff ... In the meantime, I created this: https://github.com/kubernetes-client/javascript/issues/124

**Comment by yellowhat** [comment]
Are there any update in this?
Thanks

**Comment by lblackstone** [comment]
Adding this to the Kubernetes provider has not been prioritized, but I believe all of the original use cases can be covered with the use of the [pulumi-command provider](https://github.com/pulumi/pulumi-command), or by using the [Automation API[(https://www.pulumi.com/docs/guides/automation-api/).

**Comment by lblackstone** [comment]
We don't have any current plans to add this directly to pulumi-kubernetes. You can run the `kubectl` commands directly using `pulumi-command`, or use a k8s client library with Automation API to address these use cases.
