### ISSUE TITLE
Helm: Cannot install local charts

### ISSUE THREAD

**Issue by geekflyer** [pulumi/pulumi-kubernetes#238]
currently the helm integration always assumes the chart is in a remote repository. However it is not uncommon to simply specify a local chart path.
A prominent example for where this actually required is to install istio https://istio.io/docs/setup/kubernetes/helm-install/ because istio is currently not published to any chart repo.

Please add support to install a chart from a local directory or file by specifying a filepath and skip the fetch step for those.

**Comment by saada** [comment]
It could also use the same notation as Helm itself. 
```
file://../my-helm-chart-directory
```

**Comment by hausdorff** [comment]
It's a good idea, I'm hoping to get to it next week.

**Comment by hausdorff** [comment]
Let's move this to M19, and fix at the same time as #229.
