### ISSUE TITLE
TokenRequest resource fails with weird error.

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/pulumi-kubernetes#2412]
### What happened?

K8s cluster running 1.26.
I have a simple program to create a token:
```
const namespaceName = "my-namespace";

const namespace = new k8s.core.v1.Namespace(namespaceName, {
  metadata: { name: namespaceName },
});
const myServiceAccount = new k8s.core.v1.ServiceAccount("my-serviceaccount", {
  metadata: {
    name: "my-serviceaccount",
    namespace: namespace.metadata.name,
  },
});
const tokenRequest = new k8s.authentication.v1.TokenRequest("my-token", {
    metadata: {
      name: myServiceAccount.metadata.name.apply(name => `${name}-token`),
      namespace: myServiceAccount.metadata.namespace,
    },
    spec: {
      audiences: ["my-audience"],
    },
}, {dependsOn: [myServiceAccount]});
```

Running pulumi up produces this error:
```
kubernetes:authentication.k8s.io/v1:TokenRequest (my-token):
    error: creation of resource my-namespace/my-serviceaccount-token failed because the Kubernetes API server reported that the apiVersion for this resource does not exist. Verify that any required CRDs have been created: no matches for kind "TokenRequest" in version "authentication.k8s.io/v1"
```

Running
```
kubectl create token my-serviceaccount
```
works

### Expected Behavior

There should not be an error.

As per @lblackstone:
```
The CRD part of the message doesn’t apply; this error occurs if the k8s apiserver doesn’t recognize the apiVersion of the resource in the request, which commonly happens for CustomResources that haven’t had their matching CRD applied yet. In this case, the apiVersion does appear to be registered already, so I’m not sure why it’s not finding it.
```

### Steps to reproduce

1. Stand up a 1.24 or later K8s cluster
2. Run the code given above.
3. See error.

### Output of `pulumi about`

CLI          
Version      3.67.1
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  3.27.1
nodejs      unknown

Host     
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in nodejs: executable='/Users/mitch/.nvm/versions/node/v18.0.0/bin/node' version='v18.0.0'

TYPE                               URN
pulumi:pulumi:Stack                urn:pulumi:dev::token-stuff::pulumi:pulumi:Stack::token-stuff-dev
pulumi:providers:kubernetes        urn:pulumi:dev::token-stuff::pulumi:providers:kubernetes::default_3_27_1
kubernetes:core/v1:Namespace       urn:pulumi:dev::token-stuff::kubernetes:core/v1:Namespace::my-namespace
kubernetes:core/v1:ServiceAccount  urn:pulumi:dev::token-stuff::kubernetes:core/v1:ServiceAccount::my-serviceaccount

Found no pending operations associated with dev

Backend        
Name           pulumi.com

Dependencies:
NAME                 VERSION
@pulumi/kubernetes   3.27.1
@pulumi/kubernetesx  0.1.6
@pulumi/pulumi       3.67.1
@types/node          16.18.30

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Hey @MitchellGerdisch - thanks for opening this issue. I've added it to our tracking epic for the quarter pending some RCA to determine the effort required to resolve it.

Thanks again!

**Comment by rquitales** [comment]
It looks like we need special handling for `TokenRequest`, as it is not actually a Kubernetes resource, but rather, a subresource under a service account object ([TokenRequest design doc](https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/1205-bound-service-account-tokens/README.md#design-details)).
[Link](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#tokenrequest-api) to Kubernetes documentation describing this endpoint being a subresource.
[client-go typed method](https://github.com/kubernetes/client-go/blob/v0.27.1/kubernetes/typed/core/v1/serviceaccount.go#L214) showing how a token could be created.

**Comment by rquitales** [comment]
Upon further discussion, as TokenRequest is an imperative API endpoint, we've decided to remove support for this in #2413. Historically, pulumi-kubernetes did not support imperative endpoints, so the decision was to continue on the same path for TokenRequest as well.

The current intention would be for users to still manage other declarative resources using Pulumi, but manage one-off token creation like this using a separate toolchain, eg. `kubectl`. An example workflow would thus be: `pulumi_command> + `kubectl create token`
