### ISSUE TITLE
Regression around local chart .tar.gz files

### ISSUE THREAD

**Issue by ffMathy** [pulumi/pulumi-kubernetes#2426]
### What happened?

Before #2410, local chart `.tar.gz` files could be loaded. Now it has to be an extracted chart.

### Expected Behavior

N/A

### Steps to reproduce

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by kpitzen** [comment]
Ack - I'll create the doc and set the meeting. @rquitales could you please fill the doc out once it's created, and lead the postmortem itself?

**Comment by ffMathy** [comment]
This broke again in https://github.com/pulumi/pulumi-kubernetes/pull/2532.

Are there no tests for this? Why does this keep breaking?

CC @mikhailshilkov @kpitzen

**Comment by lblackstone** [comment]
I'll take a look at this today and figure out why it regressed again. Sorry for the trouble!

**Comment by lblackstone** [comment]
@ffMathy 

> The regression is around using extracted helm charts (so folders) as paths.

https://github.com/pulumi/pulumi-kubernetes/tree/v4.1.1/tests/sdk/go/helm-release-local/step1 covers this scenario, and I wasn't able to reproduce the reported regression on my end in this case either.

My best guess is that you're somehow running an older version of the provider code, perhaps related to a replacement that was triggered by the change in #2532. If you need further help troubleshooting, I think it would be easier to track down on slack.

**Comment by ffMathy** [comment]
Thank you. For now, I have just switched to the compressed format.

Sorry for the inconvenience this report may have caused in that case. You guys rock.
