### ISSUE TITLE
CustomResource is treated as a patch resources based on CR name

### ISSUE THREAD

**Issue by caioaao** [pulumi/pulumi-kubernetes#2433]
### What happened?

If you use `kubernetes.apiextensions.CustomResource` to provision a resource that has `kind` ending with `Patch`, pulumi assumes it's a patch resource. In my case it clashes with [a custom resource from Kuma](https://kuma.io/docs/2.2.x/policies/meshproxypatch/) since it ends with `patch`.

### Expected Behavior

Only resources declared with `kubernetes.apiextensions.CustomResourcePatch` should be treated as a patch resource, regardless fo `kind`. 

### Steps to reproduce

Create any custom resource with `kind` ending with `Patch`. For example:

```typescript
new k8s.apiextensions.CustomResource(
  'proxy-config',
  {
    apiVersion: 'kuma.io/v1alpha1',
    kind: 'MeshProxyPatch',
    metadata: {
      name: 'proxy-config',
    },
 },
)
```

### Output of `pulumi about`

CLI          
Version      3.68.0
Go Version   go1.20.4
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       fedora
Version  38
Arch     x86_64

This project is written in nodejs: executable='[redacted]/.nvm/versions/node/v18.16.0/bin/node' version='v18.16.0'

Backend        
Name          [redacted]
URL            [redacted]
User           [redacted]
Organizations  

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hi @caioaao,

Thank you for reporting this issue, and I apologize for the inconvenience it has caused. I agree that treating kinds that end in Patch as a literal patch resource is not the intended behavior. I appreciate you bringing this to our attention and will be adding this to our backlog.

**Comment by mikhailshilkov** [comment]
@rquitales @lblackstone This sounds fairly bad... Is there a simple fix that we could ship here?

**Comment by lblackstone** [comment]
> @rquitales @lblackstone This sounds fairly bad... Is there a simple fix that we could ship here?

Yeah, the provider is currently using the Patch suffix as the heuristic, but this could be updated to something stricter.
