### ISSUE TITLE
ObjectMeta in ConfigMap should not contain clusterName: field not declared in schema

### ISSUE THREAD

**Issue by alabama** [pulumi/pulumi-kubernetes#2447]
### What happened?

After upgrading our k8s version from 1.23 to 1.25 I received an error while re-provisioning a ConfigMap with the key `clusterName` (https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/configmap/#clustername_nodejs) in it. This worked fine in previous versions before but created an error in the 1.25 version of k8s

The error:
```
kubernetes:core/v1:ConfigMap (foo-bar-cm):
    error: Preview failed: resource default/foo-bar-cm was not successfully created by the Kubernetes API server : failed to create typed patch object (default/foo-bar-cm; /v1, Kind=ConfigMap): .metadata.clusterName: field not declared in schema
``` 

### Expected Behavior

Remove `clusterName` from the docs as it is not part of the docs (https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/configmap/#clustername_nodejs) and is receiving and error from Kubernetes API server.

### Steps to reproduce

1. setup a cluster in k8s

2. : 
```javascript
import * as eks from '@pulumi/eks'

const cluster = new eks.Cluster(...) // you need to setup this yourself

const clusterName = cluster.eksCluster.name
const provider = new k8s.Provider('k8sProvider', {
  kubeconfig: cluster.kubeconfig, 
})

new k8s.core.v1.ConfigMap(
    'foo-bar-cm',
    {
      metadata: {
        name: 'foo-bar-cm',
        clusterName: clusterName,
      },
      data: {some: 'data'},
    },
    {
      provider: provider,
    },
  )
```

### Output of `pulumi about`

CLI
Version      3.62.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME    VERSION
kubernetes  3.29.0
nodejs  unknown

This project is written in nodejs: executable='/foo/bar/node'

Host
OS       ubuntu
Version  22.04
Arch     x86_64

can't post more of the about due to compliance

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @alabama, unfortunately the `clusterName` field is not available anymore in Kubernetes 1.25. Compare [the 1.23 schema](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#objectmeta-v1-meta) to [the 1.25 schema](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#objectmeta-v1-meta). You will need to remove it from your configuration.

I filed #2450 to make these deprecations more visible to our users in the future. Apologies for the obscure failure mode.
