### ISSUE TITLE
Cancellation on delete could cause us to stop tracking object

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#245]
Following up from #244, in the process of review, I realized that in a handful of cases, it is possible that ctrl-c during a delete could cause the Kubernetes provider to stop tracking the object, even though it exists.

The reason is that provider does not actually check whether the returned value conforms to `await.InitializationError`, which is what the `await` package uses to signal that the API server has acknowledged the operation, but has not yet completed it.

The fix seems pretty straightforward:

- [x] "Unpack" the error in `kubeProvder#Delete` (similar to how we do it here: https://github.com/pulumi/pulumi-kubernetes/blob/2efb314c64218897bb88895bc468e7c231c8ee88/pkg/provider/provider.go#L439)
- [x] Rename `InitializationError` to something more appropriate -- perhaps `PartialError`?

**Comment by lukehoban** [comment]
@hausdorff How serious is this in practice?  Have users hit this?  Do we need to make sure to fix in 0.19?

**Comment by hausdorff** [comment]
This is very minor, you'd have to get very unlucky. But, we should solve it, let's put it into 0.20
