### ISSUE TITLE
Ability to push Helm Charts to OCI registries

### ISSUE THREAD

**Issue by liamawhite** [pulumi/pulumi-kubernetes#2451]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We currently ensure all our images are deployed using the [Docker Image resources](https://www.pulumi.com/registry/packages/docker/api-docs/image/) and would like to do the same for Helm Charts. 

See [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html) for how this works with ECR.

### Affected area/feature

Pulumi Kubernetes provider

**Comment by thomas11** [comment]
Thank you for the suggestion @liamawhite, we'll take a look at it!

**Comment by EronWright** [comment]
I believe that the `Release` resource does support `oci://` charts. I don't know whether `Chart` does. @liamawhite which resource type you have in mind?

**Comment by EronWright** [comment]
Blocked on https://github.com/pulumi/pulumi-kubernetes/issues/1914

**Comment by liamawhite** [comment]
The request isn't for consuming the chart/release it's for pushing to a registry to be consumed by these commands.

**Comment by blampe** [comment]
We're not considering adding this functionality to the Kubernetes provider at the moment. It would be reasonable to include in a standalone helm provider, but there are also currently no plans for that.
