### ISSUE TITLE
Pulumi fails to update namespace because it can't replace (delete/recreate) it due to name clash

### ISSUE THREAD

**Issue by solomonshorser** [pulumi/pulumi-kubernetes#2459]
### What happened?

Some changes occurred to a provider object (pulumi:providers:kubernetes) supporting a k8s namespace. Pulumi chose to replace the namespace, but it seems that pulumi is trying to create a new namespace (and probably delete the old one) rather than make the changes in-place. This fails because the namespace's name is not autogenerated so pulumi fails when it tries to create the new namespace because 'namespaces "my-namespace" already exists, the server was not able to generate a unique name for the object'.

We do not want autogenerated names for our namespaces so we are a bit stuck. It looks like I will need to manually remove namespaces everywhere this happens, and then run pulumi to create the new ones.

### Expected Behavior

I expected pulumi to update the namespace with the reference to the updated provider without any fuss or trouble.

### Steps to reproduce

Create the namespace like this:

```typescript
    import * as k8s from "@pulumi/kubernetes"


    const myNamespace = new k8s.core.v1.Namespace(myNamespaceName,
        {
            metadata: {
                generateName: "false",
                name: myNamespaceName
            }
        },
        { provider: myCluster }
    );
```

Make some changes to the configuration of the provider (`myCluster`, here).

Pulumi will try to update `myNamespace` as a "replace" operation, but will fail with an error message that looks like this:

<pre>
Diagnostics:
  kubernetes:core/v1:Namespace (my-namespace):
    error: resource my-namespace was not successfully created by the Kubernetes API server : namespaces "my-namespace" already exists, the server was not able to generate a unique name for the object
</pre>

### Output of `pulumi about`

<pre>
CLI
Version      3.70.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME           VERSION
command        0.7.2
gcp            6.55.1
gcp            5.26.0
google-native  0.30.0
google-native  0.26.1
kubernetes     3.26.0
nodejs         unknown

Host
OS       darwin
Version  13.4
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v20.2.0'

Dependencies:
NAME                              VERSION
@pulumi/command                   0.7.2
@pulumi/gcp                       6.55.1
@pulumi/kubernetes                3.26.0
@typescript-eslint/parser         2.34.0
@pulumi/google-native             0.30.0
@types/node                       12.20.55
@typescript-eslint/eslint-plugin  2.34.0
eslint                            6.8.0
yaml                              2.2.2
</pre>

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Hi @solomonshorser thank you for reporting this. Which change are you making to the provider, so that I could reproduce it locally?

**Comment by solomonshorser** [comment]
The kubeconfig was updated.

**Comment by lblackstone** [comment]
I was able to reproduce this error using Client-side Apply mode with the following program:

```ts
import * as k8s from "@pulumi/kubernetes";

const provider = new k8s.Provider("k8s", {
    enableServerSideApply: false,
});

new k8s.core.v1.Namespace("test",
    {
        metadata: {
            // annotations: {"test": "test"}, // Uncomment after the initial creation to cause the error
            generateName: "false",
            name: "test"
        }
    },
    { provider, replaceOnChanges: ["metadata"]}
);
```

This works without an error if the Server-side Apply mode is enabled. However, it also looks like the `generateName` parameter is being used incorrectly; the value is a prefix, not a boolean toggle, so this is a weird case. Removing that parameter also fixes the error. I'm going to mark this as fixed.

**Comment by solomonshorser** [comment]
What is "server-side apply" mode?

**Comment by lblackstone** [comment]
> What is "server-side apply" mode?

You can read more about it here: https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/

**Comment by solomonshorser** [comment]
@lblackstone I wasn't aware of this feature; thanks for the link!
