### ISSUE TITLE
Add helmChart support to kustomize.Directory resource

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-kubernetes#2470]
~Some kustomize folders contain nested helm charts. To utilize these, you need to specify `--enable-helm` as an option~

Updated description:
Kustomize optionally supports [expanding helm charts with a plugin](https://github.com/kubernetes-sigs/kustomize/blob/v3.3.1/examples/chart.md). We add experimental support for this feature in https://github.com/pulumi/pulumi-kubernetes/pull/2471 behind the `PULUMI_K8S_KUSTOMIZE_HELM` environment variable flag. If we decide to make this feature generally available, the following work still needs to be done:

1. Add a configurable path option for the `helm` binary
2. Add a test to verify that kustomization.Directory resources that don't use the `helmChart` feature do not require the `helm` binary to be present. This works currently, but could regress in the future.
3. Remove the feature flag

**Comment by jaxxstorm** [comment]
Looks like we need to upgrade to krusty v0.14 to get this functionality

**Comment by jturolla** [comment]
> Looks like we need to upgrade to krusty v0.14 to get this functionality

Didn't see that on the api release for 0.14, am I looking in the right place? Where did you get this information from? 

https://github.com/kubernetes-sigs/kustomize/releases/tag/api%2Fv0.14.0

**Comment by kpitzen** [comment]
Hi @jaxxstorm - could you provide a little more detail around what the desired design / UX looks like here? Is this an option we'd like to pass down through the pulumi cli to the provider? What would the intended behavior be when it is provided?

**Comment by jaxxstorm** [comment]
@kpitzen I'm not super familiar with this myself, but from a quick google:

https://github.com/kubernetes-sigs/kustomize/blob/master/examples/chart.md

> The flag --enable-helm exists to have the user acknowledge that kustomize is running an external program as part of the build step. It's like the --enable-plugins flag, but with a helm focus.

I believe this just needs to be added to the provider

**Comment by jturolla** [comment]
Thanks for the effort, really looking forware for this release. That was super fast and I'm really happy for the result. 🙇‍♂️

**Comment by jaxxstorm** [comment]
Looks like this was shipped in 3.30.1 so closing, thanks all!

**Comment by EronWright** [comment]
Related: https://github.com/kubernetes-sigs/kustomize/issues/4401
