### ISSUE TITLE
Helm install order doesn't work with complex installs

### ISSUE THREAD

**Issue by mrbrownt** [pulumi/pulumi-kubernetes#250]
Pulumi watches for various resource to reach a state of readiness before moving on to the deploying the next reference set in a deployment. This doesn't seem to work so well with helm. When deploying the stable/wordpress chart pulumi hangs waiting for services to become ready before any pods are deployed.

https://github.com/pulumi/pulumi-kubernetes/blob/603e3e7a2be1b0915d6125aab312fd07e1ff6cb3/sdk/nodejs/helm.ts#L110-L137

**Comment by hausdorff** [comment]
What version of Pulumi are you running? The most recent version should be spawning all resources at once, which _should_ obviate the problem.

**Comment by mrbrownt** [comment]
v0.16.1

**Comment by hausdorff** [comment]
@mrbrownt can you try `v0.17.3` and let me know how that goes?

Also, we're planning to address this in the next couple weeks -- this work is tracked in #239, so can you chime in there if v0.17.3 doesn't give a good experience?

I'll close this as a duplicate in the mean time.
