### ISSUE TITLE
Support k8s 1.28 on release

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-kubernetes#2518]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

k8s 1.28 will be released soon. The provider should support 1.28 as soon as its available.

https://github.com/kubernetes/kubernetes/releases/tag/v1.28.0-rc.0

**Comment by rquitales** [comment]
Kubernetes v1.28 is scheduled to be released on [15 August 2023](https://www.kubernetes.dev/resources/release/).

**Comment by mikhailshilkov** [comment]
@rquitales can you chat with @lblackstone about what our usual process for shipping upgrade has been, document it, and apply to this release. I believe we do all the prep ahead of the release and then merge on the day of.
