### ISSUE TITLE
generate_name prefix seems to not be honored

### ISSUE THREAD

**Issue by jforest** [pulumi/pulumi-kubernetes#2539]
### What happened?

I have both a `pv` and `pvc` being created, I specify the `pulumi_kubernetes.meta.v1.ObjectMetaArgs` `generate_name` attribute on each which should specify a prefix for the name.  But the name that results is not using my specified prefix, it appears to be using the `resource_name` of the object as the prefix instead.

### Expected Behavior

For example, my code for generating a `pvc` from the `pv` I created before
```
        # Create the PVC from the PV
        self.pvc = pulumi_kubernetes.core.v1.PersistentVolumeClaim(
            f'{self.cluster.name}-workbench-pvc',
            args=pulumi_kubernetes.core.v1.PersistentVolumeClaimInitArgs(
                metadata=pulumi_kubernetes.meta.v1.ObjectMetaArgs(
                    generate_name='workbench-pvc',
                    namespace='datascience'
                ),
                spec=pulumi_kubernetes.core.v1.PersistentVolumeClaimSpecArgs(
                    access_modes=['ReadWriteMany'],
                    resources=pulumi_kubernetes.core.v1.ResourceRequirementsArgs(
                        requests=capacity
                    ),
                    storage_class_name='',
                    volume_name=pv.metadata.name
                )
            ),
            opts=pulumi.ResourceOptions(provider=self.cluster.provider,
                                        parent=pv)
        )
```

I would expect the name of the `pvc` to be `workbench-pvc-<randomstring>` but instead I get `<cluster_name>-workbench-pvc-<randomstring>`

our cluster name is `internal-eks01` in this case
```
internal-eks01-workbench-pvc-c1aa4e6e         Bound    internal-eks01-workbench-pv-abae85d9         1200Gi     RWX                           55d
```

### Steps to reproduce

Create a `pvc` from a `pv` using the code below

 ```
        # Create the PVC from the PV
        self.pvc = pulumi_kubernetes.core.v1.PersistentVolumeClaim(
            f'{self.cluster.name}-workbench-pvc',
            args=pulumi_kubernetes.core.v1.PersistentVolumeClaimInitArgs(
                metadata=pulumi_kubernetes.meta.v1.ObjectMetaArgs(
                    generate_name='workbench-pvc',
                    namespace='datascience'
                ),
                spec=pulumi_kubernetes.core.v1.PersistentVolumeClaimSpecArgs(
                    access_modes=['ReadWriteMany'],
                    resources=pulumi_kubernetes.core.v1.ResourceRequirementsArgs(
                        requests=capacity
                    ),
                    storage_class_name='',
                    volume_name=pv.metadata.name
                )
            ),
            opts=pulumi.ResourceOptions(provider=self.cluster.provider,
                                        parent=pv)
        )
```

it will not use the `generate_name` prefix, it instead uses the `resource_name` as a prefix

### Output of `pulumi about`

```
❯ pulumi about
CLI
Version      3.77.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME                     VERSION
aws                      5.41.0
aws-native               0.72.0
kubernetes               3.28.1
kubernetes-cert-manager  0.0.5
postgresql               3.8.0
python                   unknown

Host
OS       darwin
Version  12.6.8
Arch     arm64

This project is written in python: executable='/Users/jforest/.pyenv/shims/python3' version='3.9.11
'

<SNIP SOME RESOURCES OUT>

Found no pending operations associated with jforest

Current Stack: jforest/aws-main-services/jforest
Backend
Name           pulumi.com
URL            https://app.pulumi.com/jforest
User           jforest
Organizations  jforest
```

### Additional context

versions of pulumi libraries:

```
❯ pip list | grep pulumi
pulumi                         3.68.0
pulumi-aws                     5.41.0
pulumi-aws-native              0.72.0
pulumi-kubernetes              3.28.1
pulumi-kubernetes-cert-manager 0.0.5
pulumi-postgresql              3.8.0
```

I would like to upgrade `pulumi-kubernetes` to 4.1.0, but `pulumi-kubernetes-cert-manager` will not allow versions greater than 3.x.  https://github.com/pulumi/pulumi-kubernetes-cert-manager/issues/21 and https://github.com/pulumi/pulumi-kubernetes-cert-manager/pull/22

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hello @jforest,

Thank you for raising this issue. In Kubernetes, the `generateName` field is utilized to generate a name for a resource when it's sent for creation to the K8s API Server and doesn't already have a name field set. This name generation happens on the K8s server's side.

However, in Pulumi, when resources don't explicitly contain a name field, they are auto-named by default. This Pulumi behavior is causing the `generateName` field to be ignored when sending resources to the K8s API server, as Pulumi's auto-naming process generates and sets a name which is then sent to the API server, thus overriding whatever is set in `generateName`.

To resolve this issue, we will need to implement a check to ensure that auto-naming doesn't occur when the `generateName` field is supplied. This will allow the `generateName` field to function as intended.

**Comment by gunzy83** [comment]
I have also run into this. I am going to work around it by generating our own names but I would appreciate if a fix could be prioritised. This should operate in the same way as `namePrefix` in the AWS provider.

**Comment by EronWright** [comment]
Related:
- https://github.com/pulumi/pulumi-kubernetes/pull/1618

**Comment by gunzy83** [comment]
I see this has been closed but I can't seem to find any record of why this was only fixed for CSA and not SSA (and disallows the field in YAML rendering mode). Is there a reason or will be this be supported later?
