### ISSUE TITLE
Recent change disabled python source distribution uploads, is this intended?

### ISSUE THREAD

**Issue by edude03** [pulumi/pulumi-kubernetes#2540]
### What happened?

Not sure if this is a bug or intended behaviour, but this used to work and doesn't anymore and I can't find any documentation highlighting it, so I'm assuming it's a bug. 

Installing `pulumi-kubernetes==4.1.0` (or any version greater than `4.1.0a1691604995`) with `--no-binary` with pip causes `ERROR: No matching distribution found for pulumi-kubernetes==4.1.0` 

### Expected Behavior

I would expect it to install. 

### Steps to reproduce

`pip install --no-binary :all: pulumi-kubernetes==4.1.0`

### Output of `pulumi about`

N/A

### Additional context

As far as I can tell it was broken in [This PR](https://github.com/pulumi/pulumi-kubernetes/pull/2531/files)

Using the git source as a work around by putting this in the requirements.txt:

```
pulumi-kubernetes @ git+https://github.com/pulumi/pulumi-kubernetes@v4.1.0#subdirectory=sdk/python
```

Doesn't work because the [version isn't set in the pyproject.toml](https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/python/pyproject.toml#L8)

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Hi @edude03 our intention was to transition to the wheel-based distribution. We'll look into this shortly, we were not aware of the `--no-binary` option or that this would be a breaking change.

CC @rquitales

**Comment by necaris** [comment]
@t0yv0 I'd be curious to understand how you intend to distribute the plugin using a wheel -- from what I can see the wheel doesn't actually include the resource plugin?

**Comment by t0yv0** [comment]
That is correct. The source distribution does not include the plugin either, but auto-installs them upon Python project installation. This redundant (optional) with Pulumi CLI auto-installing the plugins upon pulumi preview/up. The best place to discuss this is in https://github.com/pulumi/pulumi/issues/13709 I think.

**Comment by rquitales** [comment]
Note that v4.1.1 of the Kubernetes provider was released earlier that reverted this change. Closing this issue now but feel free to reopen should more discussion need to occur.
