### ISSUE TITLE
Change to unrelated deployment spec property causes ignore_changes to fail

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-kubernetes#2542]
### What happened?

pulumi-kubernetes is unable to ignore_changes on a property, in this case spec.replicas, when another unrelated property, in this case spec.containers[0].image, changes. This causes a SSA conflict.

### Expected Behavior

the ignore_changes directive should apply regardless of if another unrelated property is changing or not.

### Steps to reproduce

See https://github.com/phillipedwards/apps and included repro steps.

### Output of `pulumi about`

Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
kubernetes  4.1.1
python      unknown

Host     
OS       darwin
Version  13.2.1
Arch     x86_64

Dependencies:
NAME               VERSION
pip                23.2.1
pulumi-aws         5.42.0
pulumi-kubernetes  4.1.1
setuptools         68.1.2
wheel              0.41.2

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
@phillipedwards Thanks for the through repro!

**Comment by phillipedwards** [comment]
Some additional (relevant) details.

- This appears to only occur on `pulumi preview`. An update (`pulumi up -f`) does not experience this error.
- Once I successfully run a pulumi up as in the above step, I can no longer get this SSA conflict to produce. Destroying the deployment and re-running the program _does_ cause the error to occur.
- Here is the error from the above repro
```
Diagnostics:
  pulumi:pulumi:Stack (apps-phil):
    error: preview failed

  kubernetes:apps/v1:Deployment (nginx):
    error: Preview failed: 1 error occurred:
        * the Kubernetes API server reported that "nginx/nginx" failed to fully initialize or become live: Server-Side Apply field conflict detected. see https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#handle-field-conflicts-on-existing-resources for troubleshooting help
    : Apply failed with 1 conflict: conflict with "kubectl-patch" using apps/v1: .spec.replicas
```

**Comment by iwahbe** [comment]
@phillipedwards That sounds like this is an issue with unknown value handling. That's generally the cause when something works for `pulumi up -f` but not `pulumi preview`.

**Comment by rquitales** [comment]
Following up from offline discussions, this is due to a conflict between field managers when the SSA dry run update call is made. After running `pulumi up`, this bug isn't encountered anymore since the field manager in Pulumi state will be updated to the new manager of the `spec.replicas` field. This bug can occur again without destroying the deployment if another new field-manager is used to update the `spec.replicas` field.

One quick workaround would be to do a refresh before running preview, eg. `pulumi preview --refresh`.
