### ISSUE TITLE
Server-Side Apply field conflict with "kube-controller-manager" with subresource "scale" using apps/v1: .spec.replicas on DOKS

### ISSUE THREAD

**Issue by malikal-hh** [pulumi/pulumi-kubernetes#2569]
### What happened?

Server-Side Apply field conflict with "kube-controller-manager" with subresource "scale" using apps/v1: .spec.replicas on DOKS Digital Ocean Kubernetes

### Expected Behavior

Forced the patch change to the deployment

### Steps to reproduce

pulumi up

### Output of `pulumi about`

CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  4.1.1
nodejs      unknown

Host
OS       Microsoft Windows 10 Pro
Version  10.0.19045 Build 19045
Arch     x86_64

This project is written in nodejs: executable='C:\Program Files\nodejs\node.exe' version='v14.21.3'

Current Stack: organization/hh-apps/hh-apps

TYPE                                               URN
pulumi:pulumi:Stack                                urn:pulumi:hh-apps::hh-apps::pulumi:pulumi:Stack::hh-apps-hh-apps
kubernetes:yaml:ConfigFile                         urn:pulumi:hh-apps::hh-apps::kubernetes:yaml:ConfigFile::imgproxy
pulumi:providers:kubernetes                        urn:pulumi:hh-apps::hh-apps::pulumi:providers:kubernetes::default_4_1_1    
kubernetes:core/v1:ConfigMap                       urn:pulumi:hh-apps::hh-apps::kubernetes:yaml:ConfigFile$kubernetes:core/v1:ConfigMap::utility/imgproxy-config
kubernetes:core/v1:Service                         urn:pulumi:hh-apps::hh-apps::kubernetes:yaml:ConfigFile$kubernetes:core/v1:Service::utility/imgproxy
kubernetes:networking.k8s.io/v1:Ingress            urn:pulumi:hh-apps::hh-apps::kubernetes:yaml:ConfigFile$kubernetes:networking.k8s.io/v1:Ingress::utility/imgproxy
kubernetes:autoscaling/v2:HorizontalPodAutoscaler  urn:pulumi:hh-apps::hh-apps::kubernetes:yaml:ConfigFile$kubernetes:autoscaling/v2:HorizontalPodAutoscaler::utility/imgproxy
kubernetes:apps/v1:Deployment                      urn:pulumi:hh-apps::hh-apps::kubernetes:yaml:ConfigFile$kubernetes:apps/v1:Deployment::utility/imgproxy

Found no pending operations associated with hh-apps

Backend
Name           DESKTOP-MDP5LV4
URL            file://~
User           DESKTOP-MDP5LV4\ACER

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@malikal-hh Could you please provide an isolated piece of code to reproduce this issue?

**Comment by mikhailshilkov** [comment]
Hi @malikal-hh are you still affected by this issue? If so, please share a code snippet that would help us troubleshoot it. Thank you.

**Comment by EronWright** [comment]
Since the stack includes a `HorizontalPodAutoScaler`, I suppose the explanation is that the auto-scaler updated the `replicas` field. This caused a conflict with the Pulumi application. The solution is to [force overrides](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#set-the-pulumicompatchforce-annotation-to-persistently-overwrite-any-field-conflicts-for-a-resource) (if you want Pulumi to override the auto-scaler) or, more likely, to [ignore any conflict](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#use-ignorechanges-to-allow-another-controller-to-manage-a-conflicting-field) on the replicas field.

Please re-open if these options don't work for you, thanks!

**Comment by malikal-hh** [comment]
Yes actually I don’t know how to do both of it on TypeScript. The documentation is kinda lack of understanding for me

**Comment by EronWright** [comment]
Sorry for the inconvenience, let me help. I notice you're using a `ConfigFile` to make the deployment, and we'd like to ignore changes to the replicas field. 

```typescript
import * as k8s from "@pulumi/kubernetes";
import { ConfigFile } from "@pulumi/kubernetes/yaml";
import { CustomResourceOptions } from "@pulumi/pulumi";

// howto: transform a Deployment from a ConfigFile to ignore changes to spec.replicas.

const configFile = new ConfigFile("sample", {
    file: "sample.yaml",
    transformations: [(obj: any, opts: CustomResourceOptions) => {
        if (obj.kind === "Deployment" && obj.metadata.name === "nginx-deployment") {
            opts.ignoreChanges = ["spec.replicas"]
        }
    }],
})
```

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: web
...
```

Here's some code: [issue-2569.zip](https://github.com/pulumi/pulumi-kubernetes/files/12775856/issue-2569.zip)

**Comment by malikal-hh** [comment]
Great that works thank you so much.

Maybe can add more detail into each documentation
