### ISSUE TITLE
Missing PkgVersion function

### ISSUE THREAD

**Issue by hagaibarel** [pulumi/pulumi-kubernetes#2580]
### What happened?

Since version 4.1.0 the `PkgVersion()` function is missing from the sdk. It seems that https://github.com/pulumi/pulumi-kubernetes/pull/2519 moved the `pulumiUtilites.go` file to an internal pkg but that isn't importable. 

The problem is the tools such as `crd2pulumi` relay on that function when generating the code and the code is broken as of 4.1.0. 

A possible solution (see https://github.com/pulumi/pulumi/pull/13749) would be to rename the internal pkg to something else (e.g. utilities) so it can be importable

### Example

Run `crd2pulumi@1.2.5` on any crd yaml file and observe that the generated code is broken

### Output of `pulumi about`

CLI          
Version      3.85.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
go          unknown
kubernetes  4.0.3

Host     
OS       ubuntu
Version  23.04
Arch     x86_64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.21.1 linux/amd64'

*backend and resource list redacted for brevity*

Dependencies:
NAME                                        VERSION
github.com/bringg/pulib                     1.0.5
github.com/creasty/defaults                 1.7.0
github.com/onsi/ginkgo/v2                   2.12.1
github.com/onsi/gomega                      1.27.10
github.com/pulumi/pulumi-kubernetes/sdk/v4  4.0.3
github.com/pulumi/pulumi/sdk/v3             3.85.0
golang.org/x/exp                            0.0.0-20230811145659-89c5cff77bcb

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@guineveresaenger Was this effect intended in https://github.com/pulumi/pulumi/pull/13136? Can we solve this in `crd2pulumi` or do we need to change codegen again?

**Comment by guineveresaenger** [comment]
Hi! Apologies @hagaibarel  - I'm at Grace Hopper this week so reply may be slower than usual.

We _definitely_ intended to put pulumiUtilities in an `internal` package, because these are, at the heart of it, internal files.
_However_, we do have an override for providers that rely on `pulumiVersion` to be externally available and https://github.com/pulumi/pulumi/pull/13749, as you linked, is the correct path forward here.

@mikhailshilkov -we thankfully do not need to change codegen again.

**Comment by hagaibarel** [comment]
Thanks for reply @guineveresaenger, is there anything I can do to help move this forward? It's important for us as we rely on `crd2pulumi` for generating `go` typed definitions and are blocked from upgrading the `kubernetes` provider in our `pulumi` programs because of this

**Comment by honne23** [comment]
Hey I think codegen still needs to be changed as it is still using the depracted `kubernetes.PkgVersion()` while also relying on the `v3` libraries
