### ISSUE TITLE
Doc about specify helm chart with values file not clear on golang

### ISSUE THREAD

**Issue by iluwaa** [pulumi/pulumi-kubernetes#2600]
### What happened?

Usage of code example from official docs appears to error "cannot use pulumi.NewFileAsset("test") (value of type pulumi.Asset) as pulumi.AssetOrArchiveArrayInput value in struct literal: pulumi.Asset does not implement pulumi.AssetOrArchiveArrayInput (missing method ToAssetOrArchiveArrayOutput)"

### Example

https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/#specify-helm-chart-values-in-file-and-code

copy code from example to IDE 

### Output of `pulumi about`

CLI          
Version      3.87.0
Go Version   go1.21.2
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.2.1
go          unknown
kubernetes  4.3.0

Host     
OS       darwin
Version  13.6
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.21.1 darwin/arm64'

Current Stack: iluwa/vault_test/sandbox

Found no resources associated with sandbox

Found no pending operations associated with sandbox

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/iluwa
User           iluwa
Organizations  iluwa
Token type     personal

Dependencies:
NAME                                 VERSION
github.com/pulumi/pulumi-aws/sdk/v6  6.2.1
github.com/pulumi/pulumi/sdk/v3      3.86.0

Pulumi locates its logs in /var/folders/gy/_r0bdh9s0j38bt679tc0m8wc0000gq/T/ by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
Thank you for reporting this @iluwaa. The example should be fixed with the next provider release.
