### ISSUE TITLE
GOLANG `PodTemplateSpecInput` Unresolved Type

### ISSUE THREAD

**Issue by ghostsquad** [pulumi/pulumi-kubernetes#2608]
### What happened?

<img width="605" alt="image" src="https://github.com/pulumi/pulumi-kubernetes/assets/903488/8d503e25-1847-4734-bbc7-3569cbb79c30">

### Example

Goland cannot resolve `PodTemplateSpecInput` nor `corev1.PodTemplateSpecArgs`. 

### Output of `pulumi about`

```
CLI
Version      3.85.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.42.0
go          unknown
kubernetes  4.4.0

Host
OS       darwin
Version  13.6
Arch     arm64

This project is written in go: executable='/Users/ghostsquad/.asdf/shims/go' version='go version go1.21.1 darwin/arm64'

Dependencies:
NAME                                        VERSION
github.com/pkg/errors                       0.9.1
github.com/pulumi/pulumi-aws/sdk/v5         5.42.0
github.com/pulumi/pulumi-kubernetes/sdk/v4  4.4.0
github.com/pulumi/pulumi/sdk/v3             3.88.1

Pulumi locates its logs in /var/folders/87/pjnczvjx589521d5v_5ycxnc0000gn/T/ by default
warning: Could not access the backend: read ".pulumi/meta.yaml": blob (key ".pulumi/meta.yaml") (code=Unknown): AccessDenied: Access Denied
	status code: 403, request id: 475RWX028R53XHR5, host id: P9GG0cMmn48YlRZXYscya1CJyf1lU/k6AEjUXmbDMAlrrNn3+Cvs9AetmbWUhhUHDsFOPdEAuHBGDyVJyEJ/BeE8j9iuLjOImsxP3qDv4iY=
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
@ghostsquad The type seems to be there in the codebase in sdk/go/kubermetes/core/v1/pulumiTypes.go. The file is too big to be shown in GitHub, but here is a screen from VS Code:

<img width="795" alt="image" src="https://github.com/pulumi/pulumi-kubernetes/assets/1454008/4cee5f5e-a6d0-4cb7-9acc-9b1e01453de7">

Do you have a Pulumi program code snippet or steps to reproduce the compilation error that you are presumably facing?
