### ISSUE TITLE
Already-existing resources instantiated by helm charts are causing errors instead of acting as an upgrade/no-op

### ISSUE THREAD

**Issue by eshamay** [pulumi/pulumi-kubernetes#261]
My Pulumi code includes the following resources:

```
// Create the Kubernetes cluster and all associated artifacts and resources
const cluster = new eks.Cluster(environment+"-eks-cluster", {
    vpcId             : config.require("vpc-id"),
    subnetIds         : vpcSubnetIds,
    instanceType      : "m4.4xlarge",
    nodePublicKey     : config.require("worker-ssh-key"),
    nodeRootVolumeSize: 250,
    desiredCapacity   : 3,
    maxSize           : 5,
    minSize           : 1,
    nodeUserData      : userData,
    deployDashboard   : false,
});

// Update the WARM_IP_TARGET by deploying a customized version of the CNI plugin
const cni = new k8s.helm.v2.Chart("aws-k8s-cni", {
    repo: "sdp-helm",
    version: "0.2.77",
    chart: "aws-k8s-cni",
}, {providers: {kubernetes: cluster.provider}});
```

The EKS cluster creates a ServiceAccount names `aws-node`, and that same service account is also declared in the Helm chart.

The expected behavior is that the ServiceAccount in the helm chart deployment would act as an `upgrade` or no-op and would not cause an error.

The actual behavior is that `pulumi up` is failing as follows:

```
 +      └─ kubernetes:core:ServiceAccount  kube-system/aws-node           **creating failed**     1 error

Diagnostics:
  kubernetes:core:ServiceAccount (kube-system/aws-node):
    error: Plan apply failed: serviceaccounts "aws-node" already exists
```

Helm provides an `upgrade` command that would skip over existing resources. Pulumi doesn't seem to have that option. Since the entire stack's state is tracked in Pulumi it's expected that this scenario should "just work" without additional steps to workaround.

**Comment by hausdorff** [comment]
Suggesting @pgavlin for this, as he maintains the EKS package. :)

**Comment by lukehoban** [comment]
The specific issue that @eshamay raised here is addressed now via https://github.com/pulumi/pulumi-eks/pull/19.

The broader question of whether it should be possible to declare resources that already exist and have that take ownership of them and drive them to new desired states is generally part of https://github.com/pulumi/pulumi/issues/1662.
