### ISSUE TITLE
[Urgent] 4.5.0 forces a recreate on unchanged resources

### ISSUE THREAD

**Issue by paulgeringer** [pulumi/pulumi-kubernetes#2626]
### What happened?

Upgrading to 4.5.0 added the `cluster`, `namespace`, and `context` fields to the log output.

This in turn forces the create-replace of the `kubernetes:core/v1:Secret`, `kubernetes:core/v1:Service`, and `kubernetes:apps/v1:Deployment` resources, which can force changes to a cluster despite there being no functional change to the service configuration.

### Example

The issue occurs because [this metadata change](https://github.com/pulumi/pulumi-kubernetes/commit/0f84cfec4788042097a6524efab3a54e7fa7f40a#diff-418e6e7d93aeacebe7c22d5fb674b48bfa15c6a514eb3ae4744b86d447595d8eR391-R417) forces a new set of keys into the diff, and [this piece](https://github.com/pulumi/pulumi-kubernetes/commit/0f84cfec4788042097a6524efab3a54e7fa7f40a#diff-418e6e7d93aeacebe7c22d5fb674b48bfa15c6a514eb3ae4744b86d447595d8eL384-R478) guarantees that if you have a cluster defined, it will get replaced.

### Output of `pulumi about`

N/A

### Additional context

This is a major regression and should be rolled back. This causing a potential recreate is noted in the notes and is not acceptable from a backwards compatibility perspective.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by vschettino-asimov** [comment]
Same here, 4.5.0 yields a provider replacement that has a cascading effect on all resources that depend on it:

```
     Type                                                     Name                                       Plan        Info
     pulumi:pulumi:Stack                                      backend-prd                                     2 warnings
 +-  ├─ pulumi:providers:kubernetes                           prd                                 replace     [diff: +cluster,context~version]
```

**Comment by EronWright** [comment]
Fixed in https://github.com/pulumi/pulumi-kubernetes/pull/2627

To anyone who was affected, please accept our sincere apology. We have a postmortem discussion planned on how to improve our release process in the future to avoid regressions like this.
