### ISSUE TITLE
Support k8s 1.29 on release

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-kubernetes#2628]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

k8s 1.29 is in progress. The provider should support 1.29 as soon as its available.

Current tag is an alpha: https://github.com/kubernetes/kubernetes/releases/tag/v1.29.0-alpha.2

**Comment by mikhailshilkov** [comment]
@mnlumi @rquitales do we know the date? Should we open a draft PR?

**Comment by mnlumi** [comment]
I haven't seen a date yet, but based on history, I expect this to come in early December. They only have an alpha out currently, not RC yet.

**Comment by rquitales** [comment]
Final release is December 5. Code freeze is October 31. and test freeze is November 14. It probably makes sense to hold off crafting a draft PR until at least code freeze occurs and when a release candidate is cut.

**Comment by mnlumi** [comment]
https://github.com/kubernetes/kubernetes/releases/tag/v1.29.0-alpha.3 was tagged on 11/2. There are no new updates in https://groups.google.com/g/kubernetes-announce.
