### ISSUE TITLE
Server-Side Apply with Pulumi Fails to Replace StatefulSet Due to Conflict, Resulting in Deletion of Target Object

### ISSUE THREAD

**Issue by bitofsky** [pulumi/pulumi-kubernetes#2632]
#### Summary
When using server-side apply with pulumi up, if there is a conflict in the cluster's statefulset, the replace operation fails and the object is deleted from the cluster. Subsequent pulumi up shows no changes, and the object is missing in the cluster.

#### Steps to Reproduce
1. Run pulumi up with server-side apply enabled, and preview shows a replace operation for a StatefulSet.
1. If there is an existing conflict in the cluster's statefulset, the replace operation fails.
1. The object targeted for replace is deleted from the cluster.
1. Running pulumi up again shows "no changes."
1. Running kubectl get for the object returns "not found."
1. Running pulumi up -r shows the object under the create operation, and it gets created upon selecting yes.

#### Expected Behavior
1. If there is a conflict for the replace target, it should be indicated as "conflict" in the preview.
1. If the delete operation was successful in the perform phase, it's illogical for the deleted object to conflict.
1. If delete succeeded but create failed, this state should have been recorded in the backend state.
1. Should be able to retry without specifying --refresh.

### Example

```
> pulumi up
Previewing update (stack-name):
     Type                                  Name                     Plan        Info
     pulumi:pulumi:Stack                   stack-name              
     └─ kubernetes:core/v1:Namespace       namespace-name                              
 +-     ├─ kubernetes:apps/v1:StatefulSet  statefulset-name      replace     
 +-     └─ kubernetes:core/v1:Secret       statefulset-name      replace     [diff: ~data]

Resources:
    +-2 to replace
    81 unchanged

Do you want to perform this update? yes
Updating (stack-name):
     Type                                  Name                     Status                   Info
     pulumi:pulumi:Stack                   stack-name  **failed**               1 error
     └─ kubernetes:core/v1:Namespace       namespace-name                                           
 +-     ├─ kubernetes:apps/v1:StatefulSet  statefulset-name      **replacing failed**     1 error
 +-     └─ kubernetes:core/v1:Secret       statefulset-name      replaced (1s)            [diff: ~data]

Diagnostics:
  kubernetes:apps/v1:StatefulSet (statefulset-name):
    error: resource namespace-name/statefulset-name was not successfully created by the Kubernetes API server : Server-Side Apply field conflict detected. see https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#handle-field-conflicts-on-existing-resources for troubleshooting help
    : Apply failed with 1 conflict: conflict with "pulumi-kubernetes-c9fca446": .spec.volumeClaimTemplates

  pulumi:pulumi:Stack (stack-name):
    error: update failed

Resources:
    +-2 replaced
    81 unchanged

Duration: 14s
```

```
> kubectrl get sts/statefulset-name -n namespace-name
Error from server (NotFound): statefulsets.apps "statefulset-name" not found
```
```
> pulumi up
Previewing update (stack-name):
     Type                 Name                     Plan     
     pulumi:pulumi:Stack  stack-name           

Resources:
    83 unchanged
```
```
> kubectrl get sts/statefulset-name -n namespace-name
Error from server (NotFound): statefulsets.apps "statefulset-name" not found
```

### Output of `pulumi about`

CLI          
Version      3.90.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in nodejs: executable='/home/bitofsky/.nvm/versions/node/v18.12.0/bin/node' version='v18.12.0'

kubernetes  resource  4.5.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by bitofsky** [comment]
I manually set the annotation 'pulumi.com/patchFieldManager': 'my-custom-fieldmanager-name' on the StatefulSet and attempted the replace operation again.
This time, the replace operation succeeded, and I could not reproduce the issue steps.
I'm curious if the field manager can induce a conflict for objects being replaced.

**Comment by bitofsky** [comment]
Using a custom field manager prevents the error, but the resource still ends up in a deleted state. This seems to be a less desirable situation than having the error explicitly shown.

**Comment by rquitales** [comment]
@bitofsky Thanks for reporting this issue. To give me a better understanding, could you provide some sample code for me to investigate? Could you also clarify how a conflict is occurring and why a replacement is occurring. My understanding is that a typical update of a StatefulSet is that it should be in-place by default.
