### ISSUE TITLE
Installing Helm v3 Chart resource causes errors

### ISSUE THREAD

**Issue by scottslowe** [pulumi/pulumi-kubernetes#2638]
### What happened?

I was trying to use/update the [`kubernetes-go-helm-wordpress` example](https://github.com/pulumi/examples/tree/master/kubernetes-go-helm-wordpress) with the Kubernetes v4 provider. I kept getting this error:
```
error: an unhandled error occurred: program exited with non-zero exit code: 2

    panic: interface conversion: interface {} is nil, not *v1.Service
    goroutine 119 [running]:
    main.main.func1.1({0x0?, 0x0?})
    	/Users/slowe/Work/Code/testarea/main.go:24 +0x5c
```
Through additional testing, @rquitales verified that this is broken if the chart is installed into the "default" namespace, and is broken in preview for all namespaces. 

### Example

1. Stand up a Kubernetes cluster and obtain the Kubeconfig.
2. Clone or copy down the `kubernetes-go-helm-wordpress` example with the Kubernetes v4 provider.
3. With the Kubeconfig from step 1 active, run `pulumi up`. It should error during preview.

### Output of `pulumi about`

```
CLI
Version      3.88.0
Go Version   go1.21.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     6.5.0
awsx    2.0.2
docker  4.4.3
go      unknown

Host
OS       darwin
Version  13.5.2
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
We omit the namespace if it's `default` in the GetResource function: https://github.com/pulumi/pulumi-kubernetes/blob/f3498a9f3fccb9620cd9e46b6a09fce82a51444d/provider/pkg/gen/_go-templates/helm/v3/chart.go#L351-L353

We always need to include the namespace in generating the key. We should also double check the implementation for ConfigFile resources, and ensure it works as expected too!
