### ISSUE TITLE
setting ignoreChanges on patch resource causes fields not owned by Pulumi to be wiped out

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-kubernetes#2639]
### What happened?

Using a `DaemonsetPatch` resource to update a daemonset property such as `containers[0].image` results in Pulumi patch resource unsetting all other fields present in the daemonset when including ignoreChanges directives on unrelated fields such as spec.metadata.

### Example

1. create an EKS cluster so that kube-proxy daemonset exists
2. [kube-proxy-before-patch.txt](https://github.com/pulumi/pulumi-kubernetes/files/13171680/kube-proxy-before-patch.txt) - base manifest for the daemonset
3. Use the below program
```
package main

import (
	"encoding/json"
	// "github.com/pulumi/pulumi-aws/sdk/v6/go/aws"
	"github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes"
	appsv1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/apps/v1"
	corev1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/core/v1"
	metav1 "github.com/pulumi/pulumi-kubernetes/sdk/v4/go/kubernetes/meta/v1"
	p "github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	cfg "github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

func main() {
	p.Run(func(ctx *p.Context) error {

		sr, err := p.NewStackReference(ctx, "org/project/team", nil)
		if err != nil {
			return err
		}

		kubeconfig, err := sr.GetOutputDetails("kubeconfig")
		if err != nil {
			return err
		}

		k, err := json.Marshal(kubeconfig.Value)
		if err != nil {
			return err
		}

		provider, err := kubernetes.NewProvider(ctx, "k8s", &kubernetes.ProviderArgs{
			Kubeconfig: p.String(string(k)),
		})

		if err != nil {
			return err
		}

		c := cfg.New(ctx, "aws")
		region := c.Get("region")

		// account, err := aws.GetCallerIdentity(ctx, nil)
		// if err != nil {
		// 	return err
		// }

		latestContainerImage := p.Sprintf("602401143452.dkr.ecr.%s.amazonaws.com/eks/kube-proxy:v1.28.1-minimal-eksbuild.1", region)

		if _, err := appsv1.NewDaemonSetPatch(ctx, "kube-proxy-image",
			&appsv1.DaemonSetPatchArgs{
				Metadata: metav1.ObjectMetaPatchArgs{
					Name:      p.String("kube-proxy"),
					Namespace: p.String("kube-system"),
					Annotations: p.StringMap{
						"pulumi.com/patchForce": p.String("true"),
					},
				},
				Spec: appsv1.DaemonSetSpecPatchArgs{
					Template: corev1.PodTemplateSpecPatchArgs{
						Metadata: metav1.ObjectMetaPatchArgs{
							Labels: nil,
						},
						Spec: corev1.PodSpecPatchArgs{
							Containers: corev1.ContainerPatchArray{
								corev1.ContainerPatchArgs{
									Name:  p.String("kube-proxy"),
									Image: latestContainerImage,
									Command: p.ToStringArray([]string{
										"kube-proxy",
										"--hostname-override=$(NODE_NAME)",
										"--v=2",
										"--config=/var/lib/kube-proxy-config/config",
									}),
									Env: corev1.EnvVarPatchArray{
										corev1.EnvVarPatchArgs{
											Name: p.String("NODE_NAME"),
											ValueFrom: corev1.EnvVarSourcePatchArgs{
												FieldRef: corev1.ObjectFieldSelectorPatchArgs{
													FieldPath: p.String("spec.nodeName"),
												},
											},
										},
									},
								},
							},
						},
					},
				},
			}, p.Provider(provider), p.IgnoreChanges([]string{"spec.selector", "spec.template.metadata"})); err != nil {
			return err
		}

		ctx.Export("kubeconfig", p.String(k))
		return nil
	})
}

```
4. after pulumi up with the above patch, all fields not specified in the `DaemonsetPatch` are unset from the Daemonset.

### Output of `pulumi about`

NAME                                        VERSION
github.com/pulumi/pulumi-aws/sdk/v6         6.6.0
github.com/pulumi/pulumi-kubernetes/sdk/v4  4.5.1
github.com/pulumi/pulumi/sdk/v3             3.90.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
I was unable to replicate this.

Steps:

1. Create pristine EKS cluster (v1.24)
2. Save the kube-proxy daemon set manifest for comparison.
3. Run Pulumi up on the provided example
4. Save the kube-proxy daemon set manifest for comparison.

Here are the outputs. It looks as expected, with no fields being unset:
https://gist.github.com/rquitales/3e17080fa8ed6e220dfa6e239ccaf343

Let me know if there I'm missing something here.

**Comment by rquitales** [comment]
The repro was missing an additional step to cause this failure. We need to add another change (for example, to the image again) to cause an Update on the DaemonSetPatch resource. The initial pulumi up does a Create. It is in the Update logic/pathway that we force adopt all `kubectl` prefixed fields due to: https://github.com/pulumi/pulumi-kubernetes/blob/f3498a9f3fccb9620cd9e46b6a09fce82a51444d/provider/pkg/await/await.go#L470

This is required in non-patch resources to gracefully handle CSA -> SSA provider upgrades, but for patch resources, this SHOULD NOT occur as it will mistakenly result in unset fields as we observe in this GH issue.
