### ISSUE TITLE
CustomResource not available in Java package

### ISSUE THREAD

**Issue by trourance** [pulumi/pulumi-kubernetes#2671]
### What happened?

In pulumi kubernetes Java package, the object `CustomResource` is not available in`apiextensions` , but it is available in all other languages.

https://github.com/pulumi/pulumi-kubernetes/tree/master/sdk/java/src/main/java/com/pulumi/kubernetes/apiextensions

### Example

-

### Output of `pulumi about`

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mikhailshilkov** [comment]
This is tracked in https://github.com/pulumi/pulumi-kubernetes/issues/2274
