### ISSUE TITLE
Setting Env Variable `PULUMI_KUBERNETES_MANAGED_BY_LABEL` causes panic

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-kubernetes#2708]
### What happened?

When attempting to set the environment variable `PULUMI_KUBERNETES_MANAGED_BY_LABEL` fails with a panic `panic: interface conversion: interface {} is nil, not string`. 

### Example

[This repo](https://github.com/zbuchheit/pulumi-examples/blob/main/aws-eks-daemonPatch-stackReference/go-daemon-patch/main.go) was where I witnessed this behavior with 
```bash
PULUMI_KUBERNETES_MANAGED_BY_LABEL=pulumi-manager pulumi up
```

### Output of `pulumi about`

CLI          
Version      3.92.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME        VERSION
go          unknown
kubernetes  4.5.5

Host     
OS       darwin
Version  14.0
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.21.0 darwin/arm64'

Current Stack: zbuchheit-pulumi-corp/go-daemon-patch/dev

TYPE                               URN
pulumi:pulumi:Stack                urn:pulumi:dev::go-daemon-patch::pulumi:pulumi:Stack::go-daemon-patch-dev
pulumi:providers:pulumi            urn:pulumi:dev::go-daemon-patch::pulumi:providers:pulumi::default
pulumi:pulumi:StackReference       urn:pulumi:dev::go-daemon-patch::pulumi:pulumi:StackReference::zbuchheit-pulumi-corp/aws-ts-eks/dev
pulumi:providers:kubernetes        urn:pulumi:dev::go-daemon-patch::pulumi:providers:kubernetes::eks-kubernetes
kubernetes:apps/v1:DaemonSetPatch  urn:pulumi:dev::go-daemon-patch::kubernetes:apps/v1:DaemonSetPatch::k8s-daemonset-patch

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/zbuchheit-pulumi-corp
User           zbuchheit-pulumi-corp
Organizations  zbuchheit-pulumi-corp,
Token type     personal

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-kubernetes/sdk/v4  4.5.5
github.com/pulumi/pulumi/sdk/v3             3.92.0

### Additional context

I found this env variable in the `pulumi-kubernetes` repo [here](https://github.com/pulumi/pulumi-kubernetes/blob/037bde82c868711084689c0f59348bc00ce23827/provider/pkg/metadata/labels.go#L95) so attempted to use it. Worth noting I wasn't able to find this env variable documented anywhere.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Without digging too deep, I suspect this is due to the following line:
https://github.com/pulumi/pulumi-kubernetes/blob/037bde82c868711084689c0f59348bc00ce23827/provider/pkg/metadata/labels.go#L113

The panic occurs when we attempt to assert the Unstructured object's `app.kubernetes.io/managed-by` label value. In this case, `app.kubernetes.io/managed-by` is empty/nil, hence the panic, so we should handle this comparison in L113 by also ensuring it is not nil.

As an aside, @zbuchheit I was wondering what your intention was behind setting `PULUMI_KUBERNETES_MANAGED_BY_LABEL`?

**Comment by zbuchheit** [comment]
slightly related to #2692 I was investigating if the PULUMI_KUBERNETES_MANAGED_BY_LABEL environment variable could be used to set a field manager for server-side apply, hoping to find a way to manipulate that field without needing a code change. However, as you described and looking closer it is more about labeling resources rather than managing field ownership in server-side apply scenarios. So in this case, it doesn't do what I was attempting to accomplish, but since I came across the panic thought it would be best to open an issue for it regardless.
