### ISSUE TITLE
Update `guestbook-py` example to include full Guestbook

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#272]
The `guestbook-py` example is just a placeholder currently - we should update it to include a full working example of the Guestbook for test coverage.  We should also put a copy of this in the https://github.com/pulumi/examples repo.

**Comment by swgillespie** [comment]
I've got about half of this done already - once https://github.com/pulumi/pulumi-kubernetes/pull/266 works it will be a lot easier to add more Python tests such as guestbook to this repo.

**Comment by swgillespie** [comment]
Moving this out to M20, https://github.com/pulumi/pulumi-kubernetes/pull/288 is almost ready to land but is suffering from some infrastructure problems that we'll need to work around. The example does work, so we can be confident in this example for M19.

**Comment by lukehoban** [comment]
@hausdorff Think you can push this over the line for M19?  Would love to have this test in place since Python support for Kubernetes was a key feature we delivered this milestone.

**Comment by hausdorff** [comment]
I'll give it a shot. It seems like we _should_ be able to tell guestbook how to connect to the master with the downward API, but I won't know until I try.

**Comment by joeduffy** [comment]
@hausdorff Did you mean to close this as part of https://github.com/pulumi/pulumi-kubernetes/commit/1d8daf7bd10d2cb500c9902aa7f5b23a634ffbd1?

**Comment by hausdorff** [comment]
@joeduffy Oops, I did, yes.
