### ISSUE TITLE
Missing `objs` input property for `ConfigGroup` in Python SDK

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-kubernetes#2726]
### What happened?

In Python, There a resource called [`ConfigGroup`](https://www.pulumi.com/registry/packages/kubernetes/api-docs/yaml/configgroup/). This resource documentation shows an input property named `objs`.

However, vscode and Pylint report this property doesn't exist in the SDK for this provider.

```
Unexpected keyword argument 'objs' in constructor call Pylint(E1123:unexpected-keyword-arg)
```

However, using TypeScript as a different runtime and the property appears available.

As shown in vscode:
![image](https://github.com/pulumi/pulumi-kubernetes/assets/1161681/fc2c0da1-aaed-46a5-aa19-d9c1a49fd2e9)

### Example

Python code (invalid code)

```python
"""A Kubernetes Python Pulumi program"""

from pulumi_kubernetes.yaml import ConfigGroup

cg = ConfigGroup("example",
                 objs = {}
                 )
```

TypeScript code (valid code)
```typescript
import * as k8s from "@pulumi/kubernetes";

const cg = new k8s.yaml.ConfigGroup("example", {
    objs: {}
});
```

### Output of `pulumi about`

```
CLI          
Version      3.96.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME        VERSION
kubernetes  4.6.1
python      unknown

Host     
OS       debian
Version  12.4
Arch     x86_64

This project is written in python: executable='/home/aureq/work/customers/sekuro/k8s/venv/bin/python3' version='3.11.6'

Current Stack: menfin/zendesk/k8s-configgroup

Found no resources associated with k8s-configgroup

Found no pending operations associated with k8s-configgroup

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi
Token type     personal

Dependencies:
NAME               VERSION
pip                23.3.2
pulumi-kubernetes  4.6.1
setuptools         69.0.2
wheel              0.42.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EronWright** [comment]
I've confirmed that the `objs` property was simply not implemented in the Pulumi Python SDK. That said, the new `ConfigGroup` resource in the `pulumi_kubernetes.yaml.v2` module does support the `objs` property. This seems like a "won't fix" situation to me.
