### ISSUE TITLE
Flag for helm upgrade --install in v3.Release

### ISSUE THREAD

**Issue by awopenphone** [pulumi/pulumi-kubernetes#2763]
This was removed in 4.7.0 and I want it back. Having it allows much simpler CI/CD and updates to helm charts. I don't know how Pulumi expects users to manage automated helm deployments without this.

**Comment by mjeffryes** [comment]
Thanks for the issue @awopenphone; could you elaborate a bit on this request to give context? What was the name of the option that was removed in v4.7.0?
