### ISSUE TITLE
Improve error message of v3.release

### ISSUE THREAD

**Issue by awopenphone** [pulumi/pulumi-kubernetes#2764]
Attempting to install a previously installed chart fails with an unhelpful error message as seen here:

```
View in Browser (Ctrl+O): https://app.pulumi.com/openphone/event-stack/event/updates/26

     Type                              Name               Status         Info
     pulumi:pulumi:Stack               event-stack-event  **failed**     1 error
 ~   └─ kubernetes:helm.sh/v3:Release  event              updated        

Diagnostics:
  pulumi:pulumi:Stack (event-stack-event):
    error: update failed
```
    
This error message is unclear that the release is failing because Pulumi is using helm install and not helm upgrade and it could be made more clear as to why this is happening.

**Comment by EronWright** [comment]
@awopenphone could you elaborate on how to reproduce this issue? I observe that the Release resource was "updated", in what way?
