### ISSUE TITLE
pulumi-kubernetes.helm.v3.Release missing transformer

### ISSUE THREAD

**Issue by SnoozeFreddo** [pulumi/pulumi-kubernetes#2772]
As the title mentions there is no transformations arg. The python Chart resource does have it.

**Comment by mjeffryes** [comment]
Hi @SnoozeFreddo, the transformations option should be available inside the resource options for the the `Release` resource:

```
kubernetes.helm.Release("my_chart",..., opts=ResourceOptions(transformations=[transformation]))
```

**Comment by SnoozeFreddo** [comment]
@mjeffryes This doesn't work tho. I tried it out with the Chart and Release, i have to use transformations with

import pulumi


```
def ignore_changes_of_resources_deep(obj, opts: pulumi.ResourceOptions):
    opts.ignore_changes = ["*"]
```

**Comment by mjeffryes** [comment]
Please see the working example here:
https://github.com/mjeffryes/python-repros/blob/366bbb57d48d7fafc85a95287bc6b1c7cf29f09a/__main__.py
