### ISSUE TITLE
Resource deletion leaks a watcher

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes#2812]
### Problem description

The deletion logic seems to open a watcher that isn't necessarily closed.

https://github.com/pulumi/pulumi-kubernetes/blob/4a5bfcc516e127a51a096f34dc8797cd73a2bb30/provider/pkg/await/await.go#L739-L743

For resources that have a custom awaiter, the watcher appears to be leaked. 

### Suggestions for a fix

A simple deferred call to `watcher.Stop()` should suffice.

**Comment by blampe** [comment]
Fixed in https://github.com/pulumi/pulumi-kubernetes/pull/3133
