### ISSUE TITLE
Design/DEcision doc about whether to rely on the API server for status rather than doing it ourselves.

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-kubernetes#2829]

**Comment by rquitales** [comment]
We have decided to expand await to all resources by checking the object's status/ready conditions. We will not be updating the await logic to this approach for existing resources that we have custom await for. We may choose to revisit whether we deprecate custom await in the future - but the goal is to be able to expand awaiting without a major version release of the provider.
