### ISSUE TITLE
Release notes show raw markdown

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-kubernetes#2850]
### What happened?

It appears the latest release [`4.8.1`](https://github.com/pulumi/pulumi-kubernetes/releases/tag/v4.8.1) is showing raw markdown. I guess it should only show changes instead of the release template.

### Example

See https://github.com/pulumi/pulumi-kubernetes/releases/tag/v4.8.1

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by mjeffryes** [comment]
Yeah, the release notes for this repo just show the commit message for the last commit, which in this case it looks like we left the PR template in there.
