### ISSUE TITLE
render_yaml_to_directory option is really slow

### ISSUE THREAD

**Issue by akshanir** [pulumi/pulumi-kubernetes#2851]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I am trying to use pulumi as pure kubernetes yaml generator, but every run is really slow (minimum 20 seconds), one option is to leverage/utilize pulumi_k8s objects/classes even without using pulumi up/preview, and sense these classes have a 1-1 mapping with Kubernetes resources we can use them in this following way. 

```
deployment_args = DeploymentInitArgs( 
    metadata={
        "name": "nginx-deployment"
    },
    spec=DeploymentSpecArgs(
        replicas=1,
        selector=k8s.meta.v1.LabelSelectorArgs(match_labels=app_labels),
        template=k8s.core.v1.PodTemplateSpecArgs(
            metadata=k8s.meta.v1.ObjectMetaArgs(labels=app_labels),
            spec=k8s.core.v1.PodSpecArgs(
                containers=[
                    k8s.core.v1.ContainerArgs(
                        name="nginx",
                        image="nginx:1.14.2",
                        ports=[k8s.core.v1.ContainerPortArgs(container_port=80)]
                    )
                ]
            ),
        ),
    )
)

def recursive_vars(obj, depth=0, max_depth=100):
    if depth > max_depth:
        return str(obj)
    
    if isinstance(obj, (int, float, str, bool, type(None))):
        return obj
    
    if isinstance(obj, dict):
        return {humps.camelize(key): recursive_vars(value, depth + 1, max_depth) for key, value in obj.items()}
    
    if isinstance(obj, Sequence) and not isinstance(obj, (str, bytes)):
        iterable_type = type(obj)  # Attempt to preserve the original sequence type
        return iterable_type(recursive_vars(item, depth + 1, max_depth) for item in obj)
    
    if hasattr(obj, '__dict__'):
        return {humps.camelize(attr_name): recursive_vars(attr_value, depth + 1, max_depth) for attr_name, attr_value in vars(obj).items()}
    
    return str(obj)


deployment_dict = recursive_vars(deployment_args)

with open("./1-manifest/output_without_pulumi_sdk.yaml", 'w') as file:
    yaml.dump(deployment_dict, file, default_flow_style=False, sort_keys=True)

```
this will generate an exact match for the yaml manifests that is normally generated (since everything I am using is static), but I don't like doing this, is there a better way to do this?

**Comment by mjeffryes** [comment]
If you're set on avoiding running `pulumi up` I don't think we can suggest anything better than what you're doing. I wonder though about your comment of every run taking at least 20 seconds; that doesn't sound right to me. Have you tried running with verbose logging and [tracing](https://www.pulumi.com/docs/support/troubleshooting/#tracing) enabled to see where the time is going?
