### ISSUE TITLE
Design review for Chart MLC

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-kubernetes#2928]

**Comment by EronWright** [comment]
Here's a draft of the design doc:
https://docs.google.com/document/d/1_DZlsAyG4-3BxrAkJBj8R6wIVuzhAkxRDyq8k_Zcst4/edit?usp=sharing

I'm also working on a prototype to support the design effort (link to follow).

**Comment by EronWright** [comment]
Scheduled for Tuesday April 23, 2024.
