### ISSUE TITLE
Faulty resource update doesn't result in error of `pulumi up`

### ISSUE THREAD

**Issue by sfc-gh-jlangefeld** [pulumi/pulumi-kubernetes#2941]
### What happened?

When an update to existing k8s resources is made via `pulumi up`, it doesn't wait for readiness of that resource after the change, but takes the readiness before the change. This means that if a faulty update is made, the actual deployment is left in a bad state, with non-ready pods, without `pulumi up` failing. The example below makes the issue really clear.

We are currently blocked on this as we'd like to use Pulumi in CI/automation and we need it to report a failure if the rollout doesn't result in ready resources, otherwise we wouldn't get notified.

### Example

Here are some good steps to reproduce and to exemplify the behavior:

1. Create kind cluster via `kind create cluster`
2. Create the quickstart project as described in https://www.pulumi.com/docs/clouds/kubernetes/get-started/create-project/
3. Run `pulumi up`. This returns without error as expected
4. Ensure the created nginx pod is running:
    ```
    ╰─ kubectl get pods
    NAME                                READY   STATUS    RESTARTS   AGE
    app-dep-a7d946c6-7854ff8877-v94jd   1/1     Running   0          25m
    ```
5. Change the nginx image in `main.go` of the quickstart project to something that doesn't exist:
    ```diff
    -Image: pulumi.String("nginx"),
    +Image: pulumi.String("nginxfoobar"),
    ```
6. Run `pulumi up --refresh`. This returns without error, but it should return an error, because the new pod expectedly doesn't reach ready. Pulumi only checked the deployment readiness before the apply:
    ```
    ╰─ kubectl get pods
    NAME                                READY   STATUS         RESTARTS   AGE
    app-dep-a7d946c6-7854ff8877-v94jd   1/1     Running        0          28m
    app-dep-a7d946c6-798f4bbcf8-rwfd6   0/1     ErrImagePull   0          6s
    ```
7. Run `pulumi up --refresh` again (a second time). Now it times out as it should because pulumi saw the deployment non-readiness upon the refresh. An error can be forced after a certain time using the `pulumi.com/timeoutSeconds` annotation.

### Output of `pulumi about`

```
╰─ pulumi about
CLI
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME        VERSION
go          unknown
kubernetes  4.8.1

Host
OS       darwin
Version  14.4.1
Arch     arm64

This project is written in go: executable='/opt/homebrew/bin/go' version='go version go1.22.2 darwin/arm64'

Current Stack: jonny-langefeld/quickstart1/dev

TYPE                           URN
pulumi:pulumi:Stack            urn:pulumi:dev::quickstart1::pulumi:pulumi:Stack::quickstart1-dev
pulumi:providers:kubernetes    urn:pulumi:dev::quickstart1::pulumi:providers:kubernetes::default
kubernetes:apps/v1:Deployment  urn:pulumi:dev::quickstart1::kubernetes:apps/v1:Deployment::app-dep


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/jonny-langefeld
User           jonny-langefeld
Organizations  jonny-langefeld, snowflake
Token type     personal

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-kubernetes/sdk/v4  v4.8.1
github.com/pulumi/pulumi/sdk/v3             v3.108.1
```

### Additional context

We are planning to run pulumi in hands-off automation against many different clusters and we can't afford the example in step 6, where pulumi doesn't fail if the new resources actually didn't get ready. We'd need to error out in that case right away. So the behavior in step 7 should happen already upon the first try.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
This should now be resolved in v4.10.0 of the kubernetes provider.
