### ISSUE TITLE
Dev versions are not correctly published

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#295]
When we install dev versions of pulumi-kubernetes, Pulumi claims it can't find the Kubernetes provider. The root reason follows.

When we publish on [npm](https://www.npmjs.com/package/@pulumi/kubernetes), we have started a new versioning scheme. We publish to versions like [`v0.17.6-dev.1542840985`](https://www.npmjs.com/package/@pulumi/kubernetes/v/0.17.6-dev.1542840985), where previously we would publish versions like [`v0.17.5-dev-1542673869-gbc8bc53`](https://www.npmjs.com/package/@pulumi/kubernetes/v/0.17.5-dev-1542673869-gbc8bc53).

It seems that the Kubernetes provider is still being uploaded to S3 with a trailing hash (_i.e._, `v0.17.6-dev.1542840985+g067ef8a`, see build logs [here](https://travis-ci.com/pulumi/pulumi-kubernetes/builds/92225336#L1680)) and so when Pulumi tries to load something like `v0.17.6-dev.1542840985`, it fails to find the provider at all.

cc @ellismg I _think_ this is not correct behavior? Anyway it's blocking some of our customers.

**Comment by ellismg** [comment]
We fixed this in the CLI with this PR https://github.com/pulumi/pulumi/pull/2239, which was adopted to allow these sorts of versions to be loaded.

You should be able to install a dev build of the CLI (e.g. `curl -L https://get.pulumi.com/ | bash -s -- --version 0.16.6-dev.1542849043`) and pick up the fix.

**Comment by ellismg** [comment]
Going to close this since the problem was in the CLI and as far as I can tell it has been fixed.  If installing the above version of Pulumi does not resolve the issue, please re-open.

**Comment by lukehoban** [comment]
Should we publish a patch release of the CLI so that a released CLI works with dev builds?  That’s a reasonably common scenario for users, and much more common/easy to depend on dev packages than on a dev CLI.
