### ISSUE TITLE
`duplicate entries for key` when using `helm.v3.Chart`

### ISSUE THREAD

**Issue by ChristianRaoulis** [pulumi/pulumi-kubernetes#2961]
### What happened?

I'm trying to deploy [Bitnamis Keycloak Helm Chart](https://github.com/bitnami/charts/tree/main/bitnami/keycloak) using the `helm.v3.Chart` Class.

Deploying the chart causes an 
```
kubernetes:apps/v1:StatefulSet core-services/keycloak-chart create error: Preview failed: resource "urn:pulumi:testing::softwarefactory::kubernetes:core/v1:Namespace$kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:StatefulSet::core-services/keycloak-chart" was not successfully created by the Kubernetes API server : failed to create typed patch object (core-services/keycloak-chart; apps/v1, Kind=StatefulSet): .spec.template.spec.containers[name="keycloak"].ports: duplicate entries for key [containerPort=7800,protocol="TCP"]
```
error

### Example

```ts
import * as kubernetes from "@pulumi/kubernetes";

new kubernetes.helm.v3.Chart("keycloak", {
         chart:     "keycloak",
         fetchOpts: {
            repo: "https://charts.bitnami.com/bitnami",
         },
         values: {
            auth: {
               adminUser: "admin",
               adminPassword: "admin"
            },
         },
});
```

### Output of `pulumi about`

```
CLI          
Version      3.107.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME        VERSION
command     0.10.0
kubernetes  4.10.0
nodejs      unknown
postgresql  3.11.0
random      4.16.1

Host
OS       Microsoft Windows 11 Enterprise
Version  10.0.22621 Build 22621
Arch     x86_64

This project is written in nodejs: executable='C:\Users\A92615470\AppData\Local\pnpm\node.exe' version='v20.11.0'
```

### Additional context

I'm using the `Chart` instead of the `Release` because it allows me to access the resources generated by the helm chart.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
@ChristianRaouli This appears to be a bug in the Helm chart itself. The chart is declaring duplicate containerPort 7800 for `infinispan` and `discovery`. Please see the upstream bug (https://github.com/bitnami/charts/issues/25218) for more details.
