### ISSUE TITLE
K8 - Pulumi ESC Docs

### ISSUE THREAD

**Issue by arunkumar611** [pulumi/pulumi-kubernetes#2965]
### What happened?

We need to document ESC files and the way to use them to get K8 credentials: under https://www.pulumi.com/docs/esc/other-integrations/

Document this blog: https://www.pulumi.com/blog/esc-kubernetes-cluster-and-app/

Is there anything else we can provide a reference on how to use ESC within K8? 

### Example

...

### Output of `pulumi about`

...

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
Hi @arunkumar611. Just so I understand the request -- you'd like us to contribute API docs under https://www.pulumi.com/docs/esc/other-integrations/?

**Comment by arunkumar611** [comment]
@blampe  - yes, correct!

**Comment by EronWright** [comment]
I posted a PR and am awaiting review.
