### ISSUE TITLE
Difference in behavior on Windows : failed to determine if the following GVK is namespaced

### ISSUE THREAD

**Issue by jam-re** [pulumi/pulumi-kubernetes#2967]
### What happened?

The following object causes the following error when using Pulumi up on Windows (tested on 3.113.0 and 3.113.2) while on Linux no such error is displayed :

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{args["name"]}"
  namespace: "{args["ns"]}"
spec:
(...)
```

Provider is pulumi-kubernetes
CRD in question : https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_secretstores.yaml

` Exception: marshaling properties: awaiting input property "resources": failed to determine if the following GVK is namespaced: external-secrets.io/v1beta1, Kind=ExternalSecret`

### Example

See above

### Output of `pulumi about`

CLI                  
Version      3.113.2 
Go Version   go1.22.2
Go Compiler  gc      

Host                                    
OS       Microsoft Windows 10 Enterprise
Version  10.0.19045 Build 19045         
Arch     x86_64                         
                                        
Backend                                 
Name           REDACTED                     
URL            file://~                 
User           REDACTED
Organizations                           
Token type     personal

Pulumi locates its logs in C:\Users\REDACTED\AppData\Local\Temp\1 by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EronWright** [comment]
This error represents a failure to lookup the `ExternalSecret` CRD in the Kubernetes cluster, in using `v2.ConfigGroup` or `v1.ConfigFile`. I think you may have hit upon a limitation that we'll resolve soon.  I would recommend you use the older `ConfigGroup` or `ConfigFIle` for now.

I have some questions for @jam-re, thanks!
1. Is this error appearing during preview or during the update?
2. How are you installing the External Secrets Operator? Is it pre-installed or is the same Pulumi program installing it?  Which resource are you using, maybe a Helm `Chart` or `Release`?

**Comment by mjeffryes** [comment]
@EronWright Am I right in thinking this should be fixed now?
