### ISSUE TITLE
Improve SSA conflict error by including the pulumi manager name.

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-kubernetes#2968]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Whenever users hit a SSA conflict error they seem to be a bit confused and not fully grasp what is going on behind the scenes. I think the error message does a good job pointing them to the documentation, but I think adding in the Pulumi manager name would help drive home what is going on.

Instead of 
`Apply failed with 1 conflict: conflict with "kubectl"`

maybe something like 
`Apply failed with 1 conflict: manager "pulumi-kubernetes-xxxxxxxx" conflict with "kubectl"`

I think something like the following would help highlight there is a pulumi manager attempting to be used and it is conflicting with the existing manager.

**Comment by blampe** [comment]
Just to confirm, does the full error you're seeing look like this?

```
Server-Side Apply field conflict detected. see "https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/#handle-field-conflicts-on-existing-resources for troubleshooting help
Apply failed with 1 conflict: conflict with "kubectl"
```

I think the "Apply failed" message is coming from upstream here:

https://github.com/kubernetes/kubernetes/blob/3d58fe5a7bae1b7517dcf24fbdffc2b13e3c5fef/staging/src/k8s.io/apimachinery/pkg/util/managedfields/internal/conflict.go#L45-L71

Let's assume we can't change that for now. We _can_ preface this with some additional information like:

```
The resource has been modified by something other than Pulumi: Apply failed with 1 conflict: conflict with "kubectl"
```

Would something like that be helpful?

**Comment by zbuchheit** [comment]
Yes that is the error I witness, and I think your proposed solution makes sense. 😄

**Comment by rquitales** [comment]
I'm not sure if `something other than Pulumi` is an accurate statement for all scenarios. We could have 2 Pulumi resources/programs/stacks managing the same underlying object resulting in a conflict between Pulumi field managers.
