### ISSUE TITLE
Migration strategy for URNs whose group name changes

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#298]
The Kubernetes OpenAPI spec regularly changes the names of groups, _e.g._, `apiregistration` -> `apiregistration.k8s.io`. This is unfortunate because it causes us to change our URNs.

We should develop an aliasing strategy so that we can keep URNs up-to-date without breaking everyone using them.

A couple options off the top of my head:

* Maintain a table of mappings from group name -> "URN group name", and keep emitting the latter. I _really_ do not like making the URNs having a different form from the k8s API, though.
* Find a way to do aliasing in the engine itself, maybe? So the engine would understand both `apiregistration` and `apiregistration.k8s.io`, but we could mark the former as deprecated, or something.

cc @lukehoban @lblackstone

**Comment by pgavlin** [comment]
Is this solved with aliases?

**Comment by hausdorff** [comment]
This very likely can be solved with aliases. We still have to hook this up in the SDK. But, this happens sufficiently rarely (and will continue to be more rare as time goes on) that it's probably not worth doing in Q3.

**Comment by lukehoban** [comment]
@lblackstone Is there anything remaining to do here?
