### ISSUE TITLE
Docs for Chart v4

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-kubernetes#2993]
- [x] API Docs (chartv4.md)
- [x] ["Choosing" guide](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/choosing-the-right-helm-resource-for-your-use-case/)

**Comment by EronWright** [comment]
I prepared a PR to update the venerable guide to "Choosing the Right Helm Resource" for Chart v4.  Once we release v4 and merge the guide, we can close this issue.
