### ISSUE TITLE
ReplicaSets are orphaned

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#30]
I've noticed that when I bring up and tear down a program using `kubernetes.Deployment`, the `Deployment` itself is removed, but the `ReplicaSet` that was created by the `Deployment` gets orphaned in the cluster.

Not sure whether this is a Kubernetes issue, a `terraform-provider-kubernetes` issue, or something we should be trying to explicitly compensate for in our layer.

**Comment by hausdorff** [comment]
This should not be a bug any more, since we no longer depend on TF for Kubernetes.

**Comment by ami-descope** [comment]
how does this still happening?
