### ISSUE TITLE
Circular dependency between Service and StatefulSet with auto-name

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#303]
I hit a circular dependency with the Service awaiter when I was creating a Service + StatefulSet.

Here's the offending code:
```ts
const ssLabels = {app: `ss-test`};
export const ssService = new k8s.core.v1.Service("statefulservice", {
    spec: {
        ports: [{port: 80, name: "web"}],
        clusterIP: "None",
        selector: ssLabels,
    }
}, {provider: k8sProvider});

export const ss = new k8s.apps.v1.StatefulSet("statefulset", {
    metadata: {labels: ssLabels},
    spec: {
        selector: {matchLabels: ssLabels},
        serviceName: ssService.metadata.apply(s => s.name),
        replicas: 3,
        template: {
            metadata: {labels: ssLabels},
            spec: {
                terminationGracePeriodSeconds: 10,
                containers: [
                    {
                        name: "nginx",
                        image: "nginx",
                        ports: [
                            {
                                containerPort: 80,
                                name: "web"
                            }
                        ],
                        volumeMounts: [
                            {
                                name: "www",
                                mountPath: "/usr/share/nginx/html"
                            }
                        ]
                    }
                ],
            },
        },
        volumeClaimTemplates: [
            {
                metadata: {name: "www"},
                spec: {
                    accessModes: ["ReadWriteOnce"],
                    resources: {requests: {storage: "1Gi"}}
                }
            }
        ]
    },
}, {provider: k8sProvider});
```

The problem is that the Service was stuck waiting for pods, but the StatefulSet was waiting for the Service so that it could set the `serviceName`.
https://github.com/pulumi/pulumi-kubernetes/blob/bd7765d3b51d47c057114cb17aeb57091fe1ff63/pkg/await/core_service.go#L217

Manually setting `.metadata.name` on the Service, and `.spec.serviceName` on the StatefulSet worked as expected.

**Comment by hausdorff** [comment]
We do have an escape hatch with the `skip-await` logic, but this has a high likelihood of tripping up anyone who manually authors something like this. I'm actually not sure what we want to do here in core...

**Comment by lblackstone** [comment]
A couple of thoughts here:

1. We've run into a few problems with the Service await logic. We might want to consider if it makes sense to have a blocking wait for pods, or if that could be changed to a warning or something.
1. If the Service was not blocking here, this should have eventually resolved correctly.

**Comment by hausdorff** [comment]
For the peanut gallery:

* There is a work-around in the form of the `skip-await` annotation above.
* In the future, we do plan to offer more fine-grained await primitives (_e.g._, `skip-pod-await` or something which signals to wait for the service to initialize, but not for it to connect to pods).
* We won't be getting to this in Q3, so I'm removing the tag.

**Comment by geekofalltrades** [comment]
I ran into this exact issue today, and I don't think auto-naming is related. I did something like this (using the Python SDK):

```python
etcd_service = corev1.Service(
    "etcd",
    metadata={
        "name": "etcd",
    },
)

etcd_statefulset = appsv1.StatefulSet(
    "etcd",
    spec={
        "serviceName": etcd_service.metadata["name"],
    },
)
```

I hit exactly the same issue.
