### ISSUE TITLE
helm.v3.Chart fails to preview the changes to the Job

### ISSUE THREAD

**Issue by kirgene** [pulumi/pulumi-kubernetes#3034]
### What happened?

Preview failed when upgrading a helm chart (using `helm.v3.Chart`) that creates a `Job` resource
```
Preview failed: resource ...
was not successfully created by the Kubernetes API server:
Job.batch "argo-cd-argocd-redis-secret-init" is invalid: spec.template: Invalid value: .... 
field is immutable
```

`pulumi up -f` works fine

### Example

Use the following code to install the helm chart

```
from pulumi_kubernetes.helm.v3 import Chart, ChartOpts, FetchOpts

chart = Chart(
        'argo-cd',
        ChartOpts(
            chart='argo-cd',
            version='6.11.1',
            namespace='argo-cd',
            fetch_opts=FetchOpts(repo='https://argoproj.github.io/argo-helm'),
        )
    )
```

Then change the `version` and run `pulumi preview`

### Output of `pulumi about`

CLI          
Version      3.117.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  kubernetes  4.12.0
language  python      unknown
resource  tls         5.0.3

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
Hi @kirgene, it looks like the chart you're using has [lifecycle hooks](https://github.com/argoproj/argo-helm/blob/2c05baf7416bfac007540a16713240624c3d0bce/charts/argo-cd/templates/redis-secret-init/job.yaml#L8-L9) for this job, and the Pulumi `Chart` resource doesn't support those hooks.

We recommend using the `Release` resource instead which does support hooks. You can learn more about the difference between `Chart` and `Resource` [here](https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/choosing-the-right-helm-resource-for-your-use-case/).

**Comment by kirgene** [comment]
Hi @blampe , using Release is not an option as it doesn't support remediation of the broken/altered helm resources in the cluster.
As I mentioned, `pulumu up -f` creates all resources, including ones that are part of lifecycle hooks.

**Comment by EronWright** [comment]
I have confirmed that Chart v3 does include hook resources, whereas Chart v4 doesn't. Looks like we deliberately include hooks in v3 (see https://github.com/pulumi/pulumi-kubernetes/issues/1335) but I wouldn't say that it works correctly. I would argue that it is correct to not include hooks in v4 unless/until they're fully supported, e.g. with the correct ordering.
