### ISSUE TITLE
copy paste from doc fails invalid syntax

### ISSUE THREAD

**Issue by davidxmh** [pulumi/pulumi-kubernetes#3040]
### What happened?

Using example from doc fails 

```
import pulumi
import pulumi_kubernetes as kubernetes

service = kubernetes.core.v1.Service("service",
    metadata=kubernetes.meta.v1.ObjectMetaArgs(
        name="my-service",
    ),
    spec=kubernetes.core.v1.ServiceSpecArgs(
        ports=[kubernetes.core.v1.ServicePortArgs(
            port=80,
            protocol="TCP",
            target_port=9376,
        )],
        selector={
            "app": "MyApp",
        },
    ))
``` 

from https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/service/ 

### Example
```

Diagnostics:
  pulumi:pulumi:Stack (inference-service-dev):
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/Users/davidx/code/inference-service/deploy/app/./__main__.py", line 28, in <module>
        from pulumi_kubernetes.core.v1 import Service, ServiceSpec, ServicePort
    ImportError: cannot import name 'ServiceSpec' from 'pulumi_kubernetes.core.v1' (/Users/davidx/code/inference-service/deploy/app/venv/lib/python3.10/site-packages/pulumi_kubernetes/core/v1/__init__.py)

```

### Output of `pulumi about`

```

CLI          
Version      3.113.3
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  docker      4.5.4
resource  gcp         7.20.0
resource  kubernetes  4.12.0
language  python      unknown

Host     
OS       darwin
Version  14.4.1
Arch     arm64

This project is written in python: executable='/Library/Frameworks/Python.framework/Versions/3.12/bin/python3' version='3.12.2'

<snip>

Dependencies:
NAME               VERSION
pip                24.0
pulumi_docker      4.5.4
pulumi_gcp         7.20.0
pulumi_kubernetes  4.12.0
setuptools         69.5.1
wheel              0.43.0

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Hi @davidxmh, I can't reproduce the issue described here. Using Python v3.10 and `pulumi-kubernetes` v4.12.0, I'm able to create the resources from the example documentation without any problems.

From the error message you provided, it seems that your Pulumi program might not match the examples exactly. Specifically, I noticed you have these imports: `from pulumi_kubernetes.core.v1 import Service, ServiceSpec, ServicePort`. However, `ServiceSpec` and `ServicePort` are NOT valid types to import in your Pulumi program. You should use `ServiceSpecArgs` and `ServicePortArgs` instead.

Please let me know if this solves your issue. Thanks.

**Comment by rquitales** [comment]
As there isn't any additional updates on this, and we believe the issue can be resolved per suggestions in https://github.com/pulumi/pulumi-kubernetes/issues/3040#issuecomment-2145962602, I'll be closing this issue. Please feel free to re-open if this is not the case. Thanks!
