### ISSUE TITLE
`pulumi preview` patching issues

### ISSUE THREAD

**Issue by alayshia** [pulumi/pulumi-kubernetes#3094]
### What happened?

`pulumi preview` **updates** Kubernetes custom resource definitions while it only supposed to **patch** them in dry-run mode. 

### Example

```
import * as eks from '@pulumi/eks'; // 1.0.4
import * as k8s from '@pulumi/kubernetes'; // 4.7.1
import * as pulumi from '@pulumi/pulumi'; // 3.119.0

const cluster = new eks.Cluster('eks-cluster', {});

const k8sProvider = new k8s.Provider('eks-provider', {
    context: 'aws',
    kubeconfig: cluster.kubeconfig.apply(JSON.stringify),
    enableServerSideApply: false, // CRDs get updated regardless of the value
});

new k8s.helm.v3.Chart('karpenter-crds', {
    chart: '',
    version: '0.36.2', // alternate between '0.36.2' and '0.37.0'
    namespace: 'kube-system',
    transformations: [
        function (obj: any, _opts: pulumi.CustomResourceOptions): void {
            if (obj.kind !== "CustomResourceDefinition") {
                obj.apiVersion = "v1";
                obj.kind = "List";
            }
        }
    ],
}, { provider: k8sProvider });
```

1. `pulumi up` using `0.37.0`
2. `kubectl` to get manifest
3. `pulumi preview` with version `0.36.2`
4. `kubectl` to check if manifest has changed

### Output of `pulumi about`

'@pulumi/eks'; // 1.0.4
 '@pulumi/kubernetes'; // 4.7.1
 '@pulumi/pulumi'; // 3.119.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Our provider is not specifying the `dryRun` option here: https://github.com/pulumi/pulumi-kubernetes/blob/b6ede27fbf54aa70018cf3cca67a1110480265d8/provider/pkg/await/await.go#L499 resulting in previews always applying the resource on cluster. Thanks for reporting this issue!
