### ISSUE TITLE
Customer is blocked after updating `kube-prometheus-stack`

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-kubernetes#3108]
### Summary

Customer was on `v45.21.0` of the `kube-prometheus-stack` (https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) and has updated to `v54.2.2`. They are now seeing this error message when they try to run a preview:

```
Error:-
Diagnostics:
  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition (prometheusrules.monitoring.coreos.com):
    error: customresourcedefinitions.apiextensions.k8s.io "prometheusrules.monitoring.coreos.com" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

and are not able to run any more updates against this project/stack.

### Details

They are doing this using two Helm Chart resources and are using them in this fashion:

```typescript
const promCRDChat = new k8s.helm.v3.Chart("prometheuscrds", {
    fetchOpts: {
        repo: "https://prometheus-community.github.io/helm-charts",
        version: "54.2.2"
    },
    namespace: prometheusNamespace.metadata.name,
    chart: "kube-prometheus-stack",
    values: {
        ...
    },
    transformations: [
        (obj: any) => {
          if (obj.kind !== 'CustomResourceDefinition') {
            obj.apiVersion = 'v1';
            obj.kind = 'List';
          }
        }
      ]
});

const promChart = new k8s.helm.v3.Chart("prometheus", {
    fetchOpts: {
        repo: "https://prometheus-community.github.io/helm-charts",
        version: "54.2.2"
    },
    namespace: prometheusNamespace.metadata.name,
    chart: "kube-prometheus-stack",
    values: {
        ...
    },
    transformations: [
        (obj: any) => {
          if (obj.kind === 'CustomResourceDefinition') {
            obj.apiVersion = 'v1';
            obj.kind = 'List';
          }
        }
      ]
}, {dependsOn: [promCRDChat]});
```

so the first chart resource deploys the CRDs and the second deploys everything that's _not_ a CRD.

This method has worked for them previously when updating the chart versions until now.

It's worth also pointing out that they are setting `enableDryRun` on the Kubernetes provider.

### Reproducing this error

I've been unable to reproduce this. I've set up an EKS cluster, deployed the prometheus helm chart using the "two resource" method as detailed above and using the same versions of the CLI, the `@pulumi/pulumi` SDK and the `@pulumi/kubernetes` SDK, then updated the versions of the helm charts and re-deployed and haven't seen this error message. 

### Output of `pulumi about`

They are on the following versions of CLI/SDKs:

```
Pulumi CLI: v3.111.1
@pulumi/pulumi: v3.72.0
@pulumi/kubernetes: v3.29.1
Kubernetes: v1.28
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
It would help to know what their `prometheusrules.monitoring.coreos.com` CRD looks like.

**Comment by pierskarsenbarg** [comment]
Yaml from the cluster or json from the state (or both)?

**Comment by pierskarsenbarg** [comment]
Closing this ticket as customer is updating kubernetes package to >v4.3.0 (this was the release where we started stripping out the `resourceVersion`)
