### ISSUE TITLE
Enable schemagen to be used as a library

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-kubernetes#3121]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

The schemagen code which converts OpenAPI specs to a Pulumi schema is used when upgrading the kubernetes provider. It would also be helpful if this code can be generalized and used as a library (for example, when generated SDKs for CRDs).

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3431
