### ISSUE TITLE
Implement Parameterize RPC method

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-kubernetes#3122]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We need to implement the `Parameterize` gRPC methods within the Kubernetes provider to enable the first steps of generating typed SDKs for CRDs.

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3431
