### ISSUE TITLE
Schemagen should be able to recursively generate types

### ISSUE THREAD

**Issue by rquitales** [pulumi/pulumi-kubernetes#3149]
## Issue details

The current obtained Kubernetes schemas have flat objects, and nested objects are not inlined. Schemagen works fine on such upstream OpenAPI specs. However, CRDs tend to have inlined object definitions that schemagen will treat as an unstructured object, thus making the generated types lossy. We should enable recursive generating nested object types.

### Affected area/feature

Codegen

**Comment by cleverguy25** [comment]
Added to epic https://github.com/pulumi/home/issues/3431
