### ISSUE TITLE
Field is immutable error when Helm updates jobs

### ISSUE THREAD

**Issue by mrbrownt** [pulumi/pulumi-kubernetes#316]
I'm deploying Consul and Wordpress via helm, both of these charts use jobs to test the deployment. When running a new deployment Pulumi is issuing an update to the job definition and k8s responds with a field is immutable warning. This should be fixable by using a replace.

**Comment by hausdorff** [comment]
@mrbrownt Thanks for your patience -- last week was KubeCon and therefore very busy for us.

This is pretty easy to fix, it's just an oversight. I'll try to get something out shortly.

**Comment by hausdorff** [comment]
Taking this over, since Levi is basically out until M21.
