### ISSUE TITLE
Helm Chart resource inputs not exposed as outputs

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi-kubernetes#3165]
### What happened?

From what I can tell, it appears that accessing inputs on the `Chart` resource is either not supported, or is not exposed in the SDK properly - completions show a few available attributes and methods, but none of them are the resource inputs to the Chart itself - all other Pulumi resources (that I know of) expose their inputs as outputs, but this contract appears to fail for `Chart`.

### Example

Here's what Zed shows for available completions on Chart - TS agrees:

![Image](https://github.com/user-attachments/assets/ee4432eb-d8bf-4a13-923f-e51aed9c3a30)

### Output of `pulumi about`

```
CLI
Version      3.127.0
Go Version   go1.22.5
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  command       0.9.2
resource  docker        4.5.1
resource  docker-build  0.0.2
resource  gcp           7.7.1
resource  kubernetes    4.17.0
language  nodejs        unknown
resource  random        4.15.1

Host
OS       darwin
Version  14.3.1
Arch     arm64

This project is written in nodejs: executable='/Users/kylepitzen/.nvm/versions/node/v18.17.1/bin/node' version='v18.17.1'

Current Stack: substrate/substrate/dev

TYPE                                                          URN
<snip>


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/kpitzen-substrate
User           kpitzen-substrate
Organizations  kpitzen-substrate, substrate
Token type     personal

Dependencies:
NAME                  VERSION
@types/node           18.19.14
@pulumi/docker-build  0.0.2
@pulumi/pulumi        3.105.0
@pulumi/gcp           7.7.1
@pulumi/kubernetes    4.17.0
@pulumi/random        4.15.1
yaml                  2.4.1
@pulumi/command       0.9.2
@pulumi/docker        4.5.1

Pulumi locates its logs in /var/folders/bf/qxb5fznd3rg02wh4kfvq3r1w0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EronWright** [comment]
Which version of `Chart` are you referring to, `v3` or `v4`?

You are correct that the `Chart` resource doesn't mirror its inputs as outputs, it is 'by design' but could be revisited. Could you explain the use-case?

**Comment by kpitzen** [comment]
If it _is_ by design, it'd be great for that to be documented somewhere.  It's a design decision that breaks a contract adhered to by every other type of resource that I'm aware of.
