### ISSUE TITLE
Ingress error with ExternalName Service

### ISSUE THREAD

**Issue by jam13** [pulumi/pulumi-kubernetes#317]
I am creating an Service of type ExternalName along with an Ingress that uses it like this:
```
const service = new k8s.core.v1.Service("foo", {
    metadata: {
        name: "foo",
        namespace: "default",
    },
    spec: {
        type: "ExternalName",
        externalName: "foo.s3-website-eu-west-1.amazonaws.com",
        ports: [
            {
                port: 80,
            },
        ],
    },
}, {provider: k8sProvider});

const ingress = new k8s.extensions.v1beta1.Ingress("foo", {
    metadata: {
        annotations: {
            "kubernetes.io/ingress.class": "traefik",
            "traefik.frontend.passHostHeader": "false",
            "traefik.frontend.priority": "1"
        },
        name: "foo",
        namespace: "default",
    },
    spec: {
        rules: [
            {
                host: "*.example.com",
                http: {
                    paths: [
                        {
                            backend: {
                                serviceName: "foo",
                                servicePort: 80,
                            },
                            path: "/",
                        },
                    ],
                },
            },
        ],
    },
}, {provider: k8sProvider});
```

Both are created correctly, and it works as expected (all incoming traffic to *.example.com is proxied to an S3 bucket), however Pulumi hangs with this error:
```
error: No matching service found for ingress rule: "/"
```

It appears that it's not considering Services of this type as a valid target.

**Comment by lblackstone** [comment]
Yes, this appears to be an oversight in the provider code. I'll get this fixed shortly.

**Comment by hausdorff** [comment]
Taking over while Levi is out, this should be pretty easy to get merged in over the next few days.

**Comment by dragosbulugean** [comment]
If it helps, same thing happens with 
```"kubernetes.io/ingress.class": "nginx"```

**Comment by hausdorff** [comment]
@dragosbulugean Sorry, I'm not sure I understand. This issue should arise regardless of the annotation, as long as the `Ingress` points at a `v1/Service` whose type is `ExternalName`, right? Is there something special about the annotation that you believe is causing us to handle that case incorrectly?

If so, please open another issue -- this one is about to close.
