### ISSUE TITLE
Await for CRDs

### ISSUE THREAD

**Issue by ecerulm** [pulumi/pulumi-kubernetes#3188]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

On a setup were you have a `kubernetes.helm.v3.Release` that will install CRDs if you have a `kubernetes.yaml.v2.ConfigGroup` that will create resources using those CRDs there is no wait to really wait for those CRDs. You can use `depends_on=` to set the dependencies, but pulumi won't really wait and will try to create the resource from the `ConfigGroup` right away. 

For example in a pulumi stack that installs kapenter and a karpenter's nodepool I will get : 
```
Exception: marshaling properties: awaiting input property "resources": failed to determine if the following GVK is namespaced: karpenter.sh/v1, Kind=NodePool
``` 

This problem can be workaround today by using `time.Sleep` to force a wait period betwen the karpenter `Release` and the `ConfigGroup` 

```
wait30_seconds = time.Sleep(
    "wait30Seconds",
    create_duration="30s",
    opts=pulumi.ResourceOptions(depends_on=[karpenter]),
)

```

But it would be better if pulumi could identify somehow the helm chart includes crds and wait for those to "appear" in the Kubernetes API.

**Comment by blampe** [comment]
Hi @ecerulm. Can you clarify how this differs from https://github.com/pulumi/pulumi-kubernetes/issues/3176? It sounds very similar -- a v3 `Release` to install CRDs which are consumed by a v2 `ConfigGroup`.

As I shared in the Community Slack, the more general issue of waiting for CRDs was address very recently and is available for alpha testing if you'd like to give it a try. Pin to version 4.18.0-alpha.1724335757 and consult the [changelog](https://github.com/pulumi/pulumi-kubernetes/blob/0f834c8b0d89e0003f0dc2d527d4ca8e2cde26e9/CHANGELOG.md#added) for more details regarding `PULUMI_AWAIT_ALL` and the `pulumi.com/waitFor` annotation.

**Comment by ecerulm** [comment]
Can you believe that I forgot I already wrote #3176?
