### ISSUE TITLE
PodsMetricSource has "metric" attribute but typedDict complains about it and only accepts "name" instead

### ISSUE THREAD

**Issue by danielgruber99** [pulumi/pulumi-kubernetes#3225]
File: [themes/default/content/registry/packages/kubernetes/api-docs/autoscaling/v2/horizontalpodautoscaler/_index.md](https://www.pulumi.com/registry/packages/kubernetes/api-docs/autoscaling/v2/horizontalpodautoscaler/)

**Comment by blampe** [comment]
@danielgruber99 thanks for reporting this. We need some more information to help us understand the issue. For example what does your resource look like? What version of the provider are you using?
