### ISSUE TITLE
Unable to set Helm values to null in Go

### ISSUE THREAD

**Issue by mrlnstpn** [pulumi/pulumi-kubernetes#3234]
### What happened?

I tried to override the default value of CPU limit using `null` but it gives me `999m`, other test along with this was I tried as well to use the `AllowNullValues` but it doesn't work as well, it says 
```pulumi:pulumi:Stack (Platform-playground-mresa):
    panic: fatal: A precondition has failed for vsrc: value must be valid`
```

I'm using https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/#kubernetes-helm-sh-v3-release

### Example

```
    resources:
      requests:
        cpu: 10m
        memory: 200Mi
      limits:
        cpu: null
        memory: 200Mi

### Output of `pulumi about`

CLI          
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure         5.89.0
resource  azure-native  2.63.0
resource  azure-native  2.63.0
resource  azure-native  2.63.0
resource  azure-native  2.63.0
resource  azure-native  2.63.0
resource  azure-native  2.63.0
resource  azure-native  2.63.0
resource  azure-native  2.63.0
resource  azuread       5.53.4
language  go            unknown
resource  kubernetes    3.30.2
resource  rancher2      3.9.0

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
@mrlnstpn can you include the full Helm resource you're using in your program? That will help us reproduce this. The underlying issue is probably tracked in https://github.com/pulumi/pulumi-kubernetes/issues/2997.

**Comment by dkrieger** [comment]
@mjeffryes re-open this issue, please. it is well documented across multiple languages https://github.com/pulumi/pulumi-kubernetes/issues/2997 (this list, plus apparently python per https://github.com/pulumi/pulumi-kubernetes/issues/3178#issuecomment-2538511024 ). the requirements to reproduce this are clear: pick a helm chart with a default value (e.g. cpu limit), attempt to override with nil, observe that nothing happens. the root cause seems to be confirmed elsewhere

**Comment by guineveresaenger** [comment]
@dkrieger - you are correct, this issue should have remained open or at least become a duplicate. This should be fixed via 34293; please watch for the next release.
