### ISSUE TITLE
Add k8s.yaml.* support to Python SDK

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#325]

**Comment by lblackstone** [comment]
Split helm work out into #464

**Comment by lblackstone** [comment]
This work is close to done, but I won't be finished by tomorrow. Moving to M22

**Comment by 4c74356b41** [comment]
its not exactly clear when is 0.22 going to be released? milestone page says its 4 days overdue?

**Comment by hausdorff** [comment]
@4c74356b41 Milestones don't actually correlate to releases. We basically release whenever we feel like we should (_cf._, two weeks ago). I'm guessing we'll cut another release today or tomorrow, though.
