### ISSUE TITLE
Create a no-op helm.v4.Release resource

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-kubernetes#3263]
As revealed in this comment, https://github.com/pulumi/pulumi/issues/5961#issuecomment-2405613395, users can misinterpret the fact that there is a v4.Chart, but not a v4.Release to mean that Release is somehow not as up-to-date as rather than just a different tool. 

While we could try to solve this with by adding some disclaimers to the docs, it's probably simpler to just create bump release to helm.v4.Release and create an alias for v3.Release.

**Comment by EronWright** [comment]
Some possible changes to incorporate:
1. consistent handling of values
2. use server-side dry-run
3. schema alignment w.r.t. Chart/v4
4. implement the post-renderer args as seen in Chart/v4 (https://github.com/pulumi/pulumi-kubernetes/issues/1952)
5. use the same utility code in tool.go
7. helm release to advertise the crds
8. updated helm dependencies (https://github.com/pulumi/pulumi-kubernetes/issues/702)
9. "resources" output property (https://github.com/pulumi/pulumi-kubernetes/issues/1701)
10. chart path resolution (https://github.com/pulumi/pulumi-kubernetes/issues/2409)
11. dependency resolution (https://github.com/pulumi/pulumi-kubernetes/issues/2669)
12. update docs for v4 (https://github.com/pulumi/pulumi-kubernetes/issues/2358)
13. asset values (https://github.com/pulumi/pulumi-kubernetes/issues/2145)
14. import issues (https://github.com/pulumi/pulumi-kubernetes/issues/2116)

**Comment by EronWright** [comment]
Upon discussion with @mjeffryes , we will use this ticket to make doc changes to clarify that Release/v3 is the 'latest' version of the resource and that it is not deprecated.

Meanwhile we'll work towards a full-featured v4 resource as outlined here:
https://github.com/orgs/pulumi/projects/223/views/2
