### ISSUE TITLE
Release with v3.136.1 or higher SDK generators

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-kubernetes#3264]
### What happened?

The code generators have been upgraded to v3.136.1 or higher on the integration branch but these changes have not been released yet.  Please make a release of the latest version when appropriate. This should prevent panics around invokes.

Context in https://github.com/pulumi/ci-mgmt/issues/1104

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
Fixed in https://github.com/pulumi/pulumi-kubernetes/pull/3268
