### ISSUE TITLE
kubectl get endpointslices

### ISSUE THREAD

**Issue by cowwoc** [pulumi/pulumi-kubernetes#3303]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'd like to look up all `EndpointSlices` that reference a `Service`. Baring that, I'd like to query the equivalent of `kubectl get endpointslices -n kube-system` using Pulumi Typescript code. Meaning, "return all EndpointSlices in namespace kube-system".

I could not find a way to do this using the existing API.

**Comment by cowwoc** [comment]
The only solution I found so far is to use the Kubernetes API (`@kubernetes/client-node`) to introspect the cluster. In other words, I am forced to dig outside of the Pulumi API. Is this the expected solution?

**Comment by mjeffryes** [comment]
This is a reasonable request @cowwoc. We don't have any list or search APIs built in today, but we have heard this request occasionally. However, using `@kubernetes/client-node` is absolutely a supported way to do this today. It's explicitly a feature of the Pulumi approach that you can use any package in your language ecosystem within your Pulumi programs.

**Comment by cowwoc** [comment]
The original request was probably the result of my lack of experience. I did not realize that Services create Endpoints/EndpointSlices, so it seems much less likely that users will need to create or patch them directly. For that reason, I personally no longer need this feature. Feel free to keep the issue open or close it depending on the other demand you have seen to date. Thank you.
