### ISSUE TITLE
Publish/export kubernetes types to allow passing configuration fragments to Kubernetes pulumi resources

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#336]
@pbzdyl commented on [Fri Jan 04 2019](https://github.com/pulumi/pulumi/issues/2334)

Currently no types/interfaces are exported from `kubernetes.core.v1` namespace like `ContainerPort`, `EnvVar` etc. Without these types available it's very cumbersome to create `ComponentResource`s that assemble multiple Kubernetes resources but would like to allow customisation of these resources e.g. by passing a list of `ContainerPort`s that should be exposed in a deployment or `EnvVar`s set on the container ports in a pod.

FYI @hausdorff.

**Comment by hausdorff** [comment]
This actually is possible. You'd do something like:

```
import * as inputApi from "@pulumi/kubernetes/types/input";
const port: inputApi.core.v1.ContainerPort = {...};
```

This is the "input shape", reflecting the fields that are required at submission time. There is also an "output shape", which better reflects the fields that will be populated at output time. It's at `"@pulumi/kubernetes/types/input"`.

Let's close this for now and open again if we're still missing something.

**Comment by joeduffy** [comment]
For what it's worth, I've found this quite confusing in my interactions with the Kubernetes provider. This confusion stems from two things: 1) the modules aren't discoverable (you need to know about the "magical import" of `.../types/...`), and 2) it doesn't match the patterns we use elsewhere.

Is there something different we should be doing here? Should we reopen this and discuss?

**Comment by hausdorff** [comment]
@joeduffy yeah, let's reopen and discuss

**Comment by lblackstone** [comment]
I won't get to this in M20. Bumping to M21.

**Comment by ericrudder** [comment]
let's see if we can look at this

**Comment by lblackstone** [comment]
I took a look at this and found that the k8s node SDK differs from the TF-generated SDKs in at least the following ways:

1. In the k8s SDK, input/output types are declared as interfaces with the same names as the resource classes, and live in separate files. The TF-generated SDKs don't include a separate output interface, but have the attributes defined within the resource class. The input interface is declared in the same file and has a name of the form `<resourceClass>Args`
1. In the k8s SDK, the attributes of the input interfaces are not marked `readonly`, but the attributes of the output interfaces are marked `readonly`. The TF-generated SDKs mark every attribute as `readonly`.
1. In the k8s SDK, attributes that reference another complex type point to one of the input/output interfaces. The TF-generated SDKs point to the relevant class instead.
1. Most of the classes/interfaces in the k8s SDK are namespaced and contain identically named classes/interfaces in other namespaces.

**Comment by lblackstone** [comment]
This won't be fixed in M24, but we'll be taking a look at fixing soon.

**Comment by hausdorff** [comment]
I'm not sure I understand the discussion that's happening currently, especially the parts about TF. I understood the complaint to be: the modules containing the "internal" types (_e.g._, `"@pulumi/kubernetes/types/input"`) are not discoverable.

So, is it enough to replace this:

```typescript
import * as inputApi from "@pulumi/kubernetes/types/input";
```

with something like this:

```typescript
import * as k8s from "@pulumi/kubernetes";
// inputApi === k8s.types.input
```

The alternative proposal (as I understand it) seems to be to put these "internal types" into the namespaces that the `CustomResource` implementations exist in (_e.g._, `apps.v1.Deployment` would have a corresponding `apps.v1.DeploymentArgs` or something which is the "input shape"). We tried this in ksonnet and it completely drowned out the "core" types, resulting in an unacceptably poor authorship experience.

Open to other solutions/being convinced, but for me, the straightforward way seems like the best one here?
