### ISSUE TITLE
Port Helm charts to Pulumi

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#34]
To demonstrate what real world Kubernetes code looks like in Pulumi, we should consider porting the most popular [Helm Charts](https://github.com/kubernetes/charts) to Pulumi.  The [curated set of Bitnami Charts](https://github.com/bitnami/charts) are probably an even better place to start.

We probably want these to land in pulumi/examples, but I'm filing this here since doing so probably depends a bit on finishing up some prerequisite Kubernetes work (like the new provider).

**Comment by hausdorff** [comment]
Since we have a better-than-expected Helm provider, I think we can probably close this and focus on making super compelling examples in in kubejs: https://github.com/pulumi/kubejs/issues/3
