### ISSUE TITLE
Simplify complex awaiter code

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#343]
When we started doing "complex" awaiters (which, _e.g._, display intermediate messages as resources come online), we didn't really know what it would exactly look like. The code is accordingly more complex than it could be, with a lot of similar logic distributed across important resources.

Now that we know roughly what these features involve, @lblackstone proposes that we factor them into a common "state machine" abstraction.

**Comment by lblackstone** [comment]
I've prototyped a solution and will continue tracking this work in the linked issues (450-454). I plan to finish out `Pod` in M21, but the other awaiter refactoring will be delayed as I wrap up some other issues.
