### ISSUE TITLE
Implement `preview` using API server dry (run when available)

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#352]
See blog post here: https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/

Note that this also includes possibly replacing our `diff` functionality with the server-side diff.

**Comment by lblackstone** [comment]
Addressed by #2445 

Due to performance issues, we decided to use input diffing with changes detected by refresh rather than using dry run preview directly.
