### ISSUE TITLE
Consider using UID for resource ID instead of `[namespace/]<name>`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#353]
_cf._, https://github.com/pulumi/pulumi-kubernetes/pull/319#discussion_r248485183

**Comment by lblackstone** [comment]
This is causing problems across multiple issues now, so increasing the priority on a fix.

**Comment by lblackstone** [comment]
This turned out to be unrelated to the URN issues, and hasn't caused other problems yet that we know of. Putting it on the backlog for now.

**Comment by hausdorff** [comment]
In general this should not be causing us _problems_, it was just a suggestion from @metral from when he interviewed.

**Comment by hausdorff** [comment]
Tentatively marking this as Q3, @pgavlin, but only because we need to figure out the (hopefully) final name format for k8s resources anyway, and this might as well be in the pile of candidates.

**Comment by pgavlin** [comment]
It is worth thinking about how this interacts with import.

As it stands, import a k8s resource is quite easy in part because it is very easy to determine the ID of the resource: it is just the namespace + the name. Would this ease-of-use be negatively affected if we switched to UIDs?

**Comment by lukehoban** [comment]
What is the argument for changing the ID format?  What concrete issue does this cause for users?

**Comment by hausdorff** [comment]
The current scheme for generating an ID depends on an _a priori_ notion of (a) whether the resource is namespaced, and (b) whether that namespace is auto-populated. This would give resources a unique ID, but not require these things.

The downside is that it's a _lot_ more opaque.

**Comment by hausdorff** [comment]
This issue specifically is not super user-visible, but the other URN issues are, particularly the question around including/not including API version in the URN, which has concrete impacts on upgrading the API version a resource uses.

What I'm saying here is that if we have to change it anyway, we might as well solve _all_ the issues.

**Comment by lukehoban** [comment]
IDs and URNs are *very* different things.  Any changes to either are very disruptive. 

I still haven't yet heard any specific user-facing problem that the current ID format creates, and absent a problem, it seems clearly the right format to use for ease of users understanding what they are seeing and being able to reason about resources.  

It seems to me we should close this pending an actual issue we can articulate for users, and focus in on addressing the known user-facing issues around URNs?

**Comment by lblackstone** [comment]
I'll close this out for now.
