### ISSUE TITLE
Track all embedded API objects, and programmatically form progress messages as resources become ready

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes#354]
ref: https://github.com/pulumi/pulumi-kubernetes/pull/319#discussion_r248484878

**Comment by hausdorff** [comment]
In the case of the comment above, I think the matter is somewhat straightforward? `Deployment` has two stages: (1) waiting for `ReplicaSet` to roll out, and (2) complete. If a PV/PVC is not bound, I believe none of the `Pod`s will boot at all. So we can make PVC binding step 1, and bump everything else down by one step, right?

**Comment by hausdorff** [comment]
cc @lblackstone

**Comment by metral** [comment]
> So we can make PVC binding step 1, and bump everything else down by one step, right?

This logic works in the usecase of a PVC in a Deployment. But if we depend on other resources like ConfigMaps, Secrets etc in addition to PVCs, this increases the queue of objects to wait on, and should alter the progress updates accordingly. We should keep this in mind during the refactor as this logic can be applied to other composable objects in k8s

**Comment by lblackstone** [comment]
This will be completed as part of the ongoing await logic refactoring. Closing this out in favor of the more specific tracking issues.
