### ISSUE TITLE
Support Kustomize

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#370]
Kustomize has merged into mainline. We are going to need to ship some sort of support of it for the next version of Kubernetes.

**Comment by hausdorff** [comment]
Just a PS, we closed this because kustomize is no longer part of the official Kubernetes application definition. In the event that it gets re-merged, we will probably re-open this and reconsider.

**Comment by hausdorff** [comment]
Support for `kustomize` was added in Kubernetes v1.14.0

**Comment by lblackstone** [comment]
I'm unclear what support for this would look like. De-prioritizing until we have a clearer idea on use case / user requests.

**Comment by d-nishi** [comment]
+1 this is not priority and we should not be adding tool support without  writing for large customer asks.

**Comment by mfacenet** [comment]
As a customer, we would like to manage our cluster addons via kustomize (currently done poorly using helm), we will also be managing our application deployments via kustomize, so this has ongoing impact for us.

**Comment by wstrange** [comment]
Bump - Any update on this?  We have a few remaining helm charts that we would like to get rid of. Kustomize support would be awesome.

**Comment by lblackstone** [comment]
Sorry for the delay. I expect we'll add this feature sometime in the next quarter. In the meantime, you can generate the YAML manifest using kustomize out of band (perhaps as a step in a CI pipeline), and then use our `yaml.ConfigFile` class to manage it with Pulumi.

**Comment by hermanbanken** [comment]
I'm curious what the status on this is, as it is May already 😄 We'd like to use Kustomize in a Pulumi-integrated fashion, if possible.

**Comment by lblackstone** [comment]
I've opened a [design doc](https://docs.google.com/document/d/1LW6PeO4QINXisHwXbcdFjUbh7XvvkhKYvwcIbLZTG3Q/edit?usp=sharing) to solicit feedback on the proposed approach. Please leave comments there if you have use cases in mind.
