### ISSUE TITLE
Pulumi can't track resources created at runtime by k8s controllers and/or apps that it doesn't know about

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes#379]
By definition, pulumi can't track a resource that it doesn't know about at deployment time.

For example: If pulumi creates a nginx-ingress-controller, at runtime nginx creates a new ConfigMap resource in k8s (that pulumi doesn't know about) to store its leader election data when operating in HA mode. If at some time later the nginx-ingress-controller is deleted, the ConfigMap would be left behind in the system, and pulumi would still be unaware of its existence.

The ConfigMap left behind, or more generally speaking, any resource created in the cluster at runtime that Pulumi doesn't know about can either: amount to being garbage in the system, or could potentially cause an unforeseen race condition in an app, because the resource already exists when the app expects that it should not. In this race example, the app should technically handle the error case, but nonetheless this could impact pulumi's update process and not properly inform the user.

**Comment by hausdorff** [comment]
So concretely, we might add facilities to automatically `.get` a set of resources that depend on a given resource. For example we could automatically `.get` all the `Pod`s created by a `ReplicaSet`.

I'm not opposed to it, but for stuff like `Pod` the turnover is super, super high and may generate a lot of churn.

**Comment by lblackstone** [comment]
We don't have current plans to automatically manage other resources on the cluster that aren't part of the Pulumi stack. It's possible to import resources of interest.

Furthermore, Server-side Apply makes this less of a concern because it's possible to share resources and upsert configuration.
