### ISSUE TITLE
Resource IDs are incorrect for computed namespaced resources

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#409]
Namespaced resources are showing up incorrectly in the CLI output:
```
 +      ├─ kubernetes:core:Service     [object Object]/frontend          create
 +      ├─ kubernetes:core:Service     [object Object]/redis-master      create
```

This is due to https://github.com/pulumi/pulumi-kubernetes/blob/b3bffb6e84467eccae64fdca8437ca98cb004eaf/sdk/nodejs/provider.ts#L2196-L2201

I tried fixing the problem with
```ts
        const meta = obj["metadata"];
        let id: pulumi.Output<string> = meta["name"];
        const namespace = meta["namespace"] || undefined;
        if (namespace !== undefined) {
            id = pulumi.all([namespace, id]).apply(([ns, id]) => `${ns}/${id}`)
        }
```
but the following constructors are all expecting `name: string`. Changing that type would require updating the `pulumi/pulumi` SDK as well, which has bigger implications.

**Comment by hausdorff** [comment]
More specifically, for _computed_ namespace names. For most people this should still work.
