### ISSUE TITLE
Consider how to propagate flags to the Kubernetes provider

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#41]
`kubectl` provides a lot of options that we may eventually want to support. For example, a user can specify that they _only_ want to `apply` with JSON-merge-patch.

In Pulumi, the Kubernetes provider is largely opaque, not exposing most of these knobs. We already do support reconciling env variables with, _e.g._, `$KUBECONFIG`, but it's worth thinking about what the future is here.

**Comment by lukehoban** [comment]
I think we can close this out and open issues for any concrete things users need.  I believe we've addressed a handful of these already over the last 18 months.
