### ISSUE TITLE
Error refreshing resource referencing ExternalName service

### ISSUE THREAD

**Issue by jam13** [pulumi/pulumi-kubernetes#413]
I have an Ingress resource with a rule pointing to an ExternalName Service. A previous bug resulted in creation of this combination never completing (#317). This now works as far as I know, but when I try to refresh resources I get a related error:

```
Diagnostics:
  kubernetes:extensions:Ingress (foo):
    error: Preview failed: 2 errors occurred:
    
    * Resource 'foo' was created but failed to initialize
    * Ingress has at least one rule that does not target any Service. Field '.spec.rules[].http.paths[].backend.serviceName' may not match any active Service
 ```

**Comment by lblackstone** [comment]
Ugh, sorry about that. I'll get that fixed, and I'm actively working on https://github.com/pulumi/pulumi-kubernetes/issues/179#issuecomment-459790219 to prevent these types of issues from being blockers in the future.

**Comment by lblackstone** [comment]
Hmm, I just tried to reproduce this, but it seemed to be working (both the create and refresh).

@jam13 Can you verify that this problem still exists with the latest package `0.20.4`?

**Comment by jam13** [comment]
I'm not sure I can easily reproduce it without breaking a stack again. I had to manually repair and reimport last time it happened. If you can't reproduce then feel free to close, and if I do encounter it again I'll provide more info.

**Comment by lblackstone** [comment]
Alright, closing for now, and please re-open if you encounter this again in `0.20.4` or later.
