### ISSUE TITLE
Support serializing a plan to YAML

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#42]
The most common pattern for deployment in Kubernetes is to serialize an entire deployment plan yo YAML so that it can be audited during CR (_i.e._, it's easier to write TypeScript, but easier to read YAML), and then picked up and deployed by CI.

For fairly complex examples, I think this would actually demo pretty well: one of the advantages of a "planning" phase is that it becomes pretty clear which things happen in which order, and why it's important that Pulumi waits for each operation to be complete. Right now that value proposition is kind of hidden from the user.

**Comment by skurfuerst** [comment]
seems to be the same issue as #29

**Comment by skurfuerst** [comment]
Actually, I'd *love* to write my Kubernetes deployments using type-safe TypeScript; and then generate kubernetes yaml files (which I check into git and deploy via CI/CD).

Currently Pulumi seems very very tied to its state files, right? I understand that for other kinds of resources (AWS etc) there is no way around that; but as far as Kubernetes goes, I do not want to use an extra state repository when using Pulumi.

Is this use case way off or actually useful to others? :-) 

All the best, Sebastian

**Comment by hausdorff** [comment]
After consideration, I think we should probably close this issue out for now. We can reconsider later as we get more feedback. For now I (personally) don't see a use case that's worth the complexity.

**Comment by joeduffy** [comment]
Reopening -- had not realized we closed this. This issue is apt to come up in the future (and indeed has a handful of :+1:s), and so let's keep it as a place to aggregate and track feedback.

**Comment by joeduffy** [comment]
Actually, going to close this and keep #29, since that one has more details on scenarios.
