### ISSUE TITLE
Add toggle to disable statefulSet await logic

### ISSUE THREAD

**Issue by mazamats** [pulumi/pulumi-kubernetes#428]
Some stateful services take 12+ hours to become ready, causing deployments to never apply all changes (stale resources are not deleted since the resource creation keeps failing).

Also, most statefulSet rolling updates take longer to complete than the timeout allows (especially once you go over 5 replicas)

```
Diagnostics:
  kubernetes:apps:StatefulSet (XXXXXX-0163):
    error: Preview failed: 2 errors occurred:

    * Resource 'XXXXXXX-0163' was created but failed to initialize
    * Failed to observe the expected number of ready replicas
```

Configureable timeout values are good, but being able to disable these checks is more necessary.

**Comment by lblackstone** [comment]
@mazamats #417 just merged, which will do what you need. I'm planning to cut an official release today, but you can try it out now with `@pulumi/kubernetes: dev`.

To use it, just add the following annotation to the relevant resource: `pulumi.com/skipAwait: true`.
```ts
const pod = new k8s.core.v1.Pod("pod", {
    metadata: {
        annotations: {
            "pulumi.com/skipAwait": "true"
        }
    },
    spec: {
        containers: [
            {name: "nginx", image: "nginx:1.13-alpine"},
        ],
    },
});
```

**Comment by lblackstone** [comment]
We will likely add configurable timeouts as well for more fine-grained control.

**Comment by lblackstone** [comment]
Release 0.20.2 is out now, and includes this change.
