### ISSUE TITLE
Feature request: Output Kubernetes objects as yaml

### ISSUE THREAD

**Issue by jmreicha** [pulumi/pulumi-kubernetes#432]
Really enjoying Pulumi so far.

One thing that I think would be useful when writing/testing/debugging Kubernetes configurations is a way to have Pulumi dump out the Kubernetes objects as yaml locally before applying them anywhere, to be able to see a little bit better what is going on.

**Comment by hausdorff** [comment]
I opened the original issue -- personally I still like the idea.

I do think it would be useful to have some context on the underlying problems. @jmreicha -- is the issue just that you are having trouble understanding what's going to happen when you apply the change? Worried about auditing? Something else? The more detail you provide the easier it will be to try to do something that solves the underlying problems!

**Comment by jmreicha** [comment]
@hausdorff As a cluster operator/admin, my usual workflow when working out manifests with other tools is to modify some of the inputs and then spit out the manifest as a yaml so I can spot check it.  I definitely enjoy having that quick feedback loop of making a change and then "rendering" the config to see what it looks like before deploying anything.

For example, with helm I like to use `helm template` generate yaml files, or `kubecfg show` to spit out rendered jsonnet configurations.  I think a similar option in Pulumi would help out us ops folks when debugging and/or troubleshooting configurations.

**Comment by hausdorff** [comment]
@jmreicha Yeah, we did this in ksonnet, too. Does `pulumi preview` not suffice for these purposes?

**Comment by hausdorff** [comment]
@jmreicha actually, can we move this discussion to #29? It's a bit older and has more detail.

Thanks. Will close this as a dup.
