### ISSUE TITLE
Python SDK does not implement `.get`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#434]
@lblackstone I'm proposing that we solve this in M21 because it's so easy, and it's blocking a user. But, feel free to move around as you see fit.

**Comment by lblackstone** [comment]
@hausdorff I poked around for a few minutes and didn't find where to add this. Can you add some more details on what is needed here?

**Comment by hausdorff** [comment]
I'm not sure what it means that we didn't find where to add this? This is just a static method hanging off the `CustomResource` implementations, exactly like they do in the nodejs implementation, right?
