### ISSUE TITLE
When creating k8s resources with a custom provider, one must supply the provider for every new object

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes#439]
A user has to repeatedly declare the k8s cluster provider when creating many k8s resources. See for [more info](https://github.com/pulumi/pulumi-kubernetes/blob/master/tests/integration/istio/step1/istio.ts#L9-L29): the line `{ provider: k8sProvider }` is set twice by the user in the `namespace`, and `adminBinding` objects.

It'd be great if there was a method of setting the k8s cluster provider once for use with *many* objects, in some bounded context, to avoid having to set this every time we declare a new k8s resource instance.

**Comment by 4c74356b41** [comment]
extremely annoying

**Comment by lukehoban** [comment]
I believe this is a dupe of https://github.com/pulumi/pulumi/issues/2059.

**Comment by 4c74356b41** [comment]
yep, looks similar

**Comment by hausdorff** [comment]
Let's close as a dupe.
