### ISSUE TITLE
await job completion

### ISSUE THREAD

**Issue by igorshapiro** [pulumi/pulumi-kubernetes#449]
In my scenario I'd like to run a rails db migration job before deploying the application.
This can also be useful in phoenix apps, or any other framework that supports migrations.

Ideally, I'd like to have docker image build, migrations and deployment in one pulumi program.

Then I can have

```js
const migration = new k8s.batch.Job('migration-job', { waitToCompletion: true })
const app = new k8s.Deployment('app', { dependsOn: [migration] })
...
```

**Comment by lblackstone** [comment]
Related to #93

**Comment by lukehoban** [comment]
From Ray Zane in the Pulumi Community Slack:

> Built into `kubectl` is `kubectl wait --for=condition=complete --timeout=30s [name of job]`.

> If pulumi could behave similarly and error our in the case of either a timeout or a failed job, that would be ideal. I think `waitForCompletion` is an adequate solution to the problem, and perhaps adding a timeout. It's fairly common to run a job to run migrations *before* rolling out a deployment.

**Comment by clstokes** [comment]
A similar use case this functionality is for https://github.com/GoogleContainerTools/kaniko - e.g. wanting to waiting for a kaniko pod to complete successfully to know that an image is ready for further deployment steps.

**Comment by metral** [comment]
k8s Jobs are intentionally not really defined beyond “ensuring the specified number of them successfully terminate."

It could be a while before the Job successfully terminates, a handful of minutes, or multiple hours / days, and it’s not something we can directly perceive from the Kubernetes API status for the Job.

There could also be the case where other pulumi objects depend on said Job and if that Job is long-running and the user wants to wait for completion, this could cause all sorts of unrelated issues w.r.t timeouts, back-off timeout handlers etc. across k8s and Pulumi, not to mention if there’s an error in the Job that isn’t discovered until some longer time after the Job has begun.

The need here seems valid, so I'd like to explore options that take the following into consideration:
- The user intent to specify this functionality doen't require us to modify the API type of k8s Jobs e.g. `waitToCompletion` seems to be a part of the type in the example
- We require a bounded box of time that the user must specify to achieve a failure or success status per the Job's API `.status`, as unlimited or unspecified time can have rippling effects
- We agree that the Job's `.status` is the only way Pulumi comes to a conclusion once the time limit has been reached e.g. we won't introspect a Job's logs, container etc.

I’d be interested in how seeing what agreement we can reach to get this enabled.

**Comment by lukehoban** [comment]
>  I'd like to explore options that take the following into consideration

These all sound right to me.  Are annotations a reasonable approach to (1), or do you expect this should be a `ResourceOptions`-style additional parameter outside of the Kubernetes resource?

If annotations are a solution, does using annotations for the timeout make sense?  And could/should we have a default of 10mins or something "reasonable"?

For the most common 5 scenarios where we've seen the need/desire for this - would just using `status` be sufficient?  Or are the reasonably common use cases that extend beyond this?

**Comment by igorshapiro** [comment]
@lukehoban Annotations are perfect. But I'm not sure about the behavior. 
As I understand today annotations are valid for `creating` the resource. However in the case of a job, we want the job to be finished within the given amount of time.
Another concern is how do we cleanup the job (in the case of db migrations). Do you guys have any idea?

**Comment by lukehoban** [comment]
This request has come up a lot recently.  

This is a really valuable "building block" component that allows running arbitrary compute within the cluster in a coordinated way with other deployment steps.  

It seems very natural to support this natively in the Pulumi Kubernetes provider.

We now have annotations for timeouts for other Kuberentes resources, so it's very natural to use those to control the timeouts for `Job`s as well.   We also have a new general `timeouts` configuration option coming soon for Pulumi all-up, which will make this even easier (https://github.com/pulumi/pulumi/pull/2885).

**Comment by hausdorff** [comment]
@lukehoban @pgavlin @lblackstone: does this fit into Q3? This is a new feature. Albeit, a very useful one.

**Comment by lukehoban** [comment]
I would love to finish off the work we started here.

**Comment by lblackstone** [comment]
Planning to finish this in Q3, but won't be done for M25

**Comment by MythicManiac** [comment]
How do you opt out of this behavior? I would like to deploy a long running task and not have Pulumi wait for it to finish, but at least the `pulumi.com/skipAwait: "true"` annotation mentioned [in this article](https://www.pulumi.com/blog/improving-kubernetes-management-with-pulumis-await-logic/) does nothing.

**Comment by MythicManiac** [comment]
@lblackstone do you have any info on how can this behavior be disabled if needed?

**Comment by MythicManiac** [comment]
Turns out I had a typo in my annotation, so in case anyone else stumbles here, `pulumi.com/skipAwait: "true"` annotation on the Job resource indeed does work for this use.

**Comment by ericrudder** [comment]
Glad this is working for you @MythicManiac!

**Comment by alexhwoods** [comment]
Are there any docs with the final API for this feature? Is it simply using `dependsOn`?

**Comment by lblackstone** [comment]
> Are there any docs with the final API for this feature? Is it simply using `dependsOn`?

[The batch/v1/Job registry page](https://www.pulumi.com/registry/packages/kubernetes/api-docs/batch/v1/job/#kubernetes-batch-v1-job) has more details. Pulumi won't mark the Job resource as ready until it meets the await conditions.

**Comment by alexhwoods** [comment]
> > Are there any docs with the final API for this feature? Is it simply using `dependsOn`?
> 
> [The batch/v1/Job registry page](https://www.pulumi.com/registry/packages/kubernetes/api-docs/batch/v1/job/#kubernetes-batch-v1-job) has more details. Pulumi won't mark the Job resource as ready until it meets the await conditions.

Awesome, thank you! I think the term "ready" is throwing me off, because a job runs and then is complete; it's not long-lasting. But based on those conditions, "ready" means "completed", right?

In which case `dependsOn` is all we need to use this feature
