### ISSUE TITLE
Empty name on dynamic client Get causes client-go to panic

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#470]
In #469, we discovered that client-go v10 is panicking when we pass certain invalid namespaces into it during a `Read`. The basic idea of that PR is to have `Output<T>#toString()` emit a warning saying that you should not be calling this method, and it will throw in the future. In one of our tests, we're actually inadvertently using that function, which leads us to the following scenario I describe. Basically, when the error message is passed as a namespace, the result is a panic in client-go.

> Or, more specifically, this `idNamespace` in the code snippet below:
> 
> ```
> `${idNamespace}/my-new-cron-object`
> ```
> 
> will evaluate to an error message, which means that this string will evaluate to the following. Notice the `/my-new-cron-object` at the end of this error -- that's the name of the object that's supposed to go after `idNamespace` above.
> 
> ```
> Calling [toString] on an [Output<T>] is not supported.
>     To get the value of an Output<T> as an Output<string> consider either:
>     1: o.apply(v => `prefix${v}suffix`)
>     2: pulumi.interpolate `prefix${v}suffix`
>     See https://pulumi.io/help/outputs for more details.
>     This function may throw in a future version of @pulumi/pulumi./my-new-cron-object
> ```
>
> Apparently when we pass this beauty of a "namespace" to the client, it causes client-go to totally flip out and panic because it doesn't know what to do with that string, and it generates an `*unstructured.UnstructuredList` instead of `*unstructured.Unstructured`. Eek!
> 
> cc @lblackstone I won't get to it tonight, but we'll probably need to try upgrading client-go and then if that doesn't work, file a bug against them. I'll start by filing an issue.

To fix this, we'll probably want to do these things, in this order:

1. Upgrade client-go to see if this solves the issue.
1. If not, file a bug against client-go.
1. And lastly, make some work-around, which probably involves sanitizing the namespace somehow before it's passed to client-go.

**Comment by hausdorff** [comment]
Chatted with @lblackstone and we agree that we should fix this before the next release goes out. Tactically, I recommend putting this in a 0.16 patch release, in addition to upcoming 0.17.

**Comment by lblackstone** [comment]
I attached a debugger, and discovered that the actual reason the client is returning a list is because the `.metadata.name` is empty (`""`).

I traced that back, and found that the request ID in the RPC call is
```
Calling [toString] on an [Output<T>] is not supported.

To get the value of an Output<T> as an Output<string> consider either:
1: o.apply(v => `prefix${v}suffix`)
2: pulumi.interpolate `prefix${v}suffix`

See https://pulumi.io/help/outputs for more details.
This function may throw in a future version of @pulumi/pulumi./my-new-cron-object
```

I'm not sure why it would be set like that, but I'll add some additional error handling code around the logic that parses that ID.

**Comment by hausdorff** [comment]
Recapping the slack conversation: yes, we passed bad information to client-go, but the stack trace seems to show that the `panic` is thrown _inside_ client-go, which would completely unacceptable. It should be reporting an `error` back instead. I recommend we work around it in the short term, report the bug to upstream, and upgrade when it's fixed.

**Comment by lblackstone** [comment]
Filed https://github.com/kubernetes/client-go/issues/572

**Comment by lblackstone** [comment]
I fixed the provider code that was allowing this condition, and filed a fix for the underlying issue upstream. I'm removing the P1 priority and bumping this issue out of the milestone since it will take awhile before the upstream change is available to pull in.

**Comment by lblackstone** [comment]
https://github.com/kubernetes/kubernetes/pull/75072 has merged to upstream master.

**Comment by lblackstone** [comment]
Still need to pull in the upstream changes from client-go, but it'll likely be awhile before this makes it into a tagged release. Since we've worked around the original issue, I've bumped it from the milestone and lowered the priority.

**Comment by lblackstone** [comment]
https://github.com/kubernetes/kubernetes/commit/0118630abf4f47d17770f08e7aad862107d2ce27 is in the 1.15 branch, so this fix will likely land in client-go 12.
