### ISSUE TITLE
Split nodejs provider.ts file into meaningful components

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#479]
Currently, the generated `provider.ts` file for the nodejs SDK is > 15000 LOC, which makes for a sluggish IDE and GitHub experience.

The generator should be updated to create multiple files that are separated by component.

**Comment by hausdorff** [comment]
We've been meaning to do this for a very long time, as it's how ~all other providers work. It will also make diffs when updating the openapi spec much cleaner. So this is not _just_ a TS compiler usability problem.
