### ISSUE TITLE
Support node taint workflow

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#488]
Some common k8s use cases require taints to be applied to specific nodes. It would be nice to support that directly in Pulumi so that the user could manage the taints/tolerations in the same place.

For example:
> I want to create a dedicated node pool which requires me to taint nodes and put tolerations on the pod among other things so that they are scheduled on the given node

https://pulumi-community.slack.com/archives/C84L4E3N1/p1552939291632300?thread_ts=1552937963.631000&cid=C84L4E3N1

**Comment by blandman** [comment]
Is there any Pulumi work around for this?

**Comment by blandman** [comment]
If using gke, you can pass taints into nodeConfig under nodePools. 

```
nodePools: [{
    name: "pool-name",
    nodeConfig: {
            taints: [{
                effect: 'NoSchedule',
                key: 'dedicated',
                value: 'whatever'
            }]
        },...
    }]
```

**Comment by lukehoban** [comment]
I think we can likely close this specific issue.  I believe the two underlying things this tracks are either:
1. Adding taints via the managed Kubernetes service (GKE, EKS, AKS, etc).  This is largely already available in those packages as noted above.
2. Having the ability to patch `core.v1.Node` instances with taints/tolerations.  This is part of https://github.com/pulumi/pulumi-kubernetes/issues/264.
