### ISSUE TITLE
Duplicate resource URN with helm when using RoleList with multiple Roles in different namespaces

### ISSUE THREAD

**Issue by masterada** [pulumi/pulumi-kubernetes#489]
Prometheus operator chart lets you install multiple roles with the same names into different namespaces: https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/prometheus/role-specificNamespace.yaml#L13

This breaks pulumi, because both the resource apiVersion, kind and name is the same for these roles, resulting in generating the same URN for them.

eg: `error: Duplicate resource URN 'urn:pulumi:sbx::k8s-monitoring::kubernetes:helm.sh/v2:Chart$kubernetes:rbac.authorization.k8s.io/v1:Role::monitoring/sbx-kubernetes-monitoring-prometheus'; try giving it a unique name`

**Comment by lblackstone** [comment]
Related to https://github.com/pulumi/pulumi-kubernetes/issues/353

**Comment by CrystalMethod** [comment]
Is there any workaround?

**Comment by masterada** [comment]
> Is there any workaround?

For the prometheus operator chart, yes, set roleNamespaces to only contain 1 element (the namespace where you deploy). The roles it creates aren't really needed anyway, because the chart also creates a cluster role with the same privileges. You must set it exactly to the namespace you are deploying to, otherwise it won't work (either because the pulumi bug or because of a bug with the chart: https://github.com/helm/charts/issues/12376 )

**Comment by hausdorff** [comment]
Sorry, I'm confused -- I think what this error is saying is that you're creating `Role` with the _same_ namespace, name, apiVersion, and kind. Notice the namespace `monitoring` is included in the URN:

```
kubernetes:rbac.authorization.k8s.io/v1:Role::monitoring/sbx-kubernetes-monitoring-prometheus
```

If this is correct, then we should fix this in the upstream Helm Chart. This strikes me as the Helm equivalent of C's undefined behavior. :)

**Comment by masterada** [comment]
I believe "monitoring" is the helm release namespace, which might be different from the actual namespace set for the resource (although i will have to double check this tomorrow). The same chart works with helm.

**Comment by hausdorff** [comment]
Yes, that's right. What I'm trying to say is: this error indicates that this Helm chart is trying to create two `Role` resources called `sbx-kubernetes-monitoring-prometheus` in the `monitoring` namespace.

If this works in the original Chart, that is virtually certain to be a bug, and we should just fix it in upstream ASAP. It is truly unfortunate that this doesn't cause an error in Helm. This should absolutely not be allowed.

**Comment by masterada** [comment]
My bad, it works as expected, we probably overrode the namespace using the transformations :( Sorry for wasting your time.

For future reference:
GOOD:
```
  {
    repo: 'stable',
    chart: 'prometheus-operator',
    version: '4.2.1',
    namespace: namespace,
    values: helmValues,
    transformations: [
      (o: any) => {
        if (!o.metadata || !o.metadata.namespace) {
          Object.assign(o.metadata || {}, {
            namespace: namespace // TODO: helm template namespace issue - https://github.com/helm/helm/issues/3553
          })
        }
      }
    ]
  },
```

BAD:
```
  {
    repo: 'stable',
    chart: 'prometheus-operator',
    version: '4.2.1',
    namespace: namespace,
    values: helmValues,
    transformations: [
      (o: any) => {
        Object.assign(o.metadata || {}, {
          namespace: namespace // TODO: helm template namespace issue - https://github.com/helm/helm/issues/3553
        })
      }
    ]
  },
```

**Comment by hausdorff** [comment]
@masterada ha, no problem. It's no bother, we're happy to help. :)
