### ISSUE TITLE
Feature request: Skip k8s resource destroy if the underlying cluster is destroyed

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#491]
In cases where a stack to be destroyed includes the k8s cluster, it would be nice to skip waiting on the k8s resources to delete, since they will be deleted implicitly when the cluster is deleted.

This is an optimization, and it's possible it wouldn't play nicely with cloud provider resources like load balancers that are created in response to k8s resource creation.

**Comment by cleverguy25** [comment]
I dont think this is just an optimization.  In my case, some of the k8s resources did not want to tear themselves down, such as the Istio namespace.  So the destroy was completely blocked.

**Comment by hausdorff** [comment]
Related to, but not the same as, this: https://github.com/pulumi/pulumi-kubernetes/issues/416

**Comment by 4c74356b41** [comment]
honestly, i dont see a problem why cant you just infer that everything that depends on something will get autodeleted.

**Comment by hausdorff** [comment]
@4c74356b41 In general, anything can depend on anything, so deleting a parent guarantees nothing about whether the child has been deleted, too. This is also true generally of providers -- deleting a specific high-order provider does not guarantee that all resources using it are also deleted.

What you are really asking for is a specific exception for Kubernetes clusters, and that's what this issue is proposing -- an exception.

**Comment by 4c74356b41** [comment]
yeah, sure, what about kubernetes created and configured in the same config? what about azure resource groups in the same config (everything has to depend on them)? etc

**Comment by cleverguy25** [comment]
Maybe not an exception, but a way to denote a true parent child relationship, or know that helm and kubernetes cluster have that relationship because of the provider reference.
________________________________

**Comment by hausdorff** [comment]
I'm not sure how this proposal is different than what the issue is proposing. :)

**Comment by 4c74356b41** [comment]
because its more general? not just about kubernetes.

**Comment by cleverguy25** [comment]
Right. If you explicitly or implicitly know that there is true parent child relation ship where deleting the parent deletes the child, it doesn't matter if it is just kubernetes or any other tech.  Helm charts depend on the cluster, so maybe that relationship can be implicit from the framework code, but you can allow it to be explicitly settable as well.
________________________________

**Comment by hausdorff** [comment]
Understood. Rest assured, we will do something that works for this class of problems here. :)

**Comment by dor-utila** [comment]
Seems related to https://github.com/pulumi/pulumi/pull/11095

**Comment by lblackstone** [comment]
We don't have plans to implement this directly. However, it is possible to delete the cluster separately, and then use the `deleteUnreachable` provider option to clean up the stack. See #2489
