### ISSUE TITLE
Pulumi Helm is ignoring the namespace directive.

### ISSUE THREAD

**Issue by mfacenet** [pulumi/pulumi-kubernetes#504]
When running pulumi update including k8s helm charts, the resulting objects are not created in the namespace specified, rather, they keep being "dropped" in default. 

Source:
const ambassasdor = new k8s.helm.v2.Chart("ambassador", {
    namespace: "kube-system",
    repo: "stable",
    chart: "ambassador",
    version: "2.0.0",
  }, {
    providers: {kubernetes: k8sProvider},
  });

**Comment by mfacenet** [comment]
Of side note:
pulumi version = 0.17.3
        "@pulumi/kubernetes": {
            "version": "0.22.0",
            "resolved": "https://registry.npmjs.org/@pulumi/kubernetes/-/kubernetes-0.22.0.tgz",
            "integrity": "sha512-FYvwA8WM5f2BMEMjyHz7z6Fiw1/ZWZj4w0XBanXPh1a0sgVKEZBUuDaEu8JQHx0HAL2k4EVwjgf+BavG63e6/A==",
            "requires": {
...
            }
        },

**Comment by hausdorff** [comment]
Helm is ignoring the namespace, per https://github.com/pulumi/pulumi-kubernetes/issues/217. Let's track that issue there, but @lblackstone we should consider this evidence that we should try to fix in M22.
