### ISSUE TITLE
Undocumented `invoke` for `apply`'ing YAML

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#509]
Per https://github.com/pulumi/pulumi-eks/issues/65, it is occasionally true that we need an escape hatch to be able to apply some bit of YAML to a resource. For example, after creating a GKE or EKS cluster, various "systems" components will exist there, and occasionally it is useful to be able to patch them. This is not possible in the Pulumi resource model without the adoption mechanisms, which aren't scriptable.

This means that today we sometimes have to shell out to `kubectl`, _e.g._, in the EKS package. This is fragile and has caused more than a few bugs. We should consider exposing this through an (undocumented?) `invoke`, _e.g._:

```typescript
pulumi.runtime.invoke("pulumi:kubernetes:apply", myYaml)
```

**Comment by hausdorff** [comment]
Just as a footnote here -- we actually implemented `kubectl replace`, which is both simpler, and what we needed for EKS.

**Comment by lukehoban** [comment]
> we actually implemented `kubectl replace`

Curious - why is `kubectl replace` better here than `kubectl apply`?  Doesn't the former imply downtime?

**Comment by lukehoban** [comment]
Also - there are related scenarios like modifying the `default` storage class from what the cloud provider installed by default that would seemingly need `apply` not `replace`?

**Comment by metral** [comment]
@hausdorff I too am curious to hear any replies to both of @lukehoban's questions, particularly the scenario for storage classes, and similar cluster modifications that would occur _after the fact_ its up

**Comment by metral** [comment]
@hausdorff now that this is the kube provider, do you plan on making the changes to `@pulumi/eks` to use the new `kubectlReplace`  Invoke function to close out https://github.com/pulumi/pulumi-kubernetes/issues/509 on the `eks` side of things?
