### ISSUE TITLE
Upgrade to client-go 11

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#521]
client-go 11 is out, and we should upgrade when possible to avoid piling on technical debt.

The recommended installation method uses go modules, so hold off on this until we're ready to move the build over to go modules.

**Comment by hausdorff** [comment]
cc @jen20, I _believe_ the plan is to move to Go modules imminently. So this seems like it lines up accidentally perfectly with our existing plan.

**Comment by jen20** [comment]
I will spike a build of `pulumi-kubernetes` using modules once I'm done with a couple of the more challenging Terraform-backed providers. Is there known breakage that will need fixing up with the version bump?

**Comment by lblackstone** [comment]
@jen20 No, I don't think there are known gotchas here. I got things building successfully with go modules when I upgraded to client-go 10 awhile back, and it was a lot easier than using `dep`.
