### ISSUE TITLE
Improve await logic for old Deployment schema

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#528]
See https://github.com/pulumi/pulumi-kubernetes/pull/523/#pullrequestreview-224685092 for context.

The `extensions/v1beta1` version of `Deployment` will require separate await logic to provide meaningful status updates.

**Comment by hausdorff** [comment]
I think this is not necessary for Q3. ~Everyone should not be using `extensions/v1beta1`.

**Comment by lblackstone** [comment]
We have working support for `extensions/v1beta1` Deployment resources, and they will be removed from the k8s API starting in 1.16, so I'm going to close this out.
