### ISSUE TITLE
Introduce Helm migration story

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#54]
We know that there are many benefits from being able to convert Kubernetes YAML, and Helm Charts, to Pulumi, especially to leverage all the benefits of a language.  However, it would also be possibly nice to be able to leverage the existing ecosystem of charts.  For example:

```typescript
import * as helm from "@pulumi/helm";
const datadog = new helm.Chart("datadog", {
    apiKey: ...,
    repository: ...,
});
```

These would clearly need to be weakly typed, although one could also imagine a world where we use code-gen to create even more first class resource types.  Such as

```typescript
import {Datadog} from "@pulumi/helm-charts";
const datadog = new Datadog({ /* yay, strong typing */ });
```

Assigning to @hausdorff to think about.

**Comment by hausdorff** [comment]
x-ref to https://github.com/pulumi/pulumi/issues/1544 We want to be able to trivially install any Helm chart to a cluster _without_ Tiller.

**Comment by joeduffy** [comment]
I very much prefer the first to start because it's easy and far less disruptive to try it out. It's also a nice "better together" story.

I agree the second is useful but I think of it as a follow on activity that probably doesn't need to happen as part of the initial "moment".

**Comment by lukehoban** [comment]
@hausdorff I think this is "done" for now with https://github.com/pulumi/pulumi-kubernetes/pull/108, right?

**Comment by hausdorff** [comment]
This can be marked as done. An ancillary note is that it turned out to be hard to write a Tiller provider, so we "just" wrote the Helm adopter.

**Comment by joeduffy** [comment]
From my recent discussions with folks recently, not supporting a Tiller-based provider is actually a good thing anyway. It's worth tracking how we'd dock in with the new CRD-based Helm system, however.
