### ISSUE TITLE
Export intermediate types from k8s

### ISSUE THREAD

**Issue by farnoy** [pulumi/pulumi-kubernetes#542]
Container specifications have fields like:

            /**
             * List of environment variables to set in the container. Cannot be updated.
             */
            env?: pulumi.Input<pulumi.Input<core.v1.EnvVar>[]>;

But there's no way to import EnvVar in user code, since it's not exported. It would be useful to have this exported for extracted definitions to be typeable, like:

```ts
const appEnv: pulumi.Input<core.v1.EnvVar>[]> = [
  {name: 'WHATEVER', value: 'TEST'},
];

// later, in some definition
env: [
 ...appEnv,
  {name: 'SOMETHING', value: 'ELSE'},
],
```

We can't have these extracted variables typechecked properly if these types are not reachable.

**Comment by hausdorff** [comment]
These types actually are exported. You need a line like: `import * as input from "@pulumi/kubernetes/types/input";`.

I'm going to close this issue, but we'll think more about whether we should expose these in a clearer way.

**Comment by farnoy** [comment]
Good to know, thanks!

**Comment by lukehoban** [comment]
https://github.com/pulumi/pulumi-kubernetes/issues/336 is also tracking improving this.
