### ISSUE TITLE
Issue with 1.14

### ISSUE THREAD

**Issue by emalamisura-c2m** [pulumi/pulumi-kubernetes#548]
When I attempted to follow the configmap-rollout tutorial using minikube and kubectl 1.14 I get the following error:

```
Plan apply failed: 1 error occurred:

* SchemaError(io.k8s.api.extensions.v1beta1.IngressRule): invalid object doesn't have additional properties
update failed
Resources:
    2 unchanged
 
Duration: 1s
```

I verified that I only had kubectl 1.14 installed in case there was a dependency issue somewhere I deleted minikube environment and recreated ensuring it was recreated using only 1.14. Same exact issue.  

Although I have noticed, that sometimes with the same configuration and steps I will get this error instead:

```
Plan apply failed: 1 error occurred:

* SchemaError(io.k8s.api.batch.v1beta1.JobTemplateSpec): invalid object doesn't have additional properties
update failed
Resources:
    2 unchanged
 
Duration: 1s
```

**Comment by emalamisura-c2m** [comment]
So I have confirmed this is specific to 1.14.  I deleted minkube and then forced version 1.12.6 by doing 

`minikube start --minikube-version v1.12.6`

and it worked exactly how I would expect it.  I was trying to trace this down in the kubernetes example, but it was taking me entirely too long and I have to get this stuff done. I may re-approach it but if someone from team can take a look at this, its definitely an issue.

**Comment by lukehoban** [comment]
@lblackstone @hausdorff Is this a Kubernetes 1.14-specific issue with the await logic for `IngressRule`?  Is this an expected failure mode?  Is there are workaround?

**Comment by hausdorff** [comment]
This error is coming from the Kubernetes API server, it's reporting the schema is malformed. This should not affect the await logic at all, an error like this would very probably occur if the resource itself was malformatted.

What does the resource look like?

**Comment by lblackstone** [comment]
We don't have enough info to troubleshoot - feel free to reopen with more details.
