### ISSUE TITLE
cert-manager error: "failed to determine if the following GVK is namespaced"

### ISSUE THREAD

**Issue by ggilmore** [pulumi/pulumi-kubernetes#553]
When trying to upgrade from cert-manager [v0.6.0](https://github.com/jetstack/cert-manager/releases/tag/v0.6.0) to [v0.7.2](https://github.com/jetstack/cert-manager/releases/tag/v0.7.2), `pulumi up` fails with the following error: 

```
Previewing update (dev):

     Type                                      Name                                  Plan       Info
     pulumi:pulumi:Stack                       pulumi-api-gvk-repro-dev
     ├─ kubernetes:yaml:ConfigGroup            cert-manager
 +   │  └─ kubernetes:yaml:ConfigFile          cert-manager-0.7.2.yaml               create
 +   │     ├─ kubernetes:core:ServiceAccount   cert-manager/cert-manager-cainjector  create
 ~   │     └─ kubernetes:core:ServiceAccount   cert-manager/cert-manager-webhook     update     [diff: ~metadata]
     └─ kubernetes:apiregistration:APIService  v1beta1.admission.certmanager.k8s.io             1 error

Diagnostics:
  kubernetes:apiregistration:APIService (v1beta1.admission.certmanager.k8s.io):
    error: failed to determine if the following GVK is namespaced: apiregistration/v1beta1, Kind=APIService
```

I've created a repository that reproduces this behavior here: https://github.com/ggilmore/pulumi-api-gvk-repro

Reproduction steps:

1. Set the `gcp:project`, `gcp:zone`, `pulumi-api-gvk-repro:gcloudEmail` (gcp email address to create the `cluster-admin` role binding) settings in your stack configuration. 

1. Run `yarn` to install the dependencies

1. Run `pulumi up`, see that everything is created correctly. This step installs cert-manager [v0.6.0](https://github.com/jetstack/cert-manager/releases/tag/v0.6.0)

1. In the `cert-manager` `"files"` array on https://github.com/ggilmore/pulumi-api-gvk-repro/blob/c11acb0e456b252b5d8bec1770364f773b6636d4/index.ts#L94-L97,  uncomment the file path for cert-manager [v0.7.2](https://github.com/jetstack/cert-manager/releases/tag/v0.7.2) and delete the file path for cert-manager [v0.6.0](https://github.com/jetstack/cert-manager/releases/tag/v0.6.0)

1. Run `pulumi up` again to attempt to install cert-manager [v0.7.2](https://github.com/jetstack/cert-manager/releases/tag/v0.7.2) 

1. See the following error:

```
Previewing update (dev):

     Type                                      Name                                  Plan       Info
     pulumi:pulumi:Stack                       pulumi-api-gvk-repro-dev
     ├─ kubernetes:yaml:ConfigGroup            cert-manager
 +   │  └─ kubernetes:yaml:ConfigFile          cert-manager-0.7.2.yaml               create
 +   │     ├─ kubernetes:core:ServiceAccount   cert-manager/cert-manager-cainjector  create
 ~   │     └─ kubernetes:core:ServiceAccount   cert-manager/cert-manager-webhook     update     [diff: ~metadata]
     └─ kubernetes:apiregistration:APIService  v1beta1.admission.certmanager.k8s.io             1 error

Diagnostics:
  kubernetes:apiregistration:APIService (v1beta1.admission.certmanager.k8s.io):
    error: failed to determine if the following GVK is namespaced: apiregistration/v1beta1, Kind=APIService
```

**Comment by lblackstone** [comment]
@ggilmore Thanks for the detailed repro! I tracked down the bug and have a fix PR up now. Assuming the test suite doesn't uncover further problems, the fix will be available in the dev release later today. You can pull that in with `"@pulumi/kubernetes": "dev",` in your `package.json`
