### ISSUE TITLE
Allow LoadBalancer on minikube

### ISSUE THREAD

**Issue by emalamisura-c2m** [pulumi/pulumi-kubernetes#567]
While there is nothing in particular preventing this, the deployment fails because on minikube a LoadBalancer never gets an external ip. Why would I want to use a LoadBalancer in minikube? Well because the advice around thus has changed, and now you use minikube service <servicename> which will give it a temporary external ip attached to your localhost. This works better than kubectl port-forward since it is able to handle a significantly larger load without crashing.

**Comment by hausdorff** [comment]
You can skip the await logic with `skipAwait`: https://blog.pulumi.com/improving-kubernetes-management-with-pulumis-await-logic

Does this work for your use case?
