### ISSUE TITLE
Automatically alias different ApiVersions

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#573]
See https://github.com/pulumi/pulumi-kubernetes/issues/546#issuecomment-496271690 for details

**Comment by redbaron** [comment]
been  hit by this, would be very nice to see it addressed.

**Comment by lukehoban** [comment]
There's a couple remaining questions on precisely which API versions are guaranteed to be compatible in Kubernetes which we are hashing out on the PR at https://github.com/pulumi/pulumi-kubernetes/pull/798.  Pushing this to M28 to finalize.
