### ISSUE TITLE
Deploying kubernetes-dashboard via helm chart fails

### ISSUE THREAD

**Issue by kennyjwilli** [pulumi/pulumi-kubernetes#578]
The below code will fail to deploy with the follow error.

```typescript
const cluster = new eks.Cluster(`k8s-cluster`, {
    vpcId: vpc.id,
    subnetIds: vpc.publicSubnetIds,
    deployDashboard: false
});
const k8sProvider = cluster.provider;

const k8sDashboardChart = new k8s.helm.v2.Chart("kubernetes-dashboard", {
    repo: "stable",
    chart: "kubernetes-dashboard",
    version: "1.5.2",
    namespace: "kube-system"
}, {providers: {kubernetes: k8sProvider}});
```

error:
```
  kubernetes:core:Service (kubernetes-dashboard):
    error: Plan apply failed: 2 errors occurred:
    	* Timeout occurred for 'kubernetes-dashboard'
    	* Service does not target any Pods. Selected Pods may not be ready, or field '.spec.selector' may not match labels on any Pods
```

**Comment by metral** [comment]
Closing in favor of https://github.com/pulumi/pulumi-eks/issues/142

**Comment by lblackstone** [comment]
This was failing with the following error:
```
  Warning  FailedCreate  26s (x15 over 108s)  replicaset-controller  Error creating: pods "kubernetes-dashboard-6b64f75d74-" is forbidden: error looking up service account default/kubernetes-dashboard: serviceaccount "kubernetes-dashboard" not found
```
It works as expected if you leave off the `namespace` parameter.

**Comment by lblackstone** [comment]
Related #217

**Comment by kennyjwilli** [comment]
@lblackstone I have just tried the code [here](https://gist.github.com/kennyjwilli/662ae731bd6cb102d1ca6310a36f93f6) without the `namespace` parameter set on [line 56](https://gist.github.com/kennyjwilli/662ae731bd6cb102d1ca6310a36f93f6#file-index-ts-L56). `pulumi up` fails with the following message: 

```
Diagnostics:
  pulumi:pulumi:Stack (k8s-dash-helm-test1):
    error: update failed
 
  kubernetes:core:Service (kubernetes-dashboard):
    error: Plan apply failed: 2 errors occurred:
    	* Timeout occurred for 'kubernetes-dashboard'
    	* Service does not target any Pods. Selected Pods may not be ready, or field '.spec.selector' may not match labels on any Pods
 
  kubernetes:extensions:Deployment (kubernetes-dashboard):
    error: Plan apply failed: 3 errors occurred:
    	* Timeout occurred for 'kubernetes-dashboard'
    	* Minimum number of Pods to consider the application live was not attained
    	* 1 Pods failed to schedule because: [Unschedulable] no nodes available to schedule pods
```

**Comment by metral** [comment]
@kennyjwilli Are you sure there are nodes available in the cluster? That error says there are none.

What does `kubectl get nodes` return?

Ah - I think I know what your problem is in that linked example: you create a `role` & `instanceProfile` and pass the `instanceProfile` to the `NodeGroup` but do not set the given `role` on the cluster. You must do that for the NodeGroup to join the cluster as shown [here](https://github.com/pulumi/pulumi-eks/blob/master/nodejs/eks/examples/nodegroup/index.ts#L24).

See `instanceRole` and `instanceRoles` in the [ref docs](https://pulumi.io/reference/pkg/nodejs/pulumi/eks/#ClusterOptions-instanceRole).

Try setting `instanceRole: role0` in your `eksCluster` definition, and see if this works for you with @lblackstone's namespace omission suggestion.

**Comment by kennyjwilli** [comment]
Oh wow, totally missed that. You're probably right. I have added the `instanceRole: role0` to my `Cluster` and run `pulumi up`. The update fails with the same message:

```
Diagnostics:
  pulumi:pulumi:Stack (k8s-dash-helm-test1):
    error: update failed
 
  kubernetes:core:Service (kubernetes-dashboard):
    error: Plan apply failed: 2 errors occurred:
    	* Timeout occurred for 'kubernetes-dashboard'
    	* Service does not target any Pods. Selected Pods may not be ready, or field '.spec.selector' may not match labels on any Pods
 
  kubernetes:extensions:Deployment (kubernetes-dashboard):
    error: Plan apply failed: 3 errors occurred:
    	* Timeout occurred for 'kubernetes-dashboard'
    	* Minimum number of Pods to consider the application live was not attained
    	* 1 Pods failed to schedule because: [Unschedulable] 0/2 nodes are available: 2 node(s) had taints that the pod didn't tolerate.
```

This seems like something you should be able to recover from without needing to recreate the whole cluster. Perhaps this deserves a separate ticket to fix? 

Further, it seems far too easy to trip over yourself by forgetting something like this. Getting into a state like this does not seem desirable. Is there a way Pulumi could catch this much earlier?

**Comment by metral** [comment]
> This seems like something you should be able to recover from without needing to recreate the whole cluster. Perhaps this deserves a separate ticket to fix?

The roles are used to update the `aws-auth` [configmap](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html), which is how the Nodes join the cluster. Given how the cluster does not change, I don't imagine this should trigger replacing a cluster - @lukehoban thoughts?

> Further, it seems far too easy to trip over yourself by forgetting something like this. Getting into a state like this does not seem desirable. Is there a way Pulumi could catch this much earlier?

I'm sure we can build in checks that make sense, but we should first identify if this may either be an issue in your stack, or in `pulumi/eks` that we should track in a separate issue from this one.

**Comment by kennyjwilli** [comment]
It sounds like a `pulumi/eks` issue. The stack I am using is the one linked previously [here](https://gist.github.com/kennyjwilli/662ae731bd6cb102d1ca6310a36f93f6). It should be easy to replicate the issue.

**Comment by metral** [comment]
@kennyjwilli I've opened up https://github.com/pulumi/pulumi-eks/issues/174 to track the role update errors. Thanks for your feedback!

**Comment by metral** [comment]
@kennyjwilli I've copied your notes over to the new [issue](https://github.com/pulumi/pulumi-eks/issues/174).

Let's continue any discussions there. Thanks!
