### ISSUE TITLE
Add Python support

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#59]
The steps to this are:

- [ ] Emit Python 2.7 to start and unblock the ecosystem.
- [ ] Transition this to emit Python 3 once @swgillespie gets to a point where we can use the (new, upcoming) Python 3 language provider.

**Comment by hausdorff** [comment]
Not prioritize for 0.17. Moving to 0.18.

**Comment by slikk66** [comment]
Vote for K8s python!

**Comment by hausdorff** [comment]
Plot twist, I'll kick this off by adding the tweaks to emit Python 2.7.

**Comment by lukehoban** [comment]
We should also add test coverage.

**Comment by lukehoban** [comment]
I believe this is done now - including tests.  Closing out.  Feel free to open new issues if there is follow up Python work to do.
