### ISSUE TITLE
Include an example of deploying the kube-dashboard Helm chart

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes#600]
Per [thread](https://github.com/pulumi/pulumi-eks/issues/142#issuecomment-503635095), and our inclination to [deprecate](https://github.com/pulumi/pulumi-eks/issues/155#issuecomment-501932824) the dashboard from `pulumi/eks`, we should document how to deploy the Helm chart for folks looking to use it on k8s clusters.

**Comment by kennyjwilli** [comment]
I'd also suggest documenting the deployment for the dashboard via helm chart be secured as per [this post](https://blog.heptio.com/on-securing-the-kubernetes-dashboard-16b09b1b7aca).

**Comment by hausdorff** [comment]
This This might not be necessary for Q3. The k8s dashboard is used quite infrequently.

**Comment by lukehoban** [comment]
This has not come up much, and the chart is easy to install directly for those looking to do so.  https://github.com/kubernetes/dashboard/tree/master/aio/deploy/helm-chart/kubernetes-dashboard.
