### ISSUE TITLE
A failed Deployment update doesn't seem to fail

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#611]
If I update an existing Deployment to reference an erroneous image name, the update succeeds, even though the resulting Pod ends up in an endless backoff.

The resulting `kubectl get po` looks like this:

```
$ kubectl get po
NAME                              READY     STATUS             RESTARTS   AGE
nginx-u76btcdw-9b5ccdb7-psf64     0/1       ImagePullBackOff   0          22s
nginx-u76btcdw-9cb4784bd-vjrww    1/1       Running            0          52s
```

`nginx-u76btcdw-9cb4784bd-vjrww` is the old Pod running the correctly named image -- which I assume would go away once the rollout has completed -- and `nginx-u76btcdw-9b5ccdb7-psf64` is the newly created Pod that is meant to replace it, but cannot, due to the mistyped image name.

This is inconsistent with what happens with a new `Deployment`. Shouldn't this fail too?

-------

@lblackstone Update:
I've fixed this for all apiVersions except for `extensions/v1beta1`, which will require additional work. Will close out this issue once #656 is done.

**Comment by joeduffy** [comment]
This seems to be true of other update failures, e.g. if I update a Deployment to use an unsatisfiable nodeSelector constraint. Again, on the first update, I get the error I would expect, `1 Pods failed to schedule because: [Unschedulable] 0/3 nodes are available: 3 node(s) didn't match node selector`, but not when subsequently updating an existing Deployment.

**Comment by lblackstone** [comment]
Yep, I was able to reproduce this failure. It must be a bug in the await logic. 😬

**Comment by hausdorff** [comment]
Plan is to fix this immediately, I assume?

**Comment by lblackstone** [comment]
From what I can tell so far, it seems that updating the Deployment generates an Event with the Deployment object from the previous (successful) generation. This causes the await logic to pass immediately before it sees the subsequent Events come through with the invalid image spec. 

The logic does seem to work correctly once the updated Event stream comes through.

**Comment by lblackstone** [comment]
This bug has been root-caused, but we haven't yet agreed on how to fix (proposal in #615). Will tackle this early in M25.

**Comment by hausdorff** [comment]
We might want to save the last `v1.WatchEvent` as an annotation, but for this bug specifically, I think we should do the following to mitigate this bug:

* During an `Update`, start the `.Watch` _BEFORE_ issuing the actual update operation.
* Ignore the first `v1.WatchEvent` -- we don't need it.
* _NOW_ issue the update and proceed as usual.

This bug must have been introduced in the transition to the `.Watch` APIs generally, which is disappointing. This is a big enough deal I think we should actually sit down and use the kube provider in anger to make sure there's nothing else obviously wrong with it.

**Comment by hausdorff** [comment]
I should amend what I said above—I'd forgotten that we actually did write the `apps/v1` await logic to be resilient to the watch/create timing discrepancy.

Unfortunately, the information that we rely on for this is not present in `extensions/v1beta1`. So, we need to change the await logic again to deal with this.
