### ISSUE TITLE
Helm chart duplicate URNs

### ISSUE THREAD

**Issue by timmyers** [pulumi/pulumi-kubernetes#616]
This is another issue around the problem of resulting in duplicate URN's with the usage of helm charts.  Previous, similar issues include #489 and #520.

A `resourcePrefix` option was added to address this in #599, however this occurs even with that fix.

Some helm charts instantiate resources of `type: APIService` (or other similar types), which will require `metadata.name` to take on a specific format.  An example value for an `APIService` resource might be `v1beta1.metrics.k8s.io`.  These names are hard coded, and not interpolated based on the release name.

The `resourcePrefix` only affects the release name, and so does not prevent these resources from colliding if multiple are instantiated.

```typescript
class K8SMetricsServer extends pulumi.ComponentResource {
  public constructor(name: string, settingsIgnored: { }, opts?: pulumi.ComponentResourceOptions) {
    super('infrastructure:k8s-metrics-server', name, { }, opts);

    const defaultOpts = { parent: this };

    const chartIgnored = new k8s.helm.v2.Chart(name, {
      repo: 'stable',
      chart: 'metrics-server',
      version: '2.8.2',
      resourcePrefix: name,
    }, defaultOpts);

    this.registerOutputs();
  }
}

export default async (): Promise<void> => {
    const metricsServer1 = new K8SMetricsServer("metrics1", {}, {});
    const metricsServer2 = new K8SMetricsServer("metrics2", {}, {});
};
```

```shell
pulumi preview

...

Diagnostics:
  pulumi:pulumi:Stack (infrastructure-clusters):
    (node:76310) ExperimentalWarning: queueMicrotask() is experimental.
 
  kubernetes:apiregistration:APIService (kube-system/v1beta1.metrics.k8s.io):
    error: Duplicate resource URN 'urn:pulumi:clusters::infrastructure::infrastructure:k8s-cluster-v2$infrastructure:k8s-metrics-server$kubernetes:helm.sh/v2:Chart$kubernetes:apiregistration/v1beta1:APIService::kube-system/v1beta1.metrics.k8s.io'; try giving it a unique name
```

**Comment by mazamats** [comment]
Just ran into this as well, seems that `resourcePrefix` is only being used for the component constructor.
