### ISSUE TITLE
Failure to update cert-manager 0.7->0.8 ConfigFile url changed `refusing to delete protected resource`

### ISSUE THREAD

**Issue by rosskevin** [pulumi/pulumi-kubernetes#629]
Trying to upgrade cert-manager from 0.7.2 to 0.8.0, and they have changed the location of the raw manifest.

Previously, it was:
https://raw.githubusercontent.com/jetstack/cert-manager/release-0.7/deploy/manifests/cert-manager.yaml

The updated location is:
https://github.com/jetstack/cert-manager/releases/download/v0.8.1/cert-manager.yaml

Failure:
![infrastructure_—_circleci_ba8b39223eb7____project_cloud_infrastructure_—_-zsh_▸_-zsh_—_317×102](https://user-images.githubusercontent.com/136564/61064395-4bf9eb00-a3c7-11e9-9bc3-a9eb46d6888c.gif)

```
Diagnostics:
  kubernetes:yaml:ConfigFile (https://raw.githubusercontent.com/jetstack/cert-manager/release-0.7/deploy/manifests/cert-manager.yaml):
    error: Preview failed: refusing to delete protected resource 'urn:pulumi:production::advisorintake-infrastructure::af:pulumi:CertManager$kubernetes:yaml:ConfigFile::https://raw.githubusercontent.com/jetstack/cert-manager/release-0.7/deploy/manifests/cert-manager.yaml'
```

## Reproduction
```ts
// Install the CustomResourceDefinitions and cert-manager itself
const installCertManager = (url: string) => {
    const certManager = new k8s.yaml.ConfigFile(url,
      undefined,
      { parent: this },
    )
}
```

### install 0.7

```ts
installCertManager('https://raw.githubusercontent.com/jetstack/cert-manager/release-0.7/deploy/manifests/cert-manager.yaml')
```

### install 0.8.1

```ts
installCertManager('https://github.com/jetstack/cert-manager/releases/download/v0.8.1/cert-manager.yaml')
```

**Comment by lukehoban** [comment]
As you marked this resource (or its parent) as `protect: true`?  As far as I know - that’s the only way to get the error above. 

You will need to undo the protection on either the component or the specific child to be allowed to delete it (or replace it - as that requires a delete).

**Comment by rosskevin** [comment]
Hah! sorry, I forgot.  Pulumi has been so convenient that we somewhat get the set and forget mindset, so getting back into it is sometimes a learning thing.  

The update was not successful (recurrence of another issue) so I'll file a separate issue.
