### ISSUE TITLE
Pulumi with Helm unable to install large chart

### ISSUE THREAD

**Issue by minhphl** [pulumi/pulumi-kubernetes#643]
When installing [Prometheus Operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) using Helm chart:

```js
const chart = new k8s.helm.v2.Chart('prometheus-operator', {
  repo: 'stable',
  chart: 'prometheus-operator',
  values: {
    fullNameOverride: 'prometheus-operator'
  }
})
```

I get this error:

```
Error: spawnSync /bin/sh ENOBUFS
        at /Users/minh/Work/kubernetes-cluster/node_modules/@pulumi/kubernetes/helm/v2/helm.js:115:23
        at OutputImpl.<anonymous> (/Users/minh/Work/kubernetes-cluster/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:109:47)
        at Generator.next (<anonymous>)
        at fulfilled (/Users/minh/Work/kubernetes-cluster/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/output.js:17:58)
```

Seems like the issue is due to default `maxBuffer` of `child_process.execSync()` being `1024 * 1024` (https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options), which is smaller than the output of `helm template`.

Manually adding a large value of `maxBuffer` to `execSync` works https://github.com/pulumi/pulumi-kubernetes/blob/eb771e06c90a5363917260bfa4688498170e17e1/sdk/nodejs/helm/v2/helm.ts#L174-L176

**Comment by gitfool** [comment]
I just hit this too. @lblackstone looking forward to a release with #864 in it. 😉

**Comment by lblackstone** [comment]
v.1.3.0 is out now with this fix
