### ISSUE TITLE
API server normalization of values is causing a preview to show changes when one is not expected in testing.

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes#644]
This error showed up in CI cron jobs in the last 24 hours of `pulumi/eks` tests:

A deployment marked with resources `2048Mi` is being normalized to `2Gi` on the initial update, and then on the `empty` `pulumi preview` step it is trying to change it back to `2048Mi` - this unexpected change causes the test to fail when it does not expect changes.

This occurs on `pulumi preview` right after an initial `pulumi up` of a Deployment using resources with `2048Mi` notation.

```
metral@argon:~/temp-clusters/migrate-nodegroups-6$ pul preview --diff
Previewing update (test6):
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:test6::migrate-nodegroups::pulumi:pulumi:Stack::migrate-nodegroups-test6]
    ~ kubernetes:apps/v1:Deployment: (update)
        [id=apps-ql27r77a/nginx-ing-cntlr-tr0nrsi8]
        [urn=urn:pulumi:test6::migrate-nodegroups::kubernetes:apps/v1:Deployment::nginx-ing-cntlr]
        [provider=urn:pulumi:test6::migrate-nodegroups::eks:index:Cluster$pulumi:providers:kubernetes::migrate-nodegroups-provider::4316e425-4b56-4dd0-9d7e-78555a61b922]
      ~ spec: {
          ~ template: {
              ~ spec: {
                  ~ containers: [
                      ~ [0]: {
                              ~ resources: {
                                  ~ limits  : {
                                      ~ memory: "2Gi" => "2048Mi"
                                    }
                                  ~ requests: {
                                      ~ memory: "1Gi" => "1024Mi"
                                    }
                                }
                            }
                    ]
                }
            }
        }
Resources:
    ~ 1 to update
    84 unchanged
```

**Versions**:
- `pulumi/pulumi`: 0.17.25
- `pulumi/kubernetes`: 0.25.2
- `pulumi/eks`: 0.18.10

See related Slack [conversation](https://pulumi.slack.com/archives/CBUP505U7/p1562651913033000
) about a similar type of error occurring in the aws-tf-provider a couple weeks back.

**Comment by arnediekmann** [comment]
This is biting us as well for StatefulSets especially - is there a date when we can expect this change as part of a new release of `@pulumi/pulumi-kubernetes`?
