### ISSUE TITLE
Pulumi unable to install Helm chart with Helm installed via Snap Store

### ISSUE THREAD

**Issue by ghost** [pulumi/pulumi-kubernetes#650]
# Description

OS: Ubuntu 19.04

1. Install `helm` using Snap Store:

```bash
sudo snap install helm --classic
```

2. Install Helm chart using Pulumi:

```js
const operator = new k8s.helm.v2.Chart('kubedb-operator', {
  namespace: 'kube-system',
  chart: 'kubedb',
  version: '0.12.0',
  fetchOpts: {
    repo: 'https://charts.appscode.com/stable/'
  },
  values: {},
  transformations: [
    manifest => {
      if (manifest.metadata) {
        manifest.metadata.namespace = targetedNamespace
      } else {
        manifest = {
          namespace: targetedNamespace
        }
      }

      return manifest
    }
  ]
})
```

3. `pulumi up` finishes quickly (~ 1 sec), and no resources are created.

This issue doesn't happen when `helm` is installed by manually copying the downloaded binary to system's `PATH`

**Comment by lblackstone** [comment]
@minhphl Does the `helm` binary appear on your `PATH` when it's installed via the Snap Store? Our SDK shells out to `helm`, and expects it to be present on the `PATH`.

**Comment by minhphl** [comment]
@lblackstone It does. After digging a little deeper I found out that this line:

```js
execSync(`helm fetch ${shell.quote([chart])} ${flags.join(" ")}`);
```

Doesn't produce anything at the designated path (`/tmp/tmp-foo`), but doesn't give any error whatsoever.

**Comment by lblackstone** [comment]
This applies to the helm.v2.Chart resource, which won't be updated. This issue should not affect the helm.v3.Chart or helm.v3.Release resources.
