### ISSUE TITLE
Deployment claims to be initialized immediately when rollout fails

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#652]
Take a vanilla v1 deployment, change the image tag to be something that doesn't exist, and a `pulumi up` will report success immediately.

**Comment by lukehoban** [comment]
Isn't this the same as https://github.com/pulumi/pulumi-kubernetes/issues/611?  

The text of the descriptions is effectively identical:

>  I update an existing Deployment to reference an erroneous image name, the update succeeds, even though the resulting Pod ends up in an endless backoff.

> Take a vanilla v1 deployment, change the image tag to be something that doesn't exist, and a pulumi up will report success immediately.

**Comment by hausdorff** [comment]
I just came back to say: I thought we checked in #646 today so I thought this was a regression. With that PR this does seem to be fixed.
