### ISSUE TITLE
Feature:  Support for multiple values files in helm charts

### ISSUE THREAD

**Issue by bazzuka** [pulumi/pulumi-kubernetes#659]
Add ability to include multiple files to `helm template` command, like --values values1.yaml --values values2.yaml directly from filesystem.

From helm documentation:

> There are two ways to pass configuration data during install:
> 
> --values (or -f): Specify a YAML file with overrides. This can be specified multiple times and the rightmost file will take precedence
> --set (and its variants --set-string and --set-file): Specify overrides on the command line.
> If both are used, --set values are merged into --values with higher precedence. 

Thanks in advance

**Comment by lukehoban** [comment]
@bazzuka what would you want this to look like in the Pulumi API?

I believe this is already possible by reading the files off disk yourself, yank parsing them, merging the values, and passing the resulting object to the Pulumi helm chart API.

**Comment by bazzuka** [comment]
values (Optional[pulumi.Inputs]) – Optional overrides for chart values.
values_files (Optional[List[Callable]) - Optional overrides for chart yaml values files.

I wrote simple python example: 
``` 
           config=helm.ChartOpts(chart=chart,
                                  namespace=namespace,
                                  values = {'buildId': '234',
                                            'appName': project,
                                            'imageTag': tag,
                                            'environment': 'release'},
                                  values_files = ['path_to_values/values.default.yaml', 'path_to_values/values.release.yaml']
                                  )
```

```
    values_files = ['path_to_values/values.default.yaml', 'path_to_values/values.release.yaml']
    extend_values_list = []
    for file in values_files:
        extend_values_list.append('--values')
        extend_values_list.append(file)

    cmd = ['helm', 'template', chart, '--name', release_name,
           '--values', default_values, '--values', overrides.name]

    cmd.extend(extend_values_list)
```

**Comment by darkn3rd** [comment]
Any update?

**Comment by lblackstone** [comment]
Still on the backlog for now. If you really need this in the meantime, you can use `helm template` to generate the YAML, and then use `yaml.ConfigGroup` to manage the manifests with Pulumi.

**Comment by griffithq** [comment]
Any update on this or how others are working around this?

**Comment by mikhailshilkov** [comment]
@viveklak Does Helm Release support this yet?

**Comment by viveklak** [comment]
> @viveklak Does Helm Release support this yet?

Yes - this has been supported in helm release as of https://github.com/pulumi/pulumi-kubernetes/releases/tag/v3.12.1

**Comment by mikhailshilkov** [comment]
Brilliant! @griffithq would that be an option for you?

**Comment by magick93** [comment]
Thanks @viveklak - are there any docs on how to use this?

**Comment by EronWright** [comment]
Here's the documentation on how to use multiple values files with the `v3.Release` resource:
https://www.pulumi.com/registry/packages/kubernetes/api-docs/helm/v3/release/#specify-helm-chart-values-in-file-and-code

Sorry to report that `v3.Chart` doesn't support this.

**Comment by EronWright** [comment]
Update: the upcoming Chart v4 resource has full support for multiple values files. Enjoy!

```python
"""A Kubernetes Python Pulumi program"""

import pulumi
from pulumi_kubernetes.helm.v4 import Chart,RepositoryOptsArgs

nginx = Chart("nginx",
    chart="bitnami/nginx",
    value_yaml_files=[
        pulumi.FileAsset("path_to_values/values.default.yaml"),
        pulumi.FileAsset("path_to_values/values.release.yaml")
    ],
    values={
        "service": {
            "type": "ClusterIP"
        },
        "notes": pulumi.FileAsset("./notes.txt")
    }
)
```
