### ISSUE TITLE
Helm date format error

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#667]
I came across [a chart](https://github.com/kedacore/keda/tree/8ffd9a3e236e39eafcf0ec85616d6111783e0273/chart/keda) that includes a `.tpl` [file](https://github.com/kedacore/keda/blob/8ffd9a3e236e39eafcf0ec85616d6111783e0273/chart/keda/templates/_helpers.tpl) which apparently is used to define some common values for the chart. I get the following errors when I try to install the chart:

```
  kubernetes:core:Service (default/keda-keda-edge):
    error: Plan apply failed: resource keda-keda-edge/%!s(MISSING) was not successfully created by the Kubernetes API server default: Service "keda-keda-edge" is invalid: metadata.labels: Invalid value: "2019-07-30T00:00:00.000Z": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

  pulumi:pulumi:Stack (pulumi-k8s-test-pulumi-k8s-test-dev):
    error: update failed

  kubernetes:core:ServiceAccount (default/keda-serviceaccount):
    error: Plan apply failed: resource keda-serviceaccount/%!s(MISSING) was not successfully created by the Kubernetes API server default: ServiceAccount "keda-serviceaccount" is invalid: metadata.labels: Invalid value: "2019-07-30T00:00:00.000Z": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

  kubernetes:rbac.authorization.k8s.io:ClusterRoleBinding (default/keda-keda-edge):
    error: Plan apply failed: resource keda-keda-edge/%!s(MISSING) was not successfully created by the Kubernetes API server default: ClusterRoleBinding.rbac.authorization.k8s.io "keda-keda-edge" is invalid: metadata.labels: Invalid value: "2019-07-30T00:00:00.000Z": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

Here's the code I used to create the chart:
```ts
const keda = new k8s.helm.v2.Chart("keda", {
        repo: "kedacore",
        chart: "keda-edge",
        version: "0.0.1-2019.07.24.21.37.42-8ffd9a3",
        values: {
            logLevel: "debug",
        },
});

```

**Comment by lblackstone** [comment]
Hmm, after some further testing, it seems that `helm template` works with this chart, so it's likely a problem with our Helm support in the Node SDK.

Here's an example of the Service object generated by `helm template`:
```yaml
# Source: keda-edge/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keda-edge
    chart: keda-edge-0.0.1-2019.07.24.21.37.42-8ffd9a3
    release: keda-edge
    date: 2019-07-30
  name: keda-edge
  namespace: default
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    name: keda-edge
    instance: keda-edge-instance
```

The date format was different in our error message, so that's probably the culprit:
```
2019-07-30
```
vs
```
2019-07-30T00:00:00.000Z
```

**Comment by mikhailshilkov** [comment]
For context, I was trying to create an example of [KEDA](https://github.com/kedacore/keda) with Pulumi by porting [this Terraform example](https://github.com/JimPaine/keda-demo)

**Comment by lblackstone** [comment]
cc @pgavlin @hausdorff 

Do you know what would cause the date to be generated in that format?

**Comment by lukehoban** [comment]
> it’s likely a problem with the Helm support on our Node SDK

We just shell out to `helm template`. Does the exact same command line we pass produce something different when you run it manually?

https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/helm/v2/helm.ts#L175

**Comment by lblackstone** [comment]
@lukehoban Yes, when I ran it manually, the date format was `2019-07-30`

**Comment by lukehoban** [comment]
Oh YAML...

```
> JSON.stringify(require('js-yaml').safeLoad(`date: 2019-07-30`))
'{"date":"2019-07-30T00:00:00.000Z"}'
```

**Comment by lukehoban** [comment]
Sounds like we need to provide the same "Schema" as Kubernetes will use to parse this YAML.  Do we know what that is?

https://github.com/nodeca/js-yaml/issues/161#issuecomment-72711349

**Comment by lukehoban** [comment]
I *think* we need to set `schema: CORE_SCHEMA` to match Kubernetes.  

```
> JSON.stringify(require('js-yaml').safeLoad(`date: 2019-07-30`, {json: true, schema: require('js-yaml').CORE_SCHEMA}))
'{"date":"2019-07-30"}'
```

**Comment by lukehoban** [comment]
Kubernetes ultimately bottoms out on using [gopkg.in/yaml.v2](https://github.com/go-yaml/yaml).  

https://github.com/kubernetes-sigs/yaml/blob/v1.1.0/yaml.go#L49

That package is not super-clear on the precise profile of YAML that it uses for parsing, or even what specification it is aiming to be compatible with.

**Comment by mikhailshilkov** [comment]
Thanks Luke, I've been grinding jsyaml to find the reason.

> I _think_ we need to set `schema: CORE_SCHEMA` to match Kubernetes.
> 
> ```
> > JSON.stringify(require('js-yaml').safeLoad(`date: 2019-07-30`, {json: true, schema: require('js-yaml').CORE_SCHEMA}))
> '{"date":"2019-07-30"}'
> ```

This fixes the problem! I have the chart deployed.
