### ISSUE TITLE
Investigate whether changes are needed to support upcoming API deprecations

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#671]
Several older APIs will be removed in the upcoming 1.16 release. We need to check and see if any work is needed in the provider to support a smooth upgrade for existing resources.

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ has details.
```
To start a v1.15.0 API server with these resources disabled to flush out dependencies on these deprecated APIs, and ensure your application/manifests will work properly against the v1.16 release, use the following --runtime-config argument:

--runtime-config=apps/v1beta1=false,apps/v1beta2=false,extensions/v1beta1/daemonsets=false,extensions/v1beta1/deployments=false,extensions/v1beta1/replicasets=false,extensions/v1beta1/networkpolicies=false,extensions/v1beta1/podsecuritypolicies=false
```

**Comment by lblackstone** [comment]
Testing this with minikube now. Steps to get the cluster running are:

1. [Install minikube](https://minikube.sigs.k8s.io/docs/start/macos/)
1. `minikube start --vm-driver=hyperkit --extra-config=apiserver.runtime-config=apps/v1beta1=false,apps/v1beta2=false,extensions/v1beta1/daemonsets=false,extensions/v1beta1/deployments=false,extensions/v1beta1/replicasets=false,extensions/v1beta1/networkpolicies=false,extensions/v1beta1/podsecuritypolicies=false`
1. Confirm k8s configuration with `kubectl api-versions` -- `apps/v1beta1` should not be present

**Comment by lblackstone** [comment]
Pulumi surfaces the relevant error when trying to create a resource with the old apiVersion that doesn't exist on a 1.16-like cluster:
```
error: Plan apply failed: creation of resource hello-tf5m9ldu failed because the Kubernetes API server reported that the apiVersion for this resource does not exist. Verify that any required CRDs have been created: no matches for kind "Deployment" in version "apps/v1beta1"
```
The old apiVersions still exist in our SDK, so this shouldn't require any additional action for us to support at this time. Users hitting this error against a 1.16+ cluster can switch to using a supported apiVersion, and optionally use aliases to update the resource in place.

**Comment by nesl247** [comment]
@lblackstone Are there any plans for a better error message? It would be great if Pulumi was more aware and gave a better error message, such as `apps/v1beta1/Deployment was removed in 1.16. Please upgrade to apps/v1/Deployment or later` for example.

**Comment by lblackstone** [comment]
@nesl247 I'm working on that right now! :)

**Comment by lblackstone** [comment]
https://github.com/pulumi/pulumi-kubernetes/pull/779 adds relevant warnings for deprecated apiVersions.
