### ISSUE TITLE
Implement Go provider

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-kubernetes#70]
We will add Go support to the Kubernetes provider.  This includes the following work:
- [x] Core Kubernetes API resources (https://github.com/pulumi/pulumi-kubernetes/pull/1029)
- [x] Helm/YAML support (https://github.com/pulumi/pulumi-kubernetes/issues/1037)
- [x] apiextensions.CustomResource (https://github.com/pulumi/pulumi-kubernetes/pull/1125)

**Comment by hausdorff** [comment]
Moving (tentatively) to M17, as (1) we don't have a customer asking for this, and (2) now that the Helm support has landed in TS/JS mainline pulumi-kubernetes, adding Python support at least merits considering including Helm support, which would increase the amount of work to do by a fair amount.

**Comment by hausdorff** [comment]
Not prioritized for 0.17. Moving to 0.18.

**Comment by hausdorff** [comment]
@naveensrinivasan It's definitely on the horizon, but it's not clear how we're going to provide a really good experience for Kubernetes specifically, at least before Go 2 -- the deeply-nested nature of the API means there ends up being a lot of `interface{}`. Hence, we've marked it as "help wanted".

My personal view is that it's better to wait until we can provide a good experience, than to provide a not-very-good one that technically works. :) Could be wrong that it's not-very-good, _etc_., happy to hear different views on this.

cc @swgillespie @joeduffy @lukehoban @lblackstone

**Comment by Place1** [comment]
@hausdorff i'm not familiar with pulumi's source so forgive me if this is a silly comment, but why would k8s deeply nested API require the use of `interface{}`. Here's an example of a typed struct for a [Deployment](https://godoc.org/k8s.io/api/apps/v1#Deployment) from `client-go`, you can click all the way through it and there's no usage of `interface{}`. What am i missing?

**Comment by hausdorff** [comment]
@Place1 Think about stuff like `Service`'s `.spec.clusterIP`. The value of this property is computed by the API server. To reflect this, in other languages, we make the type `Output<T>`. Semantically this is much like a `Promise<T>` -- indicating that the values may be filled in later. In Go, this is `interface{}`.

In some sense this is _the_ Pulumi object model. `Output<T>` allows us to keep track of which resources depend on other resources (_e.g._, our `Deployment` depends on the EKS cluster).

In the case of Kubernetes specifically, the deeply-nested nature of the Kubernetes makes `interface{}` very cumbersome to deal with. This is in contrast to, say, the AWS resource model, which is "shallow".

**Comment by lukehoban** [comment]
We expect to implement this on top of the new schema-based code generators in pulumi/pulumi. There is some work in progress on that in https://github.com/pulumi/pulumi-kubernetes/commits/pgavlin/schema.
