### ISSUE TITLE
cert-manager 0.9.1 does not install

### ISSUE THREAD

**Issue by squarebracket** [pulumi/pulumi-kubernetes#710]
I tried to install cert-manager 0.9.1 using the following:

```typescript
const certManager = new k8s.yaml.ConfigFile('https://github.com/jetstack/cert-manager/releases/download/v0.9.1/cert-manager.yaml', {provider: clusterProvider});
```

This fails, with errors messages relating to the CRDs.

Notably, installation works with 0.8.1.

Both installing with a fresh stack and upgrading from 0.8.1 --> 0.9.1 failed.

**Comment by lblackstone** [comment]
@squarebracket I wasn't able to reproduce this error with the latest release (`1.0.0-beta.1`). Going to close this out, but feel free to re-open with additional details if you're still having problems.

![Screen Shot 2019-08-19 at 10 01 02 AM](https://user-images.githubusercontent.com/9253463/63280675-7ceffa00-c268-11e9-9545-dfe6ca070edf.png)
