### ISSUE TITLE
Timeout occurred for Deployment: Minimum number of Pods to consider the application live was not attained

### ISSUE THREAD

**Issue by metral** [pulumi/pulumi-kubernetes#712]
On occasion, we'll see the default 5min await logic timeout cause errors for `pulumi updates`.

For example, here are the errors returned when a spec change for Deployment was made in a step of a `pulumi/eks` test, but apparently it was not enough time.

```
 mples/tests/migrate-nodegroups ]   kubernetes:apps:Deployment (nginx-ing-cntlr):
[ mples/tests/migrate-nodegroups ]     error: Plan apply failed: 2 errors occurred:
[ mples/tests/migrate-nodegroups ]     	* Timeout occurred for 'nginx-ing-cntlr-z8bqbx14'
[ mples/tests/migrate-nodegroups ]     	* Minimum number of Pods to consider the application live was not attained
```

Should this default be increased?
Is there a way to customize the timeout?

**Comment by lblackstone** [comment]
> Should this default be increased?

I think the current timeout default works well in most cases, but it would be good to be more clear what that value is for each resource and how to override. I'll open an issue to track.

> Is there a way to customize the timeout?

Until #672 is done, you can add the [`pulumi.com/timeoutSeconds`](https://www.pulumi.com/blog/improving-kubernetes-management-with-pulumis-await-logic/#new-annotations-to-customize-kubernetes-await-logic) annotation to the Deployment in question.

**Comment by lblackstone** [comment]
Opened https://github.com/pulumi/pulumi-kubernetes/issues/714 to track the concrete improvements to make. I'll close out this issue in favor of that.
