### ISSUE TITLE
Kubernetes Python docs missing many things

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#728]
There are a lot of key things missing in our Kubernetes Python docs.

We should align our Python code generation with tfgen code generation.

Two most obvious issues:
- Resources have no properties
- Resource constructors have no documentation detailing parameter types/info

Kubernetes Python docs:

![Screen Shot 2019-08-21 at 4 52 44 PM](https://user-images.githubusercontent.com/223467/63476031-3d760900-c434-11e9-87ad-7264e787b58f.png)

vs. tfgen Python docs:

![Screen Shot 2019-08-21 at 4 57 09 PM](https://user-images.githubusercontent.com/223467/63476166-c8ef9a00-c434-11e9-9126-efdb90724dbe.png)
![Screen Shot 2019-08-21 at 4 57 24 PM](https://user-images.githubusercontent.com/223467/63476171-cd1bb780-c434-11e9-9fa4-30516718956f.png)

**Comment by hausdorff** [comment]
I noticed that we're generating docs for `translate_output_property` and `translate_input_property` in all our python docs for all providers—probably not what we want. Should we fix for Q3?
