### ISSUE TITLE
Pass correct --kube-version to `helm template`

### ISSUE THREAD

**Issue by redbaron** [pulumi/pulumi-kubernetes#753]
### Problem description

helm  template is invoked without `--kube-version`, which then internally defaults to `1.9` cluster version. 

### Suggestions for a fix

get kubernetes version from provider and pass it to `helm template --kube-version ${k8sver}`

**Comment by lblackstone** [comment]
Took a look at the [docs](https://helm.sh/docs/helm/#helm-template), and it appears that the default depends on the version of Helm you're using. It currently says that 1.14 is default.
> --kube-version string      Kubernetes version used as Capabilities.KubeVersion.Major/Minor (default "1.14")

I can't think of a way to tell what version of k8s is being targeted in general, but we could potentially expose that as an option on the Chart.

**Comment by arnediekmann** [comment]
Is exposing kube-version (like pr #894) this still on the agenda? Would be neat addition for sure.

**Comment by gitfool** [comment]
@lblackstone Please add `KubeVersion` to the chart args so we can at least control it.
