### ISSUE TITLE
intellisense broken for Python `pulumi_kubernets.Provider`

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#759]
<img width="672" alt="Screen Shot 2019-08-27 at 3 02 52 PM" src="https://user-images.githubusercontent.com/1409156/63811272-db0d8480-c8db-11e9-8c9b-b4cca3697400.png">

**Comment by hausdorff** [comment]
After some time with this, I think we're doing the right thing, and vscode is having a hard time with that. I think we should close it, but I'm also not an expert. @lukehoban?

**Comment by justinvp** [comment]
This has been addressed.
