### ISSUE TITLE
`LocalChartOpts` does not exclude fields that are not used

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#762]
One of our examples has the following code:

```typescript
export const istio = new k8s.helm.v2.Chart(
    appName,
    {
        path: "charts/istio",
        version: "1.1",
        namespace: istioNamespace,
        values: { kiali: { enabled: true } },
    },
    { dependsOn: [namespace, adminBinding, istio_init], providers: { kubernetes: k8sProvider } },
);
```

The `version` here is actually completely spurious when `path` exists. `version` is used to fetch a specific version of a Chart—when `path` is present, the `version` is implicitly whatever version of the Chart is already at `path`.

We should remove this field from the `LocalChartOpts`.

**Comment by lblackstone** [comment]
https://github.com/microsoft/TypeScript/issues/27541#issuecomment-441645267 discusses the same thing. I think we can close this out now.

**Comment by CyrusNajmabadi** [comment]
Closing out.  Alex i think this is just what we have to deal with.
