### ISSUE TITLE
yaml.ConfigGroup not implemented in Python

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#770]
`yaml.ConfigGroup` allows users to instantiate k8s resources from a wildcard set of files, like:

```typescript
const guestbook = new k8s.yaml.ConfigGroup("guestbook", { files: "yaml/*.yaml" });
```

This API is not implemented in Python.

**Comment by joeduffy** [comment]
Note that I just ran into this while bringing up some new user guides: https://www.pulumi.com/docs/guides/adopting/from_kubernetes/#deploying-multiple-kubernetes-yaml-files. Not a huge deal, however, am guessing we've forgotten about this and that it's a simple fix.

**Comment by drocsid** [comment]
https://www.pulumi.com/docs/guides/adopting/from_kubernetes/ missing documentation
