### ISSUE TITLE
Layer of abstraction for k8s resources

### ISSUE THREAD

**Issue by offlinehacker** [pulumi/pulumi-kubernetes#78]
I don't know where to put this, as it touches the general architecture of pulumi, but it now mostly affects kubernetes. The thing is, from perspective of developer, they should not think how to deploy some complex redis cluster on k8s, their only requirement would be to have a redis with clustering. What would be really useful(and make pulumi totally dope) is to have a layer of abstraction, that would abstract service deployment for different environments(k8s, cloud providers, local docker, ...). What you could do with that is following:

```
import * as services from '@pulumi/services'

const redis = new services.Redis({
  memory: '4Gi',
  persistence: true,
  clustering: true
}):

console.log(redis.url):
```

What do you think about this idea?

**Comment by joeduffy** [comment]
Definitely something we aspire to enable!

The cloud framework has a `cloud.Service` type whose purpose is exactly this.  It doesn't support Kubernetes yet (that's tracked by https://github.com/pulumi/pulumi-cloud/issues/227), but we would welcome help if you're interested.  Our thinking is to leverage minikube to run locally.

We'll have a better idea of our roadmap in the next couple weeks, including where this falls, and will share it back.

**Comment by hausdorff** [comment]
Strong thumbs up. I don't work at Pulumi, but I wrote the k8s provider, and I have a strong interest in raising the level of abstraction.

**Comment by hausdorff** [comment]
(I should say for the first cut we purposefully made it kind of boring, as we were not yet prepared to commit the core libraries to higher-level abstractions, yet.)

**Comment by hausdorff** [comment]
We're going to close this in favor of the upcoming kubernetesx work.
