### ISSUE TITLE
cannot upgrade nginx-ingress helm chart

### ISSUE THREAD

**Issue by squarebracket** [pulumi/pulumi-kubernetes#796]
### Problem description

This is probably more generalized to all helm charts, but I saw this issue with `nginx-ingress` updating from 1.17.? => 1.19.1 and from 1.19.1 => 1.20.0.

The issue occurs with the following pulumi program:
```typescript
/**
 * Install nginx-ingress to the cluster referenced by `provider`
 *
 * @param provider The cluster to which nginx-ingress will be installed
 * @return The IP of the `LoadBalancer` for the ingress
 */
export function addNginxIngress(provider: k8s.Provider): pulumi.Output<string> {
    const nginxIngressController = new k8s.helm.v2.Chart("nginxingresscontroller", {
        repo: "stable",
        chart: "nginx-ingress",
        values: {
            controller: {
                service: {
                    omitClusterIP: true,
                },
                metrics: {
                    service: {
                        omitClusterIP: true,
                    },
                },
            },
            defaultBackend: {
                service: {
                    omitClusterIP: true,
                },
            }
        },
        namespace: 'default',
    }, {
        providers: {
            kubernetes: provider
        }
    });
    const nginxIngressIP = nginxIngressController.getResourceProperty(
        "v1/Service",
        'nginxingresscontroller-nginx-ingress-controller',
        'status').loadBalancer.ingress[0].ip;
    return nginxIngressIP;
}
```

Note that the only change to resources when updating the chart is for its deployments' `metadata.labels.chart` field. Nothing else changes.

This results in pulumi hanging on the deployments:

```
error: Plan apply failed: 2 errors occurred:
	* 'nginxingresscontroller-nginx-ingress-controller' timed out waiting to be Ready
	* Minimum number of live Pods was not attained


error: Plan apply failed: 2 errors occurred:
	* 'nginxingresscontroller-nginx-ingress-default-backend' timed out waiting to be Ready
	* Minimum number of live Pods was not attained
```

However, if you inspect the deployments with `kubectl`, the chart label has been updated to the new version.

Running `pulumi stack export`, I can see the deployments have `inputs` with the chart label set to the old version, and the `outputs` set to the new version. Running `pulumi refresh` changes the `inputs` to the new version as well, but pulumi still thinks the deployment is unhealthy. 

### Errors & Logs

See above. If you need anything more verbose, please just ask.

### Affected product version(s)

Unknown. I am using 1.0.0

### Reproducing the issue

The above function should be sufficient for reproducing. Please let me know if it's not.

### Suggestions for a fix

No idea, sorry.

**Comment by lblackstone** [comment]
Good call @pgavlin -- this does appear to be the same bug I just fixed in #793. The `dev` release already contains this fix, and I'm working on cutting a tagged release today.
