### ISSUE TITLE
Plan apply failed: Could not find object of type 'v1/ServiceAccount'

### ISSUE THREAD

**Issue by colemickens** [pulumi/pulumi-kubernetes#80]
I'm currently have a Plan failing...

```
const dexLabels = { app: "dex" };
const dexNamespace = "dex";
const dexMetadata = {
    name: "dex",
    namespace: dexNamespace,
    labels: dexLabels,
};

...

const serviceAccount = new kubernetes.core.v1.ServiceAccount("dex", {
    metadata: dexMetadata,
});
```

It fails with:

```
Plan apply failed: Could not find object of type 'v1/ServiceAccount'
```

Despite the fact that it's creating my ServiceAccount:

```
$ kubectl get sa
NAME      SECRETS   AGE
default   1         2m
dex       1         15s
```

**Comment by hausdorff** [comment]
Yeah, what's happening is that the underlying dynamic client knows how to submit pretty much any kube API object, but the logic that waits for it to be initialized doesn't know what to wait on, yet. I can probably fix this for SAs today.

**Comment by colemickens** [comment]
I wouldn't mind having a no-wait-for-init mode. FWIW, for me to get this particular "chart" (?) working, I need `Role` & `RoleBinding` as well.

**Comment by hausdorff** [comment]
@colemickens Take a look at the referenced PR, it should resolve all the issues described here, including adding await logic for `Role` and `RoleBinding` (plus `ClusterRole`, `ClusterRolebinding`, _etc_.).
