### ISSUE TITLE
Feature: Add a flag to opt out of deprecation warnings

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#806]
Currently, we print a deprecation warning for apiVersions that will be removed in an upcoming k8s release. While this information should be valuable to the majority of users, some may wish to consciously disable these warnings.

Add a flag that allows users to suppress deprecation warnings.

**Comment by martaver** [comment]
What happened to this feature...?

I can't find it in the docs, or on the CLI and I have the latest version... 2.7.1

**Comment by martaver** [comment]
Ah... for anyone else, this flag was moved to the `suppressDeprecationWarnings: boolean` property in the `k8s.Provider` class.
