### ISSUE TITLE
Auto-alias all apiVersions rather than hardcoded set

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#828]
Followup from https://github.com/pulumi/pulumi-kubernetes/pull/798#discussion_r331622287

It should be possible to generate the list apiVersions for each resource for auto-aliasing purposes. This would be more robust against future API changes in k8s.

Update:
The upstream API reference docs are [generated from the OpenAPI spec](https://github.com/kubernetes-sigs/reference-docs/tree/5ee19698633e7cb5abff7e9a8307bc305b0bc985/gen-apidocs), so we should do the same. Note that we'll need to merge in older version of the spec to avoid losing deprecated + removed apiVersions.

**Comment by redbaron** [comment]
Is CRD version upgrade (https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/) is in scope of this ?

**Comment by hausdorff** [comment]
It would be very nice to get CRDs in this cut, but I'm not confident we understand enough of the subtlety to do this correctly.
