### ISSUE TITLE
Ingress await error

### ISSUE THREAD

**Issue by protometa** [pulumi/pulumi-kubernetes#83]
When initializing an Ingress with `k8s.extensions.v1beta1.Ingress('dev-ingress', {...}` I get:

    Diagnostics:
      kubernetes:extensions:Ingress: dev-ingress
        error: Plan apply failed: Could not find object of type 'extensions/v1beta1/Ingress'

**Comment by hausdorff** [comment]
Thanks for the report, will fix today.

**Comment by hausdorff** [comment]
@protometa I've put a fix into PR #85.
