### ISSUE TITLE
HELM_HOME environment variable is ignored

### ISSUE THREAD

**Issue by markphillips100** [pulumi/pulumi-kubernetes#854]
**Describe the bug**
Running a Pulumi preview command using the task, even after a HelmInstaller task successfully runs, fails to fetch a helm chart if a Chart resource exists in the Pulumi project.  The Helm tool cannot locate the `.helm` folder.

**To Reproduce**
Use a Chart resource from a Pulumi project run by the Pulumi@1 task.

**Expected behavior**
The helm Chart resource provider should locate the `.helm` folder using the HELM_HOME environment variable.

**Screenshots**
![pulumi-helm-preview-error](https://user-images.githubusercontent.com/6239029/67095629-bb1e8100-f1f9-11e9-8b61-a3c065e02158.PNG)

**Additional context**
A demo exists [here](https://dev.azure.com/mark-labs/_git/azure-pipelines-pulumi-helm-test?_a=readme) with a pipeline already setup and failing.  The failing build log is [here](https://dev.azure.com/mark-labs/azure-pipelines-pulumi-helm-test/_build/results?buildId=4).

**Comment by lblackstone** [comment]
@markphillips100 Thanks for the detailed bug report! I've fixed the issue in the linked PR, so this should work as you expect in the next release.

**Comment by markphillips100** [comment]
@lblackstone you are welcome, and thanks for fixing it so fast!  I'll test after the release.

**Comment by lblackstone** [comment]
@markphillips100 Sorry for the delay in getting this merged; things were a little hectic leading up to KubeCon. I'll cut a release that includes this fix later this week, or you can try it out using the `dev` tag prior to that.

**Comment by markphillips100** [comment]
@lblackstone I should be able to test next week so will give you an update shortly after.  Thanks.

**Comment by markphillips100** [comment]
@lblackstone just an update to say I've tested this and it works well.  Thanks.
