### ISSUE TITLE
Updating failed job should replace job instead of refreshing status

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-kubernetes#856]
### Problem description

When a `Job` fails (think migrations), and you run `pulumi up` again, it should try to retry the job, not simply try to refresh it's status.

The way it works today may make sense for some cases, but there are cases where you do need it to replace. For example, in our scenario, if the migrations fail because of an external issue (in this case it failed because of an engineering issue in the migration code), when we retry to deploy the migrations using pulumi, we currently have to delete the job, refresh pulumi, and then run `pulumi up`.

**Comment by lblackstone** [comment]
Current workarounds:
1. Delete Job / Update / Add Job / Update
1. Change a property on the Job resource that forces replacement (e.g., `.metadata.name`)

At the very least, it would be nice to add a flag to the Job resource to replace on failure. I'm not sure yet whether that behavior makes sense by default.

/cc @lukehoban @pgavlin 
This might also be valuable for other resources. This addresses a similar case to Terraform's "taint" command, allowing the user to force the replacement of a specified resource.

**Comment by nesl247** [comment]
Any update on this? It's a pain point for our CI. If our migrations fail for any application's stack, we have to solve it manually as the developers have no way of doing this themselves.

**Comment by lblackstone** [comment]
@nesl247 I want to make sure I understand the requirements here.

Are you wanting a way to force a one-time replacement of a Job, or setting the Job to always replace on update if it hasn't succeeded?

You also mentioned that your developers are unable to use the existing workarounds, so I assume that means they can't edit the Pulumi code directly?

**Comment by nesl247** [comment]
In our case it should always replace on update if it hasn't succeeded.

They have access to edit the code, they do not have access to run pulumi though. However, in this case, we need this to be automated, and not rely upon any manual changes or manual runs of pulumi.

**Comment by lblackstone** [comment]
@nesl247 Would having an annotation to force resource replacement solve your use case? I don't see a way to make the replacement conditional on the failure status, but the annotation would allow you to always recreate the Job without requiring further code changes.

**Comment by nesl247** [comment]
While it would work, it's not ideal. I'm not sure why pulumi can't make the determination based on the status of the job, given that pulumi is aware of the status of the job.

**Comment by lblackstone** [comment]
@nesl247 I figured out how to make the replace conditional on the Job status with the changes in #1575. Once this change is in, you will be able to opt Jobs into this behavior by adding the `pulumi.com/replaceUnready` annotation.

**Comment by nesl247** [comment]
@lblackstone Thanks! Though I do question why this is an annotation and not an option in pulumi. Annotations make sense for helm, but they don't make sense in pulumi IMO.

**Comment by lblackstone** [comment]
It requires quite a bit more design work and testing to make it applicable to Pulumi in general. We may decide to add this as a ResourceOption later, but for now, this is a relatively low-friction way to opt into the behavior for the k8s provider.
