### ISSUE TITLE
Feature: Automatically run `helm repo update`

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#857]
### Problem description

- Other: It would be nice to automatically run `helm repo update` as part of Chart operations to avoid requiring the user to do that out of band to get new versions of charts.

**Comment by brandonkal** [comment]
This is a slow operation. As an example, with 3 repositories, I am seeing a 17 second real time. It also depends on an internet connection which other operations do not neccessarily require. I suggest making this feature a flag of pulumi up (off by default) to not hurt usability.

**Comment by nesl247** [comment]
What may be a good compromise would be to automatically run the update if helm reports a version is missing. This is the typical scenario I believe in which we would want `helm repo update` to occur.

**Comment by lblackstone** [comment]
As an alternative to this, it's possible to specify the repo URL as part of the chart fetch options. When this option is specified, the local repo cache isn't needed.

Here's an example of this usage.
https://www.pulumi.com/docs/reference/pkg/kubernetes/helm/v3/chart/#remote-chart

**Comment by nesl247** [comment]
That's what we ended up with. This was more of an issue before the stable chart was deprecated. Now we always specify a chart url.

**Comment by lblackstone** [comment]
Given that this is not relevant to the v3 SDK, and the stable repo is no longer default, I think we can close this out.
