### ISSUE TITLE
.NET support for Kubernetes

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#863]
We are adding support for .NET to [Pulumi core](https://github.com/pulumi/pulumi/pull/3399) and to [pulumi-terraform-bridge](https://github.com/pulumi/pulumi-terraform-bridge/pull/54).  We should also add support for .NET to the Kubernetes provider.

- [x] Core Provider Code Generation (https://github.com/pulumi/pulumi-kubernetes/pull/885)
- [ ] YAML/Helm support (#957)

**Comment by lukehoban** [comment]
Here's an example based on the in-progress PR: https://github.com/pulumi/examples/pull/477

**Comment by kenlefeb** [comment]
Is the `version.txt` file supposed to be omitted? Do you have a sample of the contents, in case I want to build this package locally?

**Comment by lukehoban** [comment]
> in case I want to build this package locally?

`make build install` will build the package locally.  The `version.txt` file is written into the source package as part of the build.

**Comment by mikhailshilkov** [comment]
I'll close this issue to track Helm support in #957
