### ISSUE TITLE
ConfigGroup does not seem to read HTTP_PROXY and doesn't work behind a proxy

### ISSUE THREAD

**Issue by 0x53A** [pulumi/pulumi-kubernetes#877]
I have

```ts
const certManagerCustomResources = new k8s.yaml.ConfigGroup(`${prefix}-k8-tls-custom-resources`, {
    files: ["https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml"],
}, { provider: k8sProvider });
```

which works outside the company network, but hangs for a few minutes then errors inside it, behind a proxy.

I have set the environment variable ``HTTP_PROXY``, and everything else (pulumi itself, helm charts, etc) works.

I'm not too familiar with nodejs, but I think ``fetch`` as used [here](https://github.com/pulumi/pulumi-kubernetes/pull/638/files#diff-21d2288913d8e692d6834ce78c44a68eR254-R259) does __not__ read ``HTTP_PROXY``.

**Comment by 0x53A** [comment]
This issue is still affecting me.

Can i change from url to local file without having to destroy and recreate the CRDs?

**Comment by EronWright** [comment]
This issue is fixed with the new "v2" implementations, because the HTTP request is performed by Go code.
https://www.pulumi.com/blog/kubernetes-yaml-v2/
