### ISSUE TITLE
Provide a way to update kubeconfig from stack reference from command line

### ISSUE THREAD

**Issue by elucidsoft** [pulumi/pulumi-kubernetes#887]
### Problem description
The issue is a little complicated so I will try to explain it clearly.  Assume you have a microstack architecture such as:

- infra-cluster
- infra-webserver

- infra-cluster is responsible for creating the main cluster, and setting up the nodes.
- infra-webserver sets up a web app and uses a stack reference to pull the kubeconfig from infra-cluster stack.

Now lets say you update your cluster that forces a replace in infra-cluster.  So it recreates your cluster, but since you use microstack all of your children stacks are now orphaned because the kubeconfig that they contain is now invalid.

Normally an update would fix this because an update would pull the new kubeconfig from stack reference.  The problem arises here is that when the cluster was updated it also deleted the other resources, so your update will refuse to run due to it being out of sync.

So try to run refresh right to resync your stack?  Well, that would work, but refresh doesn't update new stack references so refresh times out because it can't connect to the new nodes because they are in a new cluster.

The current solution is a huge pain, track down the URN for the kubeconfig property, and then run a update --target <urn>

##Possible solutions

- Have a flag for refresh to update stack references when it runs.
- Have a seperate command to allow updating the property by name vs. urn
- Mark a stack reference as a 'provider' reference and when refresh runs ensure you update only stack references marked as such.  Maybe use a special type?

**Comment by pgavlin** [comment]
> The problem arises here is that when the cluster was updated it also deleted the other resources, so your update will refuse to run due to it being out of sync.

Do I understand correctly that the update fails because Pulumi cannot connect to the now-deleted cluster?

**Comment by elucidsoft** [comment]
That is correct.  Need a way to easily replace the StackReference to the provider from the old cluster to the new cluster in all of your other stacks.  Right now, I had to spend nearly 3 hours going through every single stack and resolving it one by one.

**Comment by elucidsoft** [comment]
I have been unable to reproduce this issue, I have NO idea how I did this the first time.  I repeated the exact steps on multiple clusters and it worked fine.  I am going to close this until I can repro it.
