### ISSUE TITLE
Fix .NET projection of `object`-valued properties

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#889]
There are a small number of properties in the Kubernetes API Schema that should be projected as "an arbitrary JSON object".  

It is not currently possible to correctly project these in .NET - so they are mapped to `string`.  But this will prevent using any resources that populate these properties.

These are things like the following which are typed as fully arbitrary `object`:

```json
    "io.k8s.apimachinery.pkg.apis.meta.v1.FieldsV1": {
      "description": "FieldsV1 stores a set of fields in a data structure like a Trie, in JSON format.\n\nEach key is either a '.' representing the field itself, and will always map to an empty set, or a string representing a sub-field or item. The string will follow one of these four formats: 'f:<name>', where <name> is the name of a field in a struct, or key in a map 'v:<value>', where <value> is the exact json formatted value of a list item 'i:<index>', where <index> is position of a item in a list 'k:<keys>', where <keys> is a map of  a list item's key fields to their unique values If a key maps to an empty Fields value, the field that key represents is part of the set.\n\nThe exact format is defined in sigs.k8s.io/structured-merge-diff",
      "type": "object"
    },
```

**Comment by lukehoban** [comment]
@CyrusNajmabadi What do you suggest doing here?

**Comment by lukehoban** [comment]
@CyrusNajmabadi noted at https://github.com/pulumi/pulumi-kubernetes/pull/885#discussion_r349847201:

> Can we json stringify this so it is a string in the .net side? Alternatively, we could define this in .net as an actual Json type and the marshal properly to that.

**Comment by lukehoban** [comment]
> Alternatively, we could define this in .net as an actual Json type and the marshal properly to that.

I like this - I think in practice this would make sense.  The types in question are all in some way or another things that represent JSON - so projecting them as such would be reasonable.

**Comment by CyrusNajmabadi** [comment]
> I like this - I think in practice this would make sense. The types in question are all in some way or another things that represent JSON - so projecting them as such would be reasonable.

So i undertand, can these be primitive json values?  i.e. can they just be a string/number?  or would they always be rich json values (like object/arrays)?

**Comment by lukehoban** [comment]
They are typed as `object` in JSONSchema, so I believe must be JSON objects.
