### ISSUE TITLE
[feature] smarter diff

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi-kubernetes#891]
### Problem description

An improved diff algorithm would make switching to pulumi easier.

Some notes:

- Pulumi should understand default values. For instance, the removal of `protocol: "TCP"` should not fail an import because TCP is the default when not specified.
- Pulumi should understand when a list is unordered. For example, a change in the order of items in the volume array doesn't need to fail an import.

### Suggestions for a fix

Encode an understanding of default values.

**Comment by lblackstone** [comment]
We do a better job of this in the v4 provider, and using the `pulumi import` command that didn't exist when this issue was created.
