### ISSUE TITLE
Missing k8s.autoscaling.v1.VerticalPodAutoscaler

### ISSUE THREAD

**Issue by elucidsoft** [pulumi/pulumi-kubernetes#900]
### Problem description
Missing the VerticalPodAutoscaler, here is the ref: https://cloud.google.com/kubernetes-engine/docs/how-to/vertical-pod-autoscaling

**Comment by lblackstone** [comment]
The VPA isn't part of the core k8s API [1][2], which means that it's not included in our auto-generated SDK.

From a quick skim of the repo, the VPA is [installed as a CRD](https://github.com/kubernetes/autoscaler/blob/90bec62d19e46035d11e24567fa73ba1e2899f85/vertical-pod-autoscaler/deploy/vpa-v1-crd.yaml#L2-L47), so you could use the [`k8s.apiextensions.CustomResource`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/apiextensions/#CustomResource) class to make use of it.

We don't currently have plans to include CRDs/CRs as part of the core provider SDK, so I'm going to close this issue for now.

[1] https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler
[2] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/

**Comment by lukehoban** [comment]
Note that https://github.com/pulumi/pulumi-kubernetes/issues/219 is tracking adding an easy way to create strongly typed wrappers over CRD schema which would help here.
