### ISSUE TITLE
Document provider flags

### ISSUE THREAD

**Issue by lukehoban** [pulumi/pulumi-kubernetes#909]
I could not find where `kubernetes:suppressDeprecationWarnings` is documented. We should ensure that all provider flags (config and env vars) are documented in the provider docs at https://www.pulumi.com/docs/intro/cloud-providers/kubernetes/.

**Comment by lblackstone** [comment]
We have the config flags documented here: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/#ProviderArgs

I can update those docs to include env var alternatives.

**Comment by lblackstone** [comment]
Still need to make the following update:
> I was imagining documenting the env vars outside of just API docs - inline with what we do for AWS/azure/GCP and many others at https://www.pulumi.com/docs/intro/cloud-providers/aws/#configuration.
