### ISSUE TITLE
Extremely slow Diff

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi-kubernetes#937]
[slow-pulumi-k8s-diff-brandonkal.zip](https://github.com/pulumi/pulumi-kubernetes/files/4021436/slow-pulumi-k8s-diff-brandonkal.zip)
### Problem description

Unfortunately Pulumi programs are quite slow. Here is a very simple example:
```ts
import * as k8s from '@pulumi/kubernetes'

new k8s.core.v1.Endpoints('external', {
  metadata: { name: 'external-nginx' },
  subsets: [
    {
      addresses: [{ ip: '10.0.20.111' }],
      ports: [{ name: 'https', port: 443 }],
    },
  ],
})

new k8s.core.v1.Service('svc', {
  metadata: { name: 'external-nginx' },
  spec: {
    ports: [{ name: 'https', port: 443 }],
  },
})
```
The diffs on that should not take ~7 seconds for each resource.

### Errors & Logs
See attached in zip file

### Affected product version(s)

@pulumi/kubernetes@1.4.1

### Reproducing the issue

1. Download zip file
2. View README.md
3. `time pulumi preview --tracing=file:./preview2.trace -v 9 --logtostderr --logflow 2> preview.log`
4. Wait.

### Suggestions for a fix

Unkown. Both resources can be Checked and Diffed in parallel. But the larger issue of the slow performance should be fixed first.

Related:
#827 
https://github.com/pulumi/pulumi/issues/3257

**Comment by davidkell** [comment]
We've experienced this issue. We wanted to install knative-serving on GKE with Pulumi, but the installation requires ~50 individual resources. Just `pulumi preview` took about 10 minutes to run.

Is this a recent regression or has this always been an issue with Pulumi?

**Comment by davidkell** [comment]
For what its worth, the same installation was 1m41s when we set `enableDryRun: true` in the `k8s.Provider`. That's fine for us.

**Comment by lblackstone** [comment]
@davidkell Interesting; thanks for the info! Have you noticed the slowness with other providers, or just Kubernetes?

**Comment by davidkell** [comment]
We've only worked with `gcp.container.Cluster` and `kubernetes` resources to date. The GCP cluster creation was fast (~3 minutes), but manually Istio and Knative was impossible. Even `pulumi preview` was hanging seemingly forever. For now, we are using the Istio and Cloud Run add-ons, and potentially with the `enableDryRun` option we can go back to manual install.

Will let you know if we find anything else. We are based in UK, not sure if it's the latency with all the requests per resource?

**Comment by lblackstone** [comment]
@davidkell Could you send me a trace for a slow k8s preview? Can DM me on community slack `@levi`

Instructions here:
https://www.pulumi.com/docs/troubleshooting/#performance
