### ISSUE TITLE
`refresh` and `up` fail when Kubernetes providers are deleted

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-kubernetes#950]
Suppose I have a Kubernetes cluster with some number of resources on it, using first-class providers. Suppose also that the cluster is somehow deleted out-of-band. `refresh` and `up` will now _always_ error, because we will time out looking for the cluster. And, because we cannot in general tell the difference between a deleted cluster and a cluster that's unresponsive, this essentially cripples the Pulumi, requiring manual state surgery to fix.

I can think of at least a couple other options that seem better:

* Make it very easy to recursively remove (_e.g._) a provider and all resources that use it from the state.
* Expose some kind of option (through the CLI, _e.g._) that missing providers to be treated as "deleted", and for that delete to be recursive.

The second of these seems like it will require quite a bit more work, as it seems like we will have to plumb that information through the resource graph, so that the engine knows about the missing provider, and knows to override the timeout error of the resources running on the cluster. The first seems like it would be pretty straightforward.

**Comment by lblackstone** [comment]
The PR I just linked fixes this issue by conditionally handling unreachable clusters:

1. On update, fail with an error.
![Screen Shot 2020-01-15 at 12 02 37 PM](https://user-images.githubusercontent.com/9253463/72462720-f4ca3e00-378e-11ea-8981-62a63fb50f92.png)

2. On refresh, assume that the cluster was deleted and delete the resources from Pulumi's state.
![Screen Shot 2020-01-15 at 11 36 52 AM](https://user-images.githubusercontent.com/9253463/72462781-22af8280-378f-11ea-9a3e-8d6188c4ccc0.png)

3. On delete, assume that the cluster was deleted and delete the resources from Pulumi's state.
![Screen Shot 2020-01-15 at 12 05 04 PM](https://user-images.githubusercontent.com/9253463/72462838-4a9ee600-378f-11ea-9901-0b29a9a570a1.png)

While it's possible that this approach could erroneously stop tracking resources if the cluster is only temporarily unreachable, that could be subsequently fixed using import. The preview will warn that the cluster is unreachable, so this should be unlikely in practice.
