### ISSUE TITLE
cert-manager CRD k8s.yaml.ConfigFile makes pulumi hanging indefinitely

### ISSUE THREAD

**Issue by sylv3r** [pulumi/pulumi-kubernetes#964]
### Problem description

I'm upgrading cert-manager from 0.8 to 0.13 
Since I updated the version in my scripts `pulumi up` is hanging indefinitely with a node process burning up.

I was able to narrow the problem down to this instruction (which was working fine in 0.8) : 

```
new k8s.yaml.ConfigFile(
      'crds',
      {
        file: 'https://raw.githubusercontent.com/jetstack/cert-manager/v0.13.0/deploy/manifests/00-crds.yaml',
      },
      {},
)
```
If I comment it out, the preview completes quickly, as expected (but I need it to upgrade cert-manager)

### Errors & Logs

Would love to have a way to debug why it is hanging but unfortunately I have no idea how to have more information from pulumi.

### Affected product version(s)

pulumi cli v1.9.0
@pulumi/pulumi 1.9.0
@pulumi/kubernetes 1.4.5

### Reproducing the issue

I can't provide a standalone example to reproduce it right now, I'll try to tomorrow, depending on feedbacks.

**Comment by lukehoban** [comment]
This is likely the same issue as https://github.com/pulumi/pulumi-kubernetes/issues/963.

**Comment by sylv3r** [comment]
@lukehoban yes definitely. Sorry for the duplicate, I'll follow the progress on the previous issue.
