### ISSUE TITLE
Helm nginx-ingress

### ISSUE THREAD

**Issue by roquesao** [pulumi/pulumi-kubernetes#972]
I'm using helm to install nginx-ingress-controller , I would like to know how to add annotations:

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "True"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

my code
`"use strict";
const helm = require("@pulumi/kubernetes/helm");
const pulumi = require("@pulumi/pulumi");
const aws = require("@pulumi/aws");
const awsx = require("@pulumi/awsx");
const k8s = require("@pulumi/kubernetes")

const nginx = new k8s.helm.v2.Chart("ingressnginx", {
    repo: "stable",
    chart: "nginx-ingress",
    releaseName: "v1.3",
});
`

**Comment by pgavlin** [comment]
cc @lblackstone

**Comment by lblackstone** [comment]
For Helm charts, you can either set values provided by the chart using the [`values` parameter](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/helm/v2/#ChartOpts-values), or can use the [`transformations`](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kubernetes/helm/v2/#ChartOpts-transformations) to arbitrarily modify the Chart resources.

I'm not sure which resources need those annotations, but something like this should work:
```ts
...
transformations: [
(obj: any, opts: pulumi.CustomResourceOptions) => {

    // If you want to select only certain resources, you can use the following type of conditional
    // if (obj.kind === "Deployment" && obj.metadata.name === "expected-resource-name) {

    obj.metadata.annotations = {
      ...obj.metadata.annotations,
      "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "True",
      "service.beta.kubernetes.io/aws-load-balancer-internal": "true",
      "service.beta.kubernetes.io/aws-load-balancer-type": "nlb",
  },
]
```

**Comment by mjdouble** [comment]
Does anyone have a full working example of this.  I can't get it to work.
