### ISSUE TITLE
Patching resources from multiple stacks

### ISSUE THREAD

**Issue by unthought** [pulumi/pulumi-kubernetes#979]
### Problem description

I have a question about patching ConfigMaps (or really any resource) from multiple stacks. Case in point is the aws-auth map in AWS clusters (EKS and otherwise) that bridge IAM credentials/tokens into k8s RBAC. Right now the suggested approach is to create users/roles upfront for the entire cluster and then do role assumption for one of those. However that doesn’t really work well if you have shared clusters and you want to restrict your roles more (eg. to only the namespaces they create for their own deployment, which might be dynamic (eg. PR based)).

The ConfigMap resource itself belongs logically to the stack that pulls up the cluster. But the entries can be contributed by different stacks, one per deployment. It's a bit like SecurityGroups and SecurityGroupRules in AWS.

I don't think I can use resource or yaml transformations, because I don't want to adopt the entire ConfigMap (so it doesn't get deleted if the deployment stack is destroyed), I just need a proxy on which I can manage the entry in the configmap depending on the change.

Now the thing is that I can envision how to do this with a new pulumi.dynamic.ResourceProvider, because I could just read the ConfigMap in each of diff/create/update/delete, fish out the entry that you're looking for, and do whatever I need to do (create/update/delete the entry), retrying updates to catch race conditions. The dynamic Resource becomes the placeholder for the ConfigMap *entry*, not the entire ConfigMap.

The problem that I'm having is that I can't use `@pulumi/kubernetes` itself to do that (which would be really convenient for eg `k8s.core.v1.ConfigMap.get()`), because any `@pulumi` dependencies are excluded from the dynamic provider process, and I don't know how to access the kubernetes provider from within that process (if it is at all possible).

So I have three questions:
1. is there another way how I can achieve my goal for the aws-auth map specifically (I haven't tried the new iam-aws-authenticator CRDs yet, since they're alpha).
2. is there a convenient way to implement such a dynamic ResourceProvider, given what is released today.
3. does it make sense to put this into pulumi proper (Kubernetes or not, depending on approach).

**Comment by metral** [comment]
Related https://github.com/pulumi/pulumi-kubernetes/issues/264

**Comment by lblackstone** [comment]
You can manage this type of change now using Patch resources. See https://www.pulumi.com/registry/packages/kubernetes/how-to-guides/managing-resources-with-server-side-apply/
