### ISSUE TITLE
Throttle kubernetes deployments

### ISSUE THREAD

**Issue by 0x53A** [pulumi/pulumi-kubernetes#986]
I am repeatedly hitting https://github.com/Azure/AKS/issues/1373 when doing anything in Kubernetes.

While this is not a pulumi issue, it can be exaggerated by Pulumi because a simple code change (e.g. changing a version tag) can often cascade into a lot of actual changes to the deployments.

What I would like to do is somehow (optionally!) throttle the updates to kubernetes.

For example, lets say I am deploying 10 pods. Afaik at the moment it will just deploy all 10 of them in parallel and then watch them.

Instead I would like Pulumi to only deploy 1, wait for it to complete, then continue. Maybe even insert an artificial sleep of a few seconds or whatever, I'm just getting tired of my cluster breaking.

**Comment by lblackstone** [comment]
When you use resources like Deployments, Pulumi isn't controlling Pods individually. Instead, we send the configuration to the k8s cluster, and then its controllers handle the rollout. If you want to change the rollout behavior, the k8s API is the way to do it.

If I understand your problem correctly, this should be something you can control using the [rolling update settings](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#rollingupdatedeployment-v1-apps) on a Deployment coupled with setting the [liveness/readiness}(https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) probes in your Pod configs.

I'm going to close out this issue for now, but you can reopen with more details if that doesn't solve your problem.

**Comment by 0x53A** [comment]
In my case I don't have one deployment with 10 pods but rather 10 deployments with one pod each.

In total I currently have 42 services / 42 deployments / 42 pods. Over the next few months this will surely grow to at least 100.

These deployments are created from common js functions (infrastructure as code is great!), but this means if I change something in the function (e.g. if I change the health probe), the cluster is bombarded with 42 updates and just dies.

So it would be neat if Pulumi waited for the first deployment to be "up" before sending the second deployment to the cluster.

Sorry for mixing terminology in the op.

**Comment by lblackstone** [comment]
Ok, in this case, you could use the [dependsOn](https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/pulumi/#CustomResourceOptions-dependsOn) opt to force the Deployments to be deployed serially.

Something along these lines:
```ts
const appLabels = { app: "nginx" };
const deployment1 = new k8s.apps.v1.Deployment("nginx1", {
    spec: {
        selector: { matchLabels: appLabels },
        template: {
            metadata: { labels: appLabels },
            spec: {
                containers: [{ name: "nginx", image: "nginx:1.14"}],
            },
        },
    },
});
const deployment2 = new k8s.apps.v1.Deployment("nginx2", {
    spec: {
        selector: { matchLabels: appLabels },
        template: {
            metadata: { labels: appLabels },
            spec: {
                containers: [{ name: "nginx", image: "nginx:1.14"}],
            },
        },
    },
}, {dependsOn: [deployment1]});
```

**Comment by 0x53A** [comment]
I'll try to hack something together, but this is really ugly.

My code looks like this:

```js

// ---------------
// config (will be edited by coworkers who are not too familiar with k8s)

const nginxConfig = [
  { name: "ngingx1" },
  { name: "nginx2" }
];

const otherServiceConfig = [
  { name: "svc-foo" },
];


// ---------------
// Helpers

function runNginx(props) {
    const deployment = new k8s.apps.v1.Deployment(props.name, {
        spec: {
            selector: { matchLabels: appLabels },
            template: {
                metadata: { labels: appLabels },
                spec: {
                    containers: [{ name: "nginx", image: "nginx:1.14"}],
                },
            },
        },
    });
    
    const service = ...
    
    return { deployment, service };
}


// ---------------- 
// Execute

const deployedNginxes = nginxConfig.map(runNginx);
const deployedOtherServices = otherServiceConfig.map(runOtherService);

// now set up ingress etc to route traffic to the configured services
```

**Comment by lukehoban** [comment]
BTW - there is also a `--parallel <n>` flag to `pulumi up` that you can use to limit the degree of parallelism Pulumi will use during deployment.  If the only issue is concurrency of operations against the Kubernetes API server, that may help control things without the need to edit code.

See https://www.pulumi.com/docs/reference/cli/pulumi_up/.

**Comment by 0x53A** [comment]
ohh, thats neat, I'll try it, thank you!

**Comment by 0x53A** [comment]
I did try the first suggestion (dependsOn), and it looks good so far

```js

const allDeployments : pulumi.Resource[] = [];

function runNginx(props) {
    const deployment = new k8s.apps.v1.Deployment(props.name, {
        // ...
    }, dependsOn: allDeployments.map(x => x) ); // map to get a copy of the array, otherwise you have a reference cycle
    
    const service = ...
    
    return { deployment, service };
}

```

It hasn't finished yet, but it is creating deployments one after the other successfully. Before that, it would start all of them, and all of them would fail. Then it would take about an hour of kubernetes restarting pods to get everything green. (with the node intermittently going completely red because of PLEG or whatever).
